### ISSUE TITLE
Duplicate autolink shortcut/shorthand sections in the docs

### ISSUE THREAD

**Issue by xfq** [tabatkins/bikeshed#1000]
Two sections document the autolink shortcuts/shorthands, each with its own dfn and description.

* https://tabatkins.github.io/bikeshed/#autolink-shortcuts
* https://tabatkins.github.io/bikeshed/#autolinking

I suggest merging them into one section, which will reduce repetition of information (and the strong possibility of eventual contradiction).

**Comment by tabatkins** [comment]
Ah, thanks for pointing this out. It *was*, in fact, already diverging unacceptably.
