### ISSUE TITLE
Option to generate caniuse panels for EDs only

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1010]
As discussed in https://github.com/w3c/csswg-drafts/issues/1219#issuecomment-295034986, pending some improvements to bikeshed's handling of caniuse panels (or pending agreement that it is fine as is), the CSSWG has decided to use caniuse panels in EDs only for now.

Adding this metadata in the spec, turning **Include Can I Use Panels** on and off every time I want to publish a draft based on what status it should have is a pain and error prone.

It would be great if the [**Include Can I Use Panels** key](https://tabatkins.github.io/bikeshed/#metadata-include-can-i-use-panels) was extended to make that easier. For instance, in addition of "true" and "false", it could also take "ED" and only generate caniuse table is the **Status** is ED. (or if you want to be more generic, it could take a coma separate lists of statuses, and generate if the current status is one in the list).

**Comment by frivoal** [comment]
Actually, no need for this special syntax. Instead, just setting `Include Can I Use Panels` to `yes` in the CSSWG's `defaults-ED.include` does the trick just fine, as long as you then leave it unset in the actual draft.

Submitted PR #1012 for this.

**Comment by tabatkins** [comment]
Closing in favor of #1014, since being able to do this roundabout via boilerplate files but not directly is silly.
