### ISSUE TITLE
Defining a dictionary and partial extensions of it in the same spec makes multiple identical exported dfns

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1019]
https://w3c.github.io/webappsec-credential-management/ defines a dictionary named [`CredentialRequestOptions`](https://w3c.github.io/webappsec-credential-management/#dictdef-credentialrequestoptions) and [two](https://w3c.github.io/webappsec-credential-management/#dictdef-credentialrequestoptions0) [partials](https://w3c.github.io/webappsec-credential-management/#dictdef-credentialrequestoptions1) of it. All three get a `<dfn data-dfn-type="dictionary" data-export="" id="…">`, which breaks `{{CredentialRequestOptions}}` links.

I think Bikeshed shouldn't produce a `<dfn>` for partial dictionaries.

**Comment by tabatkins** [comment]
Huh, it *already* shouldn't be doing so - partials should be forced into being links rather than dfns.  Maybe I only applied that rule to interfaces, not dictionaries? I'll check.

**Comment by tabatkins** [comment]
Just confirmed that Bikeshed does do this - it was fixed last month in bb05fdf47.  The local version being used to build the spec must just be out of date.

**Comment by jyasskin** [comment]
Thanks, and sorry for the noise. @mikewest, FYI.

**Comment by mikewest** [comment]
Hopefully fixed in https://github.com/w3c/webappsec-credential-management/commit/cad004e5e4a0cbe01f44027abe3588fcbe302370. Thanks!
