### ISSUE TITLE
When there are multiple dfns in the same spec, link-defaults suggestion is confusing

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1020]
This caused confusion in https://lists.w3.org/Archives/Public/public-webauthn/2017May/0185.html, where the error message was:

```
LINK ERROR: Multiple possible 'idl' refs for 'CredentialRequestOptions'.
Arbitrarily chose the one in webappsec-credential-management-1.
If this is wrong, insert one of the following lines into a &lt;pre class=link-defaults> block:
spec:webappsec-credential-management-1; type:dictionary; for:/; text:CredentialRequestOptions
spec:webappsec-credential-management-1; type:dictionary; for:/; text:CredentialRequestOptions
spec:webappsec-credential-management-1; type:dictionary; for:/; text:CredentialRequestOptions
```

These three suggestions are identical, and inserting them doesn't remove the error message.

The root problem is #1019, but when it encounters this situation, Bikeshed should say there's something wrong with webappsec-credential-management-1, not just give useless link-defaults suggestions.

**Comment by tabatkins** [comment]
Yeah, it's not hard to detect this and output a more useful message. Will do.

**Comment by tabatkins** [comment]
Fixed! It now calls out the indistinguishable refs explicitly, even if they appear among distinguishable ones.
