### ISSUE TITLE
<dfn> for LegacyWindowAlias identifiers

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#1021]
See https://github.com/heycam/webidl/issues/362

Given e.g.

```
[LegacyWindowAlias=SVGPoint]
interface DOMPoint {};

[LegacyWindowAlias=(SVGMatrix,WebKitCSSMatrix)]
interface DOMMatrix {};
```

the `SVGPoint`, `SVGMatrix`, `WebKitCSSMatrix` should be `<dfn>`-ed exactly the same as a proper interface name.

**Comment by tabatkins** [comment]
Done, thanks for the heads-up on the change.
