### ISSUE TITLE
remove caniuse attributes from the output

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1023]
When **Include Can I Use Panels** is false (as it is for example on csswg WDs), caniuse attributes are kept in the output markup, which then cause the spec to fail validation when trying to publish with echidna.

https://labs.w3.org/echidna/api/status?id=8eefbfc8-9ac9-4950-bea9-6591b506b640

Even if the panels are not being generated, the caniuse attribute should never be present in the output.

**Comment by xfq** [comment]
I think it's fixed by commit acdedda0d46d221a6ee9c1a136bd7bc1b361bc87.

**Comment by tabatkins** [comment]
Yup, fixed but only pinged the PR, not this issue.
