### ISSUE TITLE
Possible typo in docs

### ISSUE THREAD

**Issue by xfq** [tabatkins/bikeshed#1030]
In [§ 9.2. Linking to Stringifiers](https://tabatkins.github.io/bikeshed/#linking-to-stringifiers):

> The `stringifier` keyword itself is always linkable; it's a "dfn" type definition with `for=MyInterface` and linking text "stringification behavior". Like any other IDL construct, you can instead define the term yourself in the same way, and the IDL will link to your definition instead, like `<dfn dfn for=MyInterface>stringification behavior</dfn>`.

I might be missing something, but it looks like the "dfn dfn" should be "dfn stringifier" or "dfn export".

**Comment by tabatkins** [comment]
Nah, it's a little confusing, but the second `dfn`is a shorthand for `data-dfn-type=dfn`.

**Comment by xfq** [comment]
Sorry but I still don't understand what you mean. Would you please explain?

For example, the stringification behavior for [Range](https://github.com/whatwg/dom/blob/b2f429273e23d22acbcbdcdad46cd440ec131098/dom.bs#L8580) doesn't look like this.

**Comment by tabatkins** [comment]
Yeah, it doesn't need it, because `data-dfn-type=dfn` is the default. I just specified it explicitly up there to avoid errors from people copy-pasting.
