### ISSUE TITLE
comments with angle brackets within xmp causing parsing errors

### ISSUE THREAD

**Issue by patrickkettner** [tabatkins/bikeshed#1036]
found in the [css-typed-om](https://drafts.css-houdini.org/css-typed-om-1/) spec

![image](https://cloud.githubusercontent.com/assets/465414/26733532/be0dea48-4780-11e7-991c-b277f531fd1c.png)

smallest repro I can muster

```bs
<pre class='metadata'>
Title:  Foo
Status: LS
Shortname: Foo
Level: 0
Abstract: Foo
Editor: Foo
</pre>

<xmp class=idl>
partial namespace Foo {
    // <length>
    Foo foo(string foo);
};
</xmp>
```

Note the breakage is specifically in the `IDL Index` portion of the output

**Comment by tabatkins** [comment]
I just want to say: what in the actual fuck is going on here?!?

**Comment by tabatkins** [comment]
Hm, and using a `<pre>` with an escaped `&lt;` does the same thing.

**Comment by tabatkins** [comment]
Okay, fixed. I was highlighting the IDL index *again* (when its contents had already been highlighted), and that ended up messing up any occurrences of `<`, and caused the highlight code to misalign in wacky ways.

Fix was to just add the .highlight class to the index. That's all it needed. ^_^

**Comment by patrickkettner** [comment]
🎉🎉🎉 for simple fixes
