### ISSUE TITLE
LINK ERROR …summary of comment…

### ISSUE THREAD

**Issue by dirkschulze** [tabatkins/bikeshed#1039]
I get the following error for an FXTF ED spec:

```
LINK ERROR: No 'dfn' refs found for '…summary of comment…'.
<i data-link-type="dfn" data-lt="…summary of comment…">…summary of comment…</I>
```

and am unsure what it means.

**Comment by tabatkins** [comment]
It means that your boilerplate has an `i` in it, and you've got `Use <i> Autolinks` set to on.  Do you want to remove the `i` linking (just switch them to `a`) in your doc so we can turn off that metadata, or should I just tweak the boilerplate to say that's not a link?

**Comment by dirkschulze** [comment]
@tabatkins The masking spec still needs the old SVG perl script which transforms `<a>`. So for now I can not turn it off. Will check what it takes to remove the requirement the next days.

IMO very low priority to tweak the boilerplate.
