### ISSUE TITLE
Reference to SVG viewBox attribute missing

### ISSUE THREAD

**Issue by dirkschulze** [tabatkins/bikeshed#1040]
I currently struggle with the lack of a reference to SVGs `viewBox` attribute. Is there a way to map it to a heading?

```
<a class='attr-name' href='https://www.w3.org/TR/2011/REC-SVG11-20110816/coords.html#ViewBoxAttribute'>‘viewBox‘</a>
```

(SVG 1.1 or SVG2 doesn't matter.)

**Comment by tabatkins** [comment]
The most straightforward solution is to fix SVG. ^_^

Failing that, you can add a line to an anchors block in your spec:

```
<pre class=anchors>
url: https://www.w3.org/TR/2011/REC-SVG11-20110816/coords.html#ViewBoxAttribute; type: element-attr; for:svg; text: viewBox;
</pre>
```

Autolinks should work then.

**Comment by dirkschulze** [comment]
I added

```html
<pre class=anchors>
url: https://www.w3.org/TR/2011/REC-SVG11-20110816/coords.html#ViewBoxAttribute; type: element-attr; for:svg; text: viewBox;
</pre>
```

and used it with:

```html
<a element-atr>viewBox</a>
```

but still get the error:

```
LINK ERROR: No 'dfn' refs found for 'viewbox'.
<a element-atr="" data-link-type="dfn" data-lt="viewBox">viewBox</a>
```

Same with just using `<a>` (or still `<I>` actually) and adding `for=svg`.

**Comment by tabatkins** [comment]
Ah, because you misspelled "element-attr". 😀

**Comment by dirkschulze** [comment]
@tabatkins heh. That makes sense! Working now. Thanks!
