### ISSUE TITLE
Relative paths to templates not found on server

### ISSUE THREAD

**Issue by dirkschulze** [tabatkins/bikeshed#1041]
Get the following error when server is responsible for generating the `Overview.html` file:

```
LINE 390: Couldn't find include file 'templates/filter.md'. Error was:
[Errno 2] No such file or directory: 'templates/filter.md'
```

The source code looks like this:
```html
<pre class=include>
path: templates/filter.md
</pre>
```

Works perfectly fine locally. Had to check-in a locally generated `Overview.html` file for now.

**Comment by dirkschulze** [comment]
Source code is here: https://github.com/w3c/fxtf-drafts/blob/master/filters/Overview.bs

**Comment by tabatkins** [comment]
Sigh, yeah, this is because includes are currently resolved relative to the directory the script is run from, not the directory the spec is in.  Server runs it all from an ancestor directory.  This is something I've been meaning to fix for a while.

**Comment by tabatkins** [comment]
I fixed things - paths that should be resolved relative to the spec itself (like include paths) now correctly do so. If you've been working around this issue, you might need to correct the includes, but it'll be stable and correct from now on.
