### ISSUE TITLE
Allow highlighting of source code lines

### ISSUE THREAD

**Issue by dirkschulze** [tabatkins/bikeshed#1043]
I'd like to use something like http://prismjs.com/plugins/line-highlight/#how-to-use to highlight specific lines in my `<pre><code>` code examples. `data-line` does not work though.

**Comment by xfq** [comment]
Bikeshed has switched syntax highlighting from Prism to Pygments. FWIW, the Pygments has an `hl_lines` option: http://pygments.org/docs/formatters/?highlight=hl_lines

**Comment by tabatkins** [comment]
Ah, thanks for the pointer! I'll happily add this.

**Comment by tabatkins** [comment]
Ah, that's for the HTMLFormatter, which I don't use - I use the RawTokenFormatter to get a simplified view of the text as a linear sequence of text/class pairs, so I can more easily merge it into existing markup. Gonna have to roll my own line highlighting to make this work.

(I'll do it a ton better anyway; the Pygments option produces a table, which isn't guaranteed to line up with the lines of code.)

**Comment by tabatkins** [comment]
And done! [Per the documentation](https://tabatkins.github.io/bikeshed/#line-highlighting), use `line-highlight="2-4, 6"` (possibly combined with `line-start=N`) to highlight individual lines.
