### ISSUE TITLE
markdown blockquote not interpreted

### ISSUE THREAD

**Issue by zygoloid** [tabatkins/bikeshed#1055]
In a document like:

```
<pre class='metadata'>
...
Markup Shorthands: markdown yes
</pre>

> Markdown blockquote
```

the markdown blockquote (`> ...`) syntax is not recognized, and verbatim `>`s appear in the output document.

**Comment by tabatkins** [comment]
Yeah, I haven't added blockquotes to Bikeshed's markdown syntax yet.  I presume you'd like me to do so? ^_^

**Comment by tabatkins** [comment]
And done!
