### ISSUE TITLE
Computed metadata always comes after other metadata

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1058]
In e.g. https://streams.spec.whatwg.org/ right now, we have:

- Participate
- Commits
- Tests
- Demos
- Translation (non-normative)

The first three of these will be uniform across WHATWG specs, so I wanted to use computed metadata for them.

The last three are one-offs that need to be maintained in the spec.

However, when I try to use the computed metadata feature, it always comes after the metadata explicitly specified in the spec, which is not great.

Having explicit-in-spec metadata always be after the computed metadata would work for me... Not sure if we want something more general.

(When fixing this though, please don't break the ability to do `Text Macro: TWITTER streamsstandard` and have that make its way into the computed metadata... I can imagine a simple "process computed first" change breaking that.)

**Comment by tabatkins** [comment]
Yeah, I can't change the processing order; computed metadata *has* to go after the others.  What I need is to add the more general "reorder the metadata" facility that I've wanted for a while.

**Comment by tabatkins** [comment]
Thinking about something like:

`Metadata Order: *, Participate, Commits`

Maybe have some extra wildcard categories, like `custom*`, so the default value would be `*, custom*` to reflect the current ordering of "custom after all the built-ins".

**Comment by domenic** [comment]
That sounds absolutely perfect.

**Comment by domenic** [comment]
Would it also allow omitting metadata? E.g. if we generate "Tests" metadata for all WHATWG specs, but want to omit it in some, we could just do `Metadata Order: Participate, Commits`?

**Comment by tabatkins** [comment]
Yeah, either thru this or something else.  Maybe just a "-Foo" token in the value meaning "omit this metadata".

**Comment by tabatkins** [comment]
Ah, no, nm, this is something you'll want to be able to build up and override piecemeal, while the Metadata Order is something that is overridden fully by a later value. So I'll instead need a separate metadata that controls whether certain things are shown/hidden by default.  It'll be a comma-separated list of tokens/boolish values, like I use elsewhere.

(If the Metadata Order doesn't include something, either explicitly or via a `*` token, it'll be implicitly omitted, of course.)

**Comment by tabatkins** [comment]
Working on this right now, and ran into a situation I'm not sure about:

If you specify a key explicitly in `Metadata Order`, but that key isn't present in the spec's actual metadata, should I just skip over it, or log an error?  If the latter, should it be a fatal error, or just a warning?  It doesn't matter to my implementation what happens, I'm just not sure what would be most useful to you.

**Comment by domenic** [comment]
Ah, good question! At first I was thinking error, but after some thought I think it should skip over it. This enables cases like listing all of the metadatas in the OP in the master whatwg.include. Then ones that don't apply to a specific spec can just be not included it in that spec (instead of having to override `Metadata Order`).

**Comment by tabatkins** [comment]
That was my exact leanings, cool.

**Comment by tabatkins** [comment]
Done! Documented in <https://tabatkins.github.io/bikeshed/#rearranging-metadata>

**Comment by domenic** [comment]
Awesome! I'll try to work on updating whatwg to use these; we might end up needing a whatwg2 for a transitional period.
