### ISSUE TITLE
Combining Assume Explicit For and link-for-hint doesn't quite work right

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1061]
Given [`Assume Explicit For: yes`](https://tabatkins.github.io/bikeshed/#metadata-assume-explicit-for) and a [`link-for-hint="hint"`](https://tabatkins.github.io/bikeshed/#link-types) the autolink `[=foo=]` should first try to link to `[=hint/foo=]`, then `[=/foo=]`, and if neither exists, give an error. Right now, it appears to search for only `[=/foo=]`.

**Comment by tabatkins** [comment]
Okay, so I think this is how we want the three functionalities to interact:

for=A | forHint=B | explicitFor
✘ | ✘ | ✘ = anything
✔ | ✘ | ✘ = A/
✘ | ✔ | ✘ = B/, fallback to anything
✘ | ✘ | ✔ = /
✔ | ✔ | ✘ = A/
✔ | ✘ | ✔ = A/
✘ | ✔ | ✔ = B/, fallback to /
✔ | ✔ | ✔ = A/

Right?

**Comment by tabatkins** [comment]
And done! Looks like it works from tests, let me know if you have any trouble.
