### ISSUE TITLE
provide for explicit folding of Title without messing up the titlebar's content

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#1065]
If one has a lengthy Title (or `<H1>` value), BS runs it other towards the right and folds it at or near the obligatory [W3C] icon in upper right-hand corner of beginning of the rendered spec.  For some lengthy titles, this is suboptimal, eg for [Web Authentication](https://w3c.github.io/webauthn/). For the latter, I wanted "Web Authentication:" to be on the first title line, and the subtitle on the 2nd, and then the spec Level on the third.  

Experimentation revealed that placing `<br>`s in the title value, or `<H1>` in our case, yields explicit title folding, yay!

However, the document title as rendered by the browser+OS in the browser window's titlebar (if one has them config'd on, eg as I do with Firefox) is the literal title source value, including the explicit `<br>`s.  This unrendered literal title value is also used by chrome and safari (but not FF, go figure) in the location-bar pop-down list of potentially matching location bar values.

**Comment by tabatkins** [comment]
This is what the H1 metadata is for - if you specify it, it's used as the H1 text, and Title is only used for the title element. 😀

**Comment by equalsJeffH** [comment]
Ok, thanks, that helped me figure things out.  Though, the bikeshed documentation is unclear about this IMV. Here's the revised beginning of the webauthn spec that may help illustrate the sort of detail that would be nice in the BS doc...
```
<!--   ***********  Web Authentication - Level 1 - Spec source file *********** 
Notes:
* the h1 tag is the spec title that is rendered within the document window. Wrapping 
  may be controlled with break tags.  The spec 'Level' value is not appended.
* the Title metadata value is what is rendered in the browser's titlebar, any break 
  tags will be rendered. It also has the spec 'Level' value (gratuitously) appended. 
-->

<h1>Web Authentication:<br>An API for accessing Public Key Credentials<br>Level 1</h1>
<pre class='metadata'>
Title: Web Authentication: An API for accessing Public Key Credentials - Level 
```

**Comment by tabatkins** [comment]
Ugh, you're right, the H1 metadata isn't documented at all. Sorry about that, fixing now.
