### ISSUE TITLE
Putting <script> in <head>

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1071]
Basically each WHATWG standard has three script elements that would be nicer if they could be placed at the end of `<head>` so fetching can start earlier (they're all async/defer).

If the WHATWG-specific template thing gets fixed first though I reckon we no longer need this.

cc @domenic

**Comment by tabatkins** [comment]
What's the "WHATWG-specific template thing"?

If all the WHATWG specs use this the same way, it should just be in the boilerplate. Are y'all all putting the same `<script>` elements manually into each of your specs?

**Comment by annevk** [comment]
I thought you and @domenic had a plan to create WHATWG-specific boilerplate.

And yeah, that's what's happening. I guess I always forget that we can uplift things to Bikeshed.

**Comment by domenic** [comment]
I basically keep delaying because when we do so we need to update every spec. So I'd rather do it once. Which means I'd like to roll in https://github.com/whatwg/meta/issues/23 as well. Which is somewhat blocked on DOM/MIME Sniffing breaking the pattern, plus on https://github.com/tabatkins/bikeshed/issues/1058.

**Comment by annevk** [comment]
What if we keep the current setup around as well as legacy so we can gradually roll this out?

**Comment by domenic** [comment]
So some specs use whatwg and some use whatwg-new or something?

**Comment by annevk** [comment]
Basically, to ease the transition and spread the risk.

**Comment by domenic** [comment]
Yeah, that'll definitely work; it just means a few extra meta commits per spec which I was trying to avoid, but it's probably the right thing to do. I can work on it, although getting #1058 fixed first would be ideal.

**Comment by tabatkins** [comment]
Should I do anything with this, then, or can I close it and y'all will adjust/add boilerplate?

**Comment by domenic** [comment]
I think we can handle this entirely in the boilerplate, yeah, but maybe we can wait for @annevk to confirm he didn't have a different idea.

**Comment by annevk** [comment]
Sounds fine.
