### ISSUE TITLE
Duplicate generated "Abstract" and "Table of Contents" titles

### ISSUE THREAD

**Issue by SimonSapin** [tabatkins/bikeshed#1084]
Regenerating https://github.com/SimonSapin/wtf-8/blob/gh-pages/index.src.html shows warnings:

```
WARNING: Multiple elements have the same ID 'abstract'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'contents'.
Deduping, but this ID may not be stable across revisions.
 ✔  Successfully generated, with warnings
```

The source does not define either of these IDs. In the generated boilerplate, these two titles are indeed duplicated:
![screenshot from 2017-08-31 09-41-51](https://user-images.githubusercontent.com/291359/29912065-a40dadc6-8e30-11e7-8846-c772995a13aa.png)

**Comment by tabatkins** [comment]
A change some time ago moved header generation for those two sections to be automatic, so it didn't need to be in the boilerplate anymore. I filed <https://github.com/SimonSapin/wtf-8/pull/9> to fix your boilerplate.

**Comment by tabatkins** [comment]
(If you're using WHATWG styling, try using `Group: WHATWG` to get their up-to-date boilerplate automatically? Hopefully it works for you.)
