### ISSUE TITLE
Defining a method in a header is now ugly (monospace)

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1087]
Compare old: https://streams.spec.whatwg.org/commit-snapshots/26ba2c5de34c785778bc5ad3ca7d14eed7c6c4ef/#rs-prototype

with new: https://streams.spec.whatwg.org/#rs-prototype

I thought this might be because of our build post-processing step, but I [removed that from console](https://github.com/whatwg/console/pull/116) and it's still ugly.

At a minimum I think the section marker and the section number should stay in the normal font, even if the actual text of the header becomes monospace.

**Comment by tabatkins** [comment]
Ah, agreed, this is just the "wrap IDL stuff in `<code>`" getting a little trigger-happy.  I'll specially detect headers and avoid doing that.

(I can't even just move it down to the actual header text, as it might not be all code.  You can just use `code` directly if necessary, or autolinks in the text.)

**Comment by tabatkins** [comment]
Should be good now.

**Comment by domenic** [comment]
Hmm, I re-ran the build for whatwg/console and am still getting the ugly headers. Maybe this didn't deploy to the CSSWG servers?
