### ISSUE TITLE
Option to only link terms the first time they appear in a paragraph/section.

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#1089]
The WebIDL spec is littered with paragraphs that link to the same term multiple times, e.g.:

```
An [=ordered map=] with string [=map/keys=] can be implicitly treated as a [=dictionary=] value of a
specific [=dictionary=] |D| if all of its [=map/entries=] correspond to [=dictionary members=], in the
correct order and with the correct types, and with appropriate [=map/entries=] for any required
[=dictionary members=].
```

This ends-up being hard on the eye when reading and sort of redundant, so one option is to manually avoid the repetition, e.g.:

```
An [=ordered map=] with string [=map/keys=] can be implicitly treated as a [=dictionary=] value of a
specific dictionary |D| if all of its [=map/entries=] correspond to [=dictionary members=], in the
correct order and with the correct types, and with appropriate entries for any required
dictionary members.
```

That's a lot harder to maintain however, as you have to remember to markup terms later in the paragraph or section when you're removing marked-up, and make sure you're not duplicating marked-up terms when you're adding new content.

It's hard to keep consistent.

It's a lot easier to delegate this task to Bikeshed. We'd be able to markup all terms without having to take this into consideration, and have Bikeshed only transform the first one per section/paragraph into an anchor. This would probably need to be an opt-in enum (`off`, `paragraph`, `section`).

Note it might be necessary to introduce extra markup to indicate terms that need to be marked up no matter their position in the paragraph or section.

**Comment by tabatkins** [comment]
There you go. I have not yet added anything to allow forcing an autolink to stay where it is; if you do end up needing it, let me know.

**Comment by tabatkins** [comment]
(It's just a boolean, and only counts per-parent-element right now. Per section is too large to safely do, I think.)

**Comment by tobie** [comment]
Wow! Thanks!
