### ISSUE TITLE
`overlarge` class breaks alignment of tables.

### ISSUE THREAD

**Issue by jakearchibald** [tabatkins/bikeshed#1090]
See https://wicg.github.io/background-fetch/#events at wider widths.

<img width="1063" alt="screen shot 2017-09-11 at 17 58 08" src="https://user-images.githubusercontent.com/93594/30286810-d519f2ec-971a-11e7-8a12-0bdfb69ca192.png">

**Comment by tabatkins** [comment]
See <https://github.com/w3c/tr-design/issues/86> and <https://github.com/w3c/tr-design/issues/104>. :(

**Comment by tabatkins** [comment]
Fixed in Bikeshed by 01f91429, I'm gonna go PR tr-design now to fix it for everything else.
