### ISSUE TITLE
<script type=idl>

### ISSUE THREAD

**Issue by jakearchibald** [tabatkins/bikeshed#1091]
Having to do `Promise&lt;FrozenArray&lt;DOMString&gt;&gt;` is a pain. `<xmp>` helps, but code highlighters don't have great support for it.

```html
<pre class="idl"><xmp>
  [Exposed=(Window,Worker)]
  interface BackgroundFetchManager {
    Promise<BackgroundFetchRegistration> fetch(DOMString id, (RequestInfo or sequence<RequestInfo>) requests, optional BackgroundFetchOptions options);
    Promise<BackgroundFetchRegistration?> get(DOMString id);
    Promise<FrozenArray<DOMString>> getIds();
  };
</xmp></pre>
```

Whereas `<script type=idl>` could work better:

```html
<script type="idl">
  [Exposed=(Window,Worker)]
  interface BackgroundFetchManager {
    Promise<BackgroundFetchRegistration> fetch(DOMString id, (RequestInfo or sequence<RequestInfo>) requests, optional BackgroundFetchOptions options);
    Promise<BackgroundFetchRegistration?> get(DOMString id);
    Promise<FrozenArray<DOMString>> getIds();
  };
</script>
```

**Comment by tabatkins** [comment]
Your highlighter will apply arbitrary/configurable highlighting to `script` elements?

**Comment by jakearchibald** [comment]
I'm not sure, but it won't highlight it as HTML. Similar to what Github is doing above.

**Comment by tabatkins** [comment]
(I'm going ahead and adding this now, but also I just noticed: you can just do `<xmp class=idl>...</xmp>`, you know? No need to have a wrapping `<pre>`.)

**Comment by jakearchibald** [comment]
Ohh that's cool! Doesn't fix the highlighting issue, but good to know!

Thanks for making this change.

**Comment by jakearchibald** [comment]
Thanks!
