### ISSUE TITLE
Should bikeshed pick index.bs by default?

### ISSUE THREAD

**Issue by alexshalamov** [tabatkins/bikeshed#1103]
We have two .bs files in [sensors repo](https://github.com/w3c/sensors) index.bs and usecases.bs. The `glob("*.bs")` returns entries in 'arbitrary' order `[u'usecases.bs', u'index.bs']`, thus, usecases.bs is picked by default.

https://github.com/tabatkins/bikeshed/blob/afd377055fd60b78052b08cc89f300fd74918048/bikeshed/Spec.py#L45

Should the bikeshed prefer index.bs if no spec files were specified?

//cc @anssiko

**Comment by xfq** [comment]
And `Overview.bs`, I think, because CSSWG uses this name.

**Comment by tabatkins** [comment]
Yeah, I'm down with preferring index.bs or Overview.bs if they're found.

**Comment by tabatkins** [comment]
All right, should work now. Let me know if there are any issues!

**Comment by anssiko** [comment]
I can confirm this patch fixed the issue for w3c/sensors. Thanks again for the amazingly fast response and fix!
