### ISSUE TITLE
"Terms defined by reference" using wrong spec names

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1105]
https://infra.spec.whatwg.org/#index-defined-elsewhere says [encoding-1] instead of [ENCODING], mismatching https://infra.spec.whatwg.org/#informative

**Comment by domenic** [comment]
This may also be related to things going in the wrong category of informative vs. normative references https://github.com/whatwg/infra/pull/156#issuecomment-333126813

**Comment by tabatkins** [comment]
Yup, these are slightly different manifestations of the same bug; the latter is being tracked with more detail in #1106.

**Comment by tabatkins** [comment]
Looks like both bugs are fixed now, yay!
