### ISSUE TITLE
Weird behavior when there's a newline in the <a> tag

### ISSUE THREAD

**Issue by xfq** [tabatkins/bikeshed#1107]
In https://github.com/w3c/csswg-drafts/blob/6a67fdf299e5711eeb63c9672554cf62241b56af/css-text/Overview.bs#L513-L514:

```
<a href="http://rhodesmill.org/brandon/2012/one-sentence-per-line/"
>breaking the source into segments</a>
```

In the generated HTML file, it becomes:

```
<a U0003Cblockquote="" href="http://rhodesmill.org/brandon/2012/one-sentence-per-line/"> </a></p>
   <p><a U0003Cblockquote="" href="http://rhodesmill.org/brandon/2012/one-sentence-per-line/">breaking the source into segments</a>
```
If I remove the newline before the `>`, then the HTML is:

```
<a href="http://rhodesmill.org/brandon/2012/one-sentence-per-line/">breaking the source into segments</a>
```

which is correct.

**Comment by tabatkins** [comment]
This is because of my newly-added support for Markdown blockquotes - the second line is recognized as starting a blockquote segment. ^_^

That's some super bizarre markup in the first place, I'll just go fix Text.
