### ISSUE TITLE
Defining a method in a header is still ugly (monospace) 

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1108]
https://github.com/tabatkins/bikeshed/issues/1087 was marked fixed, but the problem is still appearing on console.spec.whatwg.org and streams.spec.whatwg.org.

Notably, https://github.com/tabatkins/bikeshed/commit/b8808d7e50f970e031d778b05900bc6ccb95b9f0, which purports to fix it, does not contain any tests.

**Comment by tabatkins** [comment]
Sorry about that, reopened the original issue, and closing this one.
