### ISSUE TITLE
Couldn't retrieve the file 'biblio/biblio-h5.data' from cache.

### ISSUE THREAD

**Issue by andypaicu** [tabatkins/bikeshed#1112]
As a continuation to https://github.com/tabatkins/bikeshed/issues/1110.

```
WARNING: The following <var>s were only used once in the document:
  'bypass due to integrity match', in algorithm 'script-src Pre-request check'
If these are not typos, please add an ignore='' attribute to the <var>.
FATAL ERROR: Couldn't retrieve the file 'biblio/biblio-h5.data' from cache. Something's wrong, please report this.
 ✘  Did not generate, due to fatal errors
The command "bikeshed spec ./index.src.html" exited with 1.
```

This happens both locally and on travis when building the webappsec-csp spec.

This is the PR it's happening on https://github.com/w3c/webappsec-csp/pull/247

**Comment by tabatkins** [comment]
Ah, thanks. Looks like this bug has been around for quite some time, but nobody managed to trigger it (it requires you to try to load a biblio ref whose first two letters aren't shared by a single thing in SpecRef).
