### ISSUE TITLE
`bikeshed spec` returns 0 despite link error

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1113]
https://travis-ci.org/w3c/webauthn/builds/286696061 succeeds even though there's a link error. I'd like either `bikeshed spec` to return a non-0 error code when there's a non-fatal link error or have an option to do so.

**Comment by tabatkins** [comment]
I was waiting for someone to ask for a way to kill the generation on link error.  It's very intentionally not what I'm doing by default (link errors *used to be* just plain fatal errors, I separated them out on purpose), but I'm happy to add a metadata to turn them fatal again.

**Comment by jyasskin** [comment]
For interactive use, it's great that we can get a spec generated even with link errors, but for interactive use I don't care about the exit code. If there's a metadata to make them set a non-0 exit code, I think I'd still want interactive use to be able to generate the spec.

**Comment by tabatkins** [comment]
That's what command-line metadata setting is for - you can pass `--md-Link-Errors-Are-Fatal="yes"` (or whatever I end up calling it) when Travis builds the spec.

**Comment by jyasskin** [comment]
'k, sounds good.

**Comment by xfq** [comment]
So this issue can be closed, I guess?

(It'd be good to document this, though.)

**Comment by tabatkins** [comment]
No, I haven't implemented the feature yet. 😀

**Comment by kainino0x** [comment]
Bump; we want this in gpuweb! We accidentally introduce things like `bool` when we meant `boolean`, which is a linker error because `bool` is a valid but unknown identifier.

**Comment by kainino0x** [comment]
@beaufortfrancois seems to have figured out that there's already an option (`--die-on`) for this in https://github.com/gpuweb/gpuweb/pull/366. Maybe this needs to be closed? :)

**Comment by jyasskin** [comment]
Yep, documented at https://tabatkins.github.io/bikeshed/#cli-options. Thanks!
