### ISSUE TITLE
Clickable links to WebIDL types like DOMString?

### ISSUE THREAD

**Issue by littledan** [tabatkins/bikeshed#1118]
Is there some mode of using Bikeshed that would generate these links? I would've expected it to be in the default bibliography. This came up as a question in [reviewing the WebAssembly/JS interface specification](https://github.com/WebAssembly/spec/pull/591).

**Comment by domenic** [comment]
It appears they are generated, but only in some contexts. E.g. they are linked in https://littledan.github.io/spec/document/JS.html#dictdef-moduleimportdescriptor but not in https://littledan.github.io/spec/document/JS.html#typedefdef-instanceexportsmap .

It may be in fact that only `record<>`s are missing the links. In any case, a good Bikeshed bug find.

**Comment by tabatkins** [comment]
Looks like this is a widlparser bug; specifically, the first type in a `record<>` isn't being parsed as the correct sort of thing, so it doesn't get passed to the right function to mark it up as an autolink.  I've reported this (linked above), will fix as soon as widlparser updates.

**Comment by tabatkins** [comment]
Fixed, thanks.
