### ISSUE TITLE
Add support for WebIDL mixins

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#1124]
Hi all!

WebIDL recently introduced [dedicated syntax for mixins][0].

This syntax replaces the `[NoInterfaceObject]` extended attribute and `implements statement` which have been deprecated (except for a few [legacy uses cases][1] explicitely mentioned in the spec).

You can read more about it [here][2].

In most cases, the changes should be relatively straightforward. The now deprecated:

```webidl
interface Foo { };

[NoInterfaceObject]  // (Mostly) DEPRECATED
interface Bar { };
Foo implementes Bar; // DEPRECATED
```

should just be rewritten as:

```webidl
interface Foo { };

interface mixin Bar { };
Foo includes Bar;
```

We're filing issues against specs which use the deprecated syntax, but we welcome help to warn editors about these changes.

We also filed an issue against widlparser here: plinss/widlparser#32.

Please feel free to reach out if you have any questions.

Thanks!

[0]: https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920
[1]: https://heycam.github.io/webidl/#NoInterfaceObject
[2]: https://heycam.github.io/webidl/#idl-interface-mixins

***

*Tracked in: heycam/webidl#472* | *Original pull-request: heycam/webidl#433*

**Comment by plinss** [comment]
widlparser has been updated to support mixins thanks to @romandev

**Comment by tobie** [comment]
\o/ How long does this take to be deployed on the Web service?

**Comment by tabatkins** [comment]
Should only be a few minutes - it uses a webhook to be notified of the commits as they come in.
