### ISSUE TITLE
Shepherd: please add permissions.{request,revoke}

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1129]
These are in https://jyasskin.github.io/permissions-request/ and https://jyasskin.github.io/permissions-revoke/.

**Comment by tabatkins** [comment]
Out of curiosity, is there a reason these aren't moved to under the WICG/ org?

**Comment by jyasskin** [comment]
Now they're https://wicg.github.io/permissions-request/ and https://wicg.github.io/permissions-revoke/. Thanks!

**Comment by tabatkins** [comment]
Done. Give it a bit for Shepherd to parse stuff.
