### ISSUE TITLE
Not finding SpecRef update

### ISSUE THREAD

**Issue by apowers313** [tabatkins/bikeshed#1135]
I made an update to SpecRef: tobie/specref#420

But the new reference isn't showing up in Bikeshed:

> Cthulhu:fido-2-specs apowers$ bikeshed update
Updating via manifest...
Local data is already up-to-date (2017-10-25 18:44:42.327425). Done!
Cthulhu:fido-2-specs apowers$ make watch WATCH=fido-client-to-authenticator-protocol.bs
rm -rf fido biblio.json \*.include fido-client-to-authenticator-protocol.html
cp resources/bikeshed/*.include .
cp resources/bikeshed/biblio.json .
bikeshed watch fido-client-to-authenticator-protocol.bs
FATAL ERROR: Couldn't find 'IANA-COSE' in bibliography data. Did you mean:
  iana-cose-algs-reg
  iana-tsv
  rdfa-core
  saml2-core
  poi-core
  aria-role
 ✔  Successfully generated, but fatal errors were suppressed
==============DONE==============

Any suggestions of how to fix or debug this?

**Comment by tabatkins** [comment]
Did you run `bikeshed update`?

**Comment by tabatkins** [comment]
Oh, you did. 😀 It's probably waiting for the manifest-file update script to run. That should happen every ten minutes or so, as long as my machine is still running. I'll go check it.

**Comment by tabatkins** [comment]
And yup, that script have updated anything in quite a while. I'll poke at it.

**Comment by tabatkins** [comment]
I went ahead and manually ran the script, will debug why it's not auto-running later. Confirmed that IANA-COSE shows up in the most recent data.

**Comment by apowers313** [comment]
That did the trick, thanks.

I'm curious about workflow now -- does W3C not add new references to SpecRef very often?

**Comment by tabatkins** [comment]
W3C publications get added to SpecRef automatically (there's a data file that's automatically kept up-to-date, and periodically polled by the SpecRef server).  Then, totally separately, Bikeshed's db-builder (<https://github.com/tabatkins/bikeshed-data>) periodically polls SpecRef and constructs the biblio db files, then commits them to its repo. Then Bikeshed itself gets the updated files when you run `bikeshed update`.

It's a little Rube-Goldbergian, but it works and lets everyone who's interested in each part of the stack maintain stuff to their own satisfaction. ^_^

**Comment by tabatkins** [comment]
Found the bug preventing it from updating some time ago, and the `bikeshed-data` repo is indeed chugging along nicely now, so looks like this can be closed.
