### ISSUE TITLE
bikeshed is inserting garbage characters

### ISSUE THREAD

**Issue by smfr** [tabatkins/bikeshed#1137]
Running bikeshed on css-transforms-1:
> make REMOTE=1

Resulting .html file has:

`    <p>Because of the participation to the CSS cascade, the <a class="property" data-link-type="propdesc" href="#propdef-transform" id="ref-for-propdef-transform①③">transform</a> style property overrides the <a data-link-type="element-attr" href="https://www.w3.org/TR/SVG11/coords.html#TransformAttribute" id="ref-for-TransformAttribute⑤">transform</a> presentation attribute. Therefore the container gets translated by <span class="css">100px</span> in both the horizontal and the vertical directions, instead of <span class="css">200px</span>.</p>
`
Note the `"ref-for-propdef-transform①③"`. Those bad characters are \0x2460\0x2462

**Comment by tabatkins** [comment]
That's correct. All of the autolinks gain an automatically-generated ID, and if you have more than one linking to the same dfn, they IDs would collide, so I dedup them automatically. To avoid weird visual clashes with dfns that end in digits already, I used circled digits to write the deduping number.

Can you not see those characters in your text editor?

**Comment by smfr** [comment]
I did see them in the editor and assumed they were a mistake :)
