### ISSUE TITLE
HTML comments in <pre> blocks throw fatal error

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#1139]
in the past several days, bikeshed began throwing a fatal error due to HTML comments in \<pre> blocks:
> >$ bikeshed spec
> > LINE 65: Line doesn't match the grammar `k:v; k:v; k:v`:
> >&lt;!--line count correction 0--&gt;
> > ERR Did not generate, due to fatal errors

> yeah, I figured that out in order to get webauthn PR #693 to build (see https://github.com/w3c/webauthn/pull/693/commits/f728b911e1f297f820de199551007e9f99359fbf)

**Comment by equalsJeffH** [comment]
in https://github.com/w3c/webauthn/issues/692#issuecomment-345770289, @emlun reports:

The bikeshed issue appeared in bikeshed commit [aa80a167c54650c1c8f2382945f3894ee5b80bb4](https://github.com/tabatkins/bikeshed/commit/aa80a167c54650c1c8f2382945f3894ee5b80bb4).

**Comment by xfq** [comment]
Bikeshed emits a similar error when encountering HTML comments in CSS propdefs: https://github.com/w3c/csswg-drafts/blob/85d366602c156b1735da30d99b68f3fe0908ed60/css-inline-3/Overview.bs#L247

```
FATAL ERROR: Incorrectly formatted propdef line for 'baseline-shift':
<!--line count correction 0-->

LINK ERROR: No 'dfn' refs found for 'basline alignment'.
<a data-link-type="dfn" data-lt="basline alignment">basline alignment</a>
```

**Comment by apowers313** [comment]
Hi @tabatkins -- just curious if this is a bug that eventually gets solved, or if we should consider our markdown incorrect and remove the comments from our files. Thanks!

**Comment by tabatkins** [comment]
I'm on vacation so it won't be fixed until next year, but it's something
I'll fix, yeah.

**Comment by apowers313** [comment]
Awesome, thanks. Have a good vacation. :)

**Comment by tabatkins** [comment]
I've changed my line-number handling substantially, and no longer insert comments to track changes in that. So hopefully this should now be fixed by default?

**Comment by tabatkins** [comment]
(All comments you put in manually were always okay; they get stripped early by Bikeshed, before any further processing happens. This issue was due to additional comments that Bikeshed inserted by itself, later in the process.)

**Comment by xfq** [comment]
Verified for css-inline-3. Thank you, Tab!
