### ISSUE TITLE
Old W3C patent policy link

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#1145]
Using Bikeshed to generate W3C /TR specification now gives the error:

> The patent policy (https://www.w3.org/Consortium/Patent-Policy-20040205/) you are using is no longer allowed.

Instead, it should link to the latest policy - currently the  5 February 2004 (updated 1 August 2017) policy, using an _undated_ url:
https://www.w3.org/Consortium/Patent-Policy/

This markup seems to satisfy the pubrules checker:

```
This document was produced by a group operating under
	the <a href="https://www.w3.org/Consortium/Patent-Policy/">W3C Patent Policy</a>.
```

See pubrules https://www.w3.org/pubrules/doc/rules/?profile=CR#patPolReq

**Comment by svgeesus** [comment]
I was going to do a PR but the string [occurs everywhere](https://github.com/tabatkins/bikeshed/search?utf8=%E2%9C%93&q=W3C+Patent+Policy&type=) which I suspect means you generate it somehow.

**Comment by svgeesus** [comment]
Also, the checker doesn't moan but I would guess these other two occurences should be converted to undated links too:

```
An individual who has actual knowledge of a patent which the individual believes contains <a href="https://www.w3.org/Consortium/Patent-Policy/#def-essential">Essential Claim(s)</a> must disclose the information in accordance with <a href="https://www.w3.org/Consortium/Patent-Policy/#sec-Disclosure">section 6 of the W3C Patent Policy</a>.
```

**Comment by tabatkins** [comment]
No, I don't generate it. There's just lots of copy-pasting in the boilerplates.

**Comment by xfq** [comment]
@svgeesus Please note that I haven't take the time to fix the boilerplate for all WGs yet, e.g., CSSWG still refers to the 5 February 2004 policy for the moment.
