### ISSUE TITLE
broken link on TR version

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1151]
When generating CSS-UI-3 as an ED, `<a spec=css-writing-modes-3>left</a>` correctly points to

https://drafts.csswg.org/css-writing-modes-3/#physical-left

When generating it as a CR or a PR, it points to

https://www.w3.org/TR/css-writing-modes-3/#left

The spec is right, but the anchor does not exist. It should have linked to

https://www.w3.org/TR/css-writing-modes-3/#physical-left

Not sure this is entirely bikeshed's fault, but that bug is exposed to me via bikeshed, so that's where I'm reporting it. Please pass it along to wherever the right place is if it's not here.

**Comment by frivoal** [comment]
cc @svgeesus

**Comment by svgeesus** [comment]
Is this still happening?

**Comment by frivoal** [comment]
No, seems good now.
