### ISSUE TITLE
CSS property value not linked to definition

### ISSUE THREAD

**Issue by dirkschulze** [tabatkins/bikeshed#1160]
In Filter Effects I have an issue where a CSS property value, a keyword, is not automatically referenced to its definition: https://github.com/w3c/fxtf-drafts/blob/master/filter-effects/Overview.bs#L2955

Maybe I made a mistake somewhere? I even tried the prefix `color-interpolation-filters/` the value to make it easier for Bikeshed to find the right property but it still does not work. Neither `''sRGB''` nor `''color-interpolation-filters/sRGB''` references the definition of `sRGB`.

```
<pre class='propdef'>
Name: color-interpolation-filters
Value: auto | sRGB | linearRGB
Initial: auto
Applies to: All <a>filter primitives</a>
Inherited: yes
Percentages: n/a
Computed value: as specified
Media: visual
Animatable: no
</pre>

<dl dfn-for=color-interpolation-filters>
    : <dfn>auto</dfn>
    :: Indicates that the user agent can choose either the ''color-interpolation-filters/sRGB'' or ''color-interpolation-filters/linearRGB'' spaces for filter effects color operations. This option indicates that the author doesn't require that color operations occur in a particular color space.
    : <dfn>sRGB</dfn>
    :: Indicates that filter effects color operations should occur in the sRGB color space.
    : <dfn>linearRGB</dfn>
    :: Indicates that filter effects color operations should occur in the linearized RGB color space.
</dl>
```

**Comment by tabatkins** [comment]
It needs to know what type the dfns are - add a `dfn-type=value` to the dl and it'll work.

**Comment by dirkschulze** [comment]
It indeed does. Thanks.
