### ISSUE TITLE
Merging custom keys from computed meta + in-document metadata doesn't seem to work

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1161]
This can be seen in https://github.com/whatwg/dom/pull/553 and https://github.com/whatwg/mimesniff/pull/54 with https://github.com/tabatkins/bikeshed/pull/1155 applied. I haven't tried for a minimal repro, but the basic setup is:

computed-metadata.include:

```json
{
  "!Participate": [
    "<a href=https://github.com/whatwg/[SHORTNAME]>GitHub whatwg/[SHORTNAME]</a> (<a href=https://github.com/whatwg/[SHORTNAME]/issues/new>new issue</a>, <a href=https://github.com/whatwg/[SHORTNAME]/issues>open issues</a>)",
    "<a href=https://wiki.whatwg.org/wiki/IRC>IRC: #whatwg on Freenode</a>"
  ],
  ...
}
```

spec.bs:

```html
<pre class=metadata>
...
!Participate: <a href="https://www.w3.org/Bugs/Public/buglist.cgi?product=WHATWG&amp;component=MIME&amp;resolution=---">legacy open bugs</a>
</pre>
```

The fix here should be sure to group them together according to the `Metadata Order`.

**Comment by tabatkins** [comment]
Spotted the problem - the default "join" strategy between different sources for custom metadata (anything with a `!`) is to override whatever was specified previously. That seems like it's probably a bad behavior - it's inconsistent with the default strategy *within* a source, which just appends them to the list and displays them all.

I'll change it to be consistent and append in both cases. Let me know if I need to offer more functionality here and give you a choice between the two (like a "clear" option or something).

**Comment by tabatkins** [comment]
Done, and confirmed that it works as desired with your reduction.  They'll append in priority order - defaults, then in-document, then command line, then computed-metadata, and maintain their relative ordering within each of those categories.

**Comment by domenic** [comment]
Hmm, for our purposes computed-metadata is higher priority than in-document, but it's not a big deal.

**Comment by tabatkins** [comment]
Yes, that's what I mean - the list I gave is the order they'll show up in. So computed-metadata will always show up last.

**Comment by domenic** [comment]
Yeah, whereas it'd be kind of nicer if those "defaults" showed up first, whereas the in-document "extras" showed up at the bottom of the "Participate" list. But again, not a big deal.

**Comment by tabatkins** [comment]
Doing that reasonably would require me to finally do the correctness-rewrite of metadata handling I've been intending for a while. Something for the future. ^_^
