### ISSUE TITLE
wrong case in title and h1 for paper number in wg21 papers

### ISSUE THREAD

**Issue by zygoloid** [tabatkins/bikeshed#1185]
Probably specific to "Group: wg21"

bikeshed nicely concatenates the Shortname and Revision with an intervening 'r' to form text that is inserted into the title and h1 for a paper. However, WG21 convention is that the paper number and the 'r' be capitalized when naming a paper (the lowercase name is used only for filenames of papers). Instead of:

> # p1234r5<br>Name of Proposal
> ## Draft Proposal, 10 February 2018
> *This version:* http://wg21.link/p1234r5

it would be preferable to produce:

> # P1234R5<br>Name of Proposal
> ## Draft Proposal, 10 February 2018
> *This version:* http://wg21.link/p1234r5

Note that the filename for the paper is in all-lowercase, but the paper number itself is always all-uppercase. (Ideally, the "URL:" field would be inferred from the shortname and revision too, for "Group: wg21".)

**Comment by jfbastien** [comment]
That was probably my misunderstanding. Proposed fix for the "R" capitalization in #1186. The "P" comes from the shortname directly, maybe bikeshed needs to have a "capitalize" feature, or y'know, capitalize the shortname.

Agreed on the URL bit. Wouldn't be too hard to do but I'm lazy. 😉
