### ISSUE TITLE
bikeshed template uses markdown sections

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1221]
When running `bikeshed template`, the template produces is:

```
<pre class='metadata'>
Title: Your Spec Title
Shortname: your-spec
Level: 1
Status: ED
Group: WGNAMEORWHATEVER
URL: http://example.com/url-this-spec-will-live-at
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract: A short description of your spec, one or two sentences.
</pre>

Introduction {#intro}
=====================

Introduction here.
```

My understanding is that you only get two levels here.  I would think
most specs have more than that.  And if you add more sections in this
style, bikeshed will print warnings that you should provide IDs for the
headings and suggests

```
  <h3 class="heading" data-level="1.1" id="subsection-sub"><span class="content">subsection (#sub)</span></h3>
```

**Comment by tabatkins** [comment]
Nah, Markdown headings go all the way down. `===` underline and `---` underline are the first two levels; after that you need to wrap them in three or more `#`, like

```
### Third-level heading ###
```

> And if you add more sections in this
style, bikeshed will print warnings that you should provide IDs for the
headings and suggests

Note the `{#intro}` thing in the heading - that's how you add an ID in markdown-style headings. It works for the `###`-headings too.
