### ISSUE TITLE
Add an option to turn off syntax highlighting

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1240]
You can currently omit the syntax highlighting style block using `omit style-syntax-highlighting`. However, Bikeshed still inserts a bunch of spans that are meant to be styled, which add unnecessary weight to the document. It would be nice if there was a way to turn off syntax highlighting completely, both the spans and the style block.

(Spun off of #1239.)

**Comment by tabatkins** [comment]
All right, this (and your other "please remove usability features" issues) have been grouped together under the [`Slim Build Artifact: yes` metadata](https://tabatkins.github.io/bikeshed/#metadata-slim-build-artifact). Turn it on and all of these go away. Feel free to bug me for more features to remove when this is turned on.

**Comment by domenic** [comment]
Web IDL still seems to be syntax highlighted. Otherwise, looking pretty great!!

**Comment by tabatkins** [comment]
Ah, indeed, that's a different code path that relies on the IDL parsing. Will fix.

**Comment by tabatkins** [comment]
And done. WebIDL no longer looks highlighted, and the spans that are added solely for highlighting purposes are removed.

**Comment by domenic** [comment]
Nice. Down to 877 KiB, and I think that's pretty much everything I could imagine stripping. \o/

**Comment by tabatkins** [comment]
There's definitely some classes I could go thru and remove if you wanted. ^_^
