### ISSUE TITLE
Do not insert backref anchors if "Use Dfn Panels" is set to false

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1242]
Even if you turn off the dfn panels, various IDs like `id="ref-for-concept-tree-child⑤"` are still inserted into the document, adding unnecessary weight.

(Spun off of #1239.)

**Comment by tabatkins** [comment]
I don't want to key this to dfn-panels directly; the plan is to use these IDs to track (and link to) uses of a term across the spec ecosystem, regardless of whether a spec uses dfn-panels or not.

But I'm happy to add a metadata to turn this off.
