### ISSUE TITLE
Incorrect highlighting for vars

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1247]
For historical reasons the WebAudio spec has things like `<var>detector average</var>` in algorithms.  This all get highlighted nicely, but in one case the bs source got wrapped to

```
        blah blah blah <var>detector
        average</var> blah blah.
```
and bikeshed thinks these are two different variables.

The workaround is obvious: Don't wrap here.  But it's hard to notice this until you go around clicking on all the algorithm variables and seeing the variables highlighted and noticing that something that looks like the same variable isn't highlighted.

Bikeshed doesn't produce a warning that the wrapped variable is single-use either.

**Comment by tabatkins** [comment]
Ah, somehow didn't realize that I was using different rules for comparing vars for same-ness between Python and JS. Harmonized now, and confirmed that linebreaks no longer stop the highlighting.
