### ISSUE TITLE
No entries in ToC sidebar for Abstract and Status?

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1248]
The Table of Contents sidebar doesn't include links to the Abstract or Status of this Document.  Should there be?

There's also no link to get to the beginning of the document where all the boiler plate is. Not sure if that's really needed, but I would find it useful on occasion instead of clicking on the first ToC entry (Introduction) and scrolling to the beginning.

**Comment by tabatkins** [comment]
Those are listed as `no-toc` in most boilerplates. You can turn that off if you want.

For getting to the top of the page, the Home key always works?

**Comment by rtoy** [comment]
Ah.  We're using the default, so I guess we can create our own header.include to do whatever.

I didn't know the Home key did that.  But it seems not to do that in Firefox.

Nothing to do here. Move along.....
