### ISSUE TITLE
Linking to types in argument tables

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1252]
For example, look at https://webaudio.github.io/web-audio-api/#AnalyserNode-constructors

The argument table for the constructor includes types like `BaseAudioContext` and `AnalyserOptions`.  It would be cool if these were links so I could click on one and got the the appropriate section of the spec to see what these really are.

The IDL section for this node actually includes links to the types and that's way cool, so having this in the arguments tables would be equally cool.

**Comment by toji** [comment]
Had someone point me at this, so wanted to point out that it's been a problem for WebGPU as well. I put up a speculative fix but apparently there's a better way to handle it: https://github.com/tabatkins/bikeshed/pull/1744

**Comment by toji** [comment]
Awesome! Thanks for the fix, can't wait to see it showing up in our spec!

**Comment by tabatkins** [comment]
Haven't pushed it to pip quite yet, as pushing on Friday afternoon is
always fraught. Gonna let the bots cycle first. 😃
