### ISSUE TITLE
bikeshed echidna with bikeshed errors

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1254]
The current WebAudio spec has errors from bikeshed, but the generated html is (mostly) correct. (Just missing some links within the spec and links to other specs, more or less.)

I wanted to see what pubrules the current spec has, so I tried `bikeshed echidna -just-tar`.  This stops because of the errors. Would it be possible to add a `-f` flag to generate the result anyway if `-just-tar` is also given?

**Comment by tabatkins** [comment]
The `-f` flag should work on any of the commands, it just has to be given before the sub-command name: `bikeshed -f echidna --just-tar`.

Does that work for you?

**Comment by rtoy** [comment]
Huh. I thought I tried that but must have put the `-f` in the wrong place.  `bikeshed -f echidna --just-tar` works.
