### ISSUE TITLE
Include MathJax for formulas

### ISSUE THREAD

**Issue by dirkschulze** [tabatkins/bikeshed#1257]
The Filter Effects and CSS Transforms spec use formulas. The former spec uses MathJax directly, the latter spec uses raster images created by OpenOffice/LibreOffice.

I wonder if Bikeshed could use MathJax (or another Tex converter tool) to generate SVG as visual rendition to Tex formulas. IMO it doesn't need to be interactive as MathJax itself is. Ideally, MathML could be served as primary rendition but this could be an optional addition later.

**Comment by tabatkins** [comment]
I have a mostly-complete port of KaTeX from JS to Python that I need to brush off and finish, which'll let you inline this stuff.

**Comment by sandersaares** [comment]
Is there inline formula support now? I am confused as the issue is closed, yet I do not see any mention of formulas in the docs.
