### ISSUE TITLE
WG21 / WG14 shortnames should be uppercase

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#1259]
metada.py does:

```
    "Shortname": Metadata("Shortname", "shortname", joinValue, parseLiteralCaseless),
```

That should be parseLiteral for WG21 and WG14, or they should get the same effect (e.g. .toUpper() later). Apparently we have to uppercase the paper number (but, oddly, the files themselves have to be lowercase).

I'm not sure what the less ugly approach would be. Seems like doing it later is better because doing metadata changes while parsing metadata is ugly?

**Comment by tabatkins** [comment]
What I should probably do is hold onto the original case, but also hold a lowercase version for internal purposes. (I normalize the case so I can use the shortname to look in filenames, etc.)

**Comment by jfbastien** [comment]
Works great, thanks!
