### ISSUE TITLE
Dashed lists in Bikeshed

### ISSUE THREAD

**Issue by brycelelbach** [tabatkins/bikeshed#1262]
In the C++ spec, our bulleted lists are bulleted with dashes - specifically, em dashes, e.g. "—". I've been trying to find an easy way to have our bikeshed formatted lists be rendered this way. My understanding from googling is that HTML/CSS doesn't have a native dash option for the list-style-type property.

I've been sticking this into my bikeshed documents and it seems to work:

```
<!-- https://stackoverflow.com/questions/3200249/html-list-style-type-dash -->
ul { margin: 0; list-style-type: none; }
ul > li { text-indent: -5px; }
ul > li:before { content: "—"; text-indent: -5px; }
```

Is there an easy way for us to enable this without custom CSS in Bikeshed?

Side note: Why doesn't CSS have a list-style-type dashed?

**Comment by tabatkins** [comment]
No, that CSS is the only way to do it currently.

> Side note: Why doesn't CSS have a list-style-type dashed?

Ask the original HTML authors, who provided only a few options for bulleted lists.  That said, `list-style-type: "—";` is *specified* in the Lists spec, so it's just a matter of getting implementations up to speed. ^_^

**Comment by jfbastien** [comment]
@brycelelbach do you think we should update the WG21 boilerplate with this style?

**Comment by brycelelbach** [comment]
Yah, I think so.

**Comment by brycelelbach** [comment]
Now I'm doing:

```
li { list-style-type: "— "; }
```

Which seems to be less brittle. The added space is needed, otherwise the emdash is right next to the list content.

**Comment by tabatkins** [comment]
Oh, does that consistently work cross-browser now? If so, great!

**Comment by brycelelbach** [comment]
I only tested on Firefox 52 and Chrome (version circa a year ago, don't remember the number). I'll try IE later.

On any browser that is not supported, it should do no harm (the list just won't be dashed), so I'm not super worried, even though some WG21 members probably use IE 5 or something.

**Comment by jfbastien** [comment]
@brycelelbach can you update the WG21 style with that?
