### ISSUE TITLE
Adding WPT metadata by itself doesn't result in any warnings

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1264]
https://tabatkins.github.io/bikeshed/#testing

> As this defeats Bikeshed’s ability to tell you when you’re missing any tests, Bikeshed will emit a warning as long as a wpt-rest element is in use.

> By default, wpt elements don’t display in the output document; they’re intended to annotate the source file to help with spec authoring, and trigger Bikeshed’s checks.

These two bits together make it sound like just "WPT Path Prefix: /fullscreen/" in the metadata section, or combined with "WPT Display: inline" might warn about missing tests, but that's not the case. Running `make local` at https://github.com/whatwg/fullscreen/commit/12765d7d0d233e11dfd29ce8aea87d869be8cc39 doesn't result in any output.

**Comment by foolip** [comment]
Bikeshed version was 5888e02cf0071ba98c44312075d6903689282c04.

**Comment by tabatkins** [comment]
It does indeed work as you'd expect, but I had a bug where it wouldn't find any omitted tests if your prefix started with a /.  Fixed in 16c2f3f1.

**Comment by foolip** [comment]
Confirmed working now, thanks!
