### ISSUE TITLE
Linking to <wpt> /fullscreen/interfaces.html doesn't work; test not found

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1266]
Next step after https://github.com/tabatkins/bikeshed/issues/1265 is to link to a test. I did that in https://github.com/whatwg/fullscreen/commit/84d0c6c9ab1918bae1cf884c4131fa7cc9ac8894. Now the `make local` output is:
```
bikeshed spec fullscreen.bs fullscreen.html --md-Text-Macro="SNAPSHOT-LINK LOCAL COPY"
FATAL ERROR: Couldn't find WPT test '/fullscreen/interfaces.html' - did you misspell something?
 ✘  Did not generate, due to fatal errors
Makefile:5: recipe for target 'local' failed
make: *** [local] Error 1
```

This happens also if dropping "WPT Path Prefix: /fullscreen/" and using `<wpt>/fullscreen/interfaces.html</wpt>` instead. Removing the `<wpt-rest>` element doesn't change anything.

The test [does exist](https://wpt.fyi/results/fullscreen/interfaces.html) so something about the manifest is wrong?

**Comment by foolip** [comment]
@tabatkins @lukebjerring, I tried `curl https://wpt.fyi/api/manifest` and the first time I got a manifest, but on repeat calls I see "No search results found for SHA 36bb4d778a8ad51a46e478b6ca98e39cc6f5a8e7". Perhaps this is the root cause of this and the previous issues I've had?

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/commit/36bb4d778a8ad51a46e478b6ca98e39cc6f5a8e7 has been tagged as merge_pr_11420 and does have a manifest uploaded:
https://github.com/web-platform-tests/wpt/releases/tag/merge_pr_11420

**Comment by foolip** [comment]
https://staging.wpt.fyi/api/manifest?sha=36bb4d778a8ad51a46e478b6ca98e39cc6f5a8e7 does work, however.

@lukebjerring, I'm no suspecting that this is because wpt.fyi hasn't been deployed since https://github.com/web-platform-tests/wpt.fyi/commit/abbeb9b8ff56f63c7fc449a552aa2b5406eca315, might that be it?

**Comment by lukebjerring** [comment]
Sounds like a bug in the way the "latest" sha gets cached. Will look into
it.

>

**Comment by foolip** [comment]
After https://github.com/tabatkins/bikeshed/issues/1269 I can see that bikeshed/spec-data/wpt-tests.txt and bikeshed/spec-data/readonly/wpt-tests.txt locally both have this line:
```
testharness fullscreen/interfaces.html
```

So the cause isn't the wpt.fyi API, even though there does still seem to be something wrong there.

Rather, it turns out that the problem was the leading slash...  :D

@tabatkins, https://github.com/whatwg/fullscreen/commit/fa186c23ff4a898e8b2c4a02e073e8fc92f14426 fixes the problem. It looks like you normalize away trailing slashes, can you also make this leading slash optional and update the documentation to use the slash-less style if that's your preference?

**Comment by tabatkins** [comment]
Oh whoops, indeed, and I think the examples even show with a leading slash. I'll normalize it away. ^_^

**Comment by foolip** [comment]
Now it works, thanks Tab!
