### ISSUE TITLE
Forcing case in WG21 documents is weird

### ISSUE THREAD

**Issue by brycelelbach** [tabatkins/bikeshed#1268]
Right now bikeshed will force document short names for WG21 to have the first letter in lower case, and the revision number in uppercase, e.g.

* d4321R0

This is weird, and no one else does this in WG21. We usually do one of the following (all of which are acceptable to me:

* d4321r0
* D4321R0
* D4321r0

We should either not force this choice on authors, or force a better one.

@jfbastien ping as I suspect this is your fault.

**Comment by jfbastien** [comment]
Did you try not being out of date? #1259 😜

**Comment by tabatkins** [comment]
Yup, already fixed. 😀
