### ISSUE TITLE
[`code` stuff](link) doesn't link

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1276]
https://tabatkins.github.io/bikeshed/#dfn-contract shows 

> … a [`lt` attribute]\(#changing-lt) containing one or more pipe-separated …

instead of the expected link.

I've already mentioned this to Tab, but I'm filing it so I notice when it's fixed.

**Comment by tabatkins** [comment]
Go subscribe to https://github.com/tabatkins/bikeshed/issues/832, which this is a dupe of. ^_^
