### ISSUE TITLE
FATAL ERROR: Couldn't download web-platform-tests data.

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1283]
I got this error here:
https://travis-ci.org/w3c/speech-api/builds/392627450

Snippet (log will change when I restart build):
```
$ bikeshed update
Updating via manifest...
Updating 113 files...
WARNING: Couldn't download file 'https://raw.githubusercontent.com/tabatkins/bikeshed-data/master/data/anchors/anchors-zi.data'.
<urlopen error [Errno -2] Name or service not known>
Falling back to a manual update...
Downloading anchor data...
Success!
Downloading biblio data...
Success!
Downloading Can I Use data...
Success!
Downloading link defaults...
Success!
Downloading test suite data...
Success!
Downloading languages...
Success!
Downloading web-platform-tests data...
FATAL ERROR: Couldn't download web-platform-tests data.
HTTP Error 404: Not Found
ERR Did not generate, due to fatal errors
```

Seems like first problem was a network error, but then things also went wrong when trying to down wpt data. The URL being fetched is https://wpt.fyi/api/manifest. @lukebjerring, that current returns "No search results found for SHA 0d616ece81edf50b2f6a284dfa98605ace62d3e7"

**Comment by tabatkins** [comment]
I believe this is being fixed, but I would have thought the fix would have made it off staging to the real server by now.  (I didn't want to point it to staging just to have to change it back a few days later.)

**Comment by foolip** [comment]
@lukebjerring, was this fix in staging already? Note that https://wpt.fyi/api/manifest works right now, I guess the problem is it uses the sha from master and sometimes the manifest for that hasn't been uploaded yet?

**Comment by lukebjerring** [comment]
We're currently blocked on a few issues before releasing changes to wpt.fyi.
I don't know that this issue is fixed in staging - haven't had a chance to dive into it. You can always check with fetching the same thing on staging.wpt.fyi.

**Comment by tabatkins** [comment]
(It's not a race condition like I first thought, it's a "the process meant to serve that runs out of memory and dies, and takes a little while to restart".)

**Comment by tabatkins** [comment]
But per <https://github.com/web-platform-tests/wpt.fyi/issues/220#issuecomment-398102743> the OOM has been fixed on Staging, yes.

**Comment by tabatkins** [comment]
I'm gonna close this as it'll fix itself as soon as wpt.fyi is updated.
