### ISSUE TITLE
Inconsistent Style Sheet for the TOC

### ISSUE THREAD

**Issue by siusin** [tabatkins/bikeshed#1294]
Bikeshed adds some extra rules for the TOC when UA supports `display:grid` ([L1047 to L1080](https://github.com/tabatkins/bikeshed/blob/6d3a750812441328ea98d66fac577c3ced988303/tests/github/jfbastien/papers/source/bikeshed.html#L1047)), which introduces a bug for all W3C specs using the 2016 TR style sheets (see HTML [issue #1495](https://github.com/w3c/html/issues/1495#issuecomment-401688913), the numbers in the TOC are missing).

Not sure if we should update the /TR/2016/ style sheets for this... @fantasai @plehegar

**Comment by tabatkins** [comment]
Ah, I'm not fully overriding something from base.css, so the numbers are still getting a `margin-left: -4em` and moving off-screen.  Weird.  I'll fix.

**Comment by tabatkins** [comment]
...huh, but that same style applies on CSS specs too, but without it messing anything up. CSS is confusing!

**Comment by siusin** [comment]
Hahaha, thanks.

Please let us know if any changes required on the W3C side.

**Comment by tabatkins** [comment]
Ah, CSSWG isn't using Bikeshed's stylesheet, and I haven't updated the sheet we use, so it hadn't been changed yet. Anyway, looks to be fixed now in 7956fb4

**Comment by tabatkins** [comment]
I will probably want to make some changes to base.css at some point, but it's not necessary at this moment.

**Comment by siusin** [comment]
Yeah, the numbers are there now! ... but the `margin-top` of `#toc content` and `#toc secno` are different, so ["1" and "Introduction"](https://w3c.github.io/IndexedDB/) are not on the same baseline.

Perhaps we can try remove `#toc > .toc > li > a > span { margin-top: 1.1rem;}` from the CSS.

**Comment by tabatkins** [comment]
Oh, ugh, didn't notice that, sorry. Changed it to just zero out the margin-left. Rebasing tests now and will commit in a few minutes.
