### ISSUE TITLE
Support for the ISO 8601 date format (YYYY-MM-DD) for ISO bikeshed documents

### ISSUE THREAD

**Issue by brycelelbach** [tabatkins/bikeshed#1297]
Hi @tabatkins and @jfbastien!

I got a bikeshed related request recently from Hal Finkel (@hfinkel), who is the officer of the ISO C++ Committee who (among other things) collects and publishes submitted C++ proposals on our website.

Here's his request:

> Hi, Bryce,
> 
> While I'm thinking about it, could you please update the bikeshed ISO template so that it puts the date in YYYY-MM-DD format? That's what I need for the mailing metadata, and I get to copy-and-paste it out of nearly all of the papers except for the bikeshed-generated ones (because bikeshed reformats the date into long form).
> 
> Thanks again,
> Hal

Is it possible to configure how Bikeshed formats dates from the metadata header today?

If so, can we:

* Update the default WG21 configuration to use the ISO 8601 date format (YYYY-MM-DD).

If not, can we:

* Extend Bikeshed to support user-configurable date formats. This seems like a niche feature, so I wouldn't want to over-engineer this, but it would be cool if we had configuration options similar to C++'s `strftime` and Python's `datetime`.
* Update the default WG21 configuration to use the ISO 8601 date format (YYYY-MM-DD).

**Comment by tabatkins** [comment]
Check https://tabatkins.github.io/bikeshed/#text-macros - you can just switch your boilerplate to use the [ISODATE] macro.

**Comment by brycelelbach** [comment]
Thanks!
