### ISSUE TITLE
Support [[foo|`x`]] and/or [[foo|<code>x</code>]]

### ISSUE THREAD

**Issue by Quuxplusone** [tabatkins/bikeshed#1301]
Right now, neither of the following markup syntaxes turn into links:
```
[[foo|`x`]]
[[foo|<code>x</code>]]
```
It would be nice if both of them did (but especially the first one because it's more convenient to type).

**Comment by tabatkins** [comment]
As I said in <https://github.com/tabatkins/bikeshed/issues/1356#issuecomment-425281814>, this is a dupe of #832, so I'll close this.
