### ISSUE TITLE
Add Reporting API to anchor database?

### ISSUE THREAD

**Issue by clelland** [tabatkins/bikeshed#1303]
I'm not sure what the ultimate source of the data is, but the [Reporting API](https://w3c.github.io/reporting/) spec, while appearing in biblio- data, is not being cross-referenced.

(This just moved from https://wicg.github.io/reporting/ to w3c, and I'm not certain whether it was working in the previous location or not.)

**Comment by tabatkins** [comment]
Added, give it a little bit for the anchors to show up.
