### ISSUE TITLE
Include code files in Bikeshed documents

### ISSUE THREAD

**Issue by brycelelbach** [tabatkins/bikeshed#1304]
It would be really cool if we could directly include code files into a bikeshed document.

E.g. Imagine I have a directory with:

* `include_code_files.bs`
* `hello_world.cpp`

Where `include_code_files.bs` is:

```
<pre class="metadata">
Title: Your Paper Title
Shortname: P1234
Revision: 0
Status: P
Group: WG21
Audience: SG42
URL: http://wg21.link/P1234R0
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Editor: Your Coauthor, Your Coauthor's Company http://example.com/your-coauthors-company, your-coauthors-email@example.com, http://example.com/your-coauthors-personal-website
Markup Shorthands: markdown yes
No Abstract: true
</pre>

<pre class=include-code>
path: hello_world.cpp
</pre>
```

And `hello_world.cpp` is:

```
#include <iostream>
int main() { std::cout << "hello world" << std::endl; }
```

You get the idea, hopefully :)

**Comment by tabatkins** [comment]
I think this should already work:

```
<pre>
	<pre class=include>
	path: hello_world.cpp
	</pre>
</pre>
```

**Comment by brycelelbach** [comment]
Hrm. Tab, when I try this out, bikeshed seems to enter an infinite loop of some sort and won't finish processing the document. E.g. I tried:

```
$ bikeshed -f spec include_code_files.bs
```

and the result was bikeshed hangs.

`include_code_files.bs` is as above:

```
<pre class="metadata">
Title: Including Code Files
Shortname: P1234
Revision: 0
Status: P
Group: WG21
Audience: SG42
URL: http://wg21.link/P1234R0
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Editor: Your Coauthor, Your Coauthor's Company http://example.com/your-coauthors-company, your-coauthors-email@example.com, http://example.com/your-coauthors-personal-website
Markup Shorthands: markdown yes
No Abstract: true
</pre>

<pre class=include-code>
path: hello_world.cpp
</pre>
```

And `hello_world.cpp` is as above:

```
#include <iostream>
int main() { std::cout << "hello world" << std::endl; }
```

**Comment by brycelelbach** [comment]
Can we reopen this?

**Comment by tabatkins** [comment]
@brycelelbach Is this still happening? I can't reproduce the hang on my side.

Tho note that `class=include-code` doesn't do anything, so you'll just get a nice highlighted block with `path: text.txt` in it.

**Comment by tabatkins** [comment]
Ahhhh, I see my problem. I don't look further inside of `<pre>` elements when trying to find datablocks, so I don't properly parse the insides of an include block to give it the right attributes. That falls down a bad case in my code where I just do nothing with the element, then try to process it again, infinitely.

**Comment by tabatkins** [comment]
Anyway, `include` doesn't actually do what you want; it'll parse the included file as more Bikeshed. You really do want some new `include-code` feature, so I can leave it unparsed, properly escape things, automatically highlight, let you specify a line-range to show off, etc.

This sounds like a useful feature that I'd be happy to add.

**Comment by tabatkins** [comment]
Okay, for now that case you ran into now properly triggers an error rather than infinite-looping, thanks for finding it. ^_^

**Comment by tabatkins** [comment]
Congrats, works now:

```html
<pre class="metadata">
Title: Including Code Files
Shortname: P1234
Revision: 0
Status: P
Group: WG21
Audience: SG42
URL: http://wg21.link/P1234R0
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Editor: Your Coauthor, Your Coauthor's Company http://example.com/your-coauthors-company, your-coauthors-email@example.com, http://example.com/your-coauthors-personal-website
Markup Shorthands: markdown yes
No Abstract: true
</pre>

<pre class=include-code>
path: test.txt
highlight: c++
line-highlight: 2-3, 7-11
show: 6-12
line-numbers:
</pre>
```

**Comment by tabatkins** [comment]
It responds to `Default Highlight` as normal, so you can leave the `highlight` line off in your papers.  For further documentation, see <https://tabatkins.github.io/bikeshed/#including-code>
