### ISSUE TITLE
Service Worker references do weird things

### ISSUE THREAD

**Issue by inexorabletash** [tabatkins/bikeshed#1326]
Sample spec:
```
<pre class='metadata'>
Title: Dummy
Shortname: Dummy
Status: LS
Editor: Dummy
Abstract: Dummy
</pre>

Biblio ref [[Service-Workers]]

Definition ref [=service worker registration=]

IDL ref {{ServiceWorkerGlobalScope}}
```

1. This ends up with:
* Normative: [SERVICE-WORKERS-2] Service Workers URL: https://w3c.github.io/ServiceWorker/
* Informative: [Service-Workers] Alex Russell; et al. Service Workers 1. 2 November 2017. WD. URL: https://www.w3.org/TR/service-workers-1/

2. Change the biblio ref to `[[Service-Workers current]]` and you get:
* Normative: [Service-Workers] Alex Russell; et al. Service Workers 1. URL: https://w3c.github.io/ServiceWorker/

3. Now add this to the bs:
```
<div class=note> Note ref [=Service Worker=] </div>
```
... and now there are no Normative or Informative references to any SW spec!

4. Go back and drop the `current` and you get:
* Normative: [SERVICE-WORKERS-2] Service Workers URL: https://w3c.github.io/ServiceWorker/
* Informative:  [Service-Workers] Alex Russell; et al. Service Workers 1. 2 November 2017. WD. URL: https://www.w3.org/TR/service-workers-1/

**Comment by inexorabletash** [comment]
Specifying the obvious `[[service-workers-2]]` produces an error, which is what sent me down this path...

**Comment by tabatkins** [comment]
Oof, okay, so this is a matter of clashing definitions.

Biblio data *primarily* comes from SpecRef, but it additionally comes from Shepherd (the tool that provides the term-linking db). The latter is how I ensure that linking to terms results in a biblio entry - if the term's spec name in the DB doesn't show up in SpecRef for whatever reason, I can generate a "good enough" biblio entry just from the Shepherd data.

Usually these work together nicely. SW is one that doesn't. :/  In particular:

* [According to SpecRef](https://www.specref.org/?q=service-workers), there's *one* version of SW, whose TR url is <https://www.w3.org/TR/service-workers-1/> and ED url is <https://w3c.github.io/ServiceWorker/>.  This data is extracted from the W3C data, and if you check the TR spec, it does indeed list the github.io link as its ED.
* According to Shepherd, there's a SERVICE-WORKERS-1 spec which has *only* a TR link, and a SERVICE-WORKERS-2 spec which has *only* an ED link. This, as far as I can tell, matches the actual semantics of the specs; the SW1 TR spec is going for stable Rec, and is not attempting to match the updates to the ED, thus the ED has in practice branched to the next level.

So, depending on exactly what you reference where, and how precisely I'm deduping things (I'll collapse biblio entries that have the same URL even if they show up with separate keys), you get some interesting results.  I'll list the biblios resulting from your 4 cases, with the printing annotated to tell which data source it comes from:

1. 
	```
	Normative References
	[SERVICE-WORKERS-2]
	FROM SHEPHERD Service Workers URL: https://w3c.github.io/ServiceWorker/
	Informative References
	[Service-Workers]
	FROM SPECREF Alex Russell; et al. Service Workers 1. 2 November 2017. WD. URL: https://www.w3.org/TR/service-workers-1/
	```

	More or less as expected - term refs are grabbing from the "level 2" version, as it's latest, and thus add a biblio pointing to the ED url. But "SERVICE-WORKERS" is an alias in SpecRef for SW-1, and they default to the stable url.

2.
    ```
	Normative References
	[Service-Workers]
	FROM SPECREF Alex Russell; et al. Service Workers 1. URL: https://w3c.github.io/ServiceWorker/
    ```

	Now that you've mandated "current", the biblio reference points to the github URL, so then the two references dedup.

3. (Nothing). Whoops, this is a bug on my part, a bad collision of my "don't show something as informative if it's also normative" and my "dedup same-url biblios" code. I'll fix, this should be the same as case 2.

4. 
    ```
	Normative References
	[SERVICE-WORKERS-2]
	FROM SHEPHERD Service Workers URL: https://w3c.github.io/ServiceWorker/
	Informative References
	[Service-Workers]
	FROM SPECREF Alex Russell; et al. Service Workers 1. 2 November 2017. WD. URL: https://www.w3.org/TR/service-workers-1/
    ```

	Same as case 1.

----------

Let me go bug the editors, this needs to be fixed up.

**Comment by tabatkins** [comment]
> Specifying the obvious [[service-workers-2]] produces an error, which is what sent me down this path...

Sigh, lol, more error-correction logic that assumes SpecRef is reliable and Shepherd isn't disagreeing with it about what versions exist. I'll fix.

**Comment by inexorabletash** [comment]
In case 2, the text reads "Service Workers 1". but "URL: https://w3c.github.io/ServiceWorker/" which seems like a mismatch to me; I suppose the logic is that the ED is the "current" version of SW1 per SpecRef?

**Comment by tabatkins** [comment]
That's exactly right: https://www.specref.org/?q=service-workers Per SpecRef (and the /TR spec itself, which is where SpecRef gets its data), the github URL is the Editor's Draft for the spec.

("current" and "dated" are euphemisms for TR and ED versions.)

**Comment by tabatkins** [comment]
Upon investigation, `[[service-workers-2]]` not working is (currently) an intentional design decision actually; I allow Shepherd-sourced biblio entries to be created by autolinking, to ensure that every reference has a biblio for itself (so I can link to something from the index of external terms), but don't allow you to manually refer to them, on the supposition that SpecRef should be authoritative and should be fixed if something is missing.

That said, I've been talking with @jakearchibald about getting this situation cleared up; they opened <https://github.com/w3c/ServiceWorker/issues/1353> to figure out intentions. If they end up committing to a W3C Living Standard, then I'll correct Shepherd to just collapse things down to a single reference; if they don't, then I'll get them to publish something for Level 2 to /TR, so SpecRef correctly reflects the current set of specs and matches Shepherd.  Apologies for the confusion in the meantime.

**Comment by tabatkins** [comment]
All right, and I tracked down the bug leading to the ➂ failure and fixed it, so you *do* get a single, SpecRef-sourced biblio entry in that case.

**Comment by tabatkins** [comment]
Gonna go ahead and close this then, as the only remaining weirdness is due to some datafile issues that are being tracked in the SW repository.
