### ISSUE TITLE
Convenient syntax to <dfn> multiple syntactic forms.

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1327]
For example, https://fetch.spec.whatwg.org/#header-list-contains is defined with:

```bikeshed
<dfn export for="header list" lt="contains|does not contain">contains</dfn>
```

https://fetch.spec.whatwg.org/#extract-header-values is defined with:

```bikeshed
<dfn export lt="extract header values|extracting header values">extract header values</dfn>
```

It would be nice to be able to write those definitions without repeating the unchanged parts in the `lt` attribute. For example,

```bikeshed
<dfn export for="header list">[does not ]contain[!s]</dfn>
<dfn export>extract[ing] header values</dfn>
```

Where `[!something]` says to include it in the `<dfn>`'s appearance, while `[]` would just be optional in the uses.

**Comment by tabatkins** [comment]
I'm not super interested in trying to figure out some usable microsyntax for varying English and other syntaxes; that sounds like a recipe for pain that won't be very readable or writable. But having some shorthand syntax for referring to the text content when writing an `lt` sounds reasonable. Problem is figuring it out. ^_^

Maybe just starting the `lt` with a `|` character? So like `<dfn lt="|extracting header values">extract header values</dfn>` would work.

**Comment by jyasskin** [comment]
That'll fix half of the problem most of the time, so if it's all I can get, I'll take it.

**Comment by domenic** [comment]
I'd love to encourage Bikeshed to add gerund-related smarts to its plural smarts, and figure out, either on the definition side or the linking side, how to allow `<dfn>do the thing</dfn>` to be linked via `<a>doing the thing</a>`

**Comment by tabatkins** [comment]
I too would like that, but note that my "plural smarts" are literally just me adding "ing" and "s" to the end of literally every autolink (and if they're already present, removing them) in the hopes that the resulting string is a match for a definition. There's zero actual smart there, which is what would be required for automatically grabbing the verb from a phrase.

**Comment by domenic** [comment]
Eh, I mean, you could just add "ing" to the first word in a multi-word phrase, and see if it works?

**Comment by tabatkins** [comment]
...yeah, that would probably work for a lot of things, huh.

k, I'll add it to the conjugation code.

**Comment by tabatkins** [comment]
Done, let me know how it works for you. Seems to be good from the tests I put together.
