### ISSUE TITLE
Manual spec obsolete paths / partial obsoletion

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#1330]
Bikeshed automatically lets definitions in a spec one level up obsolete the definitions in an earlier level. This is good and makes sense.

Sometimes we split modules differently in later specs, though. It would be useful to be able to say somehow that the definitions in one particular spec obsolete equivalent definitions in the other. E.g. css-pseudo-4 could say it obsoletes selectors-3, preventing the tons of ambiguous-reference errors across the CSSWG repo because we happened to split out pseudo-elements from the Selectors module for Level 4.

**Comment by tabatkins** [comment]
Ah, that's what the link-defaults file in the repo is for. I can add that.

**Comment by tabatkins** [comment]
All right, added in 3f7fdee
