### ISSUE TITLE
Hyphenated markdown code fails

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#1331]
```
<pre class="metadata">
Title: hyphen
Shortname: FAIL
Status: DREAM
Editor: JF Bastien
No Abstract: true
Markup Shorthands: markdown yes
</pre>

non-`volatile` should code-quote `volatile`
```

Fails with:

<blockquote>
  FATAL ERROR: Unknown inline tag 'non-' found:<br>
  non-`volatile`<br>
 ✘ Did not generate, due to fatal errors<br>
</blockquote>

**Comment by jfbastien** [comment]
I'm working around it with a zero-width space after the hyphen 😄

**Comment by tabatkins** [comment]
Yeah, someone else ran into this too. Didn't think there'd be that much text immediately preceding a code span!

I've gone ahead and fixed it so that hyphenated prefixes don't trigger that codepath.

**Comment by jfbastien** [comment]
Confirming that the fix works, thanks!
