### ISSUE TITLE
Way to change the header of "Note:" to something else

### ISSUE THREAD

**Issue by Quuxplusone** [tabatkins/bikeshed#1333]
I just ran into a situation where I had a `Note:` block in my paper that wanted to talk about a "note" in a paragraph quoted from another standard...
```
Modify [class.copy.elision]/3 as follows:

> If the first overload resolution fails or was not performed, <del>or if the
> type of the first parameter of the selected constructor is not an rvalue reference
> to the object's type (possibly cv-qualified),</del> overload resolution is performed
> again, considering the object as an lvalue.
> [*Note:* This two-stage overload resolution must be performed regardless of whether
> copy elision will occur. It determines the constructor to be called if elision is not
> performed, and the selected constructor must be accessible even if the call is
> elided. —*end note*]

Note: I believe that the two instances of the word "constructor" in the note
remain correct. [...] The note is correct when it says that this constructor
must be accessible even if elision is performed.
```

A reviewer was confused: is my `Note:` talking about itself? He suggested changing "the note" to "the quoted note" (or "the note in the quotation above" or something) to clarify what's happening here.

It strikes me that a more concise solution would be if I could replace `Note:` with something like `Remark:` or `Sidebar:` — still styled exactly like a Bikeshed "note", but without using the word "Note" anywhere in the styling. I tried this:
```
<div class="note" header="Remark:">
I believe that the two instances of the word "constructor" in the note
remain correct. [...] The note is correct when it says that this constructor
must be accessible even if elision is performed.
</div>
```
but this actually renders *both* the specified header *and* the word "NOTE:", so that it displays as a green box containing "NOTE: REMARK: I believe...". That's certainly not what I was going for!

Is there a way to accomplish what I want, already?  Could one be added (e.g. by handling a `really_actually_header="Remark:"` attribute on the div)?

**Comment by tabatkins** [comment]
The `heading` attribute just auto-adds a `<div class=marker>` to your container, holding the parsed HTML contents of the attribute value, and prepended with "Note:"/etc.

You can avoid this by just adding the marker-div yourself. I've documented this at <https://tabatkins.github.io/bikeshed/#notes-etc>.
