### ISSUE TITLE
"(live test)" link should sometimes use https

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#1339]
https://github.com/tabatkins/bikeshed/blob/77332301562e2ce812c013f8fa6debde320dd06e/bikeshed/wpt/wptElement.py#L74

See logic in https://github.com/web-platform-tests/wpt.fyi/blob/master/webapp/components/test-runs.html#L74

Also, could consider using web-platform-tests.live instead of w3c-test.org, I think the former has higher chances of being maintained.

**Comment by tabatkins** [comment]
Nice, fixed in df73ddac, both for scheme and new url.
