### ISSUE TITLE
crossorigin attribute shouldn't be added to a elements

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1341]
https://github.com/tabatkins/bikeshed/commit/e1ceaa2fec0eef23bbc77862c35e8e2d6505b796 added 'Force Crossorigin' metadata.

Merging a change to the fullscreen spec, I'm now seeing validation errors due to crossorigin on the `a` element:
https://travis-ci.org/whatwg/fullscreen/builds/422060260

I think the validator is correct, it's not in the spec: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

The fix would be here: https://github.com/tabatkins/bikeshed/commit/e1ceaa2fec0eef23bbc77862c35e8e2d6505b796#diff-34427d0a881f4f044a0a4c431329c89fR1351

**Comment by tabatkins** [comment]
Heh, fixed. When describing the feature he wanted, Domenic gave `a` as one of the elements. ^_^

**Comment by foolip** [comment]
I restarted https://travis-ci.org/whatwg/fullscreen/builds/422060260 and the problem is fixed, thanks Tab!
