### ISSUE TITLE
Allow symbol-named method names

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1344]
For specs which aren't using Web IDL, but are trying to use Bikeshed's linking constructs regardless, the validation on method names is too strict, when we want to use symbol-named methods.

IMO either of the following should work:

```html
<h5 method for="ReadableStreamDefaultReader">[@@asyncIterator]()</h5>
<h5 method for="ReadableStreamDefaultReader">[Symbol.asyncIterator]()</h5>
```

but they give errors. (The wrong error message; see #1343.)

**Comment by tabatkins** [comment]
They give errors because they're not valid WebIDL method names. ^_^ Closing this in favor of #1346
