### ISSUE TITLE
Cannot mark up attributes as such when they're inside dts

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1345]
Contrast https://github.com/whatwg/streams/blob/5d9498e7526d2f50618432e7aada8582d08745c0/index.bs#L521 for a method, which works fine, with an attempt to add `attribute` to https://github.com/whatwg/streams/blob/5d9498e7526d2f50618432e7aada8582d08745c0/index.bs#L540 , which fails with the error

```
[1;31mFATAL ERROR:[0m Couldn't find target attribute 'type':
<span data-attribute-info="" for="underlying source/type"></span>
```

I did some debugging. The Bikeshed source seems to throw this inside a function

```python
def fillAttributeInfoSpans(doc):
    # Auto-add <span attribute-info> to <dt><dfn> when it's an attribute or dict-member.
```

But I have no idea why I would want an extra span, or the attribute-info attribute, on my attribute definition. So I can't really tell if this function is working as expected or not since I don't know what it's supposed to accomplish.

**Comment by tabatkins** [comment]
You're not marking up an attribute, you're marking up a JS property. The IDL dfn types are intended to work with IDL, not JS per se, and they make some assumptions about the structure of your document accordingly; in this case, it assumes there's an IDL block somewhere containing that attribute, and that Bikeshed's parsing of the block has left some informational attributes on the attribute that lets it fill in some niceties, like the attribute's type and default value.

Fundamentally, the IDL types are not meant for marking up raw JS constructs; if you *really* want to write a spec like this, we'll need to work together to design a set of JS dfn types.

**Comment by tabatkins** [comment]
Closing this in favor of #1346
