### ISSUE TITLE
Supply bikeshed Docker image

### ISSUE THREAD

**Issue by sandersaares** [tabatkins/bikeshed#1354]
To be able to easily invoke bikeshed without having to worry about Python and pip and dependencies and updates and OS/distro compatibility, I request a Bikeshed Docker image be published.

Desired use case would be something like the following:

```
docker pull bikeshed
docker run --rm --volume C:\mystuff\project1\:C:\Workspace\ bikeshed spec C:\Workspace\Index.bs C:\Workspace\out\Index.html
```

I request that both Windows and Linux be supported by this Docker image.

**Comment by ddeboer** [comment]
You may want to have a look at https://github.com/netwerk-digitaal-erfgoed/bikeshed-docker, where I automated the creation and publishing (to GitHub Packages) of a Bikeshed Docker image.
