### ISSUE TITLE
Cannot *emphasize* a [[link]]

### ISSUE THREAD

**Issue by Quuxplusone** [tabatkins/bikeshed#1356]
The core language *[[Contra|should not know or care]]* that the class template
    `is_trivially_relocatable` exists, any more than it knows that the class template
    `is_trivially_destructible` exists.

renders as

    The core language *<a data-link-type="biblio" href="#biblio-contra">should not
    know or care</a>* that the class template
    <code class="highlight"><c- n>is_trivially_relocatable</c-></code> exists,
    any more than it knows that the class template
    <code class="highlight"><c- n>is_trivially_destructible</c-></code> exists. 

Notice that the asterisks rendered as asterisks, not as `<em>...</em>` tags.

Putting the asterisks inside the `[[ ]]` doesn't help, either.

Admittedly the combination of bold with a link is probably bad writing style on my part, but IMO that's no excuse to quietly misrender the markdown. :)

**Comment by tabatkins** [comment]
Yeah, this is another expression of #832 (as is your previous issue #1301). I'll close this as a duplicate, but rest assured that I'm raising the priority of that issue; it's just a big annoying rewrite that I don't want to do but know that I have to. ^_^
