### ISSUE TITLE
SVG 1.1 documents no longer referenced

### ISSUE THREAD

**Issue by dirkschulze** [tabatkins/bikeshed#1388]
The SVG 1.1 document no longer gets referenced and parsed. This possibly happened due to a recent change on publication.

https://www.w3.org/TR/SVG/ no longer links to https://www.w3.org/TR/SVG11/ but to https://www.w3.org/TR/SVG2/.

Apparently, for parsing SVG 1.1 the non-versioned address was chosen.

**Comment by tabatkins** [comment]
It gets changed elsewhere, in the Shepherd system.

So that URL just needs to be versioned now?

**Comment by dirkschulze** [comment]
@tabatkins I think so, yes.

**Comment by tabatkins** [comment]
Fixed Shepherd.
