### ISSUE TITLE
Inline links with parenthesis?

### ISSUE THREAD

**Issue by mfoltzgoogle** [tabatkins/bikeshed#1419]
I wasn't able to get an inline link with parenthesis to work correctly.  Here's what I tried:

```
[sandboxing](https://en.wikipedia.org/wiki/Sandbox_(computer_security))
[sandboxing](https://en.wikipedia.org/wiki/Sandbox_\(computer_security\))
[sandboxing](<https://en.wikipedia.org/wiki/Sandbox_(computer_security)>)
[sandboxing](https://en.wikipedia.org/wiki/Sandbox_&lpar;computer_security&rpar;)
```

In all cases the following was generated instead; the trailing paren wasn't captured.

```
<a href="https://en.wikipedia.org/wiki/Sandbox_(computer_security">sandboxing</a>)
```

**Comment by tabatkins** [comment]
Yup, that's a pretty fundamentally restriction is this syntax. There's no way to tell whether a `)` is heavily to be part of the URL or closing the link. Same reason you can't put a quote in an HTML attribute value.

Either escape the `)` (url-escaping as `%29` will work, HTML-escaping it as `&#x29;` should too) or switch to an actual `a` tag.

**Comment by domenic** [comment]
CommonMark can handle it: https://spec.commonmark.org/dingus/?text=Test%20paragraph%201.%0A%0ATest%20paragraph%202

https://spec.commonmark.org/0.28/#links

**Comment by tabatkins** [comment]
...huh, so it does. That's an interesting assumption. Welp, this is a Bikeshed bug then.

**Comment by mfoltzgoogle** [comment]
Yes, I filed this an issue since Bikeshed claimed to support CommonMark syntax :-)

**Comment by dlaliberte** [comment]
I'll work on this.

Tab says:  "Fixing this *properly* will require
a more involved parser rewrite that I've been planning to do for quite
a while, but fixing it hacking the regex into allowing paired parens,
in accordance with the CommonMark spec, should be fine for now. Don't
worry about *nested* parens, feel free to just solve top-level ones."
