### ISSUE TITLE
Flexible github repository metadata parsing.

### ISSUE THREAD

**Issue by NicolasRouquette** [tabatkins/bikeshed#1420]
Currently, the metadata syntax:

```
Repository: <url>
```
is parsed as the specification of a GithubRepository if `<url>` matches `https://github.com/<user>/<name>`.

Improve the pattern to support various Github repositories including github enterprise; e.g., https://github.enterprise.somewhere.com/<organization>/<name>`.

**Comment by tabatkins** [comment]
Fixed by #1421
