### ISSUE TITLE
TOC layout looks broken in Edge using default styling

### ISSUE THREAD

**Issue by sandersaares** [tabatkins/bikeshed#1423]
I think this issue is best demonstrated by the screenshot comparing Edge on the left and Firefox on the right. Observe the bad layout of the numbers on the left.

![image](https://user-images.githubusercontent.com/9914262/51478212-7ad9c180-1d93-11e9-93e2-a30e0c601f75.png)

I am using the W3C web service, no custom styles.

Document URL: https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html

Source: https://raw.githubusercontent.com/Dash-Industry-Forum/Ingest/master/DASH-IF-Ingest.bs.md

**Comment by dturnerx** [comment]
I am experiencing the same problem. Does anyone have a solution?

**Comment by dbaron** [comment]
This seems to be a side effect of the grid-specific ToC styles; for example, removing [this margin](https://github.com/tabatkins/bikeshed/blob/faf287cebf32287e91a51785dc509107b2a13353/bikeshed/boilerplate/stylesheet.include#L1051-L1055) makes things a bit better.  I wonder if things would be better if [this `@supports` test](https://github.com/tabatkins/bikeshed/blob/faf287cebf32287e91a51785dc509107b2a13353/bikeshed/boilerplate/stylesheet.include#L1027) were something that evaluated to false in Edge?

**Comment by dbaron** [comment]
I suspect it should be `@supports (display: grid) and (display: contents)`; Edge's lack of support for `display: contents` seems to be causing the problem.

**Comment by dturnerx** [comment]
@dbaron Thanks for that. I removed the `@supports (display: grid)` section from my doc and it looks in Edge and Chrome.

**Comment by dbaron** [comment]
I'd also note that this issue only shows up for some specs because only some `header.include` files have a `<style data-fill-with="stylesheet">` element.

<details><summary>Expand for the list of include files that have this element</summary>

```
./audiowg/header-ED.include
./dap/header-ED.include
./geolocation/header.include
./header.include
./html/header.include
./httpslocal/header.include
./immersivewebwg/header.include
./mediacapture/header-ED.include
./ricg/header.include
./sacg/header.include
./serviceworkers/header.include
./tc39/header.include
./texttracks/header-CG-DRAFT.include
./texttracks/header.include
./webappsec/header-ED.include
./web-bluetooth-cg/header.include
./webgl/header.include
./webgpu/header.include
./webml/header.include
./web-payments/header.include
./webrtc/header-ED.include
./webvr/header.include
./wg14/header.include
./wg21/header.include
./wicg/header.include
```

</details>

<details><summary>Expand for the list of include files that do **not** have this element</summary>

```
./act-rules-format/header.include
./audiowg/header.include
./csswg/header-ED.include
./csswg/header.include
./dap/header.include
./fxtf/header.include
./houdini/header.include
./i18n/header.include
./mediacapture/header.include
./svg/header.include
./test/header-DREAM.include
./test/header.include
./uievents/header.include
./wasm/header.include
./webappsec/header.include
./webapps/header.include
./webauthn/header.include
./webperf/header.include
./webplatform/header.include
./webrtc/header.include
./webspecs/header.include
./whatwg/header.include
./whatwg/header-RD.include
```
</details>

**Comment by tabatkins** [comment]
Ah, indeed, a lack of display:contents would def break things. Fixed.
