### ISSUE TITLE
railroad-diagram

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#1429]
At some point in time, `<pre class=railroad-diagram>` was the right incantation, and docs/index.bs still says that in passing. It looks like it's now `<pre class=railroad>`, but it's not really clear from the docs.

I have two papers in the test suite (P0418r1.bs and r2) which amusingly are testing the *wrong* behavior! Probably because the change happened after my papers were written.

Seems like docs should be fixed, but the old behavior should also be a fallback.

**Comment by tabatkins** [comment]
It's always been "railroad" (<https://github.com/tabatkins/bikeshed/blame/master/bikeshed/datablocks.py#L40>), but my old datablock code was a braindead regex that just looked for the substring on the line, so "railroad-diagram" used to work. Now I actually do an HTML start-tag parse by hand, so it correctly recognizes only the actual class.

The docs appear to be clear; do you see a spot where it implies railroad-diagram would work?

**Comment by jfbastien** [comment]
https://github.com/tabatkins/bikeshed/blob/33fed5007b404f885d4fe033a21ec1ce681f0504/docs/index.bs#L1883 is wrong I guess. Fixed in #1442.

**Comment by tabatkins** [comment]
Ah yup, there it is. I was looking at the actual railroad section. ^_^

**Comment by jfbastien** [comment]
That's probably how I got there in the first place... Now I should fix my old papers which use that spelling, because they won't re-build correctly!
