### ISSUE TITLE
syntax error on bracket range notation on datatypes

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1441]
If you try to put a range notation on a data type in the css property syntax (like `<integer [1,10]>`) bikeshed gets confused, throws a warning which looks like this on my machine:
> /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/html5lib/_ihatexml.py:257: DataLossWarning: Coercing non-XML name
  warnings.warn("Coercing non-XML name", DataLossWarning)

and outputs `< >` instead of `<integer [1,10]>`

**Comment by tabatkins** [comment]
Fixed in <https://github.com/tabatkins/bikeshed/commit/a9b4344c268916b34d988f14b78d7d63accf8636>
