### ISSUE TITLE
Print PDF with bookmarks corresponding to TOC

### ISSUE THREAD

**Issue by melaasar** [tabatkins/bikeshed#1457]
Thanks for Bikeshed, awesome technology! Is there a way to print a Bikeshed specification to PDF such that we get bookmarks corresponding to the TOC (as opposed or in addition to the TOC printed in the first pages)?

**Comment by tabatkins** [comment]
Bikeshed doesn't have any native PDF stuff, and I don't plan on adding any (it's a lot of complexity for a fundamentally pretty bad document tech!).

That said, there are HTML-to-PDF converters that should respect the document hierarchy and properly turn headings into bookmarks. A quick search turned up [WkHtmlToPdf](https://wkhtmltopdf.org/), which claims to do bookmarks properly.
