### ISSUE TITLE
Autolinker fails for some TR links in an odd way

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#1466]
In the [TR version of CSS Grid](https://www.w3.org/TR/css-grid-1/#grid-items), it autolinks to "text runs" and "anonymous". Both of these link to the TR version of CSS Display, but the anchors don't appear to actually exist there.  Clearly, something is wrong.

(Reported in the CSSWG repo as <https://github.com/w3c/csswg-drafts/issues/3883>)

**Comment by fantasai** [comment]
Those links *used* to be valid. https://www.w3.org/TR/2017/WD-css-display-3-20170720/

**Comment by fantasai** [comment]
Changeset that inadvertently changed their IDs: https://github.com/w3c/csswg-drafts/commit/effd3aac

**Comment by tabatkins** [comment]
Ah, yeah, I forget that adding `for` will change how the IDs generate. :(
