### ISSUE TITLE
Bikeshed not processing link-defaults block?

### ISSUE THREAD

**Issue by mfoltzgoogle** [tabatkins/bikeshed#1469]
In the following spec [1] I have:

```
<pre class="link-defaults">
spec:html; type:method; text:postMessage(message, targetOrigin, transfer)
</pre>
```

and:

```
This is similar to cross-origin communication via {{Window/postMessage()}} with a target origin of `*`.  
```

but Bikeshed still tells me:

```
bikeshed --print=plain spec index.bs
LINK ERROR: Multiple possible 'postMessage()' idl refs for 'Window'.
Arbitrarily chose https://html.spec.whatwg.org/multipage/web-messaging.html#dom-window-postmessage-options
To auto-select one of the following refs, insert one of these lines into a <pre class=link-defaults> block:
spec:html; type:method; text:postMessage(message, targetOrigin, transfer)
spec:html; type:method; text:postMessage(message, options)
{{Window/postMessage()}}
 ✔  Successfully generated, with 1 linking errors
```

Am I holding it wrong or is there something I need to do to resolve this error?

[1] https://github.com/webscreens/openscreenprotocol/blob/gh-pages/index.bs

CC @tidoust

**Comment by mfoltzgoogle** [comment]
I can fix this by adding arguments to the autolink, `{{Window/postMessage(message, targetOrigin, transfer)}}`, but that's not exactly how I want the spec to read since it's the exact flavor of the `postMessage` method is not relevant.

**Comment by tabatkins** [comment]
Holding it wrong, currently. An arg-less method autolink is specially handled, to magically link to the method regardless of arguments *if* there's only a single overload; this doesn't rely on link defaults.

(Maybe it should; I'll dig in and see if that's feasible.)

For now, you can get the autolink working and get the desired output by specifying the output manually: `{{Window/postMessage(message, targetOrigin, transfer)|postMessage()}}`.

**Comment by mfoltzgoogle** [comment]
That works!  Thanks for the prompt customer service :grin:
