### ISSUE TITLE
Support email ("cc") via echidna

### ISSUE THREAD

**Issue by marcoscaceres** [tabatkins/bikeshed#1479]
With Echidna, it's possible to pass a comma-separated list of email addresses to ping with the publication result... this is done by passing a "cc" parameter. 

An example using cURL:
https://github.com/w3c/manifest/blob/gh-pages/.travis.yml#L27-L29

Would be great if BikeShed supported `--cc` and a list of emails to pass to Echidna. Super useful when auto-publishing as otherwise one needs to check some random mailing list to see if things got published successfully or not.

**Comment by tabatkins** [comment]
Ah, that's a new feature. Happy to support it.

**Comment by tabatkins** [comment]
All right, added the `--cc` argument to `bikeshed echidna`. Let me know if it works; I don't have a good thing to test it with!

**Comment by marcoscaceres** [comment]
Just confirming cc works. Thanks again for adding it. 

Ps: sorry again about `data-lt` 😥
