### ISSUE TITLE
"This version:" link generated incorrectly

### ISSUE THREAD

**Issue by marcoscaceres** [tabatkins/bikeshed#1480]
The short name included in the "This version" link is being lower-cased, which causes W3C Specberus/PubRules to reject it. 

For example, running`bikeshed spec --md-status=WD` for the [File API](https://github.com/w3c/FileAPI) spec yields (note *fileapi*):

> https://www.w3.org/TR/2019/WD-fileapi-20190523/

But expected (FileAPI): 

> https://www.w3.org/TR/2019/WD-FileAPI-20190523/

**Comment by tabatkins** [comment]
Fixed in 6dcfb71
