### ISSUE TITLE
Implement required dictionary defaulting

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1491]
See https://github.com/heycam/webidl/pull/750. Presumably this will depend on https://github.com/plinss/widlparser/issues/39.

**Comment by plinss** [comment]
See https://github.com/plinss/widlparser/issues/39#issuecomment-515273312 notes about type resolution

**Comment by tabatkins** [comment]
And Bikeshed is now updated to widlparser trunk, so the parser should work.

**Comment by plinss** [comment]
@tabatkins lmk if you want to work on adding the type resolution to support the error detection, happy to brainstorm on that...

**Comment by tabatkins** [comment]
Yeah, I've been having discussions with @foolip about Reffy integration (which does similar scans over its own spec list, and extracts WebIDL); if Shepherd wants to handle it all that's cool with me. I'll hit you on IRC.
