### ISSUE TITLE
Wrapper for http-header autolinks

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1492]
It would be nice to have a convenient [autolink wrapper syntax](https://tabatkins.github.io/bikeshed/#autolink-wrappers) for [http-header](https://tabatkins.github.io/bikeshed/#dfn-types) definitions.

Maybe `[:` `:]` since HTTP headers use `:` both as the prefix for [pseudo-headers](https://httpwg.org/specs/rfc7540.html#PseudoHeaderFields) and as the terminator for [HTTP1 serialized headers](https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#header.fields)? On the other hand, that might make linking to pseudo-headers difficult. `[::status:]`?

**Comment by tabatkins** [comment]
This sounds reasonable. I'm fine with `[:foo:]`; `[::status:]` is just fine parsing-wise.

**Comment by tabatkins** [comment]
And finally done. `[:foo:]` or `[::pseudo-foo:]` are usable to link to `<dfn http-header>foo</dfn>` and `<dfn http-header>:pseudo-foo</dfn>`.

/cc @cbiesinger
