### ISSUE TITLE
tentative tests and WPT Path Prefix

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1497]
The WPT project has a new convention: tests that are not backed up by a spec (or in contradiction with a spec) can be accepted, and must be named ****.tentative.html (see https://web-platform-tests.org/writing-tests/file-names.html)

Bikeshed should not warn about such tests being found under the prefix specified by `WPT Path Prefix` yet not marked in the spec with `<wpt>`, since there is generally no part of the spec they can be tagged against.

**Comment by tabatkins** [comment]
Yup, sounds reasonable.

Do you want some way to list those out in the spec, like a wpt-tentative block that automatically lays them out a la wpt-rest?

**Comment by frivoal** [comment]
I guess that'd be useful too, yes.

**Comment by frivoal** [comment]
I'm kind of wondering what to do. On the one hand, the warning is annoying when you know these tests exist, and have nothing in the spec that they could be tagged against, since you can't make the warning go away.

On the other hand, as a spec editor, it is nice to know that there are tests being written against your spec, even if they're tentative, as that can raise awareness of ongoing work you ought to be paying attention to.

If we just want to silence these warnings, the patch is trivial:

```diff
diff --git a/bikeshed/wpt/wptElement.py b/bikeshed/wpt/wptElement.py
index d1554d8e..7d399084 100644
--- a/bikeshed/wpt/wptElement.py
+++ b/bikeshed/wpt/wptElement.py
@@ -125,7 +125,8 @@ def checkForOmittedTests(pathPrefix, testData, seenTestNames):
        for testPath in testData.keys():
                if prefixInPath(pathPrefix, testPath):
                        if testPath not in seenTestNames:
-                               unseenTests.append(testPath)
+                               if ".tentative" not in testPath:
+                                       unseenTests.append(testPath)
        if unseenTests:
                warn("There are {0} WPT tests underneath your path prefix aren't in your document and must be added:\n{1}",
                        len(unseenTests),
```

But do we?

**Comment by frivoal** [comment]
https://github.com/tabatkins/bikeshed/commit/8dfdf2ed5fc6ab13df001e8912368d1a94aa49dd fixes the problem, closing.
