### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by serianox** [tabatkins/bikeshed#1501]
It should be useful if the HTML documentation of bikeshed (located at [https://tabatkins.github.io/bikeshed/](https://tabatkins.github.io/bikeshed/)) is embedded in the install, in order to read it offline.

edit: fix link

**Comment by tabatkins** [comment]
It *is* embedded in the install, in `docs/index.html`. ^_^

**Comment by serianox** [comment]
Ouch... sorry for asking. :|

**Comment by tabatkins** [comment]
Not a problem!
