### ISSUE TITLE
MessagePort no longer recognized

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1505]
As shown at the bottom of https://travis-ci.com/WebAudio/web-audio-api/builds/122606215, bikeshed no longer recognizes links to MessagePorts.  For whatever reason webaudio was using 
```
<a data-link-type="idl-name" class="n" data-lt="MessagePort">MessagePort</a>
```

This used to work until this Friday or so. Travis always uses the latest bikeshed.  I updated my local copy of bikeshed and can reproduce this.

CC: @hoch

**Comment by domenic** [comment]
We had a temporary hiccup where much of the IDL in the HTML spec disappeared for a few hours. During that time the Bikeshed databases probably got updated to the bad state. I suspect by now they may be fixed, so it's worth retrying? Otherwise, @tabatkins can probably kick off a re-scrape manually.

**Comment by rtoy** [comment]
Ah, thanks! I'll try it out in a bit.

**Comment by rtoy** [comment]
Updated bikeshed now, and everything is working as it used to.

Nothing to see here; move along.
