### ISSUE TITLE
Parameter table no longer lists type and whether parameter is nullable or optional

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1511]
You can see an example of this at https://pr-preview.s3.amazonaws.com/padenot/web-audio-api/pull/1993.html#AnalyserNode-constructors.  Compare this to https://webaudio.github.io/web-audio-api/#AnalyserNode-constructors

The working draft says `context` has type `BaseAudioContext` and is not nullable and is not optional.  In the preview, nothing is given.  Only the parameter name and description are filled in.

**Comment by tabatkins** [comment]
Hm, sounds like a bug, definitely. I'm on vacation for the rest of the month, tho, so I'll have to get to this later. 😭

**Comment by rtoy** [comment]
I ran the build locally with the version of bikeshed from right now.  The issue is gone, and the table is filled correctly.

Since I can't reproduce this, I'm closing it.  If it comes up again, I'll reopen or file a new issue.
