### ISSUE TITLE
Remove https://www.w3.org/2001/tag/doc/promises-guide from Shepherd

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1512]
Folks should use IDL now which defines identical terms. This would also fix https://github.com/w3ctag/promises-guide/issues/27. I guess the alternative is that we stop exporting things there. Maybe we should just do both...

cc @domenic @Ms2ger

**Comment by Ms2ger** [comment]
I think this is no longer needed.

**Comment by tabatkins** [comment]
So wait, should I remove it or not?

**Comment by annevk** [comment]
Let's leave it now we no longer export any terms, but if it remains problematic somehow I'll reopen.
