### ISSUE TITLE
Update for constructor operation support

### ISSUE THREAD

**Issue by Ms2ger** [tabatkins/bikeshed#1513]
Probably just needs https://github.com/plinss/widlparser/issues/44 to be imported.

**Comment by plinss** [comment]
widlparser has been updated.

Note that extended attribute constructors are exposed by the 'constructors' property, but constructor operations are not, they're just regular methods. Both are exposed by the 'members' property but constructor operations have a 'method' idlType while the [Constructor] and [NamedConstructor] attributes have a 'constructor' idlType.

Let me know if this is going to be an issue for bikeshed, but it was necessary to differentiate them within widlparser.

**Comment by foolip** [comment]
Sent https://github.com/tabatkins/bikeshed/pull/1514 if anyone has the power to review.

**Comment by birtles** [comment]
It seems like this doesn't linkify `constructor`? (Unlike `[Constructor]` which was link-ified.) And it doesn't correctly linkify the arguments of the constructor either with constructor scope?

Is that right, or am I just doing it wrong?

**Comment by foolip** [comment]
That's right, see https://github.com/tabatkins/bikeshed/issues/1519.

**Comment by birtles** [comment]
Thank you!
