### ISSUE TITLE
bikeshed refs doesn't know about getUserMedia

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1518]
Run
```
bikeshed refs --text="getUserMedia()"
```
This produces nothing.  However, this autolink (used in the WebAudio spec) works: `[[mediacapture-streams#dom-mediadevices-getusermedia|getUserMedia()]]`

**Comment by tabatkins** [comment]
Ahaha, that's not a term autolink, that's a cross-spec section autolink! Totally different functionality, and that spec isn't in Shepherd, so none of its definitions are in Bikeshed's database. (Notice that `bikeshed refs --spec=mediacapture-streams` returns nothing at all.)

So I presume this means you want me to add MediaCapture Streams to the autolinking database. ^_^

**Comment by rtoy** [comment]
Ah, ok.

**Comment by tabatkins** [comment]
Just added WebAudio and Mediacapture&Streams to the Shepherd db, their definitions should percolate into Bikeshed in the next hour or so.
