### ISSUE TITLE
CSP-3 recommended by the link disambiguator but only CSP3 exists in specref

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1542]
Repro case:

```
<pre class='metadata'>
Title: Origin Policy
Status: CG-DRAFT
Group: WICG
ED: https://WICG.github.io/origin-policy
Repository: WICG/origin-policy
Shortname: origin-policy
Level: None
Editor: Mike West 56384, Google Inc., mkwst@google.com
Abstract: foo
Indent: 2
Default Biblio Status: current
Markup Shorthands: css off, markdown on
Boilerplate: omit conformance, omit feedback-header
</pre>
<pre class="abnf" dfn-type="grammar" link-type="grammar">
  <a>base64-value</a>
</pre>
```

Error output:

```
Error running preprocessor, returned code: 1.
LINK ERROR: Multiple possible 'base64-value' grammar refs.
Arbitrarily chose https://w3c.github.io/webappsec-subresource-integrity/#grammardef-base64-value
To auto-select one of the following refs, insert one of these lines into a &lt;pre class=link-defaults> block:
spec:sri-1; type:grammar; text:base64-value
spec:csp-3; type:grammar; text:base64-value
&lt;a data-link-type="grammar" data-lt="base64-value">base64-value&lt;/a>
 ✘  Did not generate, due to fatal errors
```

However, csp-3 does not exist in specref; only CSP3 does.

If I add the suggested csp-3 link default, then my bibliography contains a [CSP-3] entry which goes to the right place, and my "Terms defined by" talks about [csp-3].

If I then additionally add `Blah [[CSP3]]`, my bibliography switches to a [CSP3] entry, but "Terms defined by" still talks about [csp-3], i.e. it now references a bibliography entry which doesn't exist.

If I try to add the suggested link default but using `csp3` instead of `csp-3`, I get `LINK ERROR: No 'grammar' refs found for 'base64-value' with spec 'csp3'.`.

**Comment by tabatkins** [comment]
All right, this should be a result of the fact that it's "CSP3" in SpecRef but "csp-3" in Shepherd. I've fixed shepherd to match, so you should be able to update in a couple minutes. Let me know if it fixes the issue.

**Comment by tabatkins** [comment]
Yeah, looks fixed.
