### ISSUE TITLE
For some reason `h1–6` are 'dfn' refs, not 'element' refs.

### ISSUE THREAD

**Issue by hober** [tabatkins/bikeshed#1569]
I was surprised that `<{h1}>` failed to autolink.

If I run `bikeshed refs  --spec=html --type=element --text=track`, I get this:

```
status:    snapshot
for:       []
level:     1
url:       https://html.spec.whatwg.org/multipage/media.html#the-track-element
type:      element
export:    True
text:      track
shortname: html
normative: True
spec:      html
```

But if I run `bikeshed refs  --spec=html --type=element --text=h1`, I get this:

```
[]
```

Instead, `bikeshed refs --spec=html --type=dfn --text=h1` returns something usable:

```
status:    snapshot
for:       []
level:     1
url:       https://html.spec.whatwg.org/multipage/sections.html#the-h1-element
type:      dfn
export:    False
text:      h1
shortname: html
normative: True
spec:      html
```

**Comment by tabatkins** [comment]
It's a problem with HTML's markup, so I've filed an issue. Closing here, as it'll automatically be correct after HTML fixes themselves.
