### ISSUE TITLE
[[fingerprinting-guidance#clearing-all-local-state]] generates ugly link

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1573]
https://w3c.github.io/fingerprinting-guidance/ is in Shepherd, so by ["You can also use cross-spec section links, as long as the spec is either in Bikeshed’s linking database, or the biblio database. ... If Bikeshed knows about the spec, it link-checks you, and fills in the section number and heading in the generated text. If the spec is only in the bibliography database, Bikeshed just assumes that the link target exists and uses it directly in the text, because it has no way to tell what the section is named."](https://tabatkins.github.io/bikeshed/#section-links) I'd have thought it would insert the actual section name. Instead it shows "Mitigating Browser Fingerprinting in Web Specifications §clearing-all-local-storage". Fixing #1325 might also be sufficient.

**Comment by tabatkins** [comment]
Ah, that's because it's in Shepherd as fingerprinting-guidance-1. I should put in some logic letting you link to the latest without a number, and emit a warning asking you to clarify it.

**Comment by jyasskin** [comment]
I think I'd be sad about a warning for a spec that has only 1 level. It might also make sense to have Shepherd index it without the level, since https://github.com/w3c/fingerprinting-guidance/blob/gh-pages/index.html doesn't specify a level.

**Comment by tabatkins** [comment]
There's a lot of specs that are getting published to /TR these days that absolutely should have a level, but are allowed to go without for some reason, so I'm not sure I should change the indexing.

That said, you're right that if there's only a single version I shouldn't warn.

**Comment by tabatkins** [comment]
And fixing this just found a broken link in one of my specs, nice.
