### ISSUE TITLE
Please add the page visibility spec to Bikeshed

### ISSUE THREAD

**Issue by janiceshiu** [tabatkins/bikeshed#1577]
Hi! Is it possible to add the [page visibility spec](https://www.w3.org/TR/page-visibility/) to Bikeshed? The [screen orientation spec]( https://w3c.github.io/screen-orientation/#dependencies) references definitions from page visibility and I would like to be able to reference those terms properly using [xref](https://respec.org/xref/)

I'm happy to do the addition myself if someone could point me to a guide to do so. 

Thank you very much!

P.S. Thank you @annevk for pointing me to this repo when I asked how terms are added into xref.

cc @marcoscaceres

**Comment by tabatkins** [comment]
I've added it. (Unfortunately, the method is currently manual and requires special permissions.)

However, the definitions in this spec are, currently, completely broken. They don't have their type specified (so they all default to "dfn" type, and aren't autolinkable by syntax like `{{Document/visibilityState}}` or `{{VisibilityState}}`, and everything I looked at in a quick inspection has incorrect `for` values specified, either lacking a `for` entirely or specifying an empty `for`.

It looks like ReSpec does some live fix-up of at least some of these issues in the ED, but Bikeshed consumes the document's source, not the post-JS rendered DOM, so it won't see any of this effort. Until these are properly fixed to follow [the Bikeshed dfn contract](https://tabatkins.github.io/bikeshed/#dfn-contract), having the spec in Bikeshed will be almost useless for actually linking to the spec.  (But once you fix things, it'll get picked up automatically in an hour or less.)

**Comment by janiceshiu** [comment]
@tabatkins thanks! Will look into the Bikeshed dfn contract and reach out again if I have any problems.

**Comment by marcoscaceres** [comment]
Just FYI, we've aligned much more closely with the dfn contract. Only static docs on TR will be consumed by Shepherd - so the data in Shepherd should be good. If there is any dirty data coming from ReSpec, it probably means that the document on TR is out of date.
