### ISSUE TITLE
Documentation for developing bikeshed

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1581]
I've found out I can run `bikeshed test`, but it's very slow. I've now discovered I can also run `bikeshed test [individualtestinsidetests]`, but it doesn't really indicate why things failed. `--rebase` is nice, we should document it!

Do I need to install or is running `bikeshed update` sufficient since that also works if you pull from master?

**Comment by tabatkins** [comment]
Happy to document bikeshed testing/development more; it hasn't come up as something most users need yet, so I haven't bothered with it.

(Note also the --manual-only flag, which doesn't run all the real-world specs, just the manually-created tests. Changes test-running from a 5min affair to 20s.)

> Do I need to install or is running bikeshed update sufficient since that also works if you pull from master?

Not sure what you're asking here.

**Comment by annevk** [comment]
I wasn't sure if I needed to do anything after modifying bikeshed's code.
