### ISSUE TITLE
Should have boilerplate for immersivewebcg as copy of immersivewebwg or not

### ISSUE THREAD

**Issue by himorin** [tabatkins/bikeshed#1582]
situation: https://immersive-web.github.io/hit-test/ uses immersivewebcg for Group, and output does not have CG mark
background: W3C Immersive Web has two groups, working group and community group, in close relationship (or mostly overlapped). Bikeshed has both immersivewebwg and immersivewebcg in "bikeshed/config/status.py", but only immersivewebwg in boilerplate.

I think both WG/CG would use the same template for html generation, so the easiest way would be to make WG/CG using one group name - immersivewebwg (I suppose), but having a copy of immersivewebwg as immersivewebcg in boilerplate would work also. Which option is the way to go?

/cc @bialpio @TrevorFSmith

**Comment by tabatkins** [comment]
Which way to go is totally up to y'all; the only reason to have separate boilerplate is if you need different text. If the WG and CG have identical boilerplate text on their specs of a given Status, then it's fine to just use one.
