### ISSUE TITLE
include syntax works locally, fails on csswg.org

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#1583]
In CSS color 4:

```
<pre class="include-code lang-javascript">
path: conversions.js
highlight: js
</pre>
```

correctly inlines the javascript file, with syntax hilighting, when bikeshed is run locally. On csswg.org [the include fails](https://drafts.csswg.org/css-color-4/#color-conversion-code). Overview.bs and conversions.js are in the same directory.

**Comment by tabatkins** [comment]
Hm, this'll be something to do with the server setup. I think I recall @plinss saying that they copy the files into a temp directory to generate them; presumably they're not copying over the support files as well.

@plinss, is this an accurate read? If so, could you copy over all the files in the given folder?

**Comment by plinss** [comment]
Took a look at the server code, it does scan for includes and copies those over as well during generation. However, it's looking for &lt;pre&gt; elements with an 'include' class to find the includes. I just need to look for 'include-code' as well. Are the other types of includes? Or should I just look for classes that are 'include-*'?

**Comment by tabatkins** [comment]
Yeah, currently I've got include-code and include-raw. In case I add more in the future, might as well just grab all the include-* classnames.

**Comment by plinss** [comment]
Ok should be fixed. I'm now copying all files specified in &lt;pre&gt; with 'include' and 'include-*' classes (literally: '^include(-.+)?$', so should be safe and future-proof).

**Comment by svgeesus** [comment]
And indeed the include in CSS color 4 is now working correctly on CSSWG.org. Thanks, @plinss and @tabatkins !
