### ISSUE TITLE
Add Fetch Metadata to bikeshed's index.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#1584]
Hey @tabatkins! Would you mind poking at whatever configuration is necessary to get https://w3c.github.io/webappsec-fetch-metadata/ properly indexed so we can link to it cleanly from https://github.com/whatwg/fetch/pull/993?

Thanks!

**Comment by tabatkins** [comment]
Done, it'll be in the database in an hour or less.
