### ISSUE TITLE
DictionaryMember default [] is rendered as None

### ISSUE THREAD

**Issue by emlun** [tabatkins/bikeshed#1592]
For example, see https://www.w3.org/TR/2019/WD-webauthn-2-20191126/#dom-publickeycredentialcreationoptions-excludecredentials, where this markup:

```
    sequence<PublicKeyCredentialDescriptor>      excludeCredentials = [];
```

is rendered as:

>***excludeCredentials*, of type sequence\<PublicKeyCredentialDescriptor\>, defaulting to `None`**

I'm new to the fine details of WebIDL and Bikeshed, but if I understand the specs correctly, `[]` is a valid default value and should probably be rendered as simply "[]". In that case, the root cause of the issue seems to be here:

https://github.com/tabatkins/bikeshed/blob/2a881f0ee698433d75c6a1555514334adb37d8c7/bikeshed/idl.py#L158-L160

which does not account for that `construct.default.value` will be `None` if the default value is `[]` or `{}`, in which case the object will have `._open` and `._close` set instead of `.value`.

Changing it to this seems to fix the issue, but it doesn't seem like the right solution:

```
                value = escapeAttr("{0}".format(construct.default.value if construct.default.value else (construct.default._open.symbol + construct.default._close.symbol)))
```

I'd be happy to contribute a fix if I can get a confirmation that my understanding seems correct, and perhaps some pointers to what might be a better solution. :slightly_smiling_face:

**Comment by tabatkins** [comment]
Huh, interesting. Welp, it's definitely an error, but I'll have to look more into open/close to see what all that covers.

**Comment by emlun** [comment]
Ok, thanks for confirming! I'll look around some more and see if I can find something that seems like a good solution.

What I found is that the relevant values are set here in `Default`:

https://github.com/tabatkins/bikeshed/blob/2a881f0ee698433d75c6a1555514334adb37d8c7/bikeshed/widlparser/widlparser/productions.py#L1108-L1111

which is called from here in `DictionaryMember`:

https://github.com/tabatkins/bikeshed/blob/2a881f0ee698433d75c6a1555514334adb37d8c7/bikeshed/widlparser/widlparser/constructs.py#L1043-L1050
