### ISSUE TITLE
All wpt data seems to have disapeared, causes fatal errors

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1601]
`bikeshed spec` on a spec that uses the `<wpt>` tag (such as css-text-3 or css-contain-1) now throws fatal errors for every test mentioned, even those that used to work and that still exist in the WPT repo.

Not sure bikeshed is the guilty party, but bikeshed is where I'm experiencing the problem. Maybe wpt's export is broken, maybe bikeshed's import is broken, maybe something else. But eitherways, something's broken.

**Comment by tabatkins** [comment]
Oh jeez, something's gone quite wrong with the data source; back on Feb 1 it stopped reporting paths properly (just reporting spec names, at least with the method I use to compile the data), so we suddenly lost about 40k of lines of test data: https://github.com/tabatkins/bikeshed-data/commit/c9299490c703e5cc6a353291715797dfc39268b0

Phew, I'll investigate.

**Comment by tabatkins** [comment]
Okay, looks like WPT just changed its manifest format dramatically in <https://github.com/web-platform-tests/rfcs/pull/40> without anyone thinking to tell me, great.

**Comment by tabatkins** [comment]
Okay, fixed in 381ed22c
