### ISSUE TITLE
WebIDL errors for default argument to dictionary input

### ISSUE THREAD

**Issue by yoavweiss** [tabatkins/bikeshed#1605]
In https://github.com/WICG/ua-client-hints/pull/70#discussion_r386968212:
`Promise&lt;UADataValues&gt; getHighEntropyValues(optional UADataOptions options) = {};` triggers a bikeshed IDL error. 
`UADataOptions` is a dictionary. 
Removing ` = {}` makes the error go away.

**Comment by tabatkins** [comment]
That works just fine for me. Have you updated your Bikeshed recently?

**Comment by tabatkins** [comment]
(Well, it works fine once I move the `= {}` *into* the parentheses, which I assume you meant. ^_^)
