### ISSUE TITLE
Installation guide with pipenv

### ISSUE THREAD

**Issue by serianox** [tabatkins/bikeshed#1614]
The installation guide could be updated to mention the usage of pipenv to deploy bikeshed for a single project using pipenv.

I was able to achieve a one-step installation on Windows (with Python 2.7.x and 3.x, and pipenv installed) using the following command-line:
```
py -3 -m pipenv --three install git+https://github.com/tabatkins/bikeshed.git@master#egg=bikeshed
```
I think the same can be achieved on Unix with a similar command:
```
python -m pipenv --three install git+https://github.com/tabatkins/bikeshed.git@master#egg=bikeshed
```

edit: update to Python 3

**Comment by tabatkins** [comment]
That's not an editable install; can it `bikeshed update`? And how do you update it to a newer version?

(I know, the correct answer is "push bikeshed to pypi, duh", but I"m not doing that yet.)

**Comment by de-sh** [comment]
I use `pipenv` while working on bikeshed myself. The following is how I'd work.

```bash
# `python -m` is optional
$ pipenv install # install dependencies, uses requirements.txt if no Pipfile available
$ pipenv install -e . # equivalent to pip install -e .
$ pipenv run bikeshed update # that's about it...
```

**Comment by tabatkins** [comment]
Okay cool, was just making sure; I wasn't sure how non-editable installs worked earlier yesterday.

**Comment by serianox** [comment]
@de-sh Yes, it is even easier on Unix than I thought. :) On Windows, the -m is mandatory because I'm starting pipenv from pylauncher, but maybe I haven't found how to do it properly.

Basically on pipenv, you either `pipenv run <command>` or `pipenv shell` and then work from this shell as if you pip-installed globally your packages.

I'll dig this setup a little bit deeper, but at least we have this thread that can be found for those looking.

**Comment by serianox** [comment]
```
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: bikeshed requires Python '>=3.7' but the running Python is 2.7.17
```
:D #1138

**Comment by tabatkins** [comment]
I believe the docs now fully capture this info!
