### ISSUE TITLE
Update widlparser for ObservableArray

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1633]
Added in https://github.com/plinss/widlparser/commit/466fea9673be0560a6efa668622215eaa1f3790e but doesn't seem to work in Bikeshed yet.

**Comment by tabatkins** [comment]
It works (assuming you've updated bikeshed), but the patch isn't correct and disallows using it as an attribute value. But you can freely use it as a method return value right now.

I'll open an issue on widlparser.

**Comment by tabatkins** [comment]
Never mind, I was spelling it wrong, it works just fine in all cases. ^_^

So I assume you haven't run `pip install --upgrade bikeshed` recently, is all.  (Or possibly Peter hasn't on the server?)

**Comment by domenic** [comment]
Yeah, I guess the server is what needs updating.

**Comment by tabatkins** [comment]
K, I pinged Peter, he probably just hasn't updated the server setup to do a `pip install --upgrade -e .`, and is instead just relying on a `git pull`. I'll go ahead and close this.

**Comment by tabatkins** [comment]
Ah, Peter reminds me that the server is currently stuck on the py2 branch, which is why the update hasn't come down. He'll be updating to master this weekend.
