### ISSUE TITLE
Allow directly linking to referenced specs (by opt-in)

### ISSUE THREAD

**Issue by brycelelbach** [tabatkins/bikeshed#1641]
https://gist.github.com/brycelelbach/56ca94ac7f1f9d93348fb034288c125e

Capturing our discussion on Twitter:

> Tab: Oh, have the biblio ref link directly to the other spec, rather than to the bibliography entry?
> Bryce: Bingo, yah
> Tab: No way right now. Would you like it to still show up in the biblio too?
> Bryce: Yep 100% still want it in the biblio.

I imagine this would be something that you'd opt into via metadata.

**Comment by brycelelbach** [comment]
@tabatkins any thoughts on this?

**Comment by tabatkins** [comment]
Done. You can do this per-link by saying `[[FOO inline]]`, or default the entire doc with `Default Biblio Display: inline`.

**Comment by brycelelbach** [comment]
You rock.

On Fri, Oct 9, 2020 at 3:33 PM Tab Atkins Jr. <notifications@github.com> wrote:
>
> Done. You can do this per-link by saying [[FOO inline]], or default the entire doc with Default Biblio Display: inline.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Bryce Adelstein Lelbach aka wash (he/him/his)
US Programming Language Standards (PL22) Chair
ISO C++ Library Evolution Chair
CppCon and C++Now Program Chair
C++ Core Compute Libraries (Thrust, CUB, libcu++) Lead @ NVIDIA
--
