### ISSUE TITLE
Misplaced MDN link

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1642]
Visit https://webaudio.github.io/web-audio-api/#AudioBufferSourceNode.  A few lines up, you'll see the MDN link. If you click it, it says it's about AudioBufferSourceNode.

In fact, as I now look at other sections on audio nodes, the location of the MDN link is sometimes before the audio node section header and sometimes many lines after.  Perhaps this is a bug in the WebAudio spec?

The links are pretty cool though, and it's pretty clear what the link is about, even if it's in the wrong location.

**Comment by mkruisselbrink** [comment]
Fun, when I load that URL the MDN link starts out aligned with the header, then jumps down a bit, and then repeatedly jumps up until it ends up somewhere above the header as you say. When DOMContentLoaded fires it is at the right location, but afterwards while math formulas are rendering it moves all over the place.

**Comment by tabatkins** [comment]
Ah shoot, yeah, that'll happen.

The only sane way to put these sorts of things in is by making them children of `body` and then abspos'ing them into place, which means it's just measured from the top of the document. If stuff moves around afterwards, welp, they'll be misplaced.

I suppose I could make the code run every so often to check the height of the document and, if it's changed, rejigger everyone's positions again.  After all, they'll all be messed up if you do something like resize the window, which sucks.

(Really, CSS just needs more powerful abspos anchoring primitives, which is something I've noodled over for several years, but haven't gotten to working on yet.)

I'll record this as a bug for me to do the re-positioning thing.

**Comment by domenic** [comment]
We've had some success in HTML with placing them as children of the body but before/after the element in question, then only setting `right` when absolutely positioning. That would solve the problem, I believe.

**Comment by tabatkins** [comment]
It would for at least some things here, but it depends on what exactly is being targeted. Headings or other block-level elements, yeah, putting the `aside` just before them would work fine. But for inline definitions, I can't, unless I walk up the tree to find a block-level ancestor.

...which I suppose I could do, sure.

(Hm, I was going to say that I need this fix for dfn panels anyway, but no, those get positioned only when you summon one, so they'll only be misaligned if you summon a panel then do something to the doc.  So hm, yeah, maybe I'll do this tree-insertion stuff.

**Comment by tabatkins** [comment]
Oh, as far as I can tell this got fixed at some point. The MDN panel in question is correctly aligned, it stays aligned when I resize the window, and looking at the source it is indeed positioned right after the heading in the DOM and relying on its static vertical position.

Please lmk if there is indeed still a problem.
