### ISSUE TITLE
DOMHighResTimeStamp link missing now

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1646]
The WebAudio spec references `DomHighResTimeStamp` in
[Section 1.2.5. AudioTimeStamp](https://webaudio.github.io/web-audio-api/#AudioTimestamp).  This used to link to https://www.w3.org/TR/hr-time-2/#dom-domhighrestimestamp, but after updating bikeshed, this no longer works.

There are also lots of new additional errors when building the WebAudio spec.  For example, we get

```
LINK ERROR: No 'argument' refs found for 'numberOfChannels'.
<a data-lt="numberOfChannels" data-link-type="argument"
data-link-for="OfflineAudioContext/OfflineAudioContext(numberOfChannels,
length, sampleRate), OfflineAudioContext/constructor(numberOfChannels,
length, sampleRate)">numberOfChannels</a>
```

This error didn't use to occur.  The former is a bug in bikeshed.  The latter could very well be a bug in the WebAudio spec which is now incorrect because bikeshed tightened up something.

**Comment by tabatkins** [comment]
It looks like DOMHighResTimeStamp is linking again? Must have been an intermittent data error, since I also see it in the database.

The argumentdef failures are indeed new, and debugging is turning out to be *interesting*. More updates as I figure this out.

**Comment by tabatkins** [comment]
Pretty sure it's a bug in my webidl parser, <https://github.com/plinss/widlparser/issues/56> is tracking it.

**Comment by rtoy** [comment]
Updated bikeshed this morning.  Still get this error:
```
LINK ERROR: No 'idl-name' refs found for 'DOMHighResTimeStamp'.
<a class="n" data-link-type="idl-name" data-lt="DOMHighResTimeStamp">DOMHighResTimeStamp</a>
```
Could be that I didn't update correctly or I'm running the wrong version. (Had some troubles installing the new version but pip install is working fine.)

Thanks for looking in to this.

**Comment by rtoy** [comment]
Tried bikeshed again today.  It looks much better and most of the issues are gone.

Except I'm now getting 

> FATAL ERROR: Unknown biblio prefix '5' on key '500: Internal Server Error'

I think this make all the links to bibliographic data broken.

**Comment by rtoy** [comment]
Here's the log from running `bikeshed --print=plain -f spec`:
```
FATAL ERROR: Unknown biblio prefix '5' on key '500: Internal Server Error'
LINE -1: Couldn't find 'WEBGL' in bibliography data. Did you mean:
  webgl
  webgl-1
  webgl-103
  webgl-2
  webxr
  webidl
  webcgm
  webac
  webm
LINE ~214: Couldn't find 'webaudio-usecases' in bibliography data. Did you mean:
  webaudio-usecases
  webcrypto-usecases
  netinfo-usecases
  did-use-cases
  emma-usecases
  webrtc-nv-use-cases
LINE ~260: Couldn't find 'webrtc' in bibliography data. Did you mean:
```
and many more lines about not finding stuff in the biblio data.

**Comment by rtoy** [comment]
`bikeshed update` also does something weird (starting today?) Now it just dumps out a things like

> mdn/xslt-10.json55aeb192480c7d10e28abe26be29a9a1 mdn/xslt-20.json55aeb192480c7d10e28abe26be29a9a1 mdn/xslt-30.json

**Comment by inexorabletash** [comment]
Specifically the error is:
```
Traceback (most recent call last):
  File "/home/jsbell/.local/bin/bikeshed", line 10, in <module>
    sys.exit(main())
  File "/home/jsbell/.local/lib/python3.7/site-packages/bikeshed/cli.py", line 210, in main
    handleUpdate(options, extras)
  File "/home/jsbell/.local/lib/python3.7/site-packages/bikeshed/cli.py", line 238, in handleUpdate
    update.update(anchors=options.anchors, backrefs=options.backrefs, biblio=options.biblio, caniuse=options.caniuse, mdn=options.mdn, linkDefaults=options.linkDefaults, testSuites=options.testSuites, languages=options.languages, wpt=options.wpt, dryRun=constants.dryRun, force=options.force)
  File "/home/jsbell/.local/lib/python3.7/site-packages/bikeshed/update/main.py", line 26, in update
    success = manifest.updateByManifest(path=path, dryRun=dryRun)
  File "/home/jsbell/.local/lib/python3.7/site-packages/bikeshed/update/manifest.py", line 102, in updateByManifest
    localDt = datetime.strptime(localManifest[0].strip(), "%Y-%m-%d %H:%M:%S.%f")
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 87934a27f8af3c8f57035eb80c6346d1 mdn.json92a2...
```

... with tons of spewed data following

**Comment by tabatkins** [comment]
All right, while this is fixed in the live data, there was a period of time where the manifest was being generated wrong and put its entire contents on one line accidentally.

Looks like my code wasn't robust to the possiblity of the manifest being totally borked, so it's just straight failing.

I've fixed it locally; as soon as this update finishes, I'll push the fixed version to PyPi and you can update things. (`pip install --upgrade bikeshed`, then `bikeshed update`)

**Comment by tabatkins** [comment]
And done. Once you upgrade, you should be at version 1.1.0 (check it with `bikeshed -h`), and should be golden. Let me know if there are still any problems.

**Comment by rtoy** [comment]
Thanks @tabatkins!  This looks great and the number of errors in the WebAudio spec has been reduced.

However, `bikeshed -h` doesn't seem to print out any version number for me.

**Comment by tabatkins** [comment]
Then you're not on the latest version, since I just added it as part of the 1.1.0 release. ^_^

**Comment by inexorabletash** [comment]
My copy (via `pip3 install --upgrade bikeshed`) has the code from 5359f34a95b0f1a5081516971df96d970b9d233c but no `semver.txt` file so no version is printed.

**Comment by tabatkins** [comment]
...weird, <https://github.com/tabatkins/bikeshed/blob/master/MANIFEST.in> specifies that it should include that file.
