### ISSUE TITLE
Bikeshed web service returning 500 for Web IDL spec; local Bikeshed works fine

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1649]
I'm not sure where to report this, but I'll try here. /cc @plinss.

If you clone master of https://github.com/heycam/webidl and run

```
curl https://api.csswg.org/bikeshed/ -F file=@index.bs > out.html
```

you get

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>
```

but if you run

```
bikeshed index.bs
```

it works fine. (With Bikeshed current master and `bikeshed update` applied.)

**Comment by plinss** [comment]
Working for me. It's probable you were trying at a time the server was under heavy load and timed out. That server gets hit by spam crawlers fairly often. 

The server is due for some upgrades...

**Comment by domenic** [comment]
Thanks, it's working now! I retried once, but I should have kept retrying, I guess :)
