### ISSUE TITLE
solidus (aka "slash") "/" does not work in link text 

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#1670]
(reproduced from https://github.com/fido-alliance/fido-2-specs/pull/857#pullrequestreview-413090943):
> A note about “PIN/UV auth protocol”: Bikeshed can't link it as a definition. The solidus (‘/’) in an autolink is special and I can't get around it. Trying to use a bar to set the visible text doesn't work either because the solidus is parsed out first. Escaping it with &#47; or &sol; doesn't work because they appear to be resolved early in the parse. Thus I'm manually linking each instance.

**Comment by tabatkins** [comment]
This is a true fact; you can't use the autolink *shorthands* for that. You can still autolink, so it can still remain more robust than manual linking, just using the slightly more manual syntax that the shorthands get translated into: `<a>PIN/UN auth protocol</a>` (or if it's not a "dfn" type definition, specify it with an attribute, like `<a interface>MyCoolIDLInterface</a>`)
