### ISSUE TITLE
Question: Why `application/x-www-form-urlencoded` is element-attr and not attr-value?

### ISSUE THREAD

**Issue by sidvishnoi** [tabatkins/bikeshed#1679]
I'm trying to link to [`application/x-www-form-urlencoded`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fs-enctype-urlencoded) (https://github.com/w3c/respec/issues/2913). Bikeshed data [shows](https://github.com/tabatkins/bikeshed-data/blob/260ae9181b3940eb7301a1446c64e3eddc09b206/data/anchors/anchors-ap.data#L888-L896) it as `element-attr`. Should it not be an `attr-value`? 
If I'm not wrong, it should be linkable as `<{form/formenctype/application\/x-www-form-urlencoded}>`. That maybe too verbose, so maybe a dfn (`[=application\/x-www-form-urlencoded=]` or `[=formenctype/application\/x-www-form-urlencoded=]`)?

I didn't see HTML spec adding any context to it, so I'm not sure why Bikeshed/Shepherd picked is as element-attr.

cc: @marcoscaceres

**Comment by tabatkins** [comment]
HTML isn't a Bikeshedded spec, so most of its definitions aren't marked up explicitly with their types/etc, and Shepherd is forced to deploy heuristics to guess at what they are. In this case, it's guessing wrong.

Would you mind filing a request on HTML to mark up that definition properly?

**Comment by sidvishnoi** [comment]
Thanks for explaining that, @tabatkins!
Can you transfer this issue to HTML if possible? I'll open a new issue there otherwise
