### ISSUE TITLE
Macro substitution issue

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1696]
Say I want to have `[css-text-3]` (with brakets) as the output generated by bikeshed, based on the `[SHORTNAME]` macro.

1. I cannot use `[shortname]` as the output would be `css-text-3` without brackets

2. I cannot use `[[shortname]]` as it would think it's a biblio ref for the document called shortname

3. I cannot use `[ [shortname]]` as the output would be `[ css-text-3]`, with an extra space

4. I cannot use this `\[[shortname]]` as the output would be  `[[shortname]]`

5. I cannot use this `\[[shortname]\]` as the output would be  `\[[shortname]\]`

If there is a syntax that makes that work, I couldn't find it.

**Comment by tabatkins** [comment]
Lol, yeah, this is kinda difficult.

In the past this has been done with `[<!---->[SHORTNAME]]`. I believe that `&#x5b;[SHORTNAME]]` would also work, since I do macro substitution on the raw text, before HTML parsing.

**Comment by frivoal** [comment]
What's the problem with making option 4 (or 5) work?
