### ISSUE TITLE
Don't put "Assert:" steps in a gray box

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1700]
I've just fixed two instances of this in https://github.com/w3c/webdriver-bidi/pull/32 and https://github.com/WICG/origin-policy/pull/97.

Searching for `class="assertion"` in bikeshed/tests/github finds 16 additional cases, most of which upon brief inspection look like it's a use of https://infra.spec.whatwg.org/#assert and not the Note- or Example-style box that Bikeshed has.

If this shorthand is to do anything, it would be more useful to auto-link https://infra.spec.whatwg.org/#assert. (Manually linking it fixing the problem.)

cc @annevk @domenic

**Comment by hober** [comment]
This has caught me a couple of times too.

**Comment by tabatkins** [comment]
Hmm, the `Assert:` thing is meant to be doing the same thing as Infra's assert. Maybe I just need to merge them more together?

**Comment by foolip** [comment]
Yeah, don't give them that gray box styling, just link https://infra.spec.whatwg.org/#assert :) Not recognizing it all would also work, auto-linking certain words seems slightly magical.

**Comment by annevk** [comment]
Auto-linking is also done for other words I think, such as Note: or Example:.

**Comment by foolip** [comment]
Those turn into green and yellow boxes, right? Assert now turns into a gray box, which is weird when it's a step in an algorithm.

**Comment by jyasskin** [comment]
I think Assert no longer turns into a gray box.
