### ISSUE TITLE
MDN link obscures caniuse.com panel collapse button

### ISSUE THREAD

**Issue by heycam** [tabatkins/bikeshed#1713]
At https://drafts.csswg.org/css-ui-4/#typedef-appearance-compat-auto the caniuse.com panel covers up some of the property definition.  I want to collapse it, but the MDN link is in the way of the `⋰` button.

**Comment by sideshowbarker** [comment]
Glad you caught this. So in the stylesheet that Bikeshed generates, I think we need to make it add a some increase-z-index-on-hover for the caniuse panels. (I believe the MDN panels already have such.) I’ll try to write up a patch/PR which adds that in the right way.

**Comment by sideshowbarker** [comment]
Raised https://github.com/tabatkins/bikeshed/pull/1716
