### ISSUE TITLE
bikeshed should mark as no-export CSS values that are reusing predefined types

### ISSUE THREAD

**Issue by dontcallmedom** [tabatkins/bikeshed#1715]
When a CSS property is defined with bikeshed, and the components of the value are marked with a `<dfn>` element, these components end up being exported by default.

While this may make sense for e.g. specific keywords, I don't think it does for e.g. `<length-percentage [0,+∞]>` as in the definition of [background-size components](https://drafts.csswg.org/css-backgrounds-3/#valdef-background-size-length-percentage-0).

While one could argue the specs should explicitly set `no-export` on these `<dfn>`, since it is bikeshed that automatically set the export on them, and since there are quite a few specs where this is the case, I wonder if bikeshed could and should by default not export them.

<details><summary>List of cases</summary>
<ul><li> `&lt;absolute-size>` is exported as value in css-fonts-4
<li> `&lt;angle>` is exported as value in css-images-3, css-images-4
<li> `&lt;angle>? flip` is exported as value in css-images-3
<li> `&lt;basic-shape>` is exported as value in css-shapes-1, css-shapes-2
<li> `&lt;box>` is exported as value in css-backgrounds-4
<li> `&lt;color>` is exported as value in css-backgrounds-3, css-multicol-1, css-scrollbars-1
<li> `&lt;content-list>` is exported as value in css-content-3
<li> `&lt;counter-name> <integer>?` is exported as value in css-lists-3
<li> `&lt;counter-style-name>` is exported as value in css-counter-styles-3
<li> `&lt;counter-style>` is exported as value in css-lists-3
<li> `&lt;custom-ident>` is exported as value in css-grid-1, css-will-change-1
<li> `&lt;decibel>` is exported as value in css-speech-1
<li> `&lt;dimension-unit>` is exported as value in css-values-4
<li> `&lt;ending-shape>` is exported as value in css-images-3
<li> `&lt;family-name>` is exported as value in css-speech-1
<li> `&lt;feature-tag-value>` is exported as value in css-fonts-4
<li> `&lt;fill-rule>` is exported as value in css-shapes-2
<li> `&lt;'flex-basis'>` is exported as value in css-flexbox-1
<li> `&lt;'flex-grow'>` is exported as value in css-flexbox-1
<li> `&lt;'flex-shrink'>` is exported as value in css-flexbox-1
<li> `&lt;flex>` is exported as value in css-grid-1
<li> `&lt;frequency>` is exported as value in css-speech-1
<li> `&lt;'grid-template-rows'> / <'grid-template-columns'>` is exported as value in css-grid-1
<li> `&lt;'grid-template-rows'> / [ auto-flow && dense? ] <'grid-auto-columns'>?` is exported as value in css-grid-1
<li> `&lt;image>` is exported as value in css-content-3, css-lists-3, css-shapes-1
<li> `&lt;integer [1,∞]>` is exported as value in css-multicol-1, css-multicol-2
<li> `&lt;integer>` is exported as value in css-content-3, css-flexbox-1, css-inline-3, css-multicol-1, css-overflow-3, css-overflow-4, css-speech-1
<li> `&lt;integer> && <custom-ident>?` is exported as value in css-grid-1
<li> `&lt;keyframes-name>` is exported as value in css-animations-1
<li> `&lt;length [0,∞]>` is exported as value in css-multicol-1, css-overflow-3, css-transforms-2
<li> `&lt;length-percentage [0,∞]>` is exported as value in css-backgrounds-3, css-multicol-1
<li> `&lt;length-percentage>` is exported as value in css-backgrounds-3, css-fonts-4, css-grid-1, css-scroll-snap-1, css-shapes-1, css-sizing-3
<li> `&lt;length-percentage>+#` is exported as value in fill-stroke-3
<li> `&lt;length-percentage>{2}` is exported as value in css-images-3
<li> `&lt;length>` is exported as value in css-backgrounds-3, css-device-adapt-1, css-images-3, css-inline-3, css-multicol-1, css-page-3, css-position-3, css-scrollbars-1, css-shapes-1, css-text-3, css-text-decor-4, css-transforms-2
<li> `&lt;length>{2}` is exported as value in css-sizing-4
<li> `&lt;number [0,∞]>` is exported as value in css-backgrounds-3
<li> `&lt;number>` is exported as value in css-animations-1, css-backgrounds-3, css-flexbox-1, css-fonts-3, css-fonts-4, css-inline-3, css-shapes-1, css-speech-1, fill-stroke-3
<li> `&lt;percentage [0,∞]>` is exported as value in css-backgrounds-3
<li> `&lt;percentage>` is exported as value in css-backgrounds-3, css-device-adapt-1, css-fonts-4, css-inline-3, css-position-3, css-shapes-1, css-size-adjust-1, css-speech-1, css-text-3, css-text-decor-4, css-transforms-2
<li> `&lt;position>` is exported as value in css-images-3, css-images-4
<li> `&lt;ratio>` is exported as value in css-sizing-4
<li> `&lt;relative-size>` is exported as value in css-fonts-4
<li> `&lt;resolution>` is exported as value in css-images-4
<li> `&lt;semitones>` is exported as value in css-speech-1
<li> `&lt;size>` is exported as value in css-images-3, motion-1
<li> `&lt;string>` is exported as value in css-content-3, css-fonts-4, css-lists-3, css-overflow-3, css-shapes-1, css-shapes-2, css-text-4, css-text-decor-3, css-text-decor-4
<li> `&lt;string>+` is exported as value in css-grid-1
<li> `&lt;time>` is exported as value in css-animations-1, css-speech-1
<li> `&lt;track-list> | <auto-track-list>` is exported as value in css-grid-1
<li> `&lt;urange>` is exported as value in css-fonts-3
<li> `&lt;uri>` is exported as value in css-shapes-2, css-speech-1
<li> `&lt;url>` is exported as value in css-masking-1
</ul>
</details>

**Comment by jyasskin** [comment]
The couple of these that I just checked are setting a `data-dfn-for`, which means the exported definition won't collide with anything. And are plausibly useful link targets. Am I missing a reason this is a problem?

**Comment by tabatkins** [comment]
Additionally these are all exported as `data-dfn-type=value`, which is distinct from `data-dfn-type=type`; the latter is what's autolinked by the `<<foo>>` syntax, so there are no collisions there either. If there are collisions, they're no different from collisions in a common keyword - they do need fixing (with a `data-dfn-for`), but aren't wrong in general.
