### ISSUE TITLE
An HTML tag-closing greater-than sign at the start of a line gets weird results

### ISSUE THREAD

**Issue by andreubotella** [tabatkins/bikeshed#1722]
This
```html
<a href="https://example.com/a/link/so/long/it/goes/past/the/typical/80/characters"
>Something</a>.
```
gets processed into:
```html
<p><a U0003C href="https://example.com/a/link/so/long/it/goes/past/the/typical/80/characters" p> </a></p>
<blockquote>
 <a U0003C href="https://example.com/a/link/so/long/it/goes/past/the/typical/80/characters" p> </a>
 <p><a U0003C href="https://example.com/a/link/so/long/it/goes/past/the/typical/80/characters" p>Something</a>.</p>
</blockquote>
```

, and this
```html
<p><a href="https://example.com/a/link/so/long/it/goes/past/the/typical/80/characters"
>Something</a>.
```
into this
```html
<p><a U0003Cblockquote href="https://example.com/a/link/so/long/it/goes/past/the/typical/80/characters"> </a></p>
<p><a U0003Cblockquote href="https://example.com/a/link/so/long/it/goes/past/the/typical/80/characters">Something</a>.</p>
```

This seems to be caused because `>` at the start of a line gets replaced by `<blockquote>` even if it's part of an HTML tag, prior to parsing the HTML. This results in a `<blockquote` attribute with an empty value, which then gets [converted into the valid XML name](https://html.spec.whatwg.org/multipage/parsing.html#coercing-an-html-dom-into-an-infoset) `U0003Cblockquote`. The rest of weird behavior is probably a result of the similar pre-parsing transformations for determining paragraphs.

**Comment by tabatkins** [comment]
Yup, `>` at the start of a line causing a blockquote is part of Markdown, and Bikeshed files are written in Bikeshed-flavored Markdown.
