### ISSUE TITLE
Unhandled exception related to MDN integration

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#1731]
Try to build csswg-drafts/mediaqueries-5/Overview.bs
=> Everything is fine

Comment out `Include MDN Panels: no` and try again
=> bikeshed crashes, with the following traceback
```
WARNING: No 'media-descriptor-table' ID found. Update https://developer.mozilla.org/en-US/docs/Web/CSS/@media Specifications Table?
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/bikeshed", line 11, in <module>
    load_entry_point('bikeshed', 'console_scripts', 'bikeshed')()
  File "/Users/florian/src/bikeshed/bikeshed/cli.py", line 220, in main
    handleSpec(options, extras)
  File "/Users/florian/src/bikeshed/bikeshed/cli.py", line 256, in handleSpec
    doc.preprocess()
  File "/Users/florian/src/bikeshed/bikeshed/Spec.py", line 110, in preprocess
    self.processDocument()
  File "/Users/florian/src/bikeshed/bikeshed/Spec.py", line 204, in processDocument
    mdnspeclinks.addMdnPanels(self)
  File "/Users/florian/src/bikeshed/bikeshed/mdnspeclinks.py", line 35, in addMdnPanels
    panels = panelsFromData(doc, data)
  File "/Users/florian/src/bikeshed/bikeshed/mdnspeclinks.py", line 221, in panelsFromData
    if targetElement.getprevious() is not None \
AttributeError: 'NoneType' object has no attribute 'getprevious'
```

**Comment by sideshowbarker** [comment]
I’m looking into this right now

**Comment by sideshowbarker** [comment]
OK, https://github.com/tabatkins/bikeshed/pull/1732 has a fix.

Thanks for catching this.

To quote the description there about the cause:

> The cause is that the processing of the MDN data is a place where the code uses two loops: an outer loop and an inner loop — and the code without this change was checking for the “No 'foo' ID found” within the inner loop, and doing a continue to the next iteration of the inner loop when an ID is not found. But the code needs to instead do the “No 'foo' ID found” check inside the outer loop, and continue to the next iteration of the outer loop when an ID is not found.

**Comment by sideshowbarker** [comment]
#1735 is a fix for the root problem that caused this bug to get hit. Quoting that issue description:

> This change moves the code for generating the MDN panels until after all other code has run that adds any IDs/anchors in the output.
> 
> Otherwise, without this change, it’s possible that Bikeshed will fail to find an expected ID, and will emit a “WARNING: No 'foo' ID found” message and not generate an MDN panel at the expected place.
> 
> For example, see https://github.com/tabatkins/bikeshed/issues/1731, where the root cause of the bug was that the code for generating the MDN panels runs before the `boilerplate.addPropertyIndex` code — and so, the generated `media-descriptor-table` ID does not exist yet at the point where the code for generating the MDN panels is trying to find it.
