### ISSUE TITLE
Missing self-links (in WebAudio)

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1734]
As reported in WebAudio/web-audio-api#2205 , there are some missing links in some sections of the WebAudio spec.  @padenot discovered that this seems to be caused by [extra attributes](https://github.com/WebAudio/web-audio-api/issues/2205#issuecomment-649673964) in the `<h3>` tag.  The tags that only contain the "id" attribute have the self links.

I don't know why some tags have extra attributes.  I'm pretty sure this used to work, but can't say for certain.

**Comment by tabatkins** [comment]
Ah, I'm skipping headings that are dfns, because they'll get a self-link *or a dfn panel* from the dfn code, and the latter is happening here - clicking on the heading pops up the dfn panel, which contains a self-link.

That does look weird tho, I should just add the self-link.

**Comment by rtoy** [comment]
I don't know why some headings have dfns and some don't.  What is the recommended way?  We should change them all to the recommended style.  But they should all get a self link anyway I think, for consistency.

**Comment by rtoy** [comment]
For whatever reason, the self links are showing up again now.  In https://github.com/WebAudio/web-audio-api/issues/2205#issuecomment-665156442, I listed all the sections that were missing self links.  I checked just now at https://webaudio.github.io/web-audio-api/ and many of the listed sections now have self-links.  (I didn't check all of the sections.)

We didn't make any changes in the WebAudio spec for this.

**Comment by rtoy** [comment]
Just checked.  All the link that were missing aren't missing anymore.

Feel free to close this if you think it's fixed somehow.

**Comment by tabatkins** [comment]
Yeah, they're showing up because I fixed it like I said I should in my comment. ^_^

**Comment by rtoy** [comment]
Heh.  Thanks. I was expecting this issue to be closed when it was fixed.  But great to have the self-links in now.
