### ISSUE TITLE
argumentdef is undocumented

### ISSUE THREAD

**Issue by kainino0x** [tabatkins/bikeshed#1736]
I just noticed the `argumentdef` class [in the Web Audio spec](https://github.com/WebAudio/web-audio-api/blob/7f301c26271b8965576179404e6d287b6a334a68/index.bs#L865), which seems to be undocumented in [Bikeshed's manual](https://tabatkins.github.io/bikeshed/#table-expansion).

**Comment by kainino0x** [comment]
(oops, accidentally submitted issue early.)

Additionally, propdef, descdef, and elementdef are kind of buried in that doc section. It would be helpful to have just a small section at the top that says in a sentence what each of the 4 does (especially since I didn't immediately understand what descdef was, since it's for CSS).

**Comment by tabatkins** [comment]
Phew yeah, not only was argumentdef undocumented (and very different from the other def blocks!), the other def blocks themselves had terrible docs.

I moved them to a new top-level section, [Definition Tables](https://tabatkins.github.io/bikeshed/#def-blocks). Let me know if you need any more details clarified!

**Comment by kainino0x** [comment]
Very nice, thank you!
