### ISSUE TITLE
BS's ordering of "abstract" and "status of this document" does not match specberus/pubrules' opinion.

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#1738]
BS's ordering of "abstract" and "status of this document" does not match specberus/pubrules' opinion. 

See https://www.w3.org/pubrules/?url=http%3A%2F%2Fkingsmountain.com%2Fdoc%2Fwebauthn%2F&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004

**Comment by tabatkins** [comment]
Pubrules actually [requires the Abstract/SotD ordering](https://www.w3.org/pubrules/doc/rules/?profile=WD#document-status). Looks like Specberus is buggy in trying to enforce the opposite ordering.

**Comment by tabatkins** [comment]
Actually, reviewing [the enforcement code in Specberus](https://github.com/w3c/specberus/blob/562a87b7d5c6f47a77ecb52a28388de258d1a416/lib/rules/structure/h2.js), it looks like the code is correct - the first `h2` that's not a child of `div.head` should be Abstract, then SotD, then ToC. And that's exactly the structure you have in your spec.

I recall seeing the error in your Pubrules results earlier, but now that I try to reload them to check again, the whole thing is just freezing at 0% completion, so, uh, dunno what's up.

**Comment by tabatkins** [comment]
Okay, finally got Pubrules to load.

No, the ordering is correct in the Pubrules checker.  However, it is for some reason not skipping the subtitle h2 [like the code indicates it should be](https://github.com/w3c/specberus/blob/562a87b7d5c6f47a77ecb52a28388de258d1a416/lib/rules/structure/h2.js#L26) (it should be skipping any h2 inside of div.head, which your subtitle definitely is). [I've reported the error.](https://github.com/w3c/specberus/issues/938)

**Comment by tabatkins** [comment]
Ah, I'd accidentally been looking at a historical version of the file which still worked correctly. They swapped out the DOM library they were using a few days ago, and introduced the bug at that point. It's fixed now.

(Curious how this worked for anyone in the past week, but shrug.)

**Comment by equalsJeffH** [comment]
Thanks for tracking all this down @tabatkins !
