### ISSUE TITLE
Parallelize `bikeshed update`

### ISSUE THREAD

**Issue by ngzhian** [tabatkins/bikeshed#1741]
Hi, I was reading through https://github.com/tabatkins/bikeshed/blob/e05aa73d9f0d0e0d3b51179dbc01f0dd5b8f30a5/bikeshed/update/manifest.py#L140 and it looks like it is updating a single file at a time.

Will it be a good idea to parallelize some of this? Or will it be rude to GitHub / hit some sort of API rate limit? Wondering if you've tried this before.

**Comment by tabatkins** [comment]
This should be quite parallelizable, I've just never messed with Python's parallel stuff before.

I don't *think* this'll hit rate limits, since it's fetching static files, but who knows?

Anyway, happy to review if you want to take a crack at it.

**Comment by tabatkins** [comment]
Done in <https://github.com/tabatkins/bikeshed/commit/615efd82da01c6da028466018f7efd6846611524>

**Comment by tabatkins** [comment]
(In particular, this takes `bikeshed update` on my laptop from processing ~3 files/sec to processing ~**200** files/sec.)

**Comment by ngzhian** [comment]
x-posting this, i see some hangs on CI builds (https://travis-ci.org/github/WebAssembly/simd/builds/716629866), and also locally, haven't been able to root cause this yet..

**Comment by frivoal** [comment]
Wow, things are so much faster now! Very much appreciated.
