### ISSUE TITLE
The `!important` token breaks the CSS highlighter

### ISSUE THREAD

**Issue by andreubotella** [tabatkins/bikeshed#1745]
See https://drafts.csswg.org/css2/#example-7e2b6175 or https://html.spec.whatwg.org/multipage/rendering.html#hidden-elements

**Comment by tabatkins** [comment]
A bunch of things broke the highlighter, yeah. For some reason I was trying to capture CSS syntax pretty exactly, and was missing enough bits that it would often break.

Instead I *should* have just been doing a much simpler tokenization, which I've done in <https://github.com/tabatkins/bikeshed/commit/17d5fe84adeb13c5d889536c16cccd3cd861591e>. Looking at the changes in my tests, it looks like a uniform improvement, so 👍
