### ISSUE TITLE
Custom style and Javascript

### ISSUE THREAD

**Issue by simoncozens** [tabatkins/bikeshed#1748]
I'm hoping to use bikeshed for maintaining a spec document, but I would like to be able to add custom CSS (for styling) and JS (to add hypothes.is annotations) to the output. I can't see that there's a way to do this currently beyond hacking the output document, but I notice that things like the Fetch spec look different. Is importing custom stylesheets implemented at the moment, and if not, could it be?

**Comment by tabatkins** [comment]
Bikeshed's source format is just Markdown+HTML, so you can include `link`, `style`, or `script` elements in your document as you wish.

**Comment by simoncozens** [comment]
Ohhh, of course! Thanks.
