### ISSUE TITLE
Can't pip install

### ISSUE THREAD

**Issue by jakearchibald** [tabatkins/bikeshed#1749]
```sh
pip3 install -r /Users/jakearchibald/dev/bikeshed/requirements.txt
```

Fails with:

```sh
ERROR: Could not find a version that satisfies the requirement widlparser<2,>=1.0.4 (from -r /Users/jakearchibald/dev/bikeshed/requirements.txt (line 13)) (from versions: none)
ERROR: No matching distribution found for widlparser<2,>=1.0.4 (from -r /Users/jakearchibald/dev/bikeshed/requirements.txt (line 13))
```

**Comment by jakearchibald** [comment]
Bikeshed recommended I run the above when I was running bikeshed update, but it seems like that isn't part of the installation docs, so I'll close this and try and follow those.

**Comment by jakearchibald** [comment]
If anyone else lands here with the same here, I followed https://tabatkins.github.io/bikeshed/#install-pyenv to get the installation working on OSX.

**Comment by tabatkins** [comment]
Huh tho. I know plinss just published a new version, and it was a backwards-incompatible change so it's correct to bump the major version number, but surely pypi would still let you install the last v1??? Weird
