### ISSUE TITLE
Can't docker-install

### ISSUE THREAD

**Issue by jakearchibald** [tabatkins/bikeshed#1750]
```
docker build --tag=bikeshed:latest .
```

Fails with

```
/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py:236: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
ERROR: Location-changing options found in --install-option: ['--prefix'] from command line. This is unsupported, use pip-level options like --user, --prefix, --root, and --target instead.
The command '/bin/sh -c pip install --install-option="--prefix=/install" -r /requirements.txt' returned a non-zero code: 1
```

Docker version 19.03.12, build 48a66213fe, on OSX.

**Comment by jespertheend** [comment]
I'm having the same issue, is there a workaround for this?

**Comment by tabatkins** [comment]
I don't have a single clue how Docker works; the current documentation and support for using Docker is based on one user who apparently understands it.  I can't meaningfully support this, unfortunately, but I'm happy to update docs as necessary if y'all find out how.

**Comment by jespertheend** [comment]
Ah no worries. To be honest I have no idea how docker works either. I decided to use it for the first time today because I wanted to see what all the fuzz was about.
I suppose `pip3 install bikeshed` is the workaround then.
