### ISSUE TITLE
LINK ERROR: No 'idl' refs found for 'registerProtocolHandler()' with for='['NavigatorContentUtils']'.

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1753]
@plinss @tabatkins did something change recently why this would no longer work?

Is this perhaps fallout from the void/undefined change?

**Comment by plinss** [comment]
Yeah, there was a change to the triggers for Shepherd's IDL detection that broke the HTML spec, reverted.

**Comment by tabatkins** [comment]
Closing because the hiccup was fixed.
