### ISSUE TITLE
Import definitions from Reffy data

### ISSUE THREAD

**Issue by dontcallmedom** [tabatkins/bikeshed#1761]
[reffy](https://github.com/tidoust/reffy) supports extracting definitions from specs identified as [browser specs](https://github.com/w3c/browser-specs) and publishes its extracts as [JSON data](https://github.com/w3c/webref/tree/master/ed/dfns).

These definitions cover a broader set set of specifications and extract them daily from the latest editors draft (including for ReSpec documents), with around 20K more definitions identified in the process (see a [more detailed comparison with Shepherd data](https://github.com/tidoust/reffy/issues/332#issuecomment-652541992).

If needed, the index of all specifications crawled for definitions is available in a [JSON file](https://github.com/w3c/webref/tree/master/ed/index.json), along with metadata about each specification. The list and metadata directly come from [browser-specs](https://github.com/w3c/browser-specs/blob/master/index.json).

(beyond my involvement in reffy, getting this done would also be very useful to me as a spec contributor since a number of WebRTC specs are stuck in terms of using auto-links due to outdated data in the Shepherd data)

/cc @tidoust

**Comment by dontcallmedom** [comment]
this would also address #1756 & #1664

**Comment by dontcallmedom** [comment]
@tabatkins is there anything @tidoust or I could do to help on this?

**Comment by jyasskin** [comment]
Per https://lists.w3.org/Archives/Public/spec-prod/2023JanMar/0004.html, I think this is finished. 🎉
