### ISSUE TITLE
`term-for-` and `ref-for-` ids are named for URL instead of term

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1768]
https://github.com/WICG/webpackage/blob/ec0871e80e7822434841df8a3c048fe9e8af999b/loading.bs#L182 defines a "SHA-256" term pointing to http://csrc.nist.gov/publications/fips/fips180-4/fips-180-4.pdf, but the ID for the term in https://wicg.github.io/webpackage/loading.html#index-defined-elsewhere is just `term-for-`.

[Subject Public Key Info](https://github.com/WICG/webpackage/blob/ec0871e80e7822434841df8a3c048fe9e8af999b/loading.bs#L104) gets an ID of `term-for-section-4.1.2.7`, so I think it's using the URL instead of the term itself for the ID. These get disambiguated with `①` when they collide (e.g. https://wicg.github.io/webpackage/loading.html#term-for-section-4.2%E2%91%A0), but it seems likely to lead to less stable URLs in general.

References are similarly affected, getting `ref-for-section-4.1.2.7` instead of the term itself.

**Comment by tabatkins** [comment]
That is indeed exactly what I do; I just pull the ID off of the reference and slam that into some other strings for ID/linking.

I'm not sure I understand how this is a problem, tho.  For one, these IDs are for internal usage; they shouldn't commonly be shared outside. For second, and perhaps more importantly, they're as stable as the link itself, right? Theoretically, if you had multiple different documents that all used the same ID they could collide, and thus one changing could cause a cascade of changes, but that seems quite rare.

I could change this if necessary (at the time I generate these, I have access to the element itself), I'm just not sure I see the need to do so.

**Comment by nschonni** [comment]
#1857 will fix the case where it's just `term-for`

**Comment by nschonni** [comment]
@jyasskin the fix has landed in the repo if you want to see if it resolves it for you

**Comment by jyasskin** [comment]
It's still happening, but looking at the other issues, this one doesn't seem worth prioritizing.
