### ISSUE TITLE
FrozenArray not hyperlinked

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#1769]
WebAudio wanted to update some things to use `FrozenArray` like so:

```
callback AudioWorkletProcessorCallback =
  boolean (FrozenArray<FrozenArray<Float32Array>> input,
           FrozenArray<FrozenArray<Float32Array>> output,
           FrozenArray<Float32Array> parameters);
```

This works and `Float32Array` is nicely hyperlinked.  But `FrozenArray` is not.  Fairly minor issue that isn't blocking WebAudio.  This is a "nice to have" feature.

**Comment by tabatkins** [comment]
All right, just pushed fixes for this. I'll be cutting a new release in a sec.
