### ISSUE TITLE
Metadata for WG21 papers

### ISSUE THREAD

**Issue by dangelog** [tabatkins/bikeshed#1777]
Hi,

I'd like to suggest some cleanups for the WG21 audience groups:

https://github.com/tabatkins/bikeshed/blob/master/bikeshed/metadata.py#L772

* The map contains `"LEWG":"SG18"`, but this is incorrect, **LEWGI** is SG18 (https://isocpp.org/std/the-committee) -- in fact, LEWG is already present in the `namedAudiences` on the line above;
* Also add other study groups to the map:
```
"Modules":"SG2", "Networking":"SG4", "FeatureTesting":"SG10", "LowLatency":"SG14", "Tooling":"SG15", "MachineLearning":"SG19", "Education":"SG20", "Contracts":"SG21"
```

Thank you!

**Comment by tabatkins** [comment]
@brycelelbach Yo, wanna PR this? I can give you commit rights, too.

**Comment by dangelog** [comment]
I can try and create a patch... do you accept pull requests?

**Comment by dangelog** [comment]
Cheers, thanks!
