### ISSUE TITLE
Setting 'Editor Term' breaks 'Metadata Include: Editor off'

### ISSUE THREAD

**Issue by hober** [tabatkins/bikeshed#1786]
In this case, I had `Editor Term: Author Authors`, and found I had to use `Metadata Include: Author off`.

**Comment by tabatkins** [comment]
I'm real curious what you're doing to trigger these now. ^_^

**Comment by hober** [comment]
> I'm real curious what you're doing to trigger these now. ^_^

I'm just trying to write a blog post. :)

**Comment by tabatkins** [comment]
Oh neat, I'd idly thought about using Bikeshed for a blogging engine too.

Anyway, this actually uncovered some other issues with how I was handling `Editor Term`, so nice catch! Fix will be pushed as soon as tests finish rebasing.
