### ISSUE TITLE
Support ReSpec-style triple-square-bracket inline ref syntax.

### ISSUE THREAD

**Issue by hober** [tabatkins/bikeshed#1794]
In ReSpec, `[[RFC8890]]` will produce a `[RFC8890]` link which, when clicked, goes to the biblio entry for RFC 8890 in this document.

If you instead type `[[[RFC8890]]]`, it generates a link that goes directly to RFC 8890.

It'd be great if Bikeshed supported this too.

cc @marcoscaceres, because I'm sure I got the description of ReSpec's behavior wrong.

**Comment by marcoscaceres** [comment]
Not wrong :) We treat "[[[" as an "expansion", so it will expand a reference to its title and link to the appropriate spec. 

So, [[[DOM]]] expands to `<a href="https://...">DOM Standard</a>` + it adds the reference to the bibliography. This is useful when citing documents where the spec-ID doesn't really tell you anything about what the document being cited (RFCs are a perfect example, as their ids don't carry any meaning).

We also support expanding local id refs for various elements (e.g., h2-h6)... like [[[#some-heading-id]]], which becomes `<a href="#some-heading-id">x.x the section heading text</a>`.

**Comment by tabatkins** [comment]
Done, tho I went with a different syntax, since I already have a way to specify handling instructions on a biblio autolink. You can do this per-link by saying `[[FOO inline]]`, or default the entire doc with `Default Biblio Display: inline`.
