### ISSUE TITLE
Multiple elements have the same ID 'conventions'

### ISSUE THREAD

**Issue by kvark** [tabatkins/bikeshed#1805]
We see it on CI - https://travis-ci.org/github/gpuweb/gpuweb/jobs/738047124#L260
As far as I can see, the source has only one thing called "conventions" - https://github.com/gpuweb/gpuweb/blob/cafeb4f32f4ac0d8788505dddebace6d3ba00f72/spec/index.bs#L460

**Comment by tabatkins** [comment]
Yeah, I recently added the ability for all W3C specs to have W3C-specific default boilerplates, and part of that was adding a somewhat expanded footer that a few groups shared. This happened to have a section with `id=conventions`, about the use of RFC 2119 terminology and such.

I've renamed the IDs in the w3c-default footer to be less likely to collide with anything, thanks!
