### ISSUE TITLE
Updating twice makes references work

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1815]
This is weird:

https://travis-ci.org/github/jyasskin/webpackage/jobs/741727823 runs `bikeshed update` twice and succeeds, while https://travis-ci.org/github/jyasskin/webpackage/jobs/741765013 only runs it once and fails. The second `update` updates 1443 files.

**Comment by tabatkins** [comment]
That's.... extremely weird. Let me see if I can reproduce...

**Comment by tabatkins** [comment]
Yup, definitely reproducable locally, which is *weird as hell*, since it *should* be downloading the same manifest file both times... I'll figure out what's up.

**Comment by jyasskin** [comment]
This might have been fixed for now with 0260be71da33966cb4f88ddc059b8c60d05dfed7?

**Comment by tabatkins** [comment]
Should have been, yes.
