### ISSUE TITLE
The Unofficial Draft marks are too strong in dark mode

### ISSUE THREAD

**Issue by npm1** [tabatkins/bikeshed#1819]
The background "UNOFFICIAL DRAFT" on dark mode looks really bad, making the specs almost unreadable. I also see that now the spec is laid out in a fixed with column, and to the right of it is a bunch of wasted space (on my large screen). I'll note that the watermark on that side looks more correct.

**Comment by mmocny** [comment]
<img width="1355" alt="Screen Shot 2020-11-11 at 11 28 07 AM" src="https://user-images.githubusercontent.com/474282/98837609-280e4580-2411-11eb-9ff5-f12a5c368aff.png">

**Comment by tabatkins** [comment]
Ugh, with the recent changes to how page background is specified in the W3C stylesheets, Bikeshed's darkmode fix to use the darkmode-version of the UD image must gotten overridden.

Sorry about that, will fix.

**Comment by tabatkins** [comment]
The width is on purpose, tho, to maintain a reasonable line-length for optimal reading. On very wide screens it does mean there's a lot of empty space, but that's an intentional decision on the part of W3C spec styling, and I agree with it.
