### ISSUE TITLE
Need to allow linking to "manual" test in <wpt>

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#1820]
Since wpt.fyi doesn't display manual tests (due to no way to collect pass data currently), I'm excluding those tests from the paths I allow you to link in a `<wpt>` element.

However, manual tests are still useful to link to, so I should allow it and just vary how I do the output for them.

(See, for example, `css/CSS2/values/numbers-units-002.xht`)

**Comment by frivoal** [comment]
This is a dup of https://github.com/tabatkins/bikeshed/issues/1783 (but I don't mind if you close mine in favor of yours. As long as it's on your radar, I'm good).
