### ISSUE TITLE
Undesirable updating of obsolete references

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#1822]
The ED of [CSS Fonts 4](https://drafts.csswg.org/bikeshed/css-fonts-4/) is not building on drafts.csswg.org because of a "fatal error".

> FATAL ERROR: Obsolete biblio ref: [DOM-Level-2-Style] is replaced by [DOM].

Firstly, that should be a warning not a fatal error.

Secondly, that sort of auto-updating should not be happening. It should be opt-in.

Here is the text around that reference:

> The DOM Level 2 Style specification [[DOM-LEVEL-2-STYLE]]
> defined a different variant of this rule.
> This definition supersedes that one.

So yes, it is a biblio link to an outdated specification. That is the point. Its also why this is an informative reference, not a normative reference. And forcing this to point to DOM LS makes the sentence meaningless because _the entire point_ is to say that this is a change from that old specification.

**Comment by tabatkins** [comment]
In most cases you *do* want things to be auto-updated to the newest thing, but I agree that it would be useful to still force a ref to an obsoleted spec for rare cases like this.

**Comment by tabatkins** [comment]
All right, you can now intentionally link to an obsoleted reference by specifying `obsolete` in the biblio ref, like `[[dom-level-2-style obsolete]]`.
