### ISSUE TITLE
Documentation of Windows-based Docker run command is wrong

### ISSUE THREAD

**Issue by mquadrat** [tabatkins/bikeshed#1829]
From the current documentation: 

`docker run --rm --volume C:\mystuff\project1\:\data bikeshed spec \data\Index.bs \data\out\Index.html`

The correct command line would be 

`docker run --rm --volume C:\mystuff\project1\:/data <organization>/bikeshed:<date> bikeshed spec /data/Index.bs /data/out/Index.html`

Note that the original command left out the image name and wrongfully changed all of the slashes to backslashes.

**Comment by tabatkins** [comment]
I have absolutely no idea how Docker works and leave the documentation of that solely to people using Docker; if you could PR the docs file I'll be happy to accept it.

**Comment by jyasskin** [comment]
Fixed by #2154.
