### ISSUE TITLE
include004 tests failing on Windows

### ISSUE THREAD

**Issue by nschonni** [tabatkins/bikeshed#1853]
I'm not sure if there is a globbing or related issue that behaves differently on Windows than the macOS and Linux CI runners.
EX: from https://github.com/tabatkins/bikeshed/runs/1670529548?check_suite_focus=true
```
 Failed Tests:
* include004-files\include004-2.bs
* include004-files\include004-files\include004-2.bs
* include004-files\include004-files\include004.bs
* include004-files\include004.bs
```
Seems to affect both Python 3.7, 3.8, and 3.9

**Comment by tabatkins** [comment]
I'm pretty sure it's <https://github.com/tabatkins/bikeshed/blob/master/bikeshed/test.py#L26>, and is caused by the differences in path separator. :/  I'll have to think about how to replace that; I probably have to use the path APIs to split it into segments and then check the segments individually instead.

**Comment by tabatkins** [comment]
Okay, 8425d57f should have fixed it, we'll see if I did it right when the tests cycle.

**Comment by nschonni** [comment]
Which do you think is the bug:
1. Windows reading the `.bs` file in the nested folder
2. macOS/Linux not reading the file in subfolder

If 1, then the globbing on Windows needs to be fixed
If 2, then the snapshot needs to get updated and the globbing fixed on macOS/Linux

**Comment by nschonni** [comment]
Oops, looks like I was slow in commenting, but CI doesn't seem happy with the change

**Comment by tabatkins** [comment]
I'd just made a typo. Fixed in the next commit, and CI is now green on all systems, yay!

**Comment by tabatkins** [comment]
(The problem was 1; that line, and the preceding `if` condition, were both correctly working on systems with `/` as the path separator, and failing on Windows.)

**Comment by nschonni** [comment]
awesome!
