### ISSUE TITLE
Tests for multi-level specs, and <wpt-rest>

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#1895]
Using the `<wpt-ignore>` tag results in the following warning

> WARNING: &lt;wpt-rest> is intended for debugging only. Move the tests to &lt;wpt>ents next to what they're testing.

Consider some specification CSS-foo, which has css-foo-3, css-foo-4, and css-foo-5, and assume each level adds features compared to the previous one. Remembering that WPT removed levels and will put all tests for all levels into wpt/css/css-foo/ then we have the following choices:

1. Use `<wpt-ignore>` in css-foo-3 to stop the tests from levels 4 and 5 being complained about; and again in css-foo-4 to stop it from complaining about tests from level 5; and maybe also in css-foo-5 because it is a delta spec or because you want to focus attention on just the new features
2. Use `<wpt>` but not `<wpt-ignore>`. Get used to ignoring a ton of warnings each time you build the spec locally
3. Don't use the wpt feature

None of these are ideal, so the actual benefit of the wpt tags is hard to realize for multi-level or multi-version specs.

**Comment by tabatkins** [comment]
I'm not sure what you mean `<wpt-ignore>`. Are you referring to `<wpt-rest>`?

**Comment by svgeesus** [comment]
OOps, yes

**Comment by svgeesus** [comment]
It was even right there in the quoted warning.

**Comment by tabatkins** [comment]
Unfortunately, I don't have a better suggestion. There simply isn't any WPT metadata indicating whether a given test is meant for a particular level. So yeah, we're stuck with a choice between "don't use wpt at all" and "get a persistent warning".  (Note that the "missing WPT tests" error message is much less obnoxious now, but I haven't updated pip with a version with the fix yet; I need to get on that. It's still a little longer than the wpt-rest message, at least.)

I think that a `<wpt-ignore>` element was requested in the past, where you could list tests that are technically under your prefix but that don't actually apply. Iirc the use-case it was requested for got solved a different way, but maybe that would help a little here? It would require regular maintenance (adding more entries to the old specs whenever tests were added for new features), but when it's up-to-date it would let you build cleanly without warnings. Would that help?

**Comment by svgeesus** [comment]
Hmm, that might help. It would help if someone adds a new test so you get flagged; then you can either add it to your spec or add it to the exclude list.

 Needs input from more people before going that way.

**Comment by frivoal** [comment]
What I've been doing is listing all the tests for level n+1 in a wpt element in the level n spec, but putting the hidden attribute on it. That silences the bikeshed warnings about not having listed the test, and but since it's irrelevant to the reader of that level, it doesn't show, so everybody is happy (except for having to identify these tests manually, but I don't see a work around that).

**Comment by svgeesus** [comment]
`<wpt hidden title="previous level tests"...>` is working fine for me, I think this issue can be closed now.
