### ISSUE TITLE
Categorize a group

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#1935]
I thought that copying the boilerplate for another W3C group would mean that the newly created boilerplate would identify a W3C group (in particular, I changed the group ID for the patent policy) but it seems not:

> FATAL ERROR: You used Status: ED, but that's limited to the 'w3c', 'fido', or 'khronos' orgs, and your group 'webfontswg' isn't recognized as being in any of those orgs. If this is wrong, please file a Bikeshed issue to categorize your group properly, and/or try:
Status: w3c/ED
Status: fido/ED
Status: khronos/ED
 ✘ Did not generate, due to fatal errors

So, what step did I miss?

The sole hit on "categorize" in the bikeshed documentation is unrelated to this.

I see the documentation also says to file an issue. 

> Bikeshed has a listing of what Groups are associated with the W3C. If your Group isn’t on that list, it’ll complain when you try to use a W3C status. Please file a bug on Bikeshed to add your Group, and/or prefix your status like Status: w3c/ED.

Isn't that something that could be done as part of a PR when adding a new group?

**Comment by tabatkins** [comment]
It certainly can be, if my brain is working well enough to remember that it has to be done. ^_^ I'll fix shortly.
