### ISSUE TITLE
Please add https://wicg.github.io/serial/ to the index

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#1950]
Thanks!

**Comment by domenic** [comment]
It might also be a problem on my end... I'm trying to do `{{Serial/requestPort()}}` and getting an error. But I'm also getting that error for `{{Notification/requestPermission()}}`, and I'm pretty sure that one is exported...

**Comment by tabatkins** [comment]
Added!

And note that you can check what specs Bikeshed is currently aware of by looking at <https://github.com/tabatkins/bikeshed/blob/master/bikeshed/spec-data/readonly/specs.json>.

**Comment by domenic** [comment]
Hmm, it still doesn't seem to work, and that file shows last updated November 2020...

**Comment by tabatkins** [comment]
I haven't updated the datafiles in the default install in a while, but it's there in the live datafiles <https://github.com/tabatkins/bikeshed-data/blob/master/data/specs.json>, so it should be getting picked up.

That said, it's a ReSpec spec, so if something isn't working well I wouldn't be surprised.
