### ISSUE TITLE
spec-data/readonly/biblio/biblio-rf.data not updated?

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#1957]
spec-data/readonly/biblio/biblio-rf.data does not have an entry for eg RFC8949, yet the latter exists in https://www.specref.org/?q=8949

**Comment by equalsJeffH** [comment]
hm.  so https://raw.githubusercontent.com/tabatkins/bikeshed/master/bikeshed/spec-data/readonly/biblio/biblio-rf.data does not contain RFC8949, AFAICT.

However, after I locally did a `bikeshed update --skip-manifest`  it appears I now have proper data wrt RFC8949:
```
Source file modified. Rebuilding...
FATAL ERROR: Obsolete biblio ref: [rfc7049] is replaced by [rfc8949].
FATAL ERROR: Obsolete biblio ref: [rfc7049] is replaced by [RFC7049].
 ✔  Successfully generated, with warnings
```

...weird.

**Comment by tabatkins** [comment]
The built-in data files are only updated occasionally, when I think of it (and have the time to then verify that the changes in the test files are expected). So it's not unusual to run into this situation; I assume 8949 is a relatively recent publication?

(This is why all the instructions for running Bikeshed have you run `bikeshed update` immediately, too.)

**Comment by equalsJeffH** [comment]
thx @tabatkins 
> I assume 8949 is a relatively recent publication?

Yes.
