### ISSUE TITLE
`bikeshed update` repeatedly downloading all data files

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#1961]
On MacOS with a just-updated bikeshed 2.2.3:
```
$ bikeshed update
Updating via manifest...
Deleted 9 old data files.
Updating 959 files...
Updated 958/959...
Done!
$ bikeshed update
Updating via manifest...
Deleted 9 old data files.
Updating 959 files...
Done!
$ python --version
Python 3.9.1
```

What else would help debug?

**Comment by tabatkins** [comment]
Ah, known issue that I've fixed upstream but haven't cut a release for yet. I'm cutting one this afternoon, I'll ping in a bit.

**Comment by tabatkins** [comment]
Okay new release has been cut, lmk if it fixes your issue.

**Comment by jyasskin** [comment]
Oops, yes, that fixed it.
