### ISSUE TITLE
Add tt to list of inline elements

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#1962]
Currently starting a line with `<tt>` will break the paragraph. Probably needs to be added to list of inline elements.

**Comment by nschonni** [comment]
The tag is obsolete https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt

**Comment by tabatkins** [comment]
Yeah after discussing with @fantasai I'm not going to do anything special for the obsolete elements, since the spec won't validate with `<tt>` in it anyway.
