### ISSUE TITLE
Formatting of enums

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1968]
WHATWG / Infra style of formatting strings is

> "`test`"

whereby the quotes denote its a string and `<code>` denotes the actual value. Would it be okay to make Bikeshed match that? Or failing that, another preference?

cc @domenic

**Comment by domenic** [comment]
I'm not sure I understand the issue. I always reference enum values in Bikeshed using `"{{EnumName/enum-value}}"` and it seems to work fine.

**Comment by annevk** [comment]
The output you get from Bikeshed is

> `"test"`

as far as I can tell, e.g., in the Storage Standard, and not

> "`test`"

**Comment by tabatkins** [comment]
Bikeshed doesn't do any magic transportation of quote characters. If you put them outside the autolink, like Domenic showed, they won't be in the `code`.

**Comment by annevk** [comment]
Ooh, I see now. Excellent, thank you both.
