### ISSUE TITLE
Quote escaping in <pre>

### ISSUE THREAD

**Issue by tidoust** [tabatkins/bikeshed#1972]
Bikeshed escapes the opening quote that appears in the definition of [`<final-bg-layer>`](https://drafts.csswg.org/css-backgrounds/#typedef-final-bg-layer) in CSS Backgrounds and Borders, producing `<\'background-color'>`, which seems incorrect from a [Value definition syntax](https://www.w3.org/TR/css-values-4/#value-defs) perspective. I would rather expect to see `<'background-color'>`.

The escaping only happens when the definition is in a `<pre>`.

Minimal code to reproduce the behavior:
```html
<pre><<'foo'>></pre>
```
... for which Bikeshed currently generates:

```html
<pre><a class="production" data-link-type="propdesc">&lt;\'foo'&gt;</a></pre>
```

If the escaping is intended, is there any way to prevent it?

**Comment by dontcallmedom** [comment]
[`<xmp>`](https://tabatkins.github.io/bikeshed/#xmp)?

**Comment by tabatkins** [comment]
No, that's just a bug, and I'm not sure why it's doing so. Uh, I'll see what's up.
