### ISSUE TITLE
Double Fetch Metadata Request Headers reference

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#1983]
Fetch has both [WEBAPPSEC-FETCH-METADATA-1] and [FETCH-METADATA]. The former does not exist per https://www.specref.org/?q=WEBAPPSEC-FETCH-METADATA-1 and is also not mentioned in Fetch directly. I guess it got in there through Shepherd perhaps?

cc @plinss

**Comment by plinss** [comment]
Shepherd does have webappsec-fetch-metadata-1 (I'm guessing @tabatkins added it?) 

I can rename it to fetch-metadata, but will that break references elsewhere?

**Comment by annevk** [comment]
I don't think anything but Fetch references it. @mikewest would probably know.

**Comment by jyasskin** [comment]
[Fetch](https://fetch.spec.whatwg.org/#biblio-fetch-metadata) doesn't have this problem anymore, and I suspect #1761 will fix it more generally.
