### ISSUE TITLE
Support boxes overlap spec prose and each other

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#1984]
The support boxes have two problems with styling atm:

1. They overlap spec prose in narrow windows.
2. They overlap each other when sections are short.

See https://drafts.csswg.org/css-cascade-5/#default for an example

I suggest starting them out as collapsed rather than expanded, that should fix both problems.

**Comment by jyasskin** [comment]
I think this got fixed, by starting the boxes out collapsed as you suggested, although I don't see the commit that did it. I do see another problem at https://drafts.csswg.org/css-cascade-4/#initial, where the CanIUse box sits directly on the MDN box: https://github.com/tabatkins/bikeshed/issues/2442.
