### ISSUE TITLE
Running tests gets slower and slower, memory usage keeps growing

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1997]
When updating the tests for https://github.com/tabatkins/bikeshed/pull/1996 I noticed that the tests run slower and slower.

The first ~100 tests are small ones (not whole specs) and take ~7 seconds to run.

Getting through the next 100 tests takes ~76 seconds.

The next 100 takes ~80 seconds.

Then it takes ~90 seconds.

The final 70 then take another ~90 seconds.

Memory usage keeps increasing, from <100MB initially to >1GB at the end.

The slowdown isn't very pronounced and could be explained by the memory leak, not sure.

**Comment by tabatkins** [comment]
I'd noticed that, but didn't realize it was growing quite that large. I'm looking into memory tracing just to get myself comfortable with this. I know the leak has to be the databases getting filled as I pull in more and more files, but what I'm not sure about is why they're not getting collected.

**Comment by tabatkins** [comment]
Oh, I think I fixed this - I found where I was leaking memory. (It was a cache that I created as a global rather than attaching to the document.)
