### ISSUE TITLE
Bikeshed warns of missing wpt tests, but won't tell me which ones

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#2002]
> WARNING: There are 63 WPT tests (too many to display individually) underneath your path prefix '/css/css-text/' that aren't in your document.

Great. Now, how do I go about finding what tests these are. Show them anyway, add a verbose option, dump them into a log... doesn't matter much to me, but let me know which tests.

**Comment by tabatkins** [comment]
Using a `<wpt-rest>` will do it, at least. I should probably mention this, or add a command-line flag that triggers showing.

**Comment by tabatkins** [comment]
Oh, I fixed this a while back and didn't close this issue. It's back to printing all of them on the command line, with directions to use `<wpt hidden>` if necessary.
