### ISSUE TITLE
[[SHORTNAME inline]] doesn't do what is advertised

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#2003]
Bikeshed lets me do this, which is very nice:

> Browser must foo the bar, as defined in [[shortname#relevant-section]].

The link will have "spec title § section number section name" as it's text, and point to the right section in that spec. All good.

Now, if I want to follow the same pattern, but point to a the entire spec, according to [the documentation](https://tabatkins.github.io/bikeshed/#biblio-mods), this should do it:

> Browser must foo the bar, as defined in [[shortname inline]].

Unfortunately, it doesn't work. The link text is the spec's title, as expected, but the link takes you to the bibliography just as [[shortname]] would, which isn't what the documentation says (it claims "the link goes straight to that document, rather than going to the bibliography first").

If this is not intended, there's a bug. If it is intended, the documentation is wrong. But in that case, I'd still want a feature that does what the documentation talks about.

**Comment by tabatkins** [comment]
Hm, that's a bug, yeah. It should still *create* a biblio entry, but the link should bypass it and go straight to the source. Weird.
