### ISSUE TITLE
Release with aiohttp==3.7.4?

### ISSUE THREAD

**Issue by lbam** [tabatkins/bikeshed#2007]
Hello,

The current release of bikeshed requires aiohttp==3.7.3, which has a security issue. This has been fixed in https://github.com/tabatkins/bikeshed/commit/24b346f6f7b4ef86a9efa9c719c372236fafd211, but not in any release on PyPI. Would you care to release a 2.3.1 or 2.4.0 with that commit? Currently, we have to pin a dependent package to Github instead of PyPi (https://github.com/Amsterdam/amsterdam-schema/pull/196) which slows down our build a lot.

**Comment by tabatkins** [comment]
Currently on 3.8.3, so this is long-since fixed. ^_^
