### ISSUE TITLE
Use cite element for bilbiographies

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#2012]
`[[FOOBAR inline]]` generates `<a href="http://example.com/foobar>The foobar standard</a>`, but maybe it should generate `<cite><a href="http://example.com/foobar>The foobar standard</a></cite>` or `<a href="http://example.com/foobar><cite>The foobar standard<cite></a>`.

Same question for `[[FOOBAR#baz]]`: should it do something like `<a href="http://example.com/foobar#baz><cite>The foobar standard<cite> § 3.2 The Baz Property</a>`

Same question for entries in the Reference section.

I'm asking because I suspect the answer's yes, and am willing to send a pull request, but I'd rather check that you agree before doing it.

**Comment by tabatkins** [comment]
Looking at HTML, yes, `cite` seems appropriate for these usages. I'd accept a PR.

**Comment by frivoal** [comment]
>  I'd accept a PR.

PR made (#2016) a little while back. Have a look?
