### ISSUE TITLE
Temporarily disable testharness injection until specberus bug is fixed

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#2025]
This means we can't publish: https://github.com/w3c/specberus/issues/1202. It should be fixed, but until it is, if bikeshed could stop injecting testharness stuff, that'd be nice.

**Comment by svgeesus** [comment]
I would rather push on specberus to fix their recently-introduced bug. We have been publishing with these annotations for years, we already have the required exception.

**Comment by frivoal** [comment]
Resolved on the specberus side. Bikeshed no longer needs to do any workaround

**Comment by tabatkins** [comment]
All right, reverted.
