### ISSUE TITLE
Add an option to allow inline linking to use shortnames

### ISSUE THREAD

**Issue by brycelelbach** [tabatkins/bikeshed#2032]
Hi @tabatkins!!!!

Typically, when I insert a reference, e.g. `[[P1000]]`, the link text is the shortname of the reference, e.g. [[P1000]](https://wg21.link/P1000).

However, if I use the awesome `[[FOO inline]]` or `Default Biblio Display: inline` feature from #1641, then the link text is the full name of the reference, NOT the shortname, e.g. [C++ IS Schedule](https://wg21.link/P1000) instead of [[P1000]](https://wg21.link/P1000).

I'd like to be able to do inline links to biblio references which use the shortname as link text, not the full name.

**Comment by tabatkins** [comment]
I thought that's what you were asking for when I added the feature. ^_^

I can add in another variant that still generates the biblio tag but directly links, yeah.

**Comment by brycelelbach** [comment]
Awesome - sorry, maybe I was unclear!

**Comment by brycelelbach** [comment]
Any ETA on this? If it's easy to do I might be able to do it myself if you point me in the right direction.
