### ISSUE TITLE
Highlighting bug

### ISSUE THREAD

**Issue by gkoller** [tabatkins/bikeshed#2048]
Rendering the following .bs file:

```
<pre class='metadata'>
Title: Higlighting Bug
Shortname: high-bug
Revision: 1.0.1
Status: LS
URL: https://example.org
Editor: Guido
Abstract: Any example to demonstrate the highlighting bug
Markup Shorthands: css no, markdown yes
Indent: 4
Default highlight: json
Boilerplate: copyright no, footer no
</pre>

Introduction {#intro}
=====================

Bla Bla Bla

Highlighting Bug {#high-bug}
----------------------------

* list item
* list item with `literal`
* list item with `{"json": "make me sad"}`
```
with Bikeshed > 2.2.3 results in the following output:

![20210506_154831_screenshot](https://user-images.githubusercontent.com/4290278/117309532-c8a26700-ae82-11eb-9a66-85cb76ea0646.png)

I suspect the `Default highlight: json` to have something to do with that. If I set it to `python` instead of `json` the word `literal` is consistently highlighted.

Version 2.2.3 was the last version of Bikeshed without this problem.

**Comment by tabatkins** [comment]
This is working as intended - that's the behavior of the JSON parser in Pygments. See [the lexer code](https://github.com/pygments/pygments/blob/master/pygments/lexers/data.py#L450-L456) for details - for some reason, they just consider anything that contains any of the characters from true/false/null to be a valid literal, so `teral` qualifies.
