### ISSUE TITLE
Invalid CSS in boilerplate stylesheet

### ISSUE THREAD

**Issue by tidoust** [tabatkins/bikeshed#2064]
The boilerplate stylesheet contains a weird `text-decoratin` line that cannot be parsed as CSS:
https://github.com/tabatkins/bikeshed/blob/main/bikeshed/boilerplate/stylesheet.include#L596

This was introduced last time the file was updated in https://github.com/tabatkins/bikeshed/commit/9126fc153a6696bc9236c45df9535399338e71b3

**Comment by tabatkins** [comment]
lol, indeed. Fixed, thanks.
