### ISSUE TITLE
bikeshed emitting `path` attributes on html elements

### ISSUE THREAD

**Issue by mozfreddyb** [tabatkins/bikeshed#2067]
Hi,

I am currently facing an issue with submitting HTML through the [Nu Html Checker](https://validator.github.io/validator/), which complains about `path` attributes on generated HTML.

To be fair, I am not sure if it's reasonable for bikeshed to switch to conformant HTML output (e.g., `data-path`?) or whether this is acceptable behavior for bikeshed.

My bikeshed snippet looks like this:
```html
<pre class=include-code>
path: resources/baseline-element-allow-list.json
highlight: js
</pre>
```

and the generated HTML looks like this
```html
<pre class="include-code highlight" path="resources/baseline-element-allow-list.json">....
```

The full files are available in a [spec PR](https://github.com/WICG/sanitizer-api/pull/94/checks?check_run_id=2662804882), which contains a GitHub actions tab with a lot of logs and more context, for your convenience :)

Thanks!

**Comment by tabatkins** [comment]
Ah, that's a bug, it should be removed in the output. Thanks for the report!

**Comment by mozfreddyb** [comment]
I can try and write a pull request, if you can point me to the approximate source lines (and if you think this is easy enough to do :))

**Comment by tabatkins** [comment]
I'm fixing it right now, no worries.

**Comment by tabatkins** [comment]
Whoops, stripped them too early, highlighting isn't triggering now.
