### ISSUE TITLE
Please use @data-path rather than @path when including files

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2069]
When bikeshed includes an external file, it adds a `path` attribute at the point of inclusion, which is invalid HTML and has to be fixed manually when publishing to /TR

> Attribute “path” not allowed on element “pre” at this point.

Changing this to `data-path` would solve this (which is what I did manually)

**Comment by tabatkins** [comment]
That's specifically on a *code* inclusion, right? An element with `class="include-code"`? 

If so, I fixed that earlier this week; it's in the latest version. ^_^
