### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by xfq** [tabatkins/bikeshed#2084]
The GitHub action for https://github.com/w3c/sensors emitted some errors, probably because the Bikeshed version used does not contain the latest commits. Is there a plan to release a new version?

**Comment by tabatkins** [comment]
I cut new versions regularly. Gimme some time. ^_^

**Comment by tabatkins** [comment]
And released 2.4.3: https://github.com/tabatkins/bikeshed/issues/1773#issuecomment-861687363
