### ISSUE TITLE
Amendment boxes and bikeshed link highlighting

### ISSUE THREAD

**Issue by rtoy** [tabatkins/bikeshed#2104]
As part of the process for updating a living standard with [amendment boxes](https://fantasai.inkedblade.net/style/design/w3c-restyle/2020/readme#amendment), the insertions and deletions must be noted.  As shown in the sample, deletions are red text that are struck through and insertions are green text.  This works great (I think) in bikeshed, but when the inserted or deleted text includes bikeshed links, the links aren't colored correctly or struck through.  This makes for confusing diffs because you can't tell if the link is to be inserted/deleted or not.

For an example, see https://pr-preview.s3.amazonaws.com/rtoy/web-audio-api/pull/2363.html#c2361-1.

Step 1.3 is confusing because you can't easily tell if "IsDetachedBuffer" is added, removed, or unchanged.  Clicking the "Show Current" or "Show Future" shows the correct text.

Step 1.3.2 is confusing because the "Detach" link is listed twice, because the link changed. (It could be argued that that should not be marked at all since only the link changed and not the associated text.)

**Comment by tabatkins** [comment]
They're definitely struck-thru on my machine (stable Chrome on Windows), but the color is indeed still the link-blue rather than the ins/del red/green. This styling comes from the W3C's base.css, tho, not Bikeshed - could you raise this at <https://github.com/w3c/tr-design/>?

I don't think there's any reasonable way to distinguish things like "link destination changed, but not text"; it's either confusing or incomplete. ¯\_(ツ)_/¯

**Comment by rtoy** [comment]
I think I wasn't clear.  the text is struck thru and red (and green), but links are not.

I'll file an issue as you suggest.

For the case where link changed but not the text, if they were colored (and struck thru), then it would be a bit clear that something changed instead of showing up as a duplicate links.

**Comment by tabatkins** [comment]
Yeah, I meant the links are definitely struck thru on my machine: 

![image](https://user-images.githubusercontent.com/682840/125537106-29a5d4ce-dcd4-4ea8-a444-7682fba7a141.png)

But yeah, if they were red/green as well it would definitely make it clearer.

**Comment by rtoy** [comment]
Oh, you're right. I couldn't see that until I really zoomed in.  The dotted strike thru is pretty hard to see.  I think solid would be nicer, but that's a TR design question.

Thanks for your help.

**Comment by fantasai** [comment]
Also major bug in Chrome, using the text-decoration-color of the descendant of the DEL element! It's much clearer in Firefox which uses the right colors...
