### ISSUE TITLE
Anolis supported multiple references linked by a single id

### ISSUE THREAD

**Issue by GPHemsley** [tabatkins/bikeshed#2137]
Prior to the move to Bikeshed, WHATWG cross-references were managed in a separate repo, which allowed a single reference ID to point to multiple actual references.

For example, here's the reference entry for the ID "HTTP":
https://github.com/whatwg/xref/blob/c275b8f3c9d1ae654b42c3db5ad2c723e77c8e8e/references.json#L339-L369

There are other examples in the same file.

It doesn't appear that SpecRef supports this concept, and the ID "HTTP11" there is an alias to just RFC 7230:
https://github.com/tobie/specref/blob/a6e795ff6de993110ffb4f34227f64ac62c488a9/refs/biblio.json#L1512-L1514

**Comment by annevk** [comment]
I think it's fine to wontfix this. We can convert those cases to multiple independent references instead. (That's what we've done in Fetch.)

**Comment by tabatkins** [comment]
That works for me. ^_^
