### ISSUE TITLE
Live WPT results

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#2149]
scratch notes:

to get the latest run ids for each browser:

```
x = await (await fetch("https://wpt.fyi/api/runs?label=master&label=stable&max-count=1&product=chrome&product=firefox&product=safari&product=edge")).json()
```

and then to get the results for those run ids for a particular spec:

```
x = await( await fetch("https://wpt.fyi/api/search", {method:"POST", headers:{'Content-Type':'application/json'}, body: '{"run_ids": [ 5737280086999040, 5673469556555776, 6297383483736064], "query": {"path": "/css/css-easing/"}}'})).json()
```

**Comment by sideshowbarker** [comment]
Big +1 to this. I'd be super happy to help with it.

**Comment by tabatkins** [comment]
Already got it done, actually, just haven't pushed a new release with it because I want to do a final bit where I summarize the results up in the spec header, and I haven't gotten to that yet.

**Comment by sideshowbarker** [comment]
> Already got it done, actually, just haven't pushed a new release with it

ah cool

>  want to do a final bit where I summarize the results up in the spec header, and I haven't gotten to that yet

That seems like the most important part :)

Why not just replicate the summary that wpt.fyi itself shows? For example:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/194984/139748001-a1f3cbd3-fe8e-4714-8425-866b91e9c656.png">

(well, with the browser icons also shown)

**Comment by svgeesus** [comment]
Well, that seems to be working now

![image](https://user-images.githubusercontent.com/2506926/148811274-cc232e02-0954-41cc-b816-cb701c0acfab.png)

**Comment by svgeesus** [comment]
It is a shame that the WPT results don't have an option to group by specification section. Compare [the WPT report](https://wpt.fyi/results/css/css-color?label=experimental&label=master&aligned) with [the Shepherd one](https://test.csswg.org/harness/results/css-color-4_dev/grouped/).

However Shepherd is bitrotting, any tests added since like April 2021 don't show up, so the Shepherd report is less useful and indeed actively misleading.

**Comment by tabatkins** [comment]
Oooh, that would be a nice as an auto-generated appendix. I'll move that to another issue.

**Comment by tabatkins** [comment]
Closing now, as this feature is indeed done.
