### ISSUE TITLE
w3c-state

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2163]
The new `w3c-state` 2021 pubrules requirement does not seem to be supported. The specberus error is:

> Cannot find the &lt;p id="w3c-state"> element for profile and date.

> Please make sure the &lt;p id="w3c-state">W3C @@Profile, DD Month Year&lt;/p> element can be selected by document.getElementById('w3c-state');
If you are using bikeshed, please update to the latest version.
https://www.w3.org/pubrules/doc/rules/?profile=CRD#dateState

I'm using the latest version of bikeshed (pulled from GitHub just now).

What used to be an h2 in the old style is now a p with the special `id=w3c-state` and a link around the document status. See this example:

```html
<h1 id="title" class="title p-name">High Resolution Time</h1>

  <p id='w3c-state'>
    <a href='https://www.w3.org/standards/types'>W3C Candidate Recommendation Draft</a>
    <time class="dt-published" datetime="2021-11-03">03 November 2021</time>
  </p>
```
from https://github.com/w3c/specberus/blob/main/test/docs/p2021/2021-crd.html

I'm making this change manually in the bikeshed generated output, since I am apparently the lucky first person to publish a CRD since Process 2021 came into effect this month.

This will apply to all W3C documents, not just CRD.

**Comment by svgeesus** [comment]
Will be partly fixed by https://github.com/tabatkins/bikeshed-boilerplate/pull/5 although wrapping status in a link still remains to be done

**Comment by dbaron** [comment]
@svgeesus you may be interested in https://lists.w3.org/Archives/Public/spec-prod/2021OctDec/0044.html
