### ISSUE TITLE
Missing "using the Recommendation track"

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2168]
Where `Recommendation track` links to https://www.w3.org/2021/Process-20211102/#recs-and-notes

as [documented here](https://www.w3.org/pubrules/doc/rules?profile=CRD#publish)

**Comment by tabatkins** [comment]
@plh is gonna fix this (along with #2167, #2166, #2165, #2164, and #2163)

**Comment by svgeesus** [comment]
Presumably [this](https://github.com/tabatkins/bikeshed/commit/191f832a31623b6a47d3ee23d9c811df11f43430)
