### ISSUE TITLE
Installation by `pip install bikeshed` still uses outdated dependencies

### ISSUE THREAD

**Issue by saschanaz** [tabatkins/bikeshed#2181]
It installs Pillow 8.1.1 which does not support Python 3.10. It seems Pipfile has 8.3.2 instead, and the internet says Pipfile replaces requirements.txt, so why do both exist here?

**Comment by tabatkins** [comment]
I'm not 100% sure on how I've got all this set up. I don't use pipenv at this point (I might have at some point in the past? But I didn't capture its usage anywhere, so I dunno.), while I know how to update requirements.txt.

**Comment by saschanaz** [comment]
d57ceaeb2081f1398a3ae1d277fb6155a912d0e2 ᅟsays you did! (Yay commit messages!)

AFAICT the plan is to support it also in pip, so I guess having both is okay for now.

**Comment by saschanaz** [comment]
>I guess having both is okay for now.

Just to clarify, this means we should make sure both synchronized. #2182 should let Dependabot update both.

**Comment by jyasskin** [comment]
It looks like this got fixed.
