### ISSUE TITLE
bikeshed update doesn't remove outdated include files

### ISSUE THREAD

**Issue by dontcallmedom** [tabatkins/bikeshed#2186]
After running `bikeshed update` in my local checkout of bikeshed, the `bikeshed/spec-data/boilerplate/webrtc/` still has outdated include files that override the updated `w3c` includes.

The same seems to be happening to the `webtransport` boilerplate.

Generating snapshots with api.css.wg or via spec-prod results in non-pubrules compliant documents, so I assume this is not a problem specific to my checkout.

**Comment by dontcallmedom** [comment]
as far as I can tell, this is because the outdated files still shows up https://github.com/tabatkins/bikeshed-data/tree/main/data/boilerplate and in the generated manifests.

**Comment by tabatkins** [comment]
...huh, indeed, I'm getting some phantom paths persisting. I'll figure out what's up.

**Comment by tabatkins** [comment]
Ah, I hadn't added the boilerplates folder to the cleanup code. I've done so now and confirmed that a local refresh does delete the old ones, so bikeshed-data should be up-to-date in a few minutes.

I've also documented all the spots that need editting when I add new data files, so I won't forget again!
