### ISSUE TITLE
Remove white background from logos?

### ISSUE THREAD

**Issue by saschanaz** [tabatkins/bikeshed#2187]
https://w3c.github.io/web-locks/

![image](https://user-images.githubusercontent.com/3396686/144335473-68e1ff6b-47a5-438f-857d-13e8e82ade3b.png)

That white background is added by:

https://github.com/tabatkins/bikeshed/blob/0a9ef89b4d853f86861e03be236163b690bb1d4a/bikeshed/Spec.py#L714-L716

Not sure the same applies to logos.

**Comment by tabatkins** [comment]
Why wouldn't it?

**Comment by saschanaz** [comment]
I think favicons expect background colors 🤔

**Comment by saschanaz** [comment]
Oh sorry, I thought `Favicon:` added it, but it seems not. Surely it can't be generalized then.
