### ISSUE TITLE
Terms used in other specifications are transparent

### ISSUE THREAD

**Issue by cconcolato** [tabatkins/bikeshed#2190]
As an example in https://aomediacodec.github.io/av1-avif/#index-defined-elsewhere, in dark mode, the text is black on black in dark mode:
<img width="887" alt="Screen Shot 2021-12-03 at 7 02 57 PM" src="https://user-images.githubusercontent.com/1830314/144694651-92f14b85-1030-41d2-8a95-d43592fafed9.png">
or white on white in light mode:
<img width="881" alt="Screen Shot 2021-12-03 at 7 03 25 PM" src="https://user-images.githubusercontent.com/1830314/144694661-cbdb26bd-bac8-4db1-bc91-76976a3ce3b3.png">

This seems to be due to this code:
<img width="259" alt="Screen Shot 2021-12-03 at 7 05 43 PM" src="https://user-images.githubusercontent.com/1830314/144694709-a6168c56-b820-4916-9b83-beb300899eb3.png">

**Comment by cconcolato** [comment]
If it helps, this is hte code where it is set: https://github.com/tabatkins/bikeshed/blob/7f0747e0af3ffcc9b03d52b9e3753dcb305492ee/bikeshed/spec-data/readonly/boilerplate/stylesheet.include#L1269
Simply removing the line seems to fix it but I'm not sure of the side effects.

**Comment by tabatkins** [comment]
Huh, I thought I'd fixed that ages ago, but nope, it was definitely still there. Fixed in <https://github.com/tabatkins/bikeshed-boilerplate/commit/2430db035613629023b4938857c57329b675439c>
