### ISSUE TITLE
Add PNGWG to W3C Groups

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2192]
> Bikeshed has a listing of what Groups are associated with the W3C. If your Group isn’t on that list, it’ll complain when you try to use a W3C status. Please file a bug on Bikeshed to add your Group, and/or prefix your status like Status: w3c/ED.

I'm writing a spec for the [PNG Working Group](https://www.w3.org/groups/wg/png). I set the status to `w3c/NOTE-FPWD`, which avoids the fatal error and the spec is generated, but SotD is entirely empty.

Please add PNGWG to the list of W3C groups.

Also, if the SotD will still be empty after that, what should I do to fix it?

The [boilerplate readme](https://github.com/tabatkins/bikeshed-boilerplate#readme) says

> The top-level files in the boilerplate/ folder are used by default, if there's nothing more specific.

but that isn't happening.

**Comment by tabatkins** [comment]
Done, I'll cut a release in a second. (This file is in the process of being converted into a datafile that can be picked up by `bikeshed update`, but for now it's still Python and needs a fresh pip release for each update, sigh.)

> but that isn't happening.

It is, but the default `status.include` just shows off your `Status Text` metadata. Now that you're a w3c group tho, you'll get the w3c default instead, which has the stuff you want.

**Comment by svgeesus** [comment]
Thanks! Also don't rush a release just for me, I'm using the bikeshed github development version anyway.

**Comment by svgeesus** [comment]
After updating bikeshed (git pull, install, bikeshed update) I can now change `w3c/NOTE-FPWD` to just `NOTE-FPWD`  without triggering a fatal error. So I know I am running the version where PNGWG is a W3C group.

But the SotD is still empty.

**Comment by svgeesus** [comment]
I also tried copying the files from `bikeshed-boilerplate/boilerplate/w3c` to my local spec directory and adding

```html
Local Boilerplate: header yes
Local Boilerplate: footer yes
Local Boilerplate: logo yes
Local Boilerplate: copyright yes
```
but still an empty SotD.
