### ISSUE TITLE
Don't allow forless links for descriptors

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#2200]
With Contain 3 taking on width/height especially, we're getting a lot of "ambiguous property/descriptor" errors. It might be time to disallow them for descriptors and default to properties.

**Comment by tabatkins** [comment]
Yeah, I think we're long overdue to consider that a failed remnant of the old preprocessor. Some specs now have link failures I need to go clean up, but Bikeshed-wise the change is done now: all for-less propdesc autolinks are now property *only*.
