### ISSUE TITLE
Language and direction of the document

### ISSUE THREAD

**Issue by xfq** [tabatkins/bikeshed#2206]
How to specify the language and direction of the document? Is it enough to add something like the following to the head of the document?

```html
<!DOCTYPE html>
<html lang="zh-Hans" dir="ltr">
```

**Comment by tabatkins** [comment]
As it turns out, yes, that will indeed work. The HTML parser merges the attributes of multiple `html` elements automatically, and then Bikeshed will just output a single `html` at the correct place. No need for a doctype, tho.

**Comment by tabatkins** [comment]
That is to say, no need to add it to the `head` (tho you can add it to your boilerplate if your group is going to publish in a single language). If this is a one-off, you can just put `<html lang=zh-Hans>` in your bs source, and it'll Magically Work.
