### ISSUE TITLE
Generated bikeshed file couldn't pass html checker

### ISSUE THREAD

**Issue by chengweih001** [tabatkins/bikeshed#2225]
I have a bikeshed file (please see [index.bs](https://github.com/chengweih001/webusb_sameobject_patch/blob/forbikeshedissue/index.bs)) and it was able to successfully parsed by bikeshed.

However, if I supply that to [html checker](https://validator.w3.org/nu/#file), it fails with some errors like below:

```
Error: Element dl not allowed as child of element dl in this context. (Suppressing further errors from this subtree.)

From line 2472, column 5; to line 2472, column 8

 <dl>↩    <dl>↩     
```

For above example, it maps to below in bikeshed file:
```
### Methods ### {#usbdevice-methods}

<dl dfn-type=method dfn-for="USBDevice">
    : <dfn>open()</dfn>
    ::
        The {{USBDevice/open()}} method, when invoked, MUST return a new {{Promise}}
        |promise| and run the following steps <a>in parallel</a>:

          1. Let |device| be the target {{USBDevice}} object.
          2. If |device| is no longer connected to the system, <a>reject</a> |promise|
            with a {{NotFoundError}} and abort these steps.
          3. If <code>|device|.{{USBDevice/opened}}</code> is <code>true</code>
            <a>resolve</a> |promise| and abort these steps.
          4. Perform the necessary platform-specific steps to begin a session with the
            device. If these fail for any reason <a>reject</a> |promise| with a
            {{NetworkError}} and abort these steps.
          5. Set <code>|device|.{{USBDevice/opened}}</code> to <code>true</code> and
            <a>resolve</a> |promise|.
...
```
I am not sure where might go wrong, wish could get some insight for this.

**Comment by chengweih001** [comment]
We can close this one.

I later realized it is conflict between algorithm tag and dfn tag, for example:

This way algorithm tag is before dfn tag, and it causes trouble.
```
<dl dfn-type=constructor dfn-for="USBInterface">
<div algorithm="USBInterface constructor">
    : <dfn>USBInterface(|configuration|,|interfaceNumber|)</dfn>
    ::
        1. Set {{USBInterface/[[configuration]]}} to |configuration|.
```

By moving <algorithm> into <dfn> section, it fixed the issue.
```
<dl dfn-type=constructor dfn-for="USBInterface">
    : <dfn>USBInterface(|configuration|,|interfaceNumber|)</dfn>
    ::
        <div algorithm="USBInterface constructor">    
            1. Set {{USBInterface/[[configuration]]}} to |configuration|.
```

Fix for reference could be found in https://github.com/chengweih001/webusb_sameobject_patch/commit/6b111b1b5a5f1955752f4084d552b023002f1d78.
(just put for reference in case in the future anyone hit similar issue)

**Comment by tabatkins** [comment]
Hm tho, that's something I should fix. It *is* allowed to have a div around your dt/dd, so long as the div's parent is a dl.

**Comment by tabatkins** [comment]
Okay phew, this ended up being more involved than I expected, but should be done now. `dl` can now contain `div`, and you can use markdown dt/dd inside of the div as well.
