### ISSUE TITLE
Intentional reference to obsoleted rfc assigned to the updating rfc

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#2230]
https://pr-preview.s3.amazonaws.com/jyasskin/webpackage/pull/712.html#term-for-section-3.3%E2%91%A1 claims that rfc9162 defines `signedcertificatetimestamplist` even though the [definition in the `anchors` section](https://github.com/WICG/webpackage/pull/712/files#diff-1996103b610d9a87aec9e1fc3ccef78fb9a2cf8f807b5b2a6c54ea5c78b7625aR112) cites RFC6962. We're intentionally staying on the old one, and the new one removed the definition of the old one's structures, so I can't just refer to the new RFC.

**Comment by tabatkins** [comment]
Ah, I suppose the code following spec references when assembling the list from links isn't aware of the explicit biblio stuff. I should be able to tell that a ref comes from an anchors-block, tho, and honor your exact document. Will fix.
