### ISSUE TITLE
Version of Python on api.csswg.org server needs to be bumped

### ISSUE THREAD

**Issue by tidoust** [tabatkins/bikeshed#2243]
Not sure where to report the issue, but https://api.csswg.org/bikeshed/ runs Python v3.7 and recent typing related updates made to Bikeshed need Python v3.8, so the API endpoint no longer works.

**Comment by tabatkins** [comment]
Nah, the failure on 3.7 was unintentional and fixed this morning.

(The API server, unfortunately, runs on tip-of-tree Bikeshed, so when I'm using CI as intended to catch regressions, the API server also regresses.)
