### ISSUE TITLE
Used local biblio entry flagged as unused

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#2280]
https://github.com/privacycg/nav-tracking-mitigations/pull/21 is giving me a 

```
The following locally-defined biblio entries are unused and can be removed:
        * webkit-tracking-prevention
```

error even though it includes two uses of the form `[[WEBKIT-TRACKING-PREVENTION#classification-as-having-cross-site-tracking-capabilities|following criteria]]`. It looks like [cross-spec section links](https://tabatkins.github.io/bikeshed/#section-links) aren't getting counted as used. 

Similar error to #1413, but in this case the biblio reference doesn't end up in the [references](https://pr-preview.s3.amazonaws.com/privacycg/nav-tracking-mitigations/pull/21.html#references).

**Comment by tabatkins** [comment]
This touches on some hacky code that I"m still a little scared of, but I left things better than they were. Should be good now, I'll push a new version once the bots are green.
