### ISSUE TITLE
Possible duplication of biblio entries in v3.5.2

### ISSUE THREAD

**Issue by tidoust** [tabatkins/bikeshed#2284]
Latest version of Bikeshed does not seem to like seeing a mix of informative and normative references of the form `[[FOO#bar]]` and generates two biblio entries when that happens: one in the "Normative references" section, the other in the "Informative references" section.

On top of the duplication, this makes Bikeshed (rightfully) issue a "Warning: Multiple elements have the same ID 'biblio-foo'" message.

Minimal spec to reproduce the issue:

```html
<pre class='metadata'>
Title: Test
Shortname: test
Level: None
Status: w3c/ED
ED: https://example.org/
Editor: Me
Abstract: Test
</pre>

Normative reference: [[HTML#the-img-element]]

Note:
Informative reference: [[HTML#the-img-element]]
```

I cannot reproduce the problem when using other forms of references, e.g. `[=foo=]` or just `[[FOO]]`.

(Via https://github.com/gpuweb/gpuweb/issues/2951)

**Comment by tabatkins** [comment]
Ah dang, right, I saw them appearing in both in the rebased tests, but forgot that that's a problem! Will fix.
