### ISSUE TITLE
Use `lt` to override linking text, rather than `title`

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#230]
`title` has a legitimate purpose, and is sometimes worthwhile to put on links or definitions that *also* need to override their linking text; right now Bikeshed requires this conflict to be resolved in favor of dropping the meaningful title.

Talking with @fantasai, we settled on migrating over to using `x` as the linking text override.  `title` will still be usable, of course, but we'll look for `x` first, and an empty `x` will indicate "look at the text content", skipping over `title` entirely.

**Comment by tabatkins** [comment]
Okay, so current plan is actually to be more daring.  I want to start using `title` for, you know, *what it's actually designed for* (see #318), and that means breaking from precedent entirely and switching 100% to a new attribute.  Gonna poke at people and make them aware of this before I make the change.

On further thought, `x` is a bad attribute name; it clashes with `<rect x>` from SVG, for example.  (Well, not really, since it's only used on `<dfn>` and `<a>`, but semantically it's still troublesome.  Thinking about using `lt`, for "linking text".

**Comment by fantasai** [comment]
I think x is fine. Or lt is fine. Doesn't matter much.

I don't think you need to break anything here. Just use x/lt instead of 'title' when both are present, and don't auto-generate a title when one exists already. Is there something I'm not considering?

**Comment by mikewest** [comment]
For clarity, if I currently have:

    <a title="a scary and long phrase that describes some amazing thing">a friendly name</a>

I'll need to change it to:

    <a {x/lt}="a scary and long phrase that describes some amazing thing">a friendly name</a>

and then I'm done, right?

**Comment by tabatkins** [comment]
Yes, it's just a search-and-replace.

The reason I'm uncomfortable with the backwards-compatible form is that, even if people learn and only use `lt` from now on, they still have to remember that *if* they provide a `title` attribute for its normal purpose (hover text), they have to do something special with `lt` or else it'll mess up autolinking.  That's a footgun for the future that I'd rather avoid.

**Comment by tabatkins** [comment]
This change has been made.  I've gone with `lt`, for "linking text", and `local-lt`.  This is a breaking change; Bikeshed will not link things correctly if you continue to use `title`.  For a while, Bikeshed will warn you if you're using `title` on `<a>` or `<dfn>`.
