### ISSUE TITLE
Enabling WPT Display appears to break `w3c/spec-prod@v2` action

### ISSUE THREAD

**Issue by stephenmcgruer** [tabatkins/bikeshed#2305]
In https://github.com/w3c/secure-payment-confirmation/pull/193, I am trying to add WPT information to the Secure Payment Confirmation specification. However, our `w3c/spec-prod@v2` GitHub action, which builds the spec for preview, seems to break on enabling it.

The break seems to come from a post-build validation step:

```
  Validating index.html...
  $ yarn add vnu-jar --no-progress
  └─ vnu-jar@21.10.12
  $ java -jar "/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/vnu-jar/build/dist/vnu.jar" --also-check-css index.html
    "file:/home/runner/work/secure-payment-confirmation/secure-payment-confirmation.common/index.html":1839.4-1839.7: error: No “p” element in scope but a “p” end tag seen.
  ❌  Not so good... please fix the issues above.
  Error: Process completed with exit code 1.
```

Looking locally in my bikeshed-generated HTML, it **seems** (but I may be wrong!) to be this content:

```
   <p class="note" role="note">
    Note, this is an informative note.
    <details class="wpt-tests-block" dir="ltr" lang="en" open>
     <summary>Tests</summary>
     <p>Tests relating to the content of this specification
                     may be documented in “Tests” blocks like this one.
                     Any such block is non-normative.</p>
     <ul class="wpt-tests-list"></ul>
     <hr>
    </details>
   </p>
   <h3 class="no-ref no-num heading settled" id="w3c-conformant-algorithms"><span class="content">Conformant Algorithms</span><a class="self-link" href="#w3c-conformant-algorithms"></a></h3>

```

Which if I understand correctly is auto-generated from bikeshed/spec-data/boilerplate/w3c/footer.include, here:

```

    <p class="note">Note, this is an informative note.

    <wpt open title="Tests relating to the content of this specification
                     may be documented in “Tests” blocks like this one.
                     Any such block is non-normative."></wpt>

<h3 id="w3c-conformant-algorithms" class="no-ref no-num">Conformant Algorithms</h3>
```

Very strangely, in devtools I found that the browser seems to have different interpretation of the HTML than my text editor:

![image](https://user-images.githubusercontent.com/153264/174885152-7b8dacc9-2fad-44a8-b4c9-bf01d9446e78.png)

I must admit, I'm really not sure what is going on here, but I wonder if the footer should close the `<p>` tag before the `<wpt>` one?

**Comment by tabatkins** [comment]
Ah, ugh, yeah. So what's happening here is the `p`-autoclosing behavior is funky. It auto-closes on `details`, in the output, but does not autoclose for `wpt`, in the input. So Bikeshed gets a nice tree with a `<p><wpt /></p>`, converts it into `<p><details /></p>`, and spits that into the output, whereupon the browser sees that and instead makes them siblings.

(This isn't a problem in normal spec sources, as the Markdown parser emits `</p>` at the end of paragraphs properly. It's just an issue here in the boilerplates which are taken as raw HTML.)

I'll need to fix the boilerplates to add a `</p>` to the preceding paragraph.

**Comment by tabatkins** [comment]
Should be fixed in https://github.com/tabatkins/bikeshed-boilerplate/commit/b35499d7acac03c3465f24e1ac5994466b9b8be4 , please give it a few minutes to get picked up the bikeshed-data spider so it's visible to `bikeshed update`.

**Comment by stephenmcgruer** [comment]
Looks like it worked (https://github.com/w3c/secure-payment-confirmation/pull/193), thanks!
