### ISSUE TITLE
Use hyphen minus (U+002D) instead of math minus (U+2212) in ranges?

### ISSUE THREAD

**Issue by tidoust** [tabatkins/bikeshed#2308]
Bikeshed automatically converts minus signs made with hyphens (`U+002D`) that appear in ranges to mathematical minus sign  (`U+2212`) characters and I'm wondering whether that's really intended.

That is typically what happens with the [value of `font-style` in CSS Fonts](https://github.com/w3c/csswg-drafts/blob/ee5bdacebe7e5254717f6dcb86444698249f94d2/css-fonts-4/Overview.bs#L790), the hyphen in the "angle" range becomes a mathematical minus sign in the [generated spec](https://drafts.csswg.org/css-fonts-4/#font-style-prop). Before/After comparison:

```
<angle [-90deg,90deg]>
<angle [−90deg,90deg]>
```

 One other similar occurrence for the definition of `<grid-line>` in CSS Grid. Both occurrences seem to have been created by recent changes, I'm not aware of other places in CSS specs that have ranges with negative numbers.

Using that minus sign character is not incorrect per se, it's just that [CSS Values](https://www.w3.org/TR/css-values/#integers) talks about the hyphen minus when it says "The first digit of an integer may be immediately preceded by - or + to indicate the integer’s sign" and CSS parsers that can also parse the value definition syntax typically fail to parse the `U+2212` minus.

**Comment by tabatkins** [comment]
I went ahead and did this for simplicity, since I happened to write code that serialized numbers with a hyphen-minus and didn't want to go out of my way to fix it back.
