### ISSUE TITLE
Bikeshed only knows about the W3C Process and Patent Policy in some contexts

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#2317]
Given the following:

```
The following terms are defined in the [[w3c-process inline]]:

<index type=dfn spec=w3c-process></index>

The following terms are defined in the [[w3c-patent-policy inline]]:

<index type=dfn spec=w3c-patent-policy></index>
```

the two references between `[[ ]]` work fine, but the indexes don't, and bikeshed gives the following error:

```
FATAL ERROR: Unknown spec name 'w3c-process' on <index type="dfn" data-link-spec="w3c-process"></index>
FATAL ERROR: Unknown spec name 'w3c-patent-policy' on <index type="dfn" data-link-spec="w3c-patent-policy"></index>
```

What gives?

**Comment by tabatkins** [comment]
Yeah, that means I know about the name from my bibliography data source (SpecRef) but not from my definitions data source (Shepherd). We can add those specs to Shepherd, tho.

**Comment by frivoal** [comment]
Is this issue enough to let request the addition to Shepherd, or do I need to file some separate issue somewhere?

**Comment by tabatkins** [comment]
Sorry, just point me to the specs and I'm happy to add them. I meant to go look them up after posting my response but got distracted then went on vacation. ^_^

**Comment by frivoal** [comment]
* w3c-process: https://www.w3.org/Consortium/Process/
* w3c-patent-policy: https://www.w3.org/Consortium/Patent-Policy/

**Comment by frivoal** [comment]
(these URL redirect to the latest stable version)

**Comment by frivoal** [comment]
Ping?

**Comment by tabatkins** [comment]
Okay, checking these again today it seems like we have indeed added these and gotten everything working. :+1:
