### ISSUE TITLE
Warn on mixed indentation

### ISSUE THREAD

**Issue by johannhof** [tabatkins/bikeshed#2325]
In https://github.com/w3c/webappsec-credential-management/issues/202 we had some trouble with mixed indentation leading to visually correct-looking lists on some editors that rendered nonsensical in HTML.

While that's not really a bikeshed problem in itself, it may be nice to have a mode where bikeshed warns about any mixed indentation in documents.

**Comment by tabatkins** [comment]
Hm, it *is* valid and reasonable to indent with tabs followed by spaces in a `pre` (tabs to match the element's indent, then spaces to indent the code).  But outside of that, yeah, it's probably a mistake. I can detect this, and probably should have it turned on by default.

**Comment by tabatkins** [comment]
Okay, I've cut a release with this (3.9.0) and am gonna spend some time writing release notes, since I'm several versions behind. ^_^
