### ISSUE TITLE
HTTP header autolinking is typographically not correct

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#2332]
Input: `[:X-Frame-Options:]`.

Output: `<a ...>X-Frame-Options</a>`.

Desired output: best would be `` `<a ...><code>X-Frame-Options</code></a>` ``, i.e. correctly add the backticks (because header names are byte sequences). I would also accept just `<a ...><code>X-Frame-Options</code></a>` and then we could add the backticks ourselves.

**Comment by tabatkins** [comment]
Is it required that the backticks go outside of the link? I can do it either way, it just seems slightly odd to me to have the backticks outside of the `code` here.

**Comment by domenic** [comment]
(Thanks for working on this!!)

Per Infra for both strings and byte sequences, the `<code>` goes inside the punctuation. Infra doesn't have opinions about where the `<a>` should go, but we've also been keeping it inside the punctuation in existing specs.
