### ISSUE TITLE
The "algorithm" attr doesn't seem to affect bikeshed-generated html

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2337]
The [documentation says](https://tabatkins.github.io/bikeshed/#var-and-algorithms) you can add an algorithm attribute to a container or heading. And this issue implies that algorithms get some stylistic differentiator:

 - https://github.com/tabatkins/bikeshed/issues/1472

However, I am observing:

- no styling
- algorithm is not in the auto-generated  index of defined terms 

What am I doing wrong, or is this broken currently?

Here is [the bs source](https://github.com/w3c/csswg-drafts/blob/447e4de77b87c395ada7266fa9e988a3ad54f4bb/css-color-4/Overview.bs#L4171):

```html
<h2 id="color-conversion" algorithm="to convert a color">
Converting Colors</h2>
```
here is [the resulting part of the spec](https://drafts.csswg.org/css-color-4/#color-conversion) with no special styling and here is the [list of defined terms](https://drafts.csswg.org/css-color-4/#index-defined-here) with no "convert a color".

I noticed this because I wanted to autolink it, from Color 4 and also from Color 5.

**Comment by tabatkins** [comment]
As noted by #1472 not being closed yet, I don't have any automatic styling for algorithm blocks yet. It's just present in the default Bikeshed stylesheets, which the W3C specs don't use.

As for behavior, the documentation says exactly what the `algorithm` attribute does - it scopes your uses of `<var>`, no more, no less. (Currently.) This improves the accuracy of the "misspelled var" detection.

*Eventually* it will serve as a convenience for grouping algorithm arguments with the algorithm name (so you don't have to manually annotate as much), but that depends on me first setting up the "algorithms have arguments, with types, that I can check" code, which has been on my backlog for a while.
