### ISSUE TITLE
compile error in railroad diagram with definition reference in non-T

### ISSUE THREAD

**Issue by nektro** [tabatkins/bikeshed#2346]
### Bikeshed version

```
[meghan@nixos:~]$ nix-shell -p bikeshed

[nix-shell:~]$ bikeshed --version
???
```

### Step to reproduce

```bs
<pre class='metadata'>
Title: Test Specification
Status: LD
Shortname: test
Level: 1
Editor: Meghan <hello@nektro.net>
Abstract: Found a bug
</pre>

: <dfn>NL</dfn>
::
    <pre class='railroad'>
    T: 'LINE FEED (LF)' (U+000A)
    </pre>

: <dfn>WhiteSpace</dfn>
::
    <pre class='railroad'>
    OneOrMore:
        Choice:
            [=NL=]
    </pre>
```

### Expected Output

successful compile

### Actual Output

```
FATAL ERROR: Line 3 doesn't contain a valid railroad-diagram command. Got:
[=NL=]
 ✘  Did not generate, due to fatal errors
```

**Comment by nektro** [comment]
this works fine
```bs
: <dfn>WhiteSpace</dfn>
::
    <pre class='railroad'>
    T: [=NL=]
    </pre>
```

**Comment by tabatkins** [comment]
Yup, that's correct. Every kind of a railroad diagram needs to say what type of node it is.

It looks like you might be expecting it to substitute the definition from the prior section?

**Comment by nektro** [comment]
i was expecting it to be replaced with an `<a>`

> Every kind of a railroad diagram needs to say what type of node it is.

what do you mean by this?

**Comment by nektro** [comment]
ah this works, my misunderstanding on the syntax

```bs
    <pre class='railroad'>
    OneOrMore:
        Choice:
            T: [=NL=]
    </pre>
```

**Comment by nektro** [comment]
![image](https://user-images.githubusercontent.com/5464072/189577670-d79e1285-ece5-4a5e-999b-351e66e529db.png)

**Comment by nektro** [comment]
`N:` might be better if its a reference, but its compiling now. thanks for the help :)

**Comment by tabatkins** [comment]
> what do you mean by this?

Sorry, was typing on my phone, so that was an autocomplete error for "line". Every *line* in the railroad diagram syntax needs to say what type of node it is. ^_^

But yeah, you figured it out.
