### ISSUE TITLE
HTML spec definitions gone from bikeshed-data

### ISSUE THREAD

**Issue by tidoust** [tabatkins/bikeshed#2350]
Autolinking to the HTML spec no longer works, which currently prevents building of a number of specs that target HTML concepts.

All anchors apparently disappeared from bikeshed-data 6 hours ago, see https://github.com/tabatkins/bikeshed-data/commit/df9b0ddad9e76f2d5d9648452a735926e4fe02b5

Just a temporary hiccup?

**Comment by tabatkins** [comment]
It is temporary, but it happened last week for a few hours too.

@plinss , any idea why this would suddenly be happening?

**Comment by plinss** [comment]
News to me. My only idea is that the spec parsing task crashed while saving the HTML spec anchor data. As @tabatkins mentioned, it should be temporary until the next parse task. (I just kicked one off to be sure.)
