### ISSUE TITLE
WPT tests suddently under-reported on some specs

### ISSUE THREAD

**Issue by svgeesus** [tabatkins/bikeshed#2367]
I just noticed that the [bikeshed-generated CSS-Color-5](https://drafts.csswg.org/css-color-5/) now says there are **7 t**ests

![image](https://user-images.githubusercontent.com/2506926/195662776-f35383a4-bd16-4a45-a29c-5e37365a7571.png)

while previously there were hundreds. [CSS Color-4](https://w3c.github.io/csswg-drafts/css-color-4/) is still correctly reporting a few thousand tests.

![image](https://user-images.githubusercontent.com/2506926/195663216-7f693975-9b55-4f83-993f-1590a1aaa40d.png)

**Comment by tabatkins** [comment]
Yeah, this is because a number of the tests moved, so the JS can no longer find them and count their results - only 7 are left with a valid URL. If you run bikeshed on the spec (after having `bikeshed update`d recently) you'll see all the test path failures.
