### ISSUE TITLE
html, head and body tags are unclosed.

### ISSUE THREAD

**Issue by bradtriebwasser** [tabatkins/bikeshed#2376]
`bikeshed spec` and `bikeshed watch` produce an HTML file with missing closing tags for `<html>`, `<head>` and `<body>`.

Given `test.bs`:

```bs
<pre class=metadata>
Title: Bug example.
Shortname: bug-example
Abstract: Bug Example
Status: ED
TR: https://example.com
URL: https://example.com
Level: None
Editor: Brad Triebwasser, Google Inc. https://www.google.com/, btriebw@chromium.org, w3cid 00000
Repository: w3c/example
Group: examplegroup
Logo: logo.svg
Favicon: logo.svg
Complain About: accidental-2119 yes, missing-example-ids yes
Markup Shorthands: css no, markdown yes
Assume Explicit For: yes
</pre>

```

After running `bikeshed spec test.bs`, the following `test.html` is generated: https://pastebin.com/LNrxSzcr

The resulting document doesn't have any `</html>`, `</head>` or `</body>` anywhere in the document.

**Comment by tabatkins** [comment]
Yup, HTML has a number of elements with omittable end tags, and Bikeshed intentionally omits most of them. (This was added to my serializer at the explicit request of the HTML editors, in fact!)

(I leave `</p>` in place just because the rules for when it's safe to omit them are more complex than I want to worry about.)

**Comment by bradtriebwasser** [comment]
Thanks. For future reference for anyone else arriving here:

https://html.spec.whatwg.org/#the-body-element

[Tag omission in text/html](https://html.spec.whatwg.org/#concept-element-tag-omission):
A [body](https://html.spec.whatwg.org/#the-body-element) element's [start tag](https://html.spec.whatwg.org/#syntax-start-tag) can be omitted if the element is empty, or if the first thing inside the [body](https://html.spec.whatwg.org/#the-body-element) element is not [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace) or a [comment](https://html.spec.whatwg.org/#syntax-comments), except if the first thing inside the [body](https://html.spec.whatwg.org/#the-body-element) element is a [meta](https://html.spec.whatwg.org/#the-meta-element), [noscript](https://html.spec.whatwg.org/#the-noscript-element), [link](https://html.spec.whatwg.org/#the-link-element), [script](https://html.spec.whatwg.org/#the-script-element), [style](https://html.spec.whatwg.org/#the-style-element), or [template](https://html.spec.whatwg.org/#the-template-element) element.
A [body](https://html.spec.whatwg.org/#the-body-element) element's [end tag](https://html.spec.whatwg.org/#syntax-end-tag) can be omitted if the [body](https://html.spec.whatwg.org/#the-body-element) element is not immediately followed by a [comment](https://html.spec.whatwg.org/#syntax-comments).
