### ISSUE TITLE
Issue building fullscreen API spec

### ISSUE THREAD

**Issue by marcoscaceres** [tabatkins/bikeshed#2378]
With a freshly installed and updated bikeshed, I'm trying to build (locally):

https://github.com/whatwg/fullscreen/blob/main/fullscreen.bs

But it keeps telling me:

```
bikeshed update
Updating via manifest...
Gathering local manifest data...
Fetching remote manifest data...
Local data is already up-to-date with remote (2022-10-31 02:41:15)
bikeshed spec fullscreen.bs 
FATAL ERROR: Found unmatched text macro [COMMIT-SHA]. Correct the macro, or escape it with a leading backslash.
 ✘  Did not generate, due to fatal errors
```

I'm unsure how to proceed. Any guidance?

**Comment by tabatkins** [comment]
Whatwg specs need to be built with their makefile, which invokes Bikeshed with some custom variables set that their templates expect.
