### ISSUE TITLE
Headings mostly gone from bikeshed-data

### ISSUE THREAD

**Issue by tidoust** [tabatkins/bikeshed#2379]
Most [headings](https://github.com/tabatkins/bikeshed-data/tree/main/data/headings) seem to have disappeared from bikeshed-data over the last 3 days. Looking at what the Shepherd API returns, I see that `"section": true` properties seem to have mostly disappeared, e.g. see [anchors returned for CSS Viewport](https://api.csswg.org/shepherd/spec/?draft=1&anchors=1&spec=css-viewport-1) (`section` is only set for the Change appendix heading). @plinss, any recent change that could explain this behavior?

**Comment by plinss** [comment]
Investigating

**Comment by plinss** [comment]
A recent bug fix introduced another bug. Should be fixed now, tho it'll take up to an hour to re-parse all the specs.

**Comment by tidoust** [comment]
Headings are back, thanks for the fix!
