### ISSUE TITLE
script-var-click-highlighting relies on Annex B

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#2407]
Based on a quick chat with Alexey Shvaika I think that the reason algorithm highlighting doesn't work in WebKit is because the script relies on Annex B semantics.

Could it be written such that it's strict mode compatible?

**Comment by tabatkins** [comment]
Whatever I was doing doesn't appear to be written in Annex B (anymore??), but yeah, making it strict-mode was easy. ^_^
