### ISSUE TITLE
`Work Status` is a required metadata key

### ISSUE THREAD

**Issue by cdoublev** [tabatkins/bikeshed#2412]
I got this error when trying to process custom text:

```
FATAL ERROR: Not all required metadata was provided:
    Missing a 'Work Status' entry.
```

`Work Status` is documented as an optional [metadata key](https://tabatkins.github.io/bikeshed/#metadata). I would be pleased to fix the doc if this key is actually required.

**Comment by tabatkins** [comment]
It's required specifically and only for csswg documents. I don't document that in the general Bikeshed docs because it's something internal for us.
