### ISSUE TITLE
WebDriver exported definitions not being indexed?

### ISSUE THREAD

**Issue by rakuco** [tabatkins/bikeshed#2416]
w3c/webdriver#1639 exported a bunch of WebDriver <dfn>s, and I'm trying to refer to them from my spec. However, things like `[=remote end steps=]` result in errors like

    LINK ERROR: No 'dfn' refs found for 'remote end steps'.
    [=remote end steps=]

I also don't see any WebDriver terms in bikeshed-data/anchors. Does the spec need to be added to some indexer?

**Comment by tabatkins** [comment]
Yup, adding them now.

**Comment by rakuco** [comment]
Thanks, I can see that it's working now!

**Comment by tabatkins** [comment]
ah yup, changing them to be dashless. (Sigh, yet another time the W3C's lack of an editorial policy on shortname numbering bites us.)

**Comment by rakuco** [comment]
Thank you for the quick fix!
