### ISSUE TITLE
Echidna publication with images broken

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#2437]
Trying to bisect this...

* [failed run](https://labs.w3.org/echidna/api/status?id=710be6fd-a4f9-4a8b-9605-0e9e86bddf34) with latest build
* [successful run](https://labs.w3.org/echidna/api/status?id=a7114615-9506-424c-b6d6-a3587b53f613) published with bf3136d31f2a87677999ff304772d73833896ddc
* [failed run](https://labs.w3.org/echidna/api/status?id=ec4f6eda-21f5-441b-977b-a06d2e3f5576) with 6c2c66e56c99fcf6565bd519828ebfcdafd0f231
* [successful run](https://labs.w3.org/echidna/api/status?id=0e92c9da-6012-4114-9242-01728deeefd4) with a199ec99ba0a0fd53695476aa6fe58e280f82617
* [successful run](https://labs.w3.org/echidna/api/status?id=298c1c20-1b2b-45c2-a30c-71206d9c5de9) with 0fe3edbd9b38d5275e0027ec435752291bf3c4f0
* [failed run](https://labs.w3.org/echidna/api/status?id=4c4742c6-9c27-4268-b5a8-3cfd406b3567) with 30dede717a52c1142c2ec8ae48509d6533440a4a
* failed tarfile build with 4961a98f64f2a1ba42c232fda28a86d7efdddcc4

Offending commits seem to be the last two. The last successfully publishing commit was 0fe3edbd9b38d5275e0027ec435752291bf3c4f0.

**Comment by fantasai** [comment]
(I'm really confused because I know I thought I published css-pseudo-4 with an up-to-date Bikeshed yesterday, but maybe I was working with an old copy?)

**Comment by tabatkins** [comment]
Hm, my relative-path code must be screwing up here. I'll see what's going on.
