### ISSUE TITLE
Linking to W3C's HTML spec.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#254]
At some point between September and now, the autolinking mechanism flipped from pointing at W3C's HTML spec to the WHATWG's HTML spec. The entire discussion of quality and up-to-dateness to the side, it's unlikely that I can get anything through WebAppSec using all WHATWG specs all the time.

I suspect that most people using Bikeshed actually _want_ to link to WHATWG's HTML, but there might be room for a pref? Or for something like `Link Defaults: HTML` vs `Link Defaults: HTML5` (I'm a bit surprised that the latter links to WHATWG, honestly; that's not it's name)?

If I'm the only one who needs W3C references, I'd be perfectly happy generating the `anchors.data` file myself if there's some documentation about how to go about doing it. :)

**Comment by tabatkins** [comment]
Closing because you've presumably been publishing with WHATWG HTML references for a while; CSS certainly has.  And W3C's HTML has become even more of a garbage fire than it was before.
