### ISSUE TITLE
Document the cross-spec linking/metadata protocol

### ISSUE THREAD

**Issue by halindrome** [tabatkins/bikeshed#257]
The autolinking documentation seems to imply that if I want to scope a definition, I can use a specific 'scope' attribute on my dfn (e.g., property) or a generic 'dfn-for' attribute on a container.  But when I look in the code, it seems to be looking for 'data-dfn-type' and 'data-dfn-for'.  Similarly, it seems to be looking for 'data-local-title' rather than title.  

I am in the process of implementing similar behavior in ReSpec and want to support the same syntax bikeshed does - can someone please clarify - preferably in the documentation - what the preferred and supported syntax really is?

**Comment by halindrome** [comment]
Just checking in - @tabatkins did you write up this documentation?

**Comment by tabatkins** [comment]
I just did! <https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md>

**Comment by halindrome** [comment]
Thanks for providing this.  As I augment the ReSpec dfn processing I will
ensure it adhere's to this contract.

On Thu, Jul 9, 2015 at 5:25 PM, Tab Atkins Jr. <notifications@github.com>
wrote:

> I just did!
> https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tabatkins/bikeshed/issues/257#issuecomment-120164970>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
Note that I have added this stuff to respec now.  It produces data-lt for
definitions and supports aliases now.  There is still more to do on export
/ no export and namespacing of definitions, but we have a start!

On Fri, Jul 10, 2015 at 5:25 PM, Shane McCarron <halindrome@gmail.com>
wrote:

> Thanks for providing this.  As I augment the ReSpec dfn processing I will
> ensure it adhere's to this contract.
>
> On Thu, Jul 9, 2015 at 5:25 PM, Tab Atkins Jr. <notifications@github.com>
> wrote:
>
>> I just did!
>> https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tabatkins/bikeshed/issues/257#issuecomment-120164970>
>> .
>>
>
>
>
> --
> Shane McCarron
> halindrome@gmail.com
>



-- 
Shane McCarron
halindrome@gmail.com
