### ISSUE TITLE
Enable the definition of hyperlink text within railroad diagram boxes.

### ISSUE THREAD

**Issue by rubys** [tabatkins/bikeshed#270]
To illustrate the request, see http://intertwingly.net/projects/pegurl/url.html#user-info

user and password inside the railroad diagram don't hyperlink, user and password in the prose below do.

I'm not presuming that it be done automatically, but rather by requiring those that wish to have hypertext links to indicate this in the `<pre class=railroad>` content somehow.  On the off chance that it helps, in my case the anchor text, the href/id, and the title all match.

**Comment by tabatkins** [comment]
done forever ago
