### ISSUE TITLE
`local-title` terms aren't getting the conjugation fixups that real definitions are

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#309]
`<dfn local-title=generate>generate a baseline</dfn>` won't be linked by `<a>generated</a>`, even though it would be if `generate` were a normal definition.

**Comment by mikewest** [comment]
This also seems to be the case for crosslinks contained in `<pre class="anchors">...</pre>`

**Comment by tabatkins** [comment]
Hm, I appear to have broken this functionality *entirely* at some point.  That's not good.  TO THE BISECT!

**Comment by tabatkins** [comment]
Never mind, I misunderstood what was going on THIS WHOLE TIME.  As I vaguely remembered, I fixed this a while ago.  But I still had a bug *in the linkTextVariations() code*, where it didn't handle the case of `generate <-> generated`.  Fixed now.
