### ISSUE TITLE
Prism is broken due to over-escaping

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#315]
> SyntaxError: missing ) in parenthetical

due to

```js
(typeof WorkerGlobalScope !== 'undefined' &amp;&amp; self instanceof WorkerGlobalScope)
```

**Comment by tabatkins** [comment]
Can you give me a more complex example, or point to a spec source file that demonstrates it? I put just that line into a test file, and didn't get any error.

**Comment by tabatkins** [comment]
Also: what's throwing that error? That doesn't look like a Bikeshed error.

**Comment by domenic** [comment]
Sorry, I guess that wasn't quite clear. The bikeshed output currently on https://streams.spec.whatwg.org/ contains the `(typeof WorkerGlobalScope !== 'undefined' &amp;&amp; self instanceof WorkerGlobalScope)` code, which causes Firefox to the throw the `SyntaxError: missing ) in parenthetical`. I assume the reason it contains that output is Bikeshed's fault.

Source file at https://github.com/whatwg/streams/blob/master/index.bs

**Comment by tabatkins** [comment]
Never mind, figured out what you meant.  Fixed.
