### ISSUE TITLE
hover expansion for property value types

### ISSUE THREAD

**Issue by astearns** [tabatkins/bikeshed#318]
When a property has multiple <value-type> links, it's annoying to have to go back and forth in the doc to see what the type expands to. It would be cool if the expanded values could be seen in a tooltip on hover

**Comment by tabatkins** [comment]
I don't completely understand what you're suggesting.  Gimme an example of what is currently crappy, and how you'd like it to act?

**Comment by astearns** [comment]
It came up when Fantasai and I were looking at align-items (http://dev.w3.org/csswg/css-align/#align-items-property). In order to grok the values, I have to follow three links:

<baseline-position>, <self-position>, and <overflow-position>

These just enumerate some values that are being grouped. If I could hover over those groups and see that <baseline-position> expands to: baseline | last-baseline, etc. then I don't have to leave the property definition to understand the value set.

I'd classify this as a low priority, little tweak to improve readability.

**Comment by tabatkins** [comment]
Makes sense, and should be easy to do.

**Comment by tabatkins** [comment]
Done!  As long as values are properly marked up with a `for=''` attribute, type autolinks will now have a title saying what they expand to.

This adds a decent chunk of processing time; I'll have to work on performance for this feature soonish.
