### ISSUE TITLE
Some way to insert text into the document from the command line

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#322]
I'd like to be able to pass some text to bikeshed, on both the command line and in the web API, and then place it in the document at a point I specify. E.g.,

```html
<script>
  var currentCommit = "{{CURRENT-COMMIT}}"
</script>
```

I don't really know how to do this as-is. I guess I could do a second pass after bikeshed...

**Comment by tabatkins** [comment]
And done, @domenic.  Just do:

```
bikeshed spec input.bs output.html --md-Text-Macro="CURRENT-COMMIT 1234abc"
```

And you can use `[CURRENT-COMMIT]` in your spec.

**Comment by domenic** [comment]
<3

**Comment by tabatkins** [comment]
Hmm.  I dunno if you can do multiple keys with the same name or not.  That's... problematic.
