### ISSUE TITLE
Autolink shorthand for elements and element attributes.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#323]
I find myself writing `<code><a element-attr for="...">...</a></code>` more often than I'd like. It would be nice if there was a shorthand autolink for this kind of thing. If you hadn't used up ALL THE SPECIAL CHARACTERS already for boring old CSS, I'd have a reasonable suggestion for syntax. As-is, I will simply lament that `<<...>>` has already been swiped. That said, nothing matches `<iframe@src>` yet.  Or `{{iframe@src}}`, I guess. Or anything else?

**Comment by tabatkins** [comment]
Yeah, the specs I write don't have many element or element-attr links, so I don't feel this very keenly.  I'm totally open to fixing this.

(And hey, CSS only eats two of the special characters! ^_^)

I'd want the syntax to be consistent for element and element-attr definitions, so the latter can just use a / to indicate `for` values, like I do for all the other shorthands.  This, unfortunately, rules out using plain `<foo>`, as the "element" form would look like a normal element.  It also rules out `{{foo}}`, as even if we use capitalization, that still looks like an IDL attribute.

So, we've got a few other possibilities:

1. *Triple* angles: `<<<iframe>>>` and `<<<iframe/src>>>`
2. We've double all the matching chars except parens: `((iframe))` and `((iframe/src))`
3. Any special character that markdown hasn't claimed:
    1. `$iframe$` and `$iframe/src$`
    2. `%iframe%` and `%iframe/src%
    3. `|iframe|` and `|iframe/src|`
    4. `=iframe=` and `=iframe/src=`
    5. `~iframe~` and `~iframe/src~`
4. Any of the above, doubled, for lowered likelihood of collisions?
5. ???
