### ISSUE TITLE
Linking to `'self'` is difficult.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#324]
`'self'` is an autolink to a property or descriptor named "self". This is unfortunate for CSP, which uses `'self'`, `'none'`, `'unsafe-eval'`, `'unsafe-inline'`, and `'unsafe-redirect'` as values which I'd like to link to.

I was hoping that `<a title/lt/whatever="...">'self'</a>` would work, but the preprocessing for autolinks happens before takes precedence.

Would you accept a patch which turned off the CSS-specific bits for specs that don't intend to use those autolinks? Or create an escaping syntax (`\'self'`, perhaps)?

WDYT?

**Comment by tabatkins** [comment]
The usual way we handle this is to just not use single quotes; instead we use double quotes or smart quotes ‘’ for things.

But if single quotes are pretty important here, yeah, I'd accept either of those patches.

If you do the former, a metadata line like `Markup Shorthands: CSS off` would work (using the "YAML boolean" that I use in some other metadata; there's a parsing function for it in MetadataManager).

The latter has precedence - I already allow escaping some of the shorthands with an opening slash.  Extending that to all of them would be fine.

**Comment by tabatkins** [comment]
And done.  There is now a `Markup Shorthands` metadata, taking a comma-separated list of categories and bool-ish values, so you can shut off the CSS shorthands with:

```
Markup Shorthands: css no
```
