### ISSUE TITLE
Every test fails.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#325]
Some of the whitespace changes that landed a little while back don't seem to have made their way to the test suite. Everything fails, which makes it a little bit difficult to verify new changes. :)

Since it's not clear that all the changes are indeed desirable, it'd be nice if you could take a look, Tab.

We should set up a CI server... :)

**Comment by tabatkins** [comment]
Haha, shows how often I run tests. I'm a terrible person.

I've never set up a CI server before, and have no idea where to start. Any help, even just pointing me to where I can learn, would be appreciated.

**Comment by domenic** [comment]
Travis CI is very painless and easy to use. I am not sure what the best for-beginners guide is but I am hopeful that the giant "Get Started" button on http://docs.travis-ci.com/ is as helpful as it advertises.

**Comment by tabatkins** [comment]
And it works now!
