### ISSUE TITLE
Bikeshed chokes on {1,3} multiplier

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#328]
Value: [ auto | <<integer>> ]{1,3}

is a fatal error. Why is this a fatal error?

**Comment by tabatkins** [comment]
Not 100% sure *why* this occurred, but it happened because you didn't close the `<div class='issue'>` in section 6, so the entire rest of the spec was inside of an issue.  Bikeshed doesn't tend to like that very much.  When I fixed that, you build with just a single linking warning.

**Comment by fantasai** [comment]
Okay. I'm glad it builds now. That's still messed up, though. IMHO either
  a) Bikeshed spits a fatal error for propdef tables inside issues
  b) Bikeshed correctly parses propdef tables inside issues
is a correct resolution to this issue.

**Comment by tabatkins** [comment]
Yeah, some detection of the "you obviously fucked up your markup here; this stuff doesnt' belong in an issue" would be nice.  Unsure of why the grammar link is dying, actually.

**Comment by domenic** [comment]
> Yeah, some detection of the "you obviously fucked up your markup here; this stuff doesnt' belong in an issue" would be nice

+1. For me the biggest issue is unclosed `<code>` or `<b>` tags.
