### ISSUE TITLE
"Status Text" metadata field doesn't work

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#330]
https://github.com/tabatkins/bikeshed/blob/master/docs/metadata.md says that a "Status Text" metadata field will cause additional custom text to appear in the "Status of this Document" section.

However, it doesn't work for me; I get no added text.

If you need a testcase, I can provide one, but it's a patched version of the transitions spec.

**Comment by tabatkins** [comment]
So, the metadata is parsed and the text macro is loaded up, but none of the boilerplates actually use it.  Any preference on *where* in the SotD the extra text should go?

**Comment by dbaron** [comment]
It looked to me like the SVG boilerplates used it.  That said, when I tried putting [STATUSTEXT] in the CSSWG ones the way the SVG ones used it, it didn't work.

I had put them in an additional paragraph at the end.  I'm not sure if the extra empty &lt;p&gt; would be problematic for the common case of having no status text.
