### ISSUE TITLE
IDL processing puts invalid for attribute on spans giving type of property

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#333]
The processing of IDL blocks that bikeshed does puts an invalid for attribute on span elements in some cases, resulting in invalid HTML:
http://validator.w3.org/check?uri=http%3A//dev.w3.org/csswg/css-transitions/

&lt;span data-attribute-info="" for="TransitionEvent/elapsedTime"&gt; of type &lt;a data-link-type="idl-name"&gt;float&lt;/a&gt;, readonly&lt;/span&gt;

**Comment by tabatkins** [comment]
Fixed, as part of a more general "reduce the amount of bullshit I send down the wire". Those element now get emptied of their attributes, so there's nothing to be invalid about.
