### ISSUE TITLE
Linkify Employers

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#340]
In CSS Writing Modes, we used to link the Former Editors employer names to their website, e.g. <a href="http://www.antenna.co.jp/">Antenna House</a>. Seems like something broke that recently. It would be nice to be able to do that again.

**Comment by tabatkins** [comment]
That works, just read the docs for the syntax.  (Unless you mean that you tried the syntax in the docs, and something broke it?)

**Comment by tabatkins** [comment]
Yes, confirmed, it works fine if you follow the grammar in the docs.
