### ISSUE TITLE
`urlPrefix` is folding strangely.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#341]

**Comment by mikewest** [comment]
Er. Hit enter too quickly. In short: https://github.com/w3c/webappsec/commit/80ea7552044be29b483488816135bfd5b2557e94 pokes at some definitions in the POWER spec, of the form:

    <pre class="anchors">
     urlPrefix: http://www.w3.org/TR/html5/
       type: dfn
         urlPrefix: embedded-content-0.html
           text: an iframe srcdoc document
         urlPrefix: browsers.html
           text: active document
           text: ancestor browsing context
    </pre>

These are generating links without the second `urlPrefix`: e.g. `<a>ancestor browsing context</a>` links to `http://www.w3.org/TR/html5/#ancestor-browsing-context` instead of `http://www.w3.org/TR/html5/browsers.html#ancestor-browsing-context`.

Am I doing something wrong?

**Comment by tabatkins** [comment]
No, you're doing right. I guess I'm doing something wrong.
