### ISSUE TITLE
When adding IDL section, if the container is an h2, don't make another one

### ISSUE THREAD

**Issue by birtles** [tabatkins/bikeshed#352]
I want to write the following:

&lt;h2 data-fill-with="idl-index" id="interface-summary">Interface summary&lt;/h2>

But in addIDLSection, when we fetch the fill container we always add a child h2, even if the container itself is a h2. As a result we end up with two headings which looks stupid.

Ideally it should even be possible to add some introductory prose between the custom heading and the IDL summary. Maybe we could drop the h2 generation altogether? Or only drop it when the fill container is not the body element?

This is needed to fix https://github.com/w3c/web-animations/issues/49

**Comment by tabatkins** [comment]
I could possibly have it check if the element is a heading and append after versus inside, but why do you need this in the first place?  Can't you just do `<div data-fill-with=idl-index>`?  Seems like that would fix w3c/web-animations#49

**Comment by birtles** [comment]
Then you'd end up with a heading that says "IDL index" instead of "Interface summary".

**Comment by tabatkins** [comment]
Oh, so the thing is that you want to control the heading name for some reason? Note that the section is more than just interfaces.

**Comment by birtles** [comment]
I guess I don't care that much. I was thinking of interface in the sense of "Programming interface".

**Comment by birtles** [comment]
> Can't you just do <div data-fill-with=idl-index>?
I did that but unfortunately the heading it generates has no number so it messes up the document structure. I just removed the section for now and left the IDL index in its default positioning.
