### ISSUE TITLE
IDL method id generation should not include arguments

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#355]
See http://dev.w3.org/csswg/cssom-view/#dom-window-scrolloptions

I'd like the id to be `dom-window-scroll` instead

**Comment by tabatkins** [comment]
The problem is, what if you have multiple overrides of the function?  They'll have colliding IDs then.

**Comment by zcorpan** [comment]
Sometimes overrides are still have just one `dfn`, but if there is a `dfn` for each override I guess it makes sense to include the arguments in the id (but should still be separated from the method with a dash).

**Comment by tabatkins** [comment]
Done now.  As long as there aren't multiple overloads, I just generate the short form.
