### ISSUE TITLE
Feature request: Autogenerate a list of external references.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#361]
Web Bluetooth does a nice job presenting the terminology brought in from other specs: https://webbluetoothcg.github.io/web-bluetooth/#terminology (yay, @jyasskin!). I've done similar things in various WebAppSec specs (https://w3c.github.io/webappsec/specs/upgrade/#terms-defined-by-reference, for instance). Currently, these lists are lovingly hand-crafted, which is somewhat absurd. :)

@tabatkins: How would you feel about a patch to bikehsed that captured the references used to generate a document (probably by making `ReferenceManager::getRef` return a reference rather than a URL, and storing a de-duped list on the `CSSSpec` object (which we should totally rename to `WebAppSecSpec` or something :) )?

**Comment by jyasskin** [comment]
Heh, my list is a workaround for https://github.com/w3c/respec/issues/332 not being finished.

**Comment by tabatkins** [comment]
Yeah, this seems quite reasonable. Only problem is that there's no real mapping between anchor spec names and biblio entries; they should quite often coincide, but won't always.  Though I suppose we can generate at least a minimal biblio entry from the specs database when there's no match.  You could also supply a custom biblio entry if desired.

And yeah, `CSSSpec` is one of the few remaining things pointing out that I clearly designed this for the CSSWG at first. ^_^

**Comment by tabatkins** [comment]
Closing this, since the PR was merged.

Also: just landed the ability to auto-generate biblio entries from spec data, if the shortname isn't in the biblio data.  The spec data should match the autolink data, except for manually-added anchor data, so you should get all the biblio entries filling in now.
