### ISSUE TITLE
Markdown `dl` processing is a bit off.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#364]
It looks like the `dl` processing is a bit off:

    <section>
      : Yay
      :: Boo

      : Yay
      :: Boo is really long
         so I split it over two lines.
    </section>

ends up with an `htmlblock` element, which seems strange. Adding a newline between the last item in the list and the `</section>` closing tag fixes the issue.

See https://github.com/w3c/webappsec/commit/b39f40e5da6491bdde7b30b659b6f58ad513d9e8 for an example, and https://github.com/w3c/webappsec/commit/26ff8130805c064813cb930a7c6084e52fe5a970 for the fix.

**Comment by tabatkins** [comment]
Ah, I see.  DL processing is over-claiming one line if you don't end with a newline, and this makes it treat whatever's following as a DL item, which it outputs as `"<{0} data-md>".format(type)`, thus the `<htmlblock>` element (as that's the `type` of lines that contain HTML block elements).  Fixing...

**Comment by tabatkins** [comment]
And done.
