### ISSUE TITLE
Introduce shorthand syntax for <dfn attribute for=X>

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#367]
It would be nice to mirror the {{Foo/bar}} syntax with something like {{!Foo/bar}} to `dfn` the attribute/method. (Maybe {{!bar}} could also work if an ancestor has a `for` attribute?)

**Comment by zcorpan** [comment]
yay/nay?

**Comment by tabatkins** [comment]
Unfortunately, it's ambiguous. `{{Foo/bar}}` can't tell whether it's an interface attribute or a dictionary member; `{{Foo/bar()}}` can't tell whether it's a method or constructor.  It's fine when linking, because there's almost never ambiguity when matching against the set of definitions.

**Comment by tabatkins** [comment]
I could require a typing specifier, like `{{!Foo/bar!!attribute}}` (forgive the syntax, just reusing what you suggested), but I don't think that's much of an improvement over `<dfn for=Foo attribute>bar</dfn>`.  wdyt?

**Comment by zcorpan** [comment]
But you will have an IDL block, so you know from there what it is, no? If there's more than one possibility you can give a fatal error and say longhand markup is required.

**Comment by tabatkins** [comment]
Hmmm, *maybe*. It would require some funky ping-ponging.  Right now, IDL assumes that all dfns have been found, so it knows whether to mark up something as a dfn or a link.  I'd instead have to remember all the IDL dfns, then do the shorthand-dfn expansion, looking for a local dfn and filling in details from it, then changing the IDL dfns back to a link.

It's possible, but *man* would it be dodgy.

**Comment by zcorpan** [comment]
Heh, OK. I'd be happy with a WONTFIX if you can't think of a sane way to implement it.

**Comment by zcorpan** [comment]
or only support attribute and method, not constructor or dictionary member (less common anyway).
