### ISSUE TITLE
Some way to explicitly indicate "the one without a for value"

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#370]
When multiple definitions have the same type and text, you can add a `for` to the definitions to disambiguate them, so autolinks can specify `for` to point out which one they want.

This works as long as *all* the definitions have a `for` value, but what if one of them doesn't?  If a single spec defines the same term for two different things, and only puts a `for` value on one, there's currently no way to indicate that you want the one without a `for` value; omitting `for` on the link just indicates that you don't care about `for` values, not that you affirmatively want the one lacking `for`.

Just need an easy, unambiguous syntax for this.  Preferably one that can be extended to the markup shorthands.

**Comment by mikewest** [comment]
`{{//whatever}}`? `{{-/whatever}}`?

**Comment by tabatkins** [comment]
The use of a slash is not a bad idea at all.  It's already a reserved character in both the `for` attribute and the shorthands.  I like it.

**Comment by tabatkins** [comment]
Oh yeah, this was done a while ago.  A bare slash does indeed indicate "no for".  I don't think I handle this in the shorthands yet, tho.
