### ISSUE TITLE
Questions about grammatical relations, values and types.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#372]
Bikeshed helps me do the right thing when referring to things it knows about. That is, if I typo `<{meta/naem}>`, it'll helpfully note that it can't find `naem`. I'd like to be able to use this capability for other kinds of things.

For instance, https://w3c.github.io/webappsec/specs/upgrade/#insecure-requests-policy adds a property to environment settings objects that can have one of two values. There's no IDL for these, as they're not web-exposed, but it's basically like a property on an object with an enum value.

In https://github.com/w3c/webappsec/commit/1e64e464e6626e048d049d0ae3b0d65d71aeba15, I've fiddled around with abusing the `idl` type to do some autolinking. The syntax gets a bit verbose, and it's not clear that it would be comprehensible if these specs ever got automagically parsed. Is this sane? If so, would you accept a patch to extend some of the autolinking shortcuts to include spaces? If not, halp!

This is something I want to do for _many_ of the CSP directives (which, themselves, are somehow grammatically related to `Content-Security-Policy`, right?). Thoughts on how I can squeeze this sort of thing into Bikeshed's structure are welcome. :)

**Comment by tabatkins** [comment]
You don't need to use an `idl` type just to get `for=''` functionality; feel free to to make a `<dfn>foo</dfn> ... <dfn for=foo>bar</dfn>` set of definitions with the catch-all `dfn` type.  I'm using this in several places for the ongoing conversion of DOM, as it also has a lot of spec-exposed but not script-exposed values.

You can mix-and-match types, too - if you need to attach some informal concepts to an IDL type, like an interface, it's fine to have a `dfn` type definition point to an `idl` type for its `for=''` value; `for` values aren't actually checked in any way, they're just a namespacing mechanism (for now).

I've been trying to come up with better ways to handle this, though.  Unsure what I might want to do.
