### ISSUE TITLE
Unnecessary need for manual resolution of ambiguity

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#378]
As of this commit[1], with the latest bikeshed[2], I needed to disambiguate ''auto'' into ''overflow/auto'' and ''continue/auto'' inside the propdef for overflow and continue (respectively) in css-overflow/Overview.bs, otherwise bikeshed would warn me about guessing, and actually pick the wrong one in the case of continue.

Given that it is inside a propdef, this shouldn't be considered ambiguous, and bikeshed should figure it out on its own.

[1] https://github.com/w3c/csswg-drafts/commit/1c4304f1b8624b77e5c14983f589c1cca62f959f
[2] https://github.com/tabatkins/bikeshed/commit/6aff9bd1a247a130fcb97b3309c34ee5aec674d0

**Comment by tabatkins** [comment]
Done!  I had to add a new feature to handle this (the `data-link-for-hint` attribute), but it's actually a really useful thing in general.  I'll document it later, but for now, propdef tables automatically apply this and will link to the correct property's values automatically.
