### ISSUE TITLE
Add a way to define some custom elements as "opaque", like <pre>

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#380]
I was hoping to add Ecmarkup as a post-processing step for Bikeshed by writing `<emu-alg>` elements in my Bikeshed source, getting the result out unmolested in the .html, then running portions of the Ecmarkup pipeline on the .html.

This doesn't seem to work though. For example [this addition](https://github.com/whatwg/streams/commit/f9e4dc0e022648af6146a1ca3f17bc6fa0e9856b#diff-ec9cfa5f3f35ec1f84feb2e59686c34dR386) caused `bikeshed spec` to produce

```
$ bikeshed spec
←[1;31mFATAL ERROR:←[0m Line 370 isn't indented enough (needs 1 indent) to be valid Markdown:
"</emu-alg>"
```

I tried adding `emu-alg` to the list inside `isOpaqueElement` inside `htmlhelpers.py`, but it didn't seem to work.

**Comment by tabatkins** [comment]
I don't try to parse; you're running into the problem that Bikeshed assumes a 4-space (or 1-tab) indent, and you're using a 2-space.  Some of the Markdown processing will work incorrectly with that.

You can fix this by specifying `Indent: 2` in your metadata.

**Comment by domenic** [comment]
But the point of this bug is that I don't want the contents of `<emu-alg>` to be considered Markdown. I want it to be left alone, just like the contents of `<pre>`.

**Comment by tabatkins** [comment]
Oh, then you're a bit more screwed.  Hmm.  I'll have to add something to make that work.

(You still need to tell Bikeshed that you're using a 2-character indent; I don't know what else might be subtly messed up by the wrong indent level.)

**Comment by tabatkins** [comment]
Done. Add `Opaque Elements: emu-alg` (or a comma-separated list, if you need multiple).
