### ISSUE TITLE
fatal error about boolean in idl

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#381]
readonly attribute boolean is2d;

FATAL ERROR: No 'idl-name' refs found for 'boolean'.

(workaround is to add boolean to ignored terms)

**Comment by tabatkins** [comment]
Yup,"boolean" isn't detected as a definition out of the WebIDL spec.  Fix is probably just to convert WebIDL to Bikeshed, which is on my list.  For now, you just need to ignore the failure, as you've done.
