### ISSUE TITLE
dom Document gives error

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#387]
`{{Document}}`
->
```
WARNING: Multiple possible 'idl' refs for 'Document'.
Arbitrarily chose the one in html5.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:svg2; type:interface; text:Document
spec:html5; type:interface; text:Document
```

dom-ls is correct but that gives a fatal error. However on the csswg server this appears to work fine without warnings (and it points to the dom spec).

**Comment by tabatkins** [comment]
Should be fixed now.  Remember to `bikeshed update` if you're getting different results locally than the CSSWG server; it's not running any special version there or anything.

**Comment by zcorpan** [comment]
http://dev.w3.org/csswg/bikeshed/cssom-view/ still seems to give warnings for `Document` and doesn't give `dom` as an option...?

**Comment by tabatkins** [comment]
Indeed. I thought we'd fixed that. :/

**Comment by tabatkins** [comment]
All right, actually fixed now.  The `force` attribute was broken. Haven't been able to figure out *why* it was broken, but I fixed it anyway.  Now (once Shepherd re-parses DOM) Document will show up with DOM as a source.

Now I just gotta implement the "obsoletes" thing so DOM can automatically wipe out the HTML and SVG2 references.
