### ISSUE TITLE
Best practice for keeping old IDs?

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#388]
If I have a section, say `<h3 id="call-pull">CallPull(stream)</h3>`, and I rename it to e.g. `<h3 id="request-pull">RequestPull(stream)</h3>`, I'd kind of like any old links to keep working. For cases like this I don't think it's a great idea to insert something like `<p id="call-pull">Note: this abstract operation used to be called CallPull</p>` since it's low-level enough that people probably don't want to know that. (It's not like the DOM futures -> DOM promises transition.)

I had a few ideas for this, but was curious what you'd consider best practice:

- Dummy `<span id="old-id">` before (after? inside?) the `<h3>`
- Some JS code that will keep a table and do `location.replace` (pro: if user now copies URL bar it is correct)
- Something else?

Finally if we do settle on a best practice I'd be interested in maybe making it easier to author with a Bikeshed-specific trick like `<h3 id="request-pull" old-ids="call-pull">RequestPull(stream)</h3>` that gets post-processed into whatever we decide on.

**Comment by tabatkins** [comment]
I prefer a dummy <span> inside the heading.  Doesn't need to wrap or anything like that; just put an empty span after the content or something.

But yeah, having a mechanism to standardize this would be nice.

**Comment by tabatkins** [comment]
Done. Add an `oldids=''` attribute to your heading, with a comma-separated list of old IDs you want to maintain, and Bikeshed will add empty `<span>`s with the IDs to the heading.

**Comment by mikewest** [comment]
```
Traceback (most recent call last):
  File "/Users/mikewest/bin/bikeshed", line 9, in <module>
    load_entry_point('Bikeshed==0.0.0', 'console_scripts', 'bikeshed')()
  File "/Users/mikewest/Repositories/bikeshed/bikeshed/__init__.py", line 160, in main
    doc.preprocess()
  File "/Users/mikewest/Repositories/bikeshed/bikeshed/__init__.py", line 1327, in preprocess
    cleanupHTML(self)
  File "/Users/mikewest/Repositories/bikeshed/bikeshed/__init__.py", line 1184, in cleanupHTML
    for el in findAll("[oldids]"):
TypeError: findAll() takes exactly 2 arguments (1 given)
```

:(

**Comment by tabatkins** [comment]
Le sigh. That's what I get for making "trivial" changes without running it through the test case again.  Fixed.

**Comment by domenic** [comment]
<3!
