### ISSUE TITLE
Exposed=Window will make Window a link

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#390]
It doesn't happen for Exposed=(Window,Worker)...

**Comment by annevk** [comment]
See DOM to see this in action.

**Comment by tabatkins** [comment]
Are you asking for both of them to link, or neither?  Assuming you wanted both, I filed <https://github.com/plinss/widlparser/issues/7>.

**Comment by annevk** [comment]
Actually, unless they link to the thing that says [Global=Window] or [Global=Window] it probably doesn't make sense to link them.

**Comment by tabatkins** [comment]
All right, fixed.  [Exposed=Foo] names don't link at all.  When I start recognizing [Global] names, [Exposed] will link to them.
