### ISSUE TITLE
<dfn>name</dfn> !== <dfn>[[name]]</dfn>.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#392]
`<dfn>name</dfn>` !== `<dfn>[[name]]</dfn>`. The latter is used as a "slot" syntax in ECMAScript; it would be nice if Bikeshed wouldn't strip them both down to `name`. :)

**Comment by tabatkins** [comment]
You're talking about the ID generation, yeah?  It strips all the non-URL-safe chars automatically.  I can specialize the name generation for slots, though.

**Comment by tabatkins** [comment]
Done, slots now get a `-slot` appended to their ID, so they don't collide with same-named public attributes.

**Comment by mikewest** [comment]
I wub j00!

**Comment by domenic** [comment]
@mikewest how are you using this exactly? In streams I am currently not auto-linking to slots but probably should be.

**Comment by tabatkins** [comment]
@domenic I use it in Font Loading, too.  Just have a prose definition of the slot, like:

```
Foo objects have a <dfn attribute for=Foo>[[bar]]</dfn> private slot, which is initially an empty list.
```

Then you can use `{{[[bar]]}}` to autolink it.
