### ISSUE TITLE
How can I tell if a compile fails using the REST service and CURL?

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#395]
I seem to have auto-deployed a version of Streams that consists soley of

> Error running preprocessor, returned code: 1. [1;31mFATAL ERROR:[0m No 'dfn' refs found for 'structured clones' with spec 'html5'.

eek!

**Comment by tabatkins** [comment]
As documented in <https://api.csswg.org/bikeshed/>, you can ask for the err channel by passing `output=err` to curl.  You'll have to verify what it shows when the spec is passing, but you can use that as your test.

**Comment by domenic** [comment]
So is the correct method here to do two API calls for each bikeshed: first with output=err, and verify that it's empty, and second without that flag, and use the result?

Couldn't the API just return a non-200 status code so that we could use curl's `-f` flag?

**Comment by tabatkins** [comment]
Invoking @plinss...

**Comment by plinss** [comment]
Added 400 http response code when Bikeshed produces a fatal error.

Note that another option is to use the force=1 flag which would give you empty output in case of a fatal error.

**Comment by domenic** [comment]
Thanks @plinss! Implemented in my deploy script.
