### ISSUE TITLE
"Terms defined by reference" lowercases reference names

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#396]
E.g. streams says

> [html] defines the following terms: 

But I would expect

> [HTML] defines the following terms:

**Comment by tabatkins** [comment]
That term is generated off of the anchor data, from Shepherd, which stores names in lowercase.  However, I just made it so that if the term also shows up in the biblio data, it'll use the biblio casing, which is preserved.  I confirmed that this fixes you.

**Comment by domenic** [comment]
\o/ thanks!
