### ISSUE TITLE
[SERVICE-WORKERS] reference not being ED

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#397]
I thought we set something where WHATWG specs would always reference EDs?

Specref's database has an edDraft entry for service workers. However, https://streams.spec.whatwg.org/#informative has a /TRash link.

**Comment by tabatkins** [comment]
I added a way to set the default behavior, but didn't do anything special for WHATWG specs - you had to set it in your metadata for each spec.  I've now created a `defaults-whatwg.include` file with this parameter set, so whatwg specs will now prefer to reference "current" urls.
