### ISSUE TITLE
would be nice to generate pretty parameter info

### ISSUE THREAD

**Issue by ianvollick** [tabatkins/bikeshed#399]
Something like this: http://www.w3.org/TR/web-animations/#constructors

**Comment by tabatkins** [comment]
Thoughts so far:

```
<pre class="argumentdef" for="Foo/bar()">
baz: the description of the baz argument
qux: the description of the qux argument
</pre>
```

Descriptions can be multi-line and contain Markdown.  Generated result is a table like what you linked to.

**Comment by tabatkins** [comment]
And done.

Only thing to watch out for is that you need to supply the *full* method name, with args and such.  For example, given an IDL block like:

```
interface Foo {
  long bar(long qux);
};
```

you'd write the argumentdef block like:

```
<pre class="argumentdef" for="Foo/bar(qux)">
qux: description of qux
</pre>
```

You'll then get a table exactly like the one in WebAnim.

**Comment by ianvollick** [comment]
yay! thanks!
