### ISSUE TITLE
Local webserver and refreshing on save

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#401]
Have you used jekyll (http://jekyllrb.com/)? It's a static website generator. You write template html or markdown files, run "jekyll build" and it processes your files and builds the site.

You can also run "jekyll serve", and in addition to building your site, it sets up a web server on localhost.

One very nifty feature is that, by default on "jekyll server", and opt in on "jekyll build --watch", it will continuously Watch for changes in the source files and rebuild if anything changes (and spit out error on stderr while serving the old version if rebuilding fails).

It's really cool, and now I dream of "bikeshed serve", and to a lesser degree of "bikeshed build --watch". Well, they might be called "bikeshed spec --serve" and "bikeshed spec --watch", but you get my point.

Not only is having a continuously updated page to look at pretty neat, having warnings and errors scroll by in a terminal window every time you hit save is quite handy as well.

Doing it by polling is possible, but that'd be silly. If you want to get events from the OS, at the low level, it is different between OSes; linux uses something called inotify for instance. However, this is a common enough problem that I'm sure there is a variety of python libraries abstracting that for you, including cross-platform ones.

I'm not a python guy, but a bit of looking around suggests this wrapper may be a good one:

https://pypi.python.org/pypi/watchdog/

**Comment by domenic** [comment]
I built something similar in io.js https://github.com/whatwg/streams/blob/master/local-watch.js

**Comment by tabatkins** [comment]
And it's now built-in.  Run `bikeshed watch` (same input/output argument as `spec`).

This does *not* reload your page automatically, so you'll still have to do that yourself.  Making that work would be tricky, as I'd have to generate the spec twice, once injecting a script to talk back to the local http server waiting for a signal to refresh.  Maybe someday.

**Comment by tabatkins** [comment]
Do you need a local webserver version?  Why is loading from file: not acceptable?

**Comment by frivoal** [comment]
As long as you're bikeshedding specs one by one, there's probably not much difference between file: and http:, even if http gives you a tiny little bit of flexibility (think of a pair-specing session with You or Fantasai editing on one machine and the other one reading off an other one). But it's not a huge difference.

However, if you later get around supporting bikeshedding for a set of files together (either a multi-part spec like css21 or bikeshed the entire csswg-drafts repo at once), the local web server version of the specs could be generated to have local cross links, while I'd expect the file: version to be the final files.

**Comment by frivoal** [comment]
Looks like there's an issue with the current implementation. Some sections of the spec get duplicated, rather than replaced, when the spec is regenerated:

https://twitter.com/frivoal/status/606459320704892928

**Comment by tabatkins** [comment]
Fixed.
