### ISSUE TITLE
A <dfn> for an IDL member should have its contents wrapped in <code>

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#406]
Because it's code, after all. Also, should `<dfn>{{Node/baseURI}}</dfn>` be a thing?

**Comment by jyasskin** [comment]
Interestingly, I see `class="idl-code"` in most of these definitions, but no style to make that actually code-font. Probably `<code>` is more accurate than just a class since it represents the semantics. @tabatkins

**Comment by annevk** [comment]
I have since manually fixed a lot of this by the way in DOM. Wasn't worth the wait.

**Comment by tabatkins** [comment]
Fixed! If the contents aren't already wrapped in a `code`, they get wrapped.
