### ISSUE TITLE
Add "Finding of the TAG" status

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#407]
http://www.w3.org/2001/tag/doc/promises-guide is getting some flack over using "A Collection of Interesting Ideas". Future TAG findings using Bikeshed will need something similar.

**Comment by mikewest** [comment]
I'll need this for http://w3ctag.github.io/security-questionnaire/ as well.

@domenic: Is there a good document from which we could copy/paste a template?

**Comment by domenic** [comment]
Not sure what you mean exactly. I'm currently just using the defaults, I think (which mostly are derived from CSSWG stuff).

**Comment by mikewest** [comment]
I mean the text for sections like "status of this spec". Just the boilerplate that's necessary for a Finding vs a rec-track spec.

**Comment by domenic** [comment]
Oh. Well, I don't think there's any required boilerplate, and we'd like to minimize that actually. I think the status will be well-conveyed with just "Finding of the TAG."

**Comment by tabatkins** [comment]
Can you put together a minimal boilerplate? Is the default stuff you're currently getting okay, if we just changed the status?  If not, go ahead and trim down the `header.include` and `footer.include` files as necessary and PR me with something new.

It looks like y'all's two use-cases are for different groups, no?  I wonder if we can find a common group/status to give them, or if I just need to add a few extra.

**Comment by mikewest** [comment]
I think they're both planned to be published by the TAG; setting that up as a group sounds fine.

**Comment by domenic** [comment]
> Is the default stuff you're currently getting okay, if we just changed the status

Yeah, exactly. Although I guess the "This Version" link is stupid and I would love to kill it. But I guess that'd be more work than just adding a new status so nevermind :)

**Comment by tabatkins** [comment]
Okay, I've added support for the FINDING status.  It uses the W3C Note stylesheet (if your group uses the `[w3c-stylesheet]` text replacement), and sets the subtitle to "Finding of the {group}" automatically, so if you set `Group: TAG` along with it, it'll work correctly.

**Comment by domenic** [comment]
Thanks! http://www.w3.org/2001/tag/doc/promises-guide all updated.
