### ISSUE TITLE
Add status to bikeshed

### ISSUE THREAD

**Issue by gregwhitworth** [tabatkins/bikeshed#409]
To help for the automation page, please add the status of the spec to bikeshed. (http://log.csswg.org/irc.w3.org/css/2015-05-18/#e553164)

**Comment by fantasai** [comment]
By which he means, the CSSWG status category (current-work), not the W3C status

**Comment by tabatkins** [comment]
Now I just need to fix all of the specs, since they'll fail for a lack of Work Status now. ^_^
