### ISSUE TITLE
Method autolinking confusion.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#412]
https://github.com/w3c/webappsec/commit/e6c11ed448c9019620135227d750141408b207e8 introduced a number of autolinks of the form `{{get()}}`, which were intended to reference file:///usr/local/google/home/mkwst/Repositories/webappsec/specs/credentialmanagement/index.html#dom-credentialcontainer-gettypes-options. Instead, they linked to http://dev.w3.org/csswg/css-regions-1/#dom-namedflowmap-get, which was unexpected. :)

I can fix the linking by either referencing the exact signature (`{{get(types, options)}}`) or by scoping the reference (`{{CredentialContainer/get()}}`). It surprises me a little that I need to do either; it would be nice if we disambiguate locally before reaching out to other documents.

**Comment by tabatkins** [comment]
Ah, interesting.  Well, Regions is specifying those wrong, for one thing; if they'd correctly put the argument into the definition signature, the direct autolink would have failed, and I'd fall back to "try and find an unambiguous method signature with the same name", which would have picked up your local version.

But that's not a general solution; it's legitimately possible for another spec to define an argument-less method with the same name as one of your locals, and it shouldn't link that if any of the locals could work.  I'll fix it to try and find a local version first.

**Comment by tabatkins** [comment]
All right, should be all fixed! I'd been meaning to refactor the code around this anyway, so this was a great opportunity to get that done.  This should now not only work correctly for your case (look for local unambiguous arg-full method signatures when you do an arg-less method autolink, even if an arg-less method of the same name exists in the linking database), but also be substantially faster for heavy usage of the feature, as I've got a dedicated data structure to use for it.

Now to copy that for my code that searches for things according to their "for" value...
