### ISSUE TITLE
Blatantly copy ReSpec's inlining of GitHub Issues

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#415]
<https://github.com/w3c/respec/pull/443>

Coding is now done, just gotta update the docs accordingly.

**Comment by tabatkins** [comment]
DONE.

To activate, either work on your spec from within a GitHub repo, or specify the repo in a `Repository` metadata, or just use a github-style reference of the form `user/repo#issuenum`, and also specify the `Inline Github Issues` metadata.  Now, any remote github issues will have the live github issue contents inlined instead.

To create a remote issue, you can use a GitHub-style reference, like this:

```
foo foo foo

Issue(tabatkins/bikeshed#415):

bar bar bar
```

(Text after the colon is optional; if specified, it's used as a fallback for when you generate without internet, or if there is anything else making GH unreachable.  The final colon *is* required, though.)

Or, if your repo is recognized as a GH repo (either because you're working within a git repo with its origin set to a github url, or because you've manually set the `Repository` metadata to a GH url or GH-style reference), simple numeric references will work, like `Issue(415):`

**Comment by tabatkins** [comment]
When `Inline Github Issues` is specified, should I also put all the open issues into an appendix? @domenic @mikewest @annevk

**Comment by annevk** [comment]
Makes sense I guess. Kind of nice to have the open issues record for living standards inline.

**Comment by domenic** [comment]
-1 for an appendix of open issues. That appendix (in a more complete form) is just the GitHub issue list.

**Comment by tabatkins** [comment]
Good point. Compromise: when I can detect you're in a GH repo, I'll add it to the Issue Tracking metadata automatically.

**Comment by tabatkins** [comment]
Done. It's possible this'll cause duplicate entries in your spec headers; please adjust accordingly as you notice.

**Comment by annevk** [comment]
Hmm, is there a way to opt out of that? I don't want Bikeshed to mess with my header.

**Comment by tabatkins** [comment]
Hm, I guess so.  This does mess up the DOM header, with its manually-constructed pretty feedback line.  Let's see, guess I can activate this as `Boilerplate: automatic-feedback no`.  I'll have it pushed shortly.

**Comment by tabatkins** [comment]
And done. Update DOM's metadata to `Boilerplate: omit conformance, omit feedback-header` and it'll avoid generating new header stuff.

**Comment by annevk** [comment]
Hmm, this is not exactly pleasing as all WHATWG specifications would likely need that. Unless this was formatted in the way WHATWG specifications are currently formatted. Should we perhaps have some different kind of abstraction here that is more portable?

**Comment by domenic** [comment]
I think we can just add it to the base whatwg header

**Comment by tabatkins** [comment]
Rather, add it to `defaults-whatwg.include`.
