### ISSUE TITLE
FATAL ERROR: Couldn't retrieve the file 'methods.json' from cache.

### ISSUE THREAD

**Issue by Cwiiis** [tabatkins/bikeshed#417]
When I run bikeshed on a file, I get:

FATAL ERROR: Couldn't retrieve the file 'methods.json' from cache. Something's wrong, please report this.

It says to report it, so I am. I followed the installation instructions on github. I'm running a 64-bit Fedora 22 system. The contents of the file I'm running bikeshed on:

<pre class='metadata'>
Title: Web Navigation Transitions
Status: ED
ED: http://chrislord.net/files/mozilla/gaia-navigator/spec/
Shortname: nav-trans
Level: 1
Editor: Chris Lord, Mozilla, clord@mozilla.com
Abstract: This specification describes an application programming interface that allows animations to be performed between page navigations, requiring only CSS.
</pre>

<h2>Introduction</h2>

Web Navigation Transitions defines an interface and behaviour that allows animations to be performed when the user agent navigates from one location to another. This animation can involve both the existing document and the new document, allowing for transitions that visually involve both documents simultaneously.

**Comment by Cwiiis** [comment]
So Anne helped me out here, turns out that after installation, you *must* run 'bikeshed update'. This should probably be mentioned in the installation instructions, but closing this.

**Comment by tabatkins** [comment]
Ah, actually I should update the boilerplate files (so you don't need to run update) *and* update the install guide to recommend you run update.  Thanks for the report. ^_^
