### ISSUE TITLE
Opaque elements still tries to autolink

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#425]
With an `emu-alg` opaque element, an code like

```html
<emu-alg>
1. Do stuff to [[underlyingSource]]
</emu-alg>
```

I still get

```
FATAL ERROR: Couldn't find 'underlyingSource' in bibliography data. Did you mean:
```

whereas with `<pre>` I do not.

**Comment by tabatkins** [comment]
Ah, I'm not using the `Opaque Elements` stuff in enough places.  I'll refactor so everything relies on a common data source.

**Comment by tabatkins** [comment]
Fixed.
