### ISSUE TITLE
Handle obsolete biblios too

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#427]
Tobie just added obsoletion information to SpecRef in https://github.com/tobie/specref/pull/199.

Specs can now have an "obsoletes" key (pointing to the spec they're obsoleting) and/or an "obsoletedBy" key, pointing to the spec that obsoleted them.

I should throw a fatal error when someone tries to biblio-ref an obsolete spec, and tell them which spec to change their reference to.

**Comment by frivoal** [comment]
+1 on the need to support that feature, and on the way you propose to handle it. Any chance it would happen before long, or should I learn some python and try and figure out how to make that happen myself?

**Comment by tabatkins** [comment]
Ah, this just slipped down my prio list. Shouldn't be difficult to do.

**Comment by tabatkins** [comment]
And done.
