### ISSUE TITLE
Keep original <h1> element around, for attributes/markup

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#431]
<https://lists.w3.org/Archives/Public/spec-prod/2015JulSep/0006.html>

**Comment by r12a** [comment]
a compromise may be to take the h1 element from the source if the author provides one, otherwise use the title element

**Comment by tabatkins** [comment]
You don't write `<title>` elements in Bikeshed source anyway; you use `Title:` metadata in your metadata block.  But yeah, that's my plan.

(Right now, Bikeshed looks for a `Title:` metadata; failing that, looks for an `<h1>` and slurps its text. I plan to just make it slurp and preserve the entire element in that case.)

**Comment by tabatkins** [comment]
So, a bit late, but done now. ^_^

If you provide an H1 and don't set a `Title` metadata, it'll use the actual H1 you provide.
