### ISSUE TITLE
<pre><code> is styled wrong now

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#432]
Since the switch to Pygments, I think, my `<pre><code class="lang-javascript">...</code></pre>` blocks are no longer appearing as blocks. See e.g. https://streams.spec.whatwg.org/#example-ws-no-backpressure

According to https://github.com/tabatkins/bikeshed/commit/38306691c4e2a72575e3267e63403060057b6c9e#diff-b524bc5bdf612b1b6704a8719355e4b1L1 the old Prism stylesheet used to block-ify any highlighted `<code>` elements. I'm not sure what the best solution is here for Bikeshed, especially since Bikeshed doesn't seem to care about the `<pre>` part of that pattern. (Or at least doesn't anymore?) But since this is somewhat of a Bikeshed regression I thought you should know.

If the answer is that I should update my own stylesheet to block-ify code, or add a matching background to pre, that's reasonable too.

**Comment by tabatkins** [comment]
Fixed now, sorry about that.

**Comment by domenic** [comment]
:+1: https://streams.spec.whatwg.org/#example-ws-no-backpressure
