### ISSUE TITLE
Blank initial list element line requires too much space

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#435]
```
<pre class='metadata'>
Title: Test
Status: ED
ED: https://example.com/
Shortname: test
Level: 1
Abstract:
Editor:
</pre>

1. List
2.
   More list
```

complains that:
```
FATAL ERROR: Line 3 isn't indented enough (needs 1 indent) to be valid Markdown:
"   More list"
```

However, http://spec.commonmark.org/0.21/#list-items rule 3 says the content of the list only needs to be indented by {width-of-marker} + 1 spaces, which this is.

**Comment by tabatkins** [comment]
Yeah, I'm not (yet) supporting CommonMark properly.  You should be using tabs, anyway.  ^_^

I'll close this, as it's subsumed by #213.

**Comment by jyasskin** [comment]
Hm, continuation lines have the same problem. So, abandon markdown for lists, for now?

**Comment by tabatkins** [comment]
No, just either indent with a tab, or the number of spaces that qualify as an indent (default is 4, can be altered with an `Indent: <int>` metadata).
