### ISSUE TITLE
Incorrect line numbers in error messages

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#436]
```
<pre class='metadata'>
Title: Test
Status: ED
ED: https://example.com/
Shortname: test
Level: 1
Abstract:
Editor:
</pre>

1. List
2.
   More list
```

complains that:

```
FATAL ERROR: Line 3 isn't indented enough (needs 1 indent) to be valid Markdown:
"   More list"
```

However, "   More list" isn't on line 3; it's on line 13.

**Comment by tabatkins** [comment]
This is going to be more difficult than I thought.  The line numbers get screwed up by both metadata, *and* any other data blocks like `<pre class=anchors>` or `<pre class=propdef>`.  Hm, maybe I can insert markers into the stream whenever I remove/replace some lines and keep track of that as the markdown processor goes over the code...

**Comment by tabatkins** [comment]
Looks like it's right now.  Let me know if there are any off-by-one errors.
