### ISSUE TITLE
Ability to use headings to define things

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#438]
Specs like streams, ES, and [this new thing I'm working on](https://domenic.github.io/streaming-mediastreams/) define both public APIs and abstract operations underneath headings. It would be ideal to be able to define these APIs as pointing to their headings.

Right now the closest I can get (for e.g. the latter spec) is

```html
<h3 id="msr-constructor">
  <dfn constructor for="MediaStreamRecorder" lt="MediaStreamRecorder(stream)|MediaStreamRecorder(stream, options)">
    new MediaStreamRecorder(stream, options)
  </dfn>
</h3>
```

This nested dfn-inside-h3 breaks in a few ways. The biggest is that it auto-generates a new ID, much uglier than the msr-constructor one I created, and thus a new self-link hover.

Ideally I could just mark up the h3 itself as being a definition. I tried

```html
<h3 id="msr-constructor" dfn-type="constructor" dfn-for="MediaStreamRecorder" dfn-lt="MediaStreamRecorder(stream)|MediaStreamRecorder(stream, options)">
    new MediaStreamRecorder(stream, options)
</h3>
```

but this did not work.

**Comment by tabatkins** [comment]
This *should* work now.  As far as Bikeshed is concerned, it's all good.  @plinss tells me that Shepherd is already ready to handle this, and will file them correctly as the right anchor type in his API.

**Comment by domenic** [comment]
To be clear, it's the latter syntax that should work now (with dfn-type and dfn-for and dfn-lt)? Did I get it right? If so I'll give it a try.

**Comment by tabatkins** [comment]
Yes, but better - just treat it exactly like a normal <dfn>: `<h2 interface>TheFooInterface</h2>`, etc.

**Comment by domenic** [comment]
Cool! This is the syntax that ended up working:

```html
<h3 id="msr-constructor"
    constructor
    dfn-for="MediaStreamRecorder"
    lt="MediaStreamRecorder(stream, options)|MediaStreamRecorder(stream)">
  new MediaStreamRecorder(stream, options)
</h3>
```

(using for="" instead of dfn-for="" gave an error saying that I needed to use for="" or use dfn-for="" on an ancestor :-/)

**Comment by tabatkins** [comment]
Ah, that'd be a bug. I'll find and fix.
