### ISSUE TITLE
`bikeshed watch` only shows errors the first time around

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#439]
Create `test.bs`:
```
<pre class='metadata'>
Title: Test
Status: ED
ED: https://example.com/
Shortname: test
Level: 1
Abstract:
Editor:
</pre>

<pre class="idl">
interface Int {
  readonly attribute long? service;
  readonly attribute ArrayBuffer? value;
  readonly attribute ArrayBuffer value2;
  attribute ArrayBuffer? value3;
};
</pre>
```
Then run `bikeshed watch test.bs`. Once it finishes building, remove the `value3` line and save. You'll get the output:

```
$ bikeshed watch test.bs
FATAL ERROR: IDL SYNTAX ERROR LINE: 3 - skipped: "readonly attribute ArrayBuffer? value"

FATAL ERROR: IDL SYNTAX ERROR LINE: 5 - skipped: "attribute ArrayBuffer? value3"

==============DONE==============
Source file modified at 15:31:43. Rebuilding...
==============DONE==============
```

which doesn't show the remaining error on the second build.

**Comment by tabatkins** [comment]
Whoops, forgot that I dedup warnings/errors, so you don't get tons of spam messages from a single mistake throughout the doc.  I'm now resetting the cache between watch runs, so it should work.

**Comment by tabatkins** [comment]
Fixed now for real. Python's scoping semantics are confusing; *using* a variable from outside the closure is fine, but *assigning* to one creates a new local variable instead.

(Also those WebIDL errors are fixed now.)
