### ISSUE TITLE
Provide a shorter linking syntax within <pre highlight=js> blocks

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#442]
The Web Bluetooth spec has some example blocks that want to link to the called functions. Currently, it looks like the shortest way to do this is:

``` html
<pre highlight="js">
navigator.bluetooth.<a method for="Bluetooth" lt="requestDevice()">requestDevice</a>({
  filters: [{
    services: ['heart_rate'],
  }]
}).then(...);
</pre>
```

ReSpec allowed:

``` html
<pre highlight="js">
navigator.bluetooth.<a for="Bluetooth">requestDevice</a>({
...
</pre>
```

`{{Bluetooth/requestDevice}}` syntax is probably not plausible inside a `<pre>`, but maybe you could infer the `idl` link type for JS code and allow `()`-less link text for functions.

**Comment by tabatkins** [comment]
And done. You can now use the magical `<l>` element to use the autolinking shorthands *anywhere*. So you'd write:

```
<pre highlight=js>
navigator.bluetooth.<l>{{Bluetooth/requestDevice()|requestDevice}}</l>({
...
</pre>
```
(Since methods and attributes live in the same namespace, I should add a conjugation that allows leaving off the parentheses. I'll fix that next.)

**Comment by tabatkins** [comment]
And there we go, now you can just write:

```
<pre highlight=js>
navigator.bluetooth.<l>{{Bluetooth/requestDevice}}</l>({
...
</pre>
```
