### ISSUE TITLE
Inline GitHub issue headings are confusing

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#444]
See e.g. https://domenic.github.io/streaming-mediastreams/, where the heading reads

```
ISSUE 1 Issue #5 on GitHub: “Blobs vs. ArrayBuffers”
```

I would much prefer the heading to read

```
ISSUE #5: Blobs vs. ArrayBuffers
```

and for the whole heading to be a link.

**Comment by tabatkins** [comment]
This is actually already intended; if you check the source, you'll note there's a `.no-marker` on the issue container.  I just haven't updated the default stylesheet to take that into account yet.  I'll do that real quick.

**Comment by tabatkins** [comment]
And the styles have been pushed.
