### ISSUE TITLE
Can I turn off the inline issues index without a custom boilerplate?

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#445]
The answer might be "no" which is fine. But https://domenic.github.io/streaming-mediastreams/ has an issue index which I don't like having around.

**Comment by tabatkins** [comment]
It can be omitted with `Boilerplate: omit issues-index`.

But that section is helpful to both readers and reviewers.  Why don't you want it?

**Comment by domenic** [comment]
Because it literally duplicates the open issues link at the top.

**Comment by domenic** [comment]
That gives

```
←[1;31mFATAL ERROR:←[0m Couldn't find target anchor issues-index:
<a href="#issues-index">Inline In Spec</a>
```

**Comment by domenic** [comment]
Wait, my bad, it works when I merge it with my previous `Boilerplate:` line. Sorry for the noise.

**Comment by tabatkins** [comment]
Actually that's still an error on my part, but I'm glad your other metadata was able to mask the error. ^_^
