### ISSUE TITLE
Inside "Terms defined by this specification", introduce some nesting

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#446]
The most important nesting for me is nesting argument names underneath the constructor or method that defines them, to get them out of the top level.

You can also imagine:

- dictionary members underneath their dictionary
- values underneath their properties
- attributes underneath their interface?
- methods underneath their interface?
- constructors underneath their interface?

**Comment by tabatkins** [comment]
The problem I have with your request is the implication that nesting them under their "for" value would remove them from the top level.  That generally harms the concept of an index, which is to make it easy to look up a particular term - if you know something's name, you can just look it up in alphabetical order and find where it's defined.  If it might instead be nested under something else, in a completely different spot in the index, that task is much more difficult.

I'm happy to have them show up nested *as well as* at the top-level, tho.  Would that be okay?

**Comment by domenic** [comment]
To me the main problem is that I never want to look up argument names in an index. They aren't terms defined by this specification; they're just variable names used internally in some algorithms. I can see what you mean for the rest of my suggestions, but for argument names I would really rather just remove them entirely from the index, if I can't nest them.

**Comment by tabatkins** [comment]
I'm probably okay with just nesting argument names, as they're rarely that important.

**Comment by domenic** [comment]
I'd still like an option to remove them actually, the more I think about this.

**Comment by tabatkins** [comment]
After some thinking, yeah, I'll just drop arguments entirely. They're of amazingly minimal value in an index.

**Comment by tabatkins** [comment]
All right, fixed. Arguments no longer show up in the index. You can look in the IDL index if you care about them.

**Comment by domenic** [comment]
Yay, thanks!
