### ISSUE TITLE
Syntax-highlight and maybe format IDL blocks

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#449]
ReSpec's IDL presentation looks nicer than Bikeshed's:

<img width="865" alt="ReSpec formatting for BluetoothGATTCharacteristic" src="https://cloud.githubusercontent.com/assets/83420/9072614/1735d9f2-3ab1-11e5-826f-fc997f5a6fcd.png">

vs

<img width="810" alt="Bikeshed formatting for BluetoothGATTCharacteristic" src="https://cloud.githubusercontent.com/assets/83420/9072595/f9face42-3ab0-11e5-82b2-eb0e5ab0b7c0.png">

Bikeshed's line wrapping is better, but it'd be easier to read the blocks with some color.

**Comment by tabatkins** [comment]
Syntax-highlighting now automatically applies to WebIDL!
