### ISSUE TITLE
Figure out how to syntax-highlight code containing links

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#451]
Switching from ReSpec to Bikeshed loses this highlighting. For example:

ReSpec: <img width="511" alt="ReSpec highlighting a linked example" src="https://cloud.githubusercontent.com/assets/83420/9075442/a1518d8a-3ac9-11e5-9146-3b3cd748d9df.png">

vs

Bikeshed: <img width="539" alt="Bikeshed failing to highlight a linked example" src="https://cloud.githubusercontent.com/assets/83420/9075448/b264aca6-3ac9-11e5-8787-c9e15cbc27cf.png">

**Comment by tabatkins** [comment]
Okay, I discovered how respec is doing this; it's a supported feature of Highlight.js at <https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L162>. Clever implementation, but it requires support deep in the highlighting system, and Pygments doesn't provide this.

I should see if it's possible to somehow make this work, but I'm not optimistic there's an easy implementation.  Best thing I can imagine right now is doing a char-by-char walk of the original element contents and the highlighted contents, matching things up appropriately and merging the two trees.

Now that I write that down, it doesn't sound as crazy as it did at first.  I think I'm guaranteed that the raw text is identical pre and post highlighting, so this should actually work pretty well.  I'd just have to deal with highlight elements getting split across original-markup tag boundaries.

**Comment by tabatkins** [comment]
And done. Was way easier and elegant than I thought it would be, just a single screen-worth of easy-to-follow code.  Highlighting now always works, even on elements with internal structure!
