### ISSUE TITLE
Broken References lists in Fonts spec

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#454]
https://drafts.csswg.org/css-fonts/Overview.html#references vs  https://drafts.csswg.org/css-fonts/#references

Specs that are missing authors, etc. Those two should end up identical.

**Comment by tabatkins** [comment]
...huh.  Those specs don't have authors *in our biblio.ref file*.  I wonder what data source Fonts was pulling from?

Anyway, putting together a PR for SpecRef to add better versions of these.

**Comment by tabatkins** [comment]
Oh, never mind, they don't have authors in Fonts either.  I just need to stop outputting ??? when there's no author information.
