### ISSUE TITLE
Make jdaggett happy

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#455]
Issues to fix:
1. https://github.com/tabatkins/bikeshed/issues/452
2. https://github.com/tabatkins/bikeshed/issues/453
3. https://github.com/tabatkins/bikeshed/issues/454

These block converting Fonts to bikeshed.
Also, don't forget to run a text-based diff (copy-paste HTML output as text) comparison to check for errors before actually making the conversion.

**Comment by tabatkins** [comment]
Metabugs don't help.
