### ISSUE TITLE
Invisible self-link produced for <div class=note id=foo>

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#456]
```html
<pre class='metadata'>
Title: Test
Status: ED
ED: https://example.com/
Shortname: test
Level: 1
Abstract:
Editor:
</pre>

<div class=note id=my-id>
  Note
</div>
<p id="my-p">Para</p>
<ol><li id="my-li">List Item</li></ol>
```

produces:

![Missing self-link from <div class=note>](https://cloud.githubusercontent.com/assets/83420/9098545/6ece18c2-3b7f-11e5-9160-2bd522842c19.png)

This is with Chrome 45.0.2454.15. The self-link exists, and I don't see the style that's hiding it.

**Comment by tabatkins** [comment]
Ah, I finally figured this out!  Notes have to be BFCs (or else they have bad behavior around floats), and I achieve that with `overflow: auto`.  That means that anything overflowing the element in the start directions is simply clipped away.

There's no reliable way to get a BFC today that doesn't clip. ;_;  If someone would implement the Display module, I could switch the styling over to just `display: flow-root` on notes and we'd be golden.

**Comment by domenic** [comment]
So if we have no plans to use floats in our specs, then we should just do `.note, .why { overflow: inherit; }` to get back our self-links?

**Comment by tabatkins** [comment]
Yeah, that'll do it.
