### ISSUE TITLE
IDL linkifier won't linkify primitives

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#458]
Per https://github.com/whatwg/fetch/issues/108#issuecomment-130358134 I tried to add external definitions for the IDL primitives: https://github.com/domenic/streaming-mediastreams/commit/16a2ad09ec0172568b390b9ba327e4d6a697c011 However the output did not link to those primitives in the IDL block (like it does for MediaStream).

**Comment by annevk** [comment]
It seems you already filed the issue to get USVString and all linked. @tabatkins in the linked issue you state that the holdup is IDL not being done in Bikeshed. That appears to be done now. What are the next steps?

**Comment by tabatkins** [comment]
Hmm, this is gonna be tricky. Currently all the primitive types are emitted with each of their words as a separate Keyword token. I'll bug @plinss first, as I can't figure out widlparser enough to fix it myself. If that doesn't work, I'll see about merging the keywords after-the-fact into an autolink.

**Comment by tabatkins** [comment]
Issue filed <https://github.com/plinss/widlparser/issues/20>

**Comment by tabatkins** [comment]
Oh, this works now. Closing.
