### ISSUE TITLE
Duplicate references

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#461]
URL Standard now references [DOM] and [DOM-LS]. The latter because of a `<a spec=dom>` type reference.

* https://url.spec.whatwg.org/#normative

That seems broken. The DOM-LS reference also seems out-of-date as it does not use HTTPS.

**Comment by annevk** [comment]
It seems this is partially caused by https://github.com/tabatkins/bikeshed/blob/ff608218bc3f691cb4b7156437164068b8cd086d/bikeshed/spec-data/readonly/specs.json#L358 which I could change, but I'm not sure what it's for.

**Comment by annevk** [comment]
For instance, I don't understand why that file doesn't contain other specifications, such as URL.

**Comment by tabatkins** [comment]
I dropped the `-LS` from the spec name in Shepherd. This should hopefully merge the refs once it updates (give it a few minutes).
