### ISSUE TITLE
Spurious whitespace changes after recent changes

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#464]
Suspected changes:
https://github.com/tabatkins/bikeshed/commit/e0ea89ef9697e90775817c2ef0fb8666b63e9a67
https://github.com/tabatkins/bikeshed/commit/22dbe3b8e635c56042a9209d483e381f377607b7

If you take https://github.com/whatwg/mediasession/blob/6d0b21bb44bf775386622099bab8eecf819b7f9f/mediasession.html as input, the ouput will contain extra spaces before some commas and around other punctuation.

**Comment by tabatkins** [comment]
Yeah, I was doing bad things.  Should be generally fixed. I think I still have some whitespace wrong, but at least there's no longer WS added after/around punctuation.

**Comment by foolip** [comment]
There are still some things broken. If you take the same input above, you will find that whitespace has been removed in some places where it definitely belongs, the first instance of which is "active Default" becoming "activeDefault" and many similar cases where whitespace between two elements that is needed has been removed.

**Comment by foolip** [comment]
To sanity-check the output, I'm using a worddiff.py tool that I wrote for completely other purposes some time ago:
https://github.com/foolip/epubbase/blob/master/worddiff.py
