### ISSUE TITLE
<whitespace-token> rendered as an element.

### ISSUE THREAD

**Issue by SimonSapin** [tabatkins/bikeshed#465]
https://drafts.csswg.org/css-syntax/ is all broken.

**Comment by SimonSapin** [comment]
https://drafts.csswg.org/css-syntax/#consume-list-of-declarations currently renders as:

![screenshot from 2015-08-24 21-26-07](https://cloud.githubusercontent.com/assets/291359/9450058/c0b47f1a-4aa6-11e5-8099-1451427e3a5c.png)

The generated HTML contains:

```html
   <dl>
    <dt><a class="production css" data-link-type="type" href="#typedef-whitespace-token"><whitespace-token></a>
    <dt><a class="production css" data-link-type="type" href="#typedef-semicolon-token"><semicolon-token></a>
    <dd>Do nothing.
```

`<whitespace-token>` should be at least `&lt;whitespace-token>`.

**Comment by tabatkins** [comment]
Fixed, sorry about that.

(Problem with rewriting is that you lose the accumulated bugfixes! Grr)
