### ISSUE TITLE
Too much whitespace is removed

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#467]
I can't reopen https://github.com/tabatkins/bikeshed/issues/464, so to make sure this isn't lost:

If you take https://github.com/whatwg/mediasession/blob/3e9c8e39689ac944968914f87dc581c09380b27c/mediasession.html as input, the ouput will have too much whitespace stripped in a few places, the first instance of which is "active Default" becoming "activeDefault".

**Comment by astearns** [comment]
This is also happening in propdef tables (not sure if this is a separate bug). in https://drafts.csswg.org/css-flexbox/#flex-basis-property, "content | <<'width'>>" gets output as "content |<‘width’>" (with no space between '|' and '<'. Another example: https://drafts.csswg.org/css-shapes-2/#shape-inside-property
Keeping the spaces around the syntax operators makes value strings much more readable.

**Comment by tabatkins** [comment]
Yes, it's all the same bug - whitespace-only text nodes between elements are getting dropped.  For some reason, my attempts at fixing this so far are resulting in extraneous newlines being retained as well.  Work continues.

**Comment by foolip** [comment]
Thanks for working to fix this! In the future, if big breakage like this happens for https://api.csswg.org/bikeshed/ it would be nice if the changes were reverted pending a fix, as it's now been a few days in which editing the Media Session spec has required a local copy with reverts, and I advised @doomdavve to just not try any edits until this had been fixed.

**Comment by tabatkins** [comment]
Yeah, I probably should have done that.  Sorry for the inconvenience.  Had this happened any other week it would have been fixed *much* faster; unfortunately I'm in the middle of the CSSWG f2f.

**Comment by foolip** [comment]
No worries, it's been only a minor inconvenience :)

**Comment by fantasai** [comment]
The space between markup like 'box-sizing' [[CSS3UI]] is also getting collapsed.

**Comment by tabatkins** [comment]
Everything *should* be good now.  I'm still aggressively removing whitespace, I'm just doing it less aggressively now. ^_^

To be specific, I was *trying* to just remove excess WS between sibling block elements, and at the beginning/end of an element's content.  I accidentally removed *all* WS-only text nodes, causing the issues y'all saw.

Fix was to group text/inlines into anonymous blocks, and then kill any WS-only anonymous blocks. That way between-inlines WS was preserved.

If you have any remaining issues, let me know!

**Comment by foolip** [comment]
Thanks, everything looks good to me now!
