### ISSUE TITLE
Adds "Issue Tracking" with wrong GitHub repository

### ISSUE THREAD

**Issue by johnmellor** [tabatkins/bikeshed#470]
Since commit https://github.com/tabatkins/bikeshed/commit/6bd2a6aac4d5279e67a2136001d4874588c9b8d4 "When Repository is a GH repo, add it to the Issue Tracking metadata.", if I run bikeshed on my fork of [whatwg/notifications](https://github.com/whatwg/notifications/blob/master/notifications.bs) in order to create a pull request, it adds the following HTML:
```html
+     <dt>Issue Tracking:
+     <dd><a href="https://github.com/johnmellor/notifications/issues/">GitHub</a>
```

But this is the wrong URL! It should be `https://github.com/whatwg/notifications/issues`.

It also creates an inconsistency between using https://api.csswg.org/bikeshed/ (which doesn't know about git) and running bikeshed locally.

Based on these two problems, it seems it might be better to go back to explicitly listing these links in the metadata section (indeed the [notifications spec](https://github.com/whatwg/notifications/blob/master/notifications.bs) already has a `!Participate` section with this link).

@annevk @beverloo FYI

**Comment by tabatkins** [comment]
You can specify the repository manually with the `Repository` metadata, if you're running things in a way that produces inconsistent results.

**Comment by johnmellor** [comment]
Is there a way to disable this auto-generated Issue Tracking section and just show the custom `!Participate` one?

**Comment by tabatkins** [comment]
Yeah, you can add `Boilerplate: omit feedback-header` to the metadata.

(But you still want a `Repository: whatwg/notifications` entry too, if you ever plan to take advantage of inline GH issues.)
