### ISSUE TITLE
No style for class="issue"

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#476]
https://mediasession.spec.whatwg.org/#interrupting-a-media-session

Here the "The interruption may not come from another media session at all.  <https://github.com/whatwg/mediasession/issues/100>" bit has no styling at all.

Something like the style for class="note" would be nice.

CC @doomdavve

**Comment by tabatkins** [comment]
Ping @domenic @annevk, as this is a matter for their boilerplate's styling.

**Comment by annevk** [comment]
So we use `class=XXX` for issues within the WHATWG.

**Comment by tabatkins** [comment]
I was wondering about that...

Well, that just means no use of the `Issue: ` shorthand for producing issue paragraphs.  Or WHATWG can conform to Bikeshed's implicit styling decisions. Either one works for me.

**Comment by annevk** [comment]
There's no organization context available when you output the class? Shouldn't be too hard to make it a variable of sorts...

**Comment by tabatkins** [comment]
Hm, I suppose I could.

**Comment by tabatkins** [comment]
Okay, done, and I adjusted the WHATWG defaults to set the class to `XXX`.  Let me know if there are any problems.
