### ISSUE TITLE
Long terms are cut off in the indices

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#480]
And the hover text wraps into the next item:
<img width="870" alt="Screenshot showing terms like MissingServiceGenericAccessDevice and org.bluetooth.characteristic.device_name cut off by column boundaries" src="https://cloud.githubusercontent.com/assets/83420/9690215/db742bf6-52ef-11e5-8f18-0219036eb209.png">
That's from https://github.com/WebBluetoothCG/web-bluetooth/pull/157.

**Comment by tabatkins** [comment]
I did some experimentation, and just pushed a slight styling change that should help with this. The `<li>`s should now have `word-break:break-word`, which (at least in Chrome, where I tested it) will do emergency-breaking when a word can't help but overflow.

That keeps the words entirely visible (tho arbitrarily broken across lines), and prevents the hover text from wrapping to the next line.

**Comment by jyasskin** [comment]
Now the hover text gets cut off when it crosses the line boundary:
![Screenshot showing ", in §4.1.8" still cut off](https://cloud.githubusercontent.com/assets/83420/9694411/4d8dd7e2-530d-11e5-9823-44781738cf7c.png)

**Comment by tabatkins** [comment]
Yeah, that'll happen.  Columns always clip.  And we have to abspos, or else the layout jiggles when some items are hovered.  Not a ton I can do about that, unfortunately. :/
