### ISSUE TITLE
bikeshed seems to convert &nbsp; into regular space

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#482]
See css-ui-4 for an example. In the example about a phosphor screen, there is a `<span>&nbsp;</span>` that gets turned into a `<span> </span>`.

I've worked around that in this particular spec by changing the style of that element to whitespace:pre, but this is probably causing silent failures elsewhere.

**Comment by tabatkins** [comment]
Okay, confirmed that it's emitting a U+20 space.  I'm not sure *why* it's doing so, though. :/

**Comment by tabatkins** [comment]
Ohhhhh, I know what's happening.

When serializing, I simplify whitespace to a single space, to make the output prettier and more compact.  Python apparently (correctly) recognizes nbsp as whitespace.  So, if an nbsp is an element's only content, it'll get stripped/replaced with a single space.

You can see this bug *not* triggering if you put the nbsp between two non-WS chars; it'll be preserved then.

I'll fix; I only *intend* to be stripping off spaces, tabs, and newlines.
