### ISSUE TITLE
FATAL ERROR: This version of the anchor-data API is no longer supported. Please update Bikeshed.

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#484]
What I did:
```
$ bikeshed update
Downloading anchor data...
FATAL ERROR: This version of the anchor-data API is no longer supported. Please update Bikeshed.
```

This is after updating to the most recent Bikeshed manually using git pull in the repo. There's a long delay before the error, so I half suspect that this is a network timeout that isn't getting reported as such.

**Comment by tabatkins** [comment]
I just updated, and it got through fine, so yeah, probably a network timeout.  Looking at the code, not getting a resource at all will trigger that error message.

The Shepherd server was down for a bit this morning, so that's probably what it was.

**Comment by foolip** [comment]
Would it be hard to report it as a network error instead of suggesting to update?

**Comment by tabatkins** [comment]
Nah it wouldn't; I suspect that if I don't get a resource at all, it's probably always a network error.

**Comment by foolip** [comment]
Do you want a new feature request, or is this issue fine as it is?

**Comment by kba** [comment]
If the apiclient fails for any reason, the exception is [silenced and `None` is returned](https://github.com/tabatkins/bikeshed/blob/master/bikeshed/apiclient/apiclient/apiclient.py#L231-L233). The 406 error is a red herring here. In my case it was missing SSL certificates.
