### ISSUE TITLE
Examples in WHATWG specs get a blue ¶ on top of the "Example" label

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#485]
![Screenshot](http://i.imgur.com/TbBPTEC.png)

If this is because of the WHATWG stylesheet, maybe @annevk knows what should be done?

**Comment by annevk** [comment]
I don't see it?

**Comment by foolip** [comment]
Open the image in full size and look at the top right of the E in the tilted Example label.

**Comment by foolip** [comment]
I'm guessing there's some CSS that puts the ¶ a bit to the left at the top of the box, that doesn't know about the other CSS that adds the label in the same place.

**Comment by tabatkins** [comment]
Yeah, this is due to some code in the bikeshed.css file that WHATWG specs use.  Nothing to do with Bikeshed itself.
