### ISSUE TITLE
Normalize entries in propdef/etc tables to have the right casing

### ISSUE THREAD

**Issue by astearns** [tabatkins/bikeshed#486]
Sebastian Zartner notices that the css-shapes propdef tables had duplicated entries - it looks like bikeshed isn't noticing "Computed Value" because of the capital 'V'.

I fixed shapes level 1, but it's a problem in my other specs as well. Should I change those too, or could bikeshed accept (and normalize) propdef entry capitalizations?

**Comment by tabatkins** [comment]
Bikeshed should normalize.  I'll fix.
