### ISSUE TITLE
Auto-generated values link is broken

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#487]
(Look in Flexbox for an example.)

Tab, what's broken is
`<a data-link-type="biblio" href="#biblio-css-values-3">[css-values]</a> defines the following terms:`
You're removing the -3 from all instances for this spec, which I agree is a good idea for value type/combinator autolinks. But you're forgetting to remove it from this biblio reference, so it ends up being a broken fragment. (Generated as WD.)

**Comment by tabatkins** [comment]
Fixed.
