### ISSUE TITLE
'font-style' and 'font-weight' warning can't be muted

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#491]
https://github.com/whatwg/webvtt/pull/213

For 'font-style' and 'font-weight' I get this warning:

```
WARNING: Multiple possible 'propdesc' refs for 'font-style'.
Arbitrarily chose the one in css-fonts-3.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:css-fonts-3; type:property; text:font-style
spec:css-fonts-3; type:descriptor; text:font-style
WARNING: Multiple possible 'propdesc' refs for 'font-weight'.
Arbitrarily chose the one in css-fonts-3.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:css-fonts-3; type:property; text:font-weight
spec:css-fonts-3; type:descriptor; text:font-weight
```

Adding the type:property line to link-defaults does not make the warning go away.

**Comment by tabatkins** [comment]
How strange, that should definitely work.  (I just dealt with a similar issue for 'color', which is both a property and an MQ descriptor, and link defaults worked.)  I'll look into it.

**Comment by tabatkins** [comment]
And fixed.  Sorry about that, I hadn't properly considered the case where the link type is wider than the specified link-default type.  (So, in this case, the "propdesc" link type was maintained, rather than being specialized to "property" per the link default.)

**Comment by zcorpan** [comment]
Thanks!
