### ISSUE TITLE
 Enable inlining external resources

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#496]
Respec has support for this through the [`data-include` attribute](https://www.w3.org/respec/ref.html#data-include).

I'm using it to [include](https://github.com/w3c/sensors/blob/e7ed4f1/usecases.html#L89) [code samples](https://github.com/w3c/sensors/blob/e7ed4f1/examples/realtime-positioning/index.js) of Web apps within the use case doc for the Generic Sensor API.

**Comment by tabatkins** [comment]
You only need local, right?  This should be pretty easy.

**Comment by tabatkins** [comment]
Okay, v1 of inclusions are in.  I"ll document it when I'm more finished, but for now just use an `<include path='...'></include>` element.  It assumes the target document is ordinary HTML at the moment (it doesn't do Markdown or data-block expansion), but that will change.  Recursive includes are allowed, and cycles are detected.

Replacement is done very early, immediately after the document is parsed as HTML, so all the other features of Bikeshed (besides data-blocks and Markdown) work as expected in the includes.

**Comment by tobie** [comment]
Thanks!

I'll port my use case doc to it and let you know how it goes.

**Comment by tabatkins** [comment]
And all done - markdown and datablocks are now processed.  And the bug that makes the top-level elements in an inclusion be inserted backwards is fixed. ^_^
