### ISSUE TITLE
Shortcut syntax for `<var>x</var>`.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#501]
I use `<var>whatever</var>` all over algorithms in my specs. I'd like to:

1. Stop typing `<var></var>`.
2. Catch typos.

How would you feel about some sort of inline markup for `<var></var>`, and a warning if some text contained within such markup was only used once?

I'm thinking pipes, to match Chromium comment style (e.g. "Let |thing| be `false`." --> "Let <var>thing</var> be <code>false</code>."

**Comment by tabatkins** [comment]
This sounds good!

In my previous thoughts about this, I was thinking of scoping vars somehow - some attribute that declares an "algorithm" scope.  I suppose that can be deferred until later.

One wrinkle: should *all* `<var>` trigger this? I don't let the shorthands have magic powers, they have to desugar into some markup. Do we need to have some attr on `<var>` that triggers this checking?

**Comment by tabatkins** [comment]
Also: any use for auto-linking? Some way of declaring that one usage of the var is the "definition" of it, and link the other uses to it?

**Comment by mikewest** [comment]
I'd use auto linking, yes. If you think up a reasonable syntax, I'll use
it. :)

I'm not sure if all var usage should trigger this. I'd need to check my
specs. I'd bet on yes, though.

**Comment by tabatkins** [comment]
Okay, turned on the `|foo|` shorthand. Haven't turned on error-checking yet.

**Comment by frivoal** [comment]
Please revert this change. The |foo| syntax is causing lots of problems, for example, the css-text spec's source contains this:

```html
<table class="propdef">
        <tr>
          <th>Name:</th>
          <td><dfn>line-break</dfn></td>
        </tr>
        <tr>
          <th><a href="#values">Value</a>:
          <td>auto | loose | normal | strict</td>
```

If you don't already see the problem, This excerpt from the diff after updating bikeshed should give you a hint:
```diff
      <tr>
       <th><a href="#values">Value</a>: 
-      <td>auto | loose | normal | strict
+      <td>auto <var> loose </var> normal | strict
```

**Comment by frivoal** [comment]
(Note that I don't disagree with the feature, but we need a different syntax)

**Comment by tabatkins** [comment]
Whoops, silly me.  I can fix this without reverting, actually - it just needs the first/last character be non-space.  We always format grammars with spaces around those | characters.

**Comment by tabatkins** [comment]
And fixed. And added a test to ensure grammar doesn't break.

**Comment by tabatkins** [comment]
Okay, *basic* "you've only used this once in the document" error-handling is now in effect. Emits a warning, can be silenced with `Ignored Vars` metadata.

**Comment by tabatkins** [comment]
And now there's support for "algorithms". Put an `algorithm="foo"` on a container or a heading, and everything under it will be scoped to that algo.  Currently only used to make the "single use" detector more discriminating, and improve the error message.  Soon will scope the var usage and allow for linking to a defining var.

**Comment by frivoal** [comment]
Thanks. This reliance on spacing seems a tad fragile to me, but so far it seems to work...

**Comment by zcorpan** [comment]
In webvtt there's `<var>full dimension</var>` and later `<var>full&nbsp;dimension</var>` which is intended to be the same variable but bikeshed thinks they're different. The nbsp is there to avoid linebreaks in a math expression. Can you convert nbsp to space in the "single use" detector?

**Comment by zcorpan** [comment]
It appears conversion from `'` to `’` stopped working with | syntax:

index.bs

```diff
-   <li><p>Let <var>metadata</var>'s ...
+   <li><p>Let |metadata|'s ...
```

index.html

```diff
-       <p>Let <var>metadata</var>’s ...
+       <p>Let <var>metadata</var>'s ...
```

**Comment by tabatkins** [comment]
Yeah, I'll look into these.

**Comment by zcorpan** [comment]
I just noticed that webvtt has `<sub>` in some variables (i.e. `|value<sub>1</sub>|`), which doesn't work with this syntax. I'm happy to change those instances back to use `<var>`, just a heads up in case you want to support that in some way.

**Comment by tabatkins** [comment]
I *could*, but I'd prefer not to.  Keeping the shorthand tiny and preventing it from crossing markup reduces the chance of it accidentally over-claiming, or activating when it's not wanted.

**Comment by tabatkins** [comment]
@zcorpan And your other two issues are fixed now, too - NBSPs are folded when comparing vars, and smart quotes *should* work again on vars using the shorthand. Let me know if you run into any cases it doesn't.
