### ISSUE TITLE
Update Windows documentation to show how to utilize whl files

### ISSUE THREAD

**Issue by gregwhitworth** [tabatkins/bikeshed#506]
The link to [LXML](http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml) no longer references an .exe so I need to add in how to utilize this (once I figure it out myself) :)

**Comment by gregwhitworth** [comment]
@tabatkins Please assign to me - just opening this so I don't forget about it

**Comment by tabatkins** [comment]
I can't assign to you, since you don't have edit rights to the repo. But consider yourself assigned. ^_^

**Comment by tabatkins** [comment]
Yo @gregwhitworth, don't forget about this!

**Comment by gregwhitworth** [comment]
Thanks for the reminder, I did indeed forget this. I did try it when I needed to get it running on my home box and @SimonSapin suggestion didn't [work](https://twitter.com/SimonSapin/status/656185528195395584) so I'll need to dig a little bit deeper. My recent PR will allow anyone on Windows to get it to work as I found LXML without a WHL so not sure this is really necessary. I'm going to close this out until the LXML MSI is no longer there and I need to work around it again.

**Comment by SimonSapin** [comment]
@gregwhitworth, what’s the output of `pip install path/to/something.whl` with a file downloaded from http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml ?

Alternatively, https://pypi.python.org/pypi/lxml/3.5.0 has `.exe` files now. I don’t know if pip can use them or if you need to execute them directly.
