### ISSUE TITLE
specs with "Use <i> Autolinks: yes" and mailing list fail with FATAL ERROR: No 'dfn' refs found for '… message topic …'

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#510]
Specs with both "Use \<i> Autolinks: yes" and a mailing list fail with FATAL ERROR: No 'dfn' refs found for '… message topic …'  This is because of an attempt to autolink the mailing list header that is inserted in \__init__.py.

I worked around this with:
https://hg.csswg.org/drafts/rev/8621fbb4a564
https://hg.fxtf.org/drafts/rev/b32ea4df8a98
but it seems like this shouldn't happen.  (Is there an attribute that \__init__.py could put on the \<i> that would prevent it from autolinking?)

**Comment by tabatkins** [comment]
Yup, just marked it with an empty `lt` attribute.  That *should* work.

**Comment by dbaron** [comment]
Yep, confirmed that it's fixed now; I backed out the workarounds.
