### ISSUE TITLE
problems autolinking to a property in a different level of same spec

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#512]
I tried to add an issue in https://drafts.csswg.org/css-text-4/ that referred to the text-align property, which I wrote with single quotes.  (css-text-4 currently defines a new value for text-align, but doesn't redefine the property since it's currently a delta spec.)

This leads to:
FATAL ERROR: No 'property' refs found for 'text-align' with spec 'css-text-3'.

(I worked around it by not quoting 'text-align', so there's no autolinking.)

If I change the shortname in css-text-4/Overview.bs, things works fine, so it seems there's something weird about trying to autolink to a property in a different level of the same spec.

**Comment by tabatkins** [comment]
Dupe of #585
