### ISSUE TITLE
Bikeshed should require security and privacy considerations sections.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#513]
As discussed in https://w3ctag.github.io/security-questionnaire/#considerations, it would be lovely if Bikeshed would fail to compile specifications that don't contain a header labeled "Security Considerations" and a header labeled "Privacy Considerations".

WDYT, @tabatkins?

/cc @npdoty @mnot

**Comment by tabatkins** [comment]
I'm not down with requiring this for all Bikeshedded documents; Bikeshed is used outside the W3C, and can be used for non-spec things (I'm doing so privately), both of which don't need this.

But I *am* happy to maintain a list of groups that are W3C, and trigger the check/warning whenever a spec is generated for one of those groups.

**Comment by mikewest** [comment]
Ok. What do you think about the approach in https://github.com/tabatkins/bikeshed/pull/514?

**Comment by npdoty** [comment]
Should we also check for a "Privacy and Security Considerations" section? It seems like some groups are combining them, which seems like a reasonable practice we should support. Or was there a particular reason to prompt for separate sections entitled "Privacy Considerations" and "Security Considerations"?

**Comment by mikewest** [comment]
I don't have strong feelings about it. I'd be happy to support both in one section if that's a common practice.

**Comment by tabatkins** [comment]
Done.
