### ISSUE TITLE
Support for escaped identifies

### ISSUE THREAD

**Issue by deian** [tabatkins/bikeshed#517]
Based on the [WebIDL names](http://www.w3.org/TR/WebIDL/#idl-names):

> A leading "\_" is used to escape an identifier from looking like a reserved word so that, for example, an interface named “interface” can be defined. The leading "_" is dropped to unescape the identifier.

In COWL, we have an interface that has a method named `or` (see [this](https://w3c.github.io/webappsec-cowl/#dom-label-_or-label-or-domstring-other)). In the idl section it makes sense to use `_or`, but it would be nice to refer to the method as `or` elsewhere (e.g., in examples or other algorithms) while retaining links to the definition. Any thoughts on this?

**Comment by tabatkins** [comment]
Ah, good catch. I've got no problem with this; I'll look into auto-dropping the `_` where appropriate.

**Comment by tabatkins** [comment]
Fixed!

**Comment by deian** [comment]
Thanks!
