### ISSUE TITLE
idl type (double or sequence<double>) fails to preprocess

### ISSUE THREAD

**Issue by mpb** [tabatkins/bikeshed#518]
Two bugs:
* [ ] crash bug when filling an attribute-info span from a union-type attribute with a sequence (or something like that)
* [ ] bad markup (treating entire union type as an autolink) for union-types when the above doesn't crash them

---

I am trying to write the following IDL:
```idl
    <pre class="idl">
      dictionary IntersectionObserverInit {
        Element?  root = null;
        DOMString rootMargin = "0px";
        (double or sequence&lt;double>) threshold = 0;
      };
```
When I run this through https://api.csswg.org/bikeshed/ I get the following error:
```
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 5, in <module>
    bikeshed.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 181, in main
    doc.preprocess()
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 1477, in preprocess
    fillAttributeInfoSpans(self)
  File "/sites/api.csswg.org/bikeshed/bikeshed/__init__.py", line 564, in fillAttributeInfoSpans
    match.group(1),
AttributeError: 'NoneType' object has no attribute 'group'
```

Is there anything else I should be specifying in the `class="anchors"` or `class="link-defaults"` sections?

**Comment by tabatkins** [comment]
Whoops, that's a bug on my part.  At no point should Bikeshed be crashing to Python. ^_^

**Comment by mpb** [comment]
Another point of interest, when I change it to
```idl
(double or Element)
```
it says 
```
FATAL ERROR: No 'idl-name' refs found for '(double or Element)'.
```
Thanks!
