### ISSUE TITLE
Apostrophe in headings

### ISSUE THREAD

**Issue by josephshum** [tabatkins/bikeshed#521]
Is there any way to escape an ' in the headings tag (i.e, \<h3>Item that doesn't...\</h3>). Currently I am getting UnicodeEncodeErrors. I tried using \ to escape, but that just shows up in the html. Thanks!

**Comment by tabatkins** [comment]
I'd love to see concrete examples of breakage; it sounds like you're accidentally hitting the property autolinking shorthand, and it shouldn't trigger from something like that.

**Comment by josephshum** [comment]
Thanks for the reply. Here is an example (overview.bs, the only file I am building):
/////
\<pre class='metadata'>
Title: SpecName
Status: WD
Work Status: Refining
TR: http://www.w3.org/TR/SpecName/
ED: http://www.w3.org/TR/SpecName
Previous Version: http://www.w3.org/TR/SpecName
Shortname: SpecName
Level: 1
Editor: John Doe, AnOrg., AnOrg@mail.com
Abstract: Abstract sentence
Markup Shorthands: css no
\</pre>
\<h1>It's okay to have apostrophes in H1\</h1>
\<h2>But you can't have any in H2 or above\</h2>
//////
The above won't build unless the apostrophe is removed from the text inside the \<h2> tags. Please let me know if I am missing something. Thanks!

**Comment by tabatkins** [comment]
That builds for me.  Perhaps you need to update your Bikeshed?
