### ISSUE TITLE
Descriptor index broken

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#522]
There's a stray `</table>` before the beginning of the actual content, breaking everything in the descriptor index table. See https://drafts.csswg.org/css-device-adapt/#viewport-descriptor-table for an example.

**Comment by tabatkins** [comment]
...huh. I have no idea how that's happening, since I build it with DOM operations.

**Comment by frivoal** [comment]
Nonetheless it is happening, as evidenced by that document. I don't have anymore insight into what's going on, sorry. Maybe there's something subtly wrong with the source file, but I have no idea what that'd be.

**Comment by tabatkins** [comment]
Yeah, I definitely see it. I'll just have to dig in and see what's up.

**Comment by tabatkins** [comment]
Fixed! And made the code better too; this didn't affect the property descriptor tables because that part had better code and I wasn't sharing the code properly.
