### ISSUE TITLE
Drop trailing period in section numbers

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#525]
r12a would like us to drop the trailing periods from the section numbers.

**Comment by tabatkins** [comment]
Really? The period is analogous to list markers.

Pointer to his request?

**Comment by tabatkins** [comment]
Found the thread.  I thought I was just copying what the old preprocessor did, but Fonts is on the old processor, and it doesn't have dots after its section numbers.  I'm fine with changing this, whatever.

**Comment by r12a** [comment]
for posterity's sake, here's the original comment:
https://lists.w3.org/Archives/Public/spec-prod/2015OctDec/0064.html

fwiw, it looks like respec does the dot after the top level number, but not after the lower level section numbers, which i guess is fine.

what i was more interested in, however, was that section 7 numbering was wierdly different.  All counters in section 7 (only?) end with a dot.

**Comment by tabatkins** [comment]
> what i was more interested in, however, was that section 7 numbering was wierdly different. All counters in section 7 (only?) end with a dot.

That's... weird. I'm not sure why that's happening.

**Comment by fantasai** [comment]
(The sample page was copy-pasted bikeshed output with a bunch of bikeshed-specific things stripped out... since its goal isn't to be a bikeshed output sample, but a /TR requirements sample. The weird numbering was just human error, and has been fixed.)
