### ISSUE TITLE
Allow more autolinking shortcuts to use | for linktext alternative

### ISSUE THREAD

**Issue by arronei** [tabatkins/bikeshed#533]
It seems like the following autolinking shortcuts could also support the | for linktext alternatives:

* <{element/attribute}>
* [[#foo]]

**Comment by tabatkins** [comment]
`|` is for *defining* things with multiple possible linktexts.  Autolinks don't use it.

**Comment by arronei** [comment]
Autolinks do use it. e.g. {{somecrazyidlname|normal IDL name}}

And I have use cases for the others as well:

* <{a/href|href=""}>
* <{body|&lt;body>}>
* I'll concede that I probably don't need [[#foo]] but why limit this as well? I can see cases where you want a more natural text for an inline link to an heading.

**Comment by tabatkins** [comment]
Whoops, I forgot about that feature entirely!

It seems like this is best done with CSS, tho, rather than requiring you to pollute every single autolink with extra markup.  Just add:

```
a[data-link-type=element]::before { content: "<"; }
a[data-link-type=element]::after { content: ">"; }
a[data-link-type=element-attr]::after { content: '=""'; }
```

**Comment by tabatkins** [comment]
For the data-* thing, I presume you found that it doesn't work with a `*`, and that's why you're defining it as "data" instead?  That's a bug on my side, fixing it now.

**Comment by arronei** [comment]
"<{(?:([\w-]+)/)?([\w-]+)(\|[^}]+)?}>"

If you use this Regex then it will work for both elements and for element attribtues. So both my cases would be covered.

And for <{body|&lt;body>} I only need this for some and then others it can just be normal. It depends on the context. So the CSS solution wouldn't meet my needs in all cases because I would have to specify a class.
