### ISSUE TITLE
Allow <include ...> files to parse markdown

### ISSUE THREAD

**Issue by arronei** [tabatkins/bikeshed#536]
It seems as if included files using the <include> method do not processes markdown. The inclusion happens too late in the process.

I think the inclusion should happen before the transformDataBlocks(self) call inside the preprocess() method otherwise some items will not get processed correctly.

**Comment by tabatkins** [comment]
Yes, this is an acknowledged limitation at the moment, because just including HTML was simple and satisfied the use-case of the requester. I plan to make Markdown includes work.

How are you planning to use includes, btw?

**Comment by arronei** [comment]
Due to the size of the document that I am working on it has been easier to split each section into its own include and have their own local, link-defaults, anchors, biblio sections.

However, right now, if I want to build things I have to copy it back into the main document to test it all out.

**Comment by tabatkins** [comment]
So, the individual sections use *distinct* versions of their data-block stuff? So they shouldn't share?

I"m wondering, because this use-case is more in the direction of multiple-input-pages, which is something I want to address, but probably not with `<include>`.

**Comment by tabatkins** [comment]
Okay, I've added support for markdown and datablocks.  Things like `<pre class="anchors">` will be document-global, not local, but otherwise this should hopefully meet your needs.
