### ISSUE TITLE
tar files for echidna

### ISSUE THREAD

**Issue by plehegar** [tabatkins/bikeshed#537]
Echidna now includes supports for tar files:
  https://github.com/w3c/echidna/wiki/Preparing-your-document#tar-file

Bikeshed should provide the ability to create a tar file, if the document is more than a single HTML page, that can then be fetched by Echidna.

* <https://github.com/w3c/echidna/wiki/How-to-use-Echidna#tar-file>
* <https://github.com/w3c/echidna/wiki/Preparing-your-document#tar-file>
* <https://github.com/w3c/echidna/wiki/Metadata-extracted-from-the-document>

**Comment by tabatkins** [comment]
Done; Bikeshed can now publish directly to Echidna.
