### ISSUE TITLE
References for WebIDL

### ISSUE THREAD

**Issue by Ms2ger** [tabatkins/bikeshed#543]
* OMGIDL
* PERLRE
* IEEE-754

**Comment by tabatkins** [comment]
I have no memory of what this is supposed to mean, and this bug provides no context.  Can you elaborate on what I was supposed to do about this?

**Comment by Ms2ger** [comment]
Get those into whatever reference database bikeshed uses.

**Comment by tabatkins** [comment]
So those are biblio references that WebIDL currently uses, right?  Just making sure before I go write a PR for SpecRef with the new references.

**Comment by Ms2ger** [comment]
Yep

**Comment by tabatkins** [comment]
Okay, PR'd SpecRef with these references. I'll go ahead and close here.
