### ISSUE TITLE
Autolinks should not dump into Normative section

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#557]
Some of our specs (like Cascade) are getting a bunch of normative dependencies from auto-cross-links generated in examples. Probably examples should be automatically in the non-normative dependencies. There's other cases that probably ought to be non-normative as well, and it would be nice to be able to handle that without editing the output as well.

**Comment by tabatkins** [comment]
Should they be all non-normative instead?  I can probably handle the "all links in examples are non-normative" thing if they're the only thing that should move.

**Comment by tabatkins** [comment]
Okay, any autolinks that show up in notes or examples now just trigger informative biblio references.  Considering this closed unless you think there's more I should be doing.

**Comment by fantasai** [comment]
I think that's probably good enough, yeah. If we need something more we can open a separate issue.

**Comment by tabatkins** [comment]
You can also mark individual links (or containers) with a class=non-normative and it'll dump them into the informative index.

**Comment by fantasai** [comment]
LGTM
