### ISSUE TITLE
WebIDL parsing [PutForwards=] not working

### ISSUE THREAD

**Issue by arronei** [tabatkins/bikeshed#559]
interface Location {
    [PutForwards=href, Unforgeable] readonly attribute Location? location;
};

When you have the above IDL definition the parsing fails with an error stating:

"No 'idl-name' refs found for 'href'

**Comment by tabatkins** [comment]
Interesting! I'll have to special-case that, as the PutForwards value is an attribute, which isn't part of the `idl-name` supertype that I apparently default these things to.
