### ISSUE TITLE
Missing spaces between some adjacent links in generated HTML

### ISSUE THREAD

**Issue by cvrebert** [tabatkins/bikeshed#560]
Examples:
* https://drafts.csswg.org/css-syntax/#input-byte-stream
  * "get an encoding[ENCODING] for the specified value."
* https://drafts.csswg.org/css-syntax/#style-rules
  * "that associates a selector list[SELECT] with a list of property declarations."
* https://drafts.csswg.org/css-syntax/#would-start-an-identifier
  * "If the first and second code pointsare a valid escape,"

There are spaces present in the `.bs` source, which leads me to assume that there's a Bikeshed bug.

**Comment by tabatkins** [comment]
...huh.  That reflects a *very* old bug which was fixed months ago - bikeshedding the source does not produce those errors anymore. I don't understand why the live version isn't fully updated.

This looks to be a bug in the machinery that handles auto-updating the specs, not Bikeshed itself.  I've pushed a minor update to that particular spec which should hopefully force a regen and fix the issues you're seeing, and I'll bug the maintainer of the auto-updater about the issue.  Closing on my end.
