### ISSUE TITLE
Multiple dfns to the same term in one spec leads to confusing warning

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#562]
https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/dd2210d63e77fa610bc818f2c4cd4d3e69b4fc98/index.bs&paragraph=html&output=both gives:

```
WARNING: Multiple possible 'dfn' refs for 'global object'.
Arbitrarily chose the one in html.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:html; type:dfn; text:global object
```

I believe this happens because both https://html.spec.whatwg.org/multipage/webappapis.html#execution-context's-global-object and https://html.spec.whatwg.org/multipage/webappapis.html#global-object in the same spec have `<dfn>global object</dfn>`, but the message should say that, and ideally say how to suppress it.

**Comment by domenic** [comment]
Seems like a bug against HTML as well; we should fix that...

**Comment by tabatkins** [comment]
Yeah, I know that warning's confusing in this case, sorry about that. :/  The problem is that I can't do anything about it - Bikeshed's data model can't distinguish between the two any further, and I'm not willing to do something as fragile as letting you distinguish them by index.

I'll see what I can do about making the error message more informative (the only way to suppress it is to manually link, rather than autolink).

@domenic Yes, fixing it in HTML would be great.  Probably one of them needs a `data-dfn-for` so Bikeshed can distinguish them.

**Comment by domenic** [comment]
@tabatkins they have different IDs; is that not sufficient?

**Comment by tabatkins** [comment]
No, Bikeshed's data model doesn't care about IDs at all.  It distinguishes values by linking text, type, what it's namespaced under (the `for` value), and the defining spec.  This allows you to autolink by linking text, which is extremely natural and compact, and only occasionally need to disambiguate further.

Looking at the spec, in this case I'd recommend adding a `for` value to both of them - `<dfn data-dfn-for="execution context">global object</dfn>` and `<dfn data-dfn-for="environment setting object">global object</dfn>`.

**Comment by domenic** [comment]
I guess consider this a feature request for Bikeshed to learn to distinguish by IDs.

**Comment by tabatkins** [comment]
That's called "a normal link". I suppose there's a tiny benefit to autolinking by ID that the overall page URL can be updated over time, but eh.

**Comment by tabatkins** [comment]
So I just improved the error message when the only options are indistinguishable.  I'll finish this out by PRing HTML to add both `export` and `for` to those two definitions.

**Comment by tabatkins** [comment]
And, done.
