### ISSUE TITLE
Problems with install instructions

### ISSUE THREAD

**Issue by torgo** [tabatkins/bikeshed#564]
Having just gone though the install process on a new install of OS X (10.11) I thought I would note: 1) installing python 27 via MacPorts didn't automatically install `pip`. I had to issue the command `sudo easy_install pip` to install `pip`. I also found that the `pygments` library was not installed by default so I further had to `pip install pygments`. Suggest adding those steps to the [install instructions](https://github.com/tabatkins/bikeshed/blob/master/docs/install.md).

**Comment by tabatkins** [comment]
Hm, the install instructions do explicitly install pip and pygments:

> sudo port install python27 py27-pip py27-lxml py27-html5lib py27-cssselect py27-libxslt py27-libxml2 py27-pygments

Is that the command you ran?

**Comment by torgo** [comment]
Indeed they do. I guess I was blind? :) In any case, issue withdrawn.
