### ISSUE TITLE
Omit closing tags when possible

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#566]
Bikeshed currently outputs "proper" html, with closing tags on every non-void element.  It would make the output prettier and slightly smaller if I omitted closing tags when possible.

This is particularly noticeable when omittable elements are stacked, like:

```html
<ul>
 <li>
  <p>
   foo
  </p>
 </li>
</ul>
```

which could instead output as:

```html
<ul>
 <li>
  <p>
   foo
</ul>
```

**Comment by annevk** [comment]
I think it would be great that if we detect that `<p>` is the sole child of `<li>`, we just output `<li><p>` instead of adding a newline. And only add newlines if `<li>` has multiple "block-level" children.

**Comment by tabatkins** [comment]
I do need to handle the "single `<p>`" thing at the Markdown level - I'm currently violating the spec by putting a `<p>` around the contents of single-paragraph list items.

The formatter has some logic for putting things on the same line, but it doesn't cover block elements, because whether or not to pull children tags onto your line is a style decision based on individual elements.  `<li><p>` makes sense, sure, but `<li><figure>` probably doesn't.  The decision shouldn't make any difference visually, due to whitespace collapsing.

**Comment by annevk** [comment]
I think it could be for all "block-level element", as long as there is only a single child.
