### ISSUE TITLE
ValueError: Comment may not contain '--' or end with '-'

### ISSUE THREAD

**Issue by mitar** [tabatkins/bikeshed#574]
I am getting the following error when trying to compile a spec:

```
    self._element = ElementTree.Comment(data)
  File "src/lxml/lxml.etree.pyx", line 3017, in lxml.etree.Comment (src/lxml/lxml.etree.c:80806)
ValueError: Comment may not contain '--' or end with '-'
```

It comes from LXML.

Using Mac OS X, the latest clone (f2b16e621bf4db9414c77cb076f6fd47c61ca606) of this repository.

`pip freeze`:

```
-e git+https://github.com/tabatkins/bikeshed.git@f2b16e621bf4db9414c77cb076f6fd47c61ca606#egg=Bikeshed-master
cssselect==0.9.1
GDAL==1.11.2
html5lib==0.9999999
lxml==3.5.0
mercurial==3.6.2
Pygments==2.1
six==1.10.0
```

The offending line is:

```
<!----------------------------------------------------------------------------->
```

From: https://github.com/w3c/webappsec-suborigins

**Comment by tabatkins** [comment]
Correct, you can't do that: <https://html.spec.whatwg.org/multipage/syntax.html#comments>

**Comment by madhead** [comment]
Faced this issue in [Calibre](https://github.com/kovidgoyal/calibre) (it was not able to parse Amazon's book metadata due to double hyphens in comments). Upgrading `html5lib` version fixed the issue:

    $ python2 -c "import html5lib; print html5lib.__version__"
    $ 0.9999999
    $ sudo pip2 install html5lib --upgrade
    $ python2 -c "import html5lib; print html5lib.__version__"
    $ 0.999999999
