### ISSUE TITLE
Add <meta name=viewport>

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#575]
https://github.com/w3c/tr-design/issues/48#issuecomment-174114295 says bikeshed needs to add a `<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">` header for the specs to work well on mobile.

**Comment by domenic** [comment]
> shrink-to-fit=no

THAT EXPLAINS SO MUCH!!!

**Comment by tabatkins** [comment]
And done - I've updated all of the header files to have that meta-viewport now.
