### ISSUE TITLE
Section self-links are cut off

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#577]
https://api.csswg.org/bikeshed/?url=https://github.com/WebBluetoothCG/web-bluetooth/raw/gh-pages/index.bs#security-and-privacy has its self-link too far to the left, where it gets cut off by the table-of-contents pane:

<img width="697" alt="Screenshot of cut-off section self-link" src="https://cloud.githubusercontent.com/assets/83420/12542493/aefce884-c2d8-11e5-8c9b-9402e6a150c9.png">

**Comment by tabatkins** [comment]
Done, they now exactly fill the gap between the TOC and content and are centered there.
