### ISSUE TITLE
<h5> should have less visual weight than <h4> in ToC

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#578]
In the new stylesheet, 5th-level headings are indented the same amount as 4th-level, and are shown in the same font as 3rd-level headings which makes them look too important:

<img width="380" alt="Screenshot of heading levels 2-5" src="https://cloud.githubusercontent.com/assets/83420/12542572/fe8203ca-c2d9-11e5-9240-77b472f33a5b.png">

https://w3c.github.io/tr-design/src/sample.html shows them indented farther, which works, or they could be the same smaller font as their section number.

**Comment by tabatkins** [comment]
Yeah, I think @fantasai just made that indentation change this weekend.  I'll copy it over.

**Comment by tabatkins** [comment]
And done.
