### ISSUE TITLE
[PutForwards=...] does not use the dfn-for= value

### ISSUE THREAD

**Issue by arronei** [tabatkins/bikeshed#582]
When put forwards defines a new name to use for the attribute then dfn-for is not used to define that attribute properly in the IDL.

**Comment by tabatkins** [comment]
Can you give me an example? My testing when u committed the patch showed that it set up for='' properly.

**Comment by arronei** [comment]
`<dfn attribute for="HTMLBaseElement"><code>href</code></dfn>`
...
```
<pre class="idl"  data-highlight="webidl" dfn-for="Document">
    [OverrideBuiltins]
    partial /*sealed*/ interface Document {
      // resource metadata management
      [PutForwards=href, Unforgeable] readonly attribute Location? location;
    }
</pre>
```

the problem item in the PutForwards resolves like this:

`<a class="idl-code" data-link-type="attribute" for="Document" href="#dom-htmlbaseelement-href">href</a>`

This should be a definition not a link to another type

I would expect it to resolve like this
`<dfn class="idl-code" data-dfn-for="Document" data-dfn-type="attribute" data-export="" data-type="Location " id="dom-document-href">href<a class="self-link" href="#dom-document-href"></a></dfn>`

**Comment by tabatkins** [comment]
I don't understand - you seem to be asking for PutForwards to be a *definition* of an attribute? If so, that's definitely wrong - it points to an already-defined attribute elsewhere.

If you mean something else, can you elaborate on your expected behavior?

**Comment by zcorpan** [comment]
I ran into this for the DOM spec as well for https://github.com/whatwg/dom/pull/120#issuecomment-176044461

Consider this:
```
interface Element {
 [SameObject, PutForwards=value] readonly attribute DOMTokenList classList;
};
interface Attr {
           attribute DOMString value;
};
interface DOMTokenList {
           attribute DOMString value;
};
```

> WARNING: Multiple possible 'attribute' local refs for 'value'.
> Arbitrarily chose the one with type 'attribute' and for 'Attr'.

Now, given how `PutForwards` is defined, you should pick the `value` attribute of the interface from the same row where you find the `PutForwards`, in this case `DOMTokenList`, instead of something arbitrary.

**Comment by arronei** [comment]
I guess what I really need is a way to specify what the PutForwards dfn-for needs to be. In this case I need it to be 'Location' object not 'HTMLBaseElement'. How would I specify, in this case, in this IDL block, that the 'href' points to the 'Location' object?

I already have a dfn-for for the rest of the IDL block which is correct for everything else however, for the PutForwards I need a different dfn-for. How will that work? Any ideas?

**Comment by arronei** [comment]
@zcorpan Is exactly correct and I think spelled it out better than I did.

**Comment by tabatkins** [comment]
Ah, yes, I see where I messed up. I accidentally made it for the enclosing interface, not for the type of the attribute the PutForwards is on.

I am not capable of doing any Bikeshed hacking this week, but if someone would like to either fix this, or revert my earlier change for now (to stop the incorrect linking errors) I can merge that and fix it as soon as I get back next Friday.
