### ISSUE TITLE
can't auto-link to property in different level of same specification

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#585]
In https://drafts.csswg.org/css-text-4/ I'd like to make the references to "text-align" properly link to the definition of the text-align property in https://drafts.csswg.org/css-text-3/ .  This produces the error:

FATAL ERROR: No 'property' refs found for 'text-align' with spec 'css-text-3'.

I suspect what's happening is that since this is the same specification but a different level, it insists on looking in *this* specification.  (The error goes away if I change the shortname.)  That's a reasonable behavior in most cases -- i.e., if a new/old level of a specification that isn't (yet/longer) the link default defines a property, links within it should be internal, rather than to the level that is the link default.  But then there's the case of delta specifications like css-text-4, or maybe a more stable specification referencing something that was deferred to a new specification.  There should be a way to handle this -- perhaps with link-defaults explicitly saying that you really want to refer to another level, or something like that.

**Comment by tabatkins** [comment]
Your guess is right - if the set of possible refs includes multiple versions of the same spec, Bikeshed automatically removes the older version.

I think I'm doing this too early right now, tho - iirc, I delete these as a cleanup step after loading all the definitions.  I should really hold onto them so an explicit `spec=foo-3` attribute can grab them. It just requires me to upgrade the at-link-time pruning logic a little.

I'll work on this.

**Comment by tabatkins** [comment]
Fixed. Down-level refs are now just marked as unexported, rather than deleted, so you can explicitly refer to them. I've fixed Text 4 to use link-defaults on the three Text 3 properties it refers to, so it gets the right links.
