### ISSUE TITLE
FATAL ERROR: No 'dfn' refs found for 'root' with for='[u'tree']'.

### ISSUE THREAD

**Issue by mpb** [tabatkins/bikeshed#586]
Moving https://github.com/WICG/IntersectionObserver/issues/89 over to correct github page.
When processing IntersectionObserver's index.bs, bikeshed gives this error.

$ bikeshed
FATAL ERROR: No 'dfn' refs found for 'root' with for='[u'tree']'.

Line seems to be:
```
<pre class="link-defaults">
spec:dom-ls
	type:interface; text:Document
	type:dfn; for:tree; text:root
```

**Comment by tabatkins** [comment]
By coincidence I found this exact error about two weeks ago and fixed it, but then forgot to push the commit to the repo. Fixed now. ^_^
