### ISSUE TITLE
Mouseovering TOC entries in the new stylesheet causes the whole TOC to jump by a pixel or two

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#587]
Not an issue with https://w3c.github.io/tr-design/src/sample.html

But visible in https://webbluetoothcg.github.io/web-bluetooth/

**Comment by tabatkins** [comment]
Fixed - there was some battling styling in the stylesheet between general hovered links and TOC links, so the margin got changed unexpectedly by 1px when they were hovered.

I've fixed this in Bikeshed's stylesheet, and will see if the error is still in the TR stylesheet.
