### ISSUE TITLE
W3C logo SVG.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#590]
It would be nice if we could simply inline the W3C logo SVG, or include an absolute URL at https://github.com/tabatkins/bikeshed/blob/master/bikeshed/include/stylesheet.include#L120, rather than asking everyone to grab a file and put it in a subdirectory. That would be annoying busywork. :)

**Comment by tabatkins** [comment]
Thanks for pointing it out - that doesn't actually belong in the generic Bikeshed stylesheet at all!  I've removed it, and put in a note to help me remember to kill it again whenever I copypaste from the TR stylesheet.
