### ISSUE TITLE
issue when getting biblio data

### ISSUE THREAD

**Issue by stevefaulkner** [tabatkins/bikeshed#591]
When doing "bikeshed update" i get the following error:

> Downloading biblio data...
> [1;31mFATAL ERROR:[0m Couldn't download the biblio data.
> <urlopen error [Errno 1] _ssl.c:510: error:140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)

any ideas?

**Comment by tabatkins** [comment]
Still works for me.  Are you using the most recent Bikeshed?  If so, maybe it was a transient SSL error on tobie's side?

**Comment by stevefaulkner** [comment]
> Are you using the most recent Bikeshed? If so, maybe it was a transient SSL error on tobie's side?
yes, and just tried again to no avail, is there a way to get the biblio data manually?

**Comment by tabatkins** [comment]
Not really; best I can do is update the version in the repo so you can pull that yourself.

If you're still having the problem, tho, what's your platform?

**Comment by stevefaulkner** [comment]
@tabatkins Adrian batemen resolved issue for me

**Comment by tabatkins** [comment]
Hey man, don't be <https://xkcd.com/979/>, tell me what the problem was and how you solved it!
