### ISSUE TITLE
Something goes wrong in the combination of dfn-for, optional method parameters and different interfaces with the same method name.

### ISSUE THREAD

**Issue by mkruisselbrink** [tabatkins/bikeshed#592]
With this fragment of bikeshed:
```
<pre class="idl">
interface Foo {
  void matchAll(optional CacheQueryOptions options);
};
</pre>

<section dfn-for="Cache">
  <pre class="idl">
  interface RequestInfo {};
  interface Cache {
    void matchAll(optional RequestInfo request, optional CacheQueryOptions options);
  };
  dictionary CacheQueryOptions {
  };
  </pre>

  <p>
    If you use the {{Cache/matchAll(request, options)}} method, it does something.
  </p>

  <p><dfn method id="cache-matchall-method"><code>matchAll(<var>request</var>, <var>options</var>)</code></dfn> method <em class="rfc2119" title="MUST">must</em> run these steps or their equivalent (using <var>request</var> and <var>options</var>):</p>
</section>
```

bikeshed gives `FATAL ERROR: No 'idl' refs found for 'matchAll(request, options)'.`

If I remove the interface Foo, the error goes away. If I remove the optional on the request parameter of the matchAll method the error also goes away. If I add a for= on the dfn tag the error also goes away (so that's likely what I'll end up doing, since it's the only thing that doesn't actually change the spec).

Any idea what is going on here?

**Comment by tabatkins** [comment]
Ah, thank you for getting me a pretty reduced test case! I've been puzzling at this error for a while. ^_^

Let's see what I can do!

**Comment by tabatkins** [comment]
And done.  I wasn't pushing parent dfn-fors down to the dfn early enough, so it was hitting a "what method are you?" code path without knowing the interface the method was for.
