### ISSUE TITLE
Exclude data-no-idl blocks from IDL Index?

### ISSUE THREAD

**Issue by mkruisselbrink** [tabatkins/bikeshed#598]
Currently the IDL Index includes all IDL in a spec, even IDL in `<pre class="idl" data-no-idl>` blocks. Is this intentional or would it make sense to skip data-no-idl for the IDL index? Or there could even be a separate data-no-idl-index attribute?

**Comment by tabatkins** [comment]
`data-no-idl

**Comment by tabatkins** [comment]
`data-no-idl` just makes Bikeshed skip the IDL markup step, so legacy specs that have a lot of manual markup in their IDL can continue to have that.  It's not really intended to indicate that the block doesn't contain idl - if that's what you mean, just omit the `idl` class.

But sell it to me - why would you want to exclude some IDL blocks from the index?

**Comment by mkruisselbrink** [comment]
I wasn't sure if it made sense to use data-no-idl for this either, so it makes perfect sense that I should just remove the idl class (or just keep this in the IDL index).

I was mainly trying to decide what to do with the IDL in https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#extensibility; which doesn't really define any interfaces etc that are part of the spec, but is more just an example of how other specs can define stuff. Just leaving off the class=idl probably makes the most sense (although if IDL syntax highlighting ever gets added it would be unfortunate not to have that).

**Comment by domenic** [comment]
I think examples in general make sense as not going in the IDL index. You could even try to detect an ancestor with "example" in its class list.

**Comment by tabatkins** [comment]
Yeah, that makes sense and is easy. I'll go ahead and exclude IDL with a note or example ancestor. I'll have the auto formatter skip it too, but when I add "real" IDL syntax highlighting I'll need to go back in and complexify things.

**Comment by tabatkins** [comment]
Done. Feel free to mark up your IDL notes or examples with class=idl, they'll get passed over by the autoformatter and skipped by the index.
