### ISSUE TITLE
Native translation support (or markup in <dt>s)

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#600]
See https://notifications.spec.whatwg.org/ for an example. I think it would be good for the clarifying text to be inside a `<small>`.

**Comment by tabatkins** [comment]
Done. Use `Translations: 简体中文 https://w3c-html-ig-zh.github.io/notifications/whatwg/`. Comma-separated if you have more than one.

**Comment by annevk** [comment]
I don't think that does quite what I want. It would no longer say "Simplified Chinese" in a title and it would no longer have an accurate lang attribute.

**Comment by tabatkins** [comment]
Ah, I didn't look at all the markup. Be specific about what you want. ^_^

Hmm, I can either expand the syntax to take a title and a lang, or just let it be raw HTML. Do you anticipate ever needing anything more than text/title/lang/url?

**Comment by annevk** [comment]
I don't know. Maybe `hreflang` too? I'm not really experienced with linking to translations. This is a new thing for me.

**Comment by tabatkins** [comment]
Okay, thinking of this format:

```
Translation: <lang-code> <url> [ [ , name <name-in-spec-lang> ] || [ , native-name <name-in-the-lang> ] ]?
```

native-name is displayed in text content. If it's missing, name is displayed. If that's missing, use lang code.
name is displayed in the `title`. if it's missing, use lang-code.

So for your line you'd do:

```
Translation: zh https://w3c-html-ig-zh.github.io/notifications/whatwg/, name Simplified Chinese, native-name 简体中文
```

**Comment by annevk** [comment]
What does "use lang code" mean?

**Comment by annevk** [comment]
Also, we could let bikeshed keep the database of name/native-name so all you need is the URL and language, if we're automating. Might get a little ahead of ourselves with that, given the number of translations, but who knows.

**Comment by tabatkins** [comment]
The reason I don't want to do that is (a) there's a lot of languages, and (b) "name" is written in the spec's language.  While all W3C specs are written in American English, I don't see a reason to bake in that assumption to all Bikeshed-using documents. (I do in fact currently make that assumption in a few parts, like auto-generated headings, but it's fixable.)

Then again, maybe I could go ahead and do so, and just allow for the possibility of specifying a name in the spec's language later.

I did look into using existing dbs for this information, but it seems hard to do?  In particular, there's multiple types of language codes.

...okay, so here's the plan.  I'll go ahead and do what I said in <https://github.com/tabatkins/bikeshed/issues/600#issuecomment-185431658>.  I'll also maintain a manually-updated list of lang-code => english/native name mappings; if the lang code is on the list, you can omit that information from your `Translation` line.  So all you'll have to do is write `Translation: zh <url>` and be done with it.  But if someone is providing a translation in a new language, they can still supply all the info, if they don't want to bother with adding it to Bikeshed.

**Comment by tabatkins** [comment]
And done.  It's as I described above: just put a `Translation: zh https://w3c-html-ig-zh.github.io/notifications/whatwg/` line in your metadata, and Bikeshed will fill in the rest (better than you have currently, per Google recommendations!).

**Comment by tabatkins** [comment]
Nevermind, use `zh_CN` - the `zh` lang code is for the "Chinese" macrolanguage, not Simplified Chinese specifically.

**Comment by annevk** [comment]
Hmm, should that not be `zh-CN` (or maybe `zh-cn` as Wikipedia seems to do) with a hyphen? Also, is there a way to have this appear as the last `<dl>` item?

**Comment by tabatkins** [comment]
I can go ahead and accept all those variations (I'll canonicalize it to lowercase with dashes, and just convert whatever you entered into that).

I can definitely move it to below all the non-custom values.  I can't easily adjust the order relative to custom values without weird tweaking that I haven't thought thru yet.

**Comment by tabatkins** [comment]
Okay, I canonicalize the code you use.  Translations are already the very last built-in bit of header stuff.
