### ISSUE TITLE
IDL blocks should be styled with class="def" or equivalent

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#604]
Like https://w3c.github.io/tr-design/src/sample.html#def. This [worked for a while](https://webbluetoothcg.github.io/web-bluetooth/#device-discovery), and [stopped again](https://rawgit.com/WebBluetoothCG/web-bluetooth/dfn-panels/index.html#device-discovery).

**Comment by tabatkins** [comment]
I'll bug @fantasai - I thought she'd amended the selectors to include `pre.idl`, but either she didn't, or it was reverted somehow.

**Comment by tabatkins** [comment]
Never mind, I just added a cleanup step that adds `.def` to all `pre.idl:not(.def)` elements.
