### ISSUE TITLE
Bikeshed incorrectly thinks a biblio reference is informative

### ISSUE THREAD

**Issue by mkruisselbrink** [tabatkins/bikeshed#605]
Somehow 335733288287ee5ea41f39be949387a1fe3e997f made it so that bikeshed decided that the [service worker spec](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html) only depends on DOM-LS as an informative reference. I'm not sure why that would be though, since there are many normative references to terms defined by DOM-LS.

**Comment by tabatkins** [comment]
Ah, figured it out.

DOM-LS doesn't exist in the biblio database, so it gets skipped by the code that adds autolinks to norm/inform references.  Later, when I'm generating the `Terms Defined by Reference` index, the header of that subsection becomes an informative biblio ref.  It still doesnt' exist in the db, but I'm capable of generating a "fake" biblio line from the spec database.

So I just need to fix the autolink code to not fail on missing references that I can generate.
