### ISSUE TITLE
Link to updated logo

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#607]
https://lists.w3.org/Archives/Public/spec-prod/2016JanMar/0036.html

**Comment by tabatkins** [comment]
I can't do this until <https://github.com/w3c/tr-design/issues/67> is addressed.

**Comment by fantasai** [comment]
Addressed by marking wontfix... Reopen if you've got additional information to consider.

**Comment by tabatkins** [comment]
Fixed (by @zcorpan, yay!).
