### ISSUE TITLE
References inside DOM cause normative reference to https://w3c.github.io/dom/

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#609]
Writing `<a>context object</a>` yields a correct link to https://dom.spec.whatwg.org/#context-object, but in the Normative References section it causes a `[dom]` entry, which links to https://w3c.github.io/dom/, the "Unicorn Toasters Markup API". It should cause a `[whatwg-dom]` entry instead. This is related to tobie/specref#184.

**Comment by tabatkins** [comment]
Ugh, ffs, I hate all this stupid squatting.  Gonna special-case this crap and just make all dom references point to the right one.

**Comment by annevk** [comment]
Can we do the same for the other WHATWG standards? That'd be great.

**Comment by tabatkins** [comment]
Fine with me.  I'll add a pref and turn it on by default to govern this.

**Comment by tabatkins** [comment]
And done. I went through all the WHATWG-* specs in the biblio database and filtered for ones where the unprefixed version didn't point to the WHATWG spec; there were only five (NOTIFICATIONS, FULLSCREEN, DOM, URL, and ENCODING).  They all now get caught and have the whatwg- prefix added.

**Comment by annevk** [comment]
I guess only five conflicts? I believe @tobie made sure https://resources.whatwg.org/biblio.json is imported.

**Comment by tobie** [comment]
Yeah. I need to fix https://github.com/tobie/specref/issues/184, but I don't have the resources to do so right now.

**Comment by annevk** [comment]
So the way this was fixed turns URL into WHATWG-URL sometimes, but, e.g., [[!URL]] references remain untouched. That does not seem useful.

(I would also somewhat prefer it if the forks got the ORG- treatment.)

**Comment by annevk** [comment]
Okay, I guess this is acceptable. Thank you.
