### ISSUE TITLE
dfn type shorthand incorrectly matches content

### ISSUE THREAD

**Issue by arronei** [tabatkins/bikeshed#612]
The new dfn type shorthand using equals (=) incorrectly matches cases like this...

<code>&amp;lt;meta name="" content=""></code>

Suggest changing to == (may have issues with javascript) or using a different character for dfn types.

**Comment by arronei** [comment]
Other examples that are broken are...

<code>&lt;meta name='' content=''></code>
<code>&lt;meta name=test content=foo></code>
<code>&lt;meta name =test content= foo></code>

**Comment by tabatkins** [comment]
Fixed with a slightly hacky "prevent it from containing double-quotes" edit.  This won't help with some of your other examples, but those can be fixed by just using double-quoted values.

**Comment by arronei** [comment]
How about cases that are URL examples?

/find.cgi?t=cats&amp;q=fur

WE can't use = as an identifier. There are too many cases where = is a valid thing.

**Comment by arronei** [comment]
And another example...

...does not contain a U+003D EQUALS SIGN character (=), insert a U+003D EQUALS SIGN character (=) at the start...

**Comment by tabatkins** [comment]
Hrmmmm.  Okay, I guess I'll switch it to a double-equals.

**Comment by arronei** [comment]
Javascript will now cause issues with double or triple =.

if(test == "temp") || (foo == true) { ... }
if(test === "temp") || (foo === true) { ... }

**Comment by tabatkins** [comment]
`<script>` elements don't get searched for shorthands.

**Comment by arronei** [comment]
But what about <pre> and other script examples? I'm not sure if you can exclude all of those cases.

**Comment by tabatkins** [comment]
All right, I switched it up to use `[=foo=]` syntax instead.  This should be safe - it's a rare/non-existent combo, and it's directional, making it even less likely to accidentally occur on a single line.
