### ISSUE TITLE
Header text doesn't flow properly around floating W3C logo

### ISSUE THREAD

**Issue by garykac** [tabatkins/bikeshed#615]
The spec metadata info ("This version", "Latest version", ...) doesn't flow properly around the W3C logo (which is now floating right with the latest version of bikeshed) when the spec title is long(-ish).

The string "This version" is orphaned at the top of the page.

See https://w3c.github.io/uievents-key/ or https://w3c.github.io/uievents-code/ for examples.

**Comment by tabatkins** [comment]
Ugggggh more changes that @fantasai made to the W3C stylesheet without testing them on real specs. >_<

I'll fix locally in Bikeshed and bug fantasai about fixing it in the W3C stylesheet.
