### ISSUE TITLE
specification should be able to define link target for header of a propdef table entry

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#617]
Many of the entry headers in the propdef tables (e.g., "Value", "Computed value", "Animatable", "Canonical order") should be hyperlinks to the specification that defines what those entries mean.

Ideally, bikeshed should have a way for a specification to declare that it is defining one of those headers, and then other specifications that use the header would link to that definition.

Alternatively bikeshed could just hardcode what they link to; it's not something we'd need to change all that often.

**Comment by tabatkins** [comment]
I'm happy to hardcode it - just gimme the links you want them to point to.

**Comment by dbaron** [comment]
For now, I'd say:

[Value](https://drafts.csswg.org/css-values/#value-defs)
[Initial](https://drafts.csswg.org/css-cascade/#initial-values)
Applies to:  perhaps to the final paragraph in https://drafts.csswg.org/css-cascade/#computed which doesn't currently have an anchor
[Inherited](https://drafts.csswg.org/css-cascade/#inherited-property)
[Percentages](https://drafts.csswg.org/css-values/#percentages)
Media: not sure, although we should probably have wording somewhere similar to the "Applies To" wording
[Computed value](https://drafts.csswg.org/css-cascade/#computed)
[Animatable](https://drafts.csswg.org/css-transitions/#animatable-properties)
Canonical order should really be something in cssom, but I really can't find anything useful to reference
