### ISSUE TITLE
bikeshed only says "Issue Tracking: Inline In Spec" if some issues are declared with elements rather than "Issue:"

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#618]
I [just converted](https://hg.csswg.org/drafts/rev/f9154a24a424) the [bikeshed version of the CSS module template](https://drafts.csswg.org/css-module-bikeshed/) to write its issues using "Issue:" rather than &lt;p class="issue">.  This produced pretty much the expected diff in the output, except for:
```
-     <dt>Issue Tracking:
-     <dd><a href="#issues-index">Inline In Spec</a>
```

Whether I write issues using &lt;p class="issue"> or Issue: shouldn't affect whether this shows up; it should show up either way!

**Comment by tabatkins** [comment]
Fixed; sorry, didn't realize this broke when I made the note/issue/advisement classes customizable!
