### ISSUE TITLE
Sort biblio entries

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#619]
Biblio entries seem to be output in random order. They should be alphabetical.

**Comment by tabatkins** [comment]
They are sorted in alphabetical order.

**Comment by mkruisselbrink** [comment]
A rather weird alphabetical order though... Take https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#references
Not sure why WebIDL and the various WHATWG- specs are sorted where they are.

**Comment by tabatkins** [comment]
...wat

**Comment by tabatkins** [comment]
Ohhhhh, I'm sorting on the linktext as it's stored in the DB, not as it's displayed.  So things which are, for whatever reason, specified as being lowercase will sort after the things that are uppercase, but then they all get *displayed* uppercase and look confusing. ^_^
