### ISSUE TITLE
Self-links on biblio entries seem a bit excessive.

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#620]
The self-links on biblio entries seem a bit excessive and noisy. Is there a use case for them? If not, maybe better to not have them...

**Comment by tabatkins** [comment]
It's just a result of them being `<dt>`s with an `id` attribute.  I agree that it's not useful there.  Fixed.

**Comment by mkruisselbrink** [comment]
Informative biblio entries still have self links.

**Comment by tabatkins** [comment]
Ugh, indeed.  Fixing now.
