### ISSUE TITLE
can't remove from the set of ignored specs / can't reference property in css-text-4

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#622]
In the [CSS Mobile Text Size Adjustment Module](https://drafts.csswg.org/css-size-adjust/) I have references to the 'text-wrap' property, which is in css-text-4.  However, css-text-4 defaults to being an ignored spec.  This is perhaps for good reason -- we don't want references going to css-text-4 in *preference* to css-text-3.  But it seems like it should still be possible to reference css-text-4.

One possibility to fix this is to add the ability to remove from the set of ignored specs.

Another possibility is that maybe css-text-4 shouldn't be in ignored specs, but instead there should be a mechanism that *prefers* css-text-3 over css-text-4, but doesn't forbid referencing css-text-4.

(I [worked around this](https://hg.csswg.org/drafts/rev/26a37cb8aed8) by using "Ignored terms", which isn't really the right thing to do.)

**Comment by tabatkins** [comment]
Fixed - if you specify that you want a specific spec (either through link-defaults, like I just added to css-size-adjust, or via `<a spec=...>`) it won't filter according to Ignored Specs, as you presumably know what you're doing.

**Comment by dbaron** [comment]
Thanks!
