### ISSUE TITLE
An "opaque element" open tag in a comment or attr value breaks the rest of the doc

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#623]
I tried to land https://github.com/whatwg/dom/pull/184 but for some reason bikeshed now decided it would no longer auto-insert `<p>`.

**Comment by tabatkins** [comment]
Given the following markup:

```
i'm a paragraph!

<!-- beep beep, comment with a <script> -->

i should be a paragraph, but whoops I'm not
```

The markdown parser misfires on the `<script>` in the comment, and thinks the rest of the document is in a no-parsing block, so the paragraph doesn't get a <p> inserted properly.

**Comment by tabatkins** [comment]
Fixed in a less hacky way than I'd planned! I have a test now that'll exercises this example, too.
