### ISSUE TITLE
Invalid license for Web Platform WG

### ISSUE THREAD

**Issue by plehegar** [tabatkins/bikeshed#626]
The Web Platform uses the perimissive document license, not the default W3C document license.

[[
<a rel="license" href="http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document">permissive document license</a>
]]
https://www.w3.org/TR/selection-api/

for https://github.com/tabatkins/bikeshed/blob/master/bikeshed/include/copyright-webplatform.include

**Comment by tabatkins** [comment]
Okay, Arron just set up the boilerplate wrong.  Fixed.
