### ISSUE TITLE
Changing FATAL/WARNING signalling a little bit

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#627]
Right now all the errors that stop normal spec generation are marked as "FATAL ERROR". This looks really scary if you're first converting a spec, even though most errors are linking errors.  Also, not to denigrate linking errors (they definitely need to be fixed), but they clutter up the output and make it harder to find the *big* errors that might actually screw something up in the spec.

Plan
------
* [x] Switch all the linking errors to say "LINKING ERROR" instead, outputting in a different color. That way the red errors *really* stand out.  (Maybe switch linking errors to yellow, and move WARNINGs to some other color?)
* [x] Don't make linking errors fatal. Specs should still generate with linking errors.
* [x] Output a status message at the end in some cases.  Thinking of "Success, but with X linking errors", "Failure due to fatal errors", and "Success, but fatal errors were suppressed".  No message when things work correctly, as today.

Anyone see anything crazy about this that would super bug them?  @annevk @domenic @dbaron 

(@jyasskin commented elsewhere that he's cool with this.)

**Comment by dbaron** [comment]
Sounds reasonable to me.  You probably want to check with @plinss regarding the CSSWG server infrastructure (which indicates warnings/errors in the [list of CSSWG drafts](https://drafts.csswg.org/), the [list of FXTF drafts](https://drafts.fxtf.org/), and the [list of Houdini drafts](https://drafts.css-houdini.org/)).

**Comment by plinss** [comment]
Works for me. I'm currently looking for '\033[1;31m' in the output to detect the presence of fatal errors, so yeah, use different colors for the different message types. I can easily add another type of message or three and update the bikeshed icons to match. Let's just coordinate the release...

**Comment by annevk** [comment]
I think that's fine.
