### ISSUE TITLE
Add an 'enumerator' definition type

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#628]
This would be useful for things like [`FrameType`](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#contextframetype-enum) and [`PermissionName`](https://w3c.github.io/permissions/#idl-def-PermissionName) where the enumerators should link to their definitions.

**Comment by tabatkins** [comment]
Ugh, mis-click. So!  This already exists; the type is "enum", and it looks like `FrameType` already uses it. Am I misunderstanding your request?

**Comment by jyasskin** [comment]
`FrameType` is an `enum`, but it contains the enumerators (or, WebIDL's term, [enumeration values](http://heycam.github.io/webidl/#dfn-enumeration-value)) "auxiliary", "top-level", "nested", and "none". I want to link to the enumerators too.

**Comment by tabatkins** [comment]
Oh! I would not have used the word "enumerator" for that, so I was confused.  I can probably add an enum-value type.  Let me poke at the IDL markup-er and see what it does.

**Comment by tabatkins** [comment]
They're not currently markup-able by the IDL parser, so I'm seeing if plinns can make that happen for me.

**Comment by tabatkins** [comment]
Done.  The type is `enum-value`.

**Comment by tabatkins** [comment]
Oh, and don't forget the quotes.  They're definitely part of the value!
