### ISSUE TITLE
Bogus reference for UIEvents

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#630]
Generating the DOM spec today with an updated bikeshed:

```diff
-   <dd>Gary Kacmarcik; Travis Leithead. <a href="https://w3c.github.io/uievents/">UI Events Specification</a>. 7 November 2003. NOTE. URL: <a href="https://w3c.github.io/uievents/">https://w3c.github.io/uievents/</a>
+   <dd>Philippe Le Hégaret; Tim Pixley. <a href="https://w3c.github.io/uievents/">Document Object Model (DOM) Level 3 Events Specification</a>. 7 November 2003. NOTE. URL: <a href="https://w3c.github.io/uievents/">https://w3c.github.io/uievents/</a>
```

Everything except the URL now looks bogus... (Maybe not a bug in bikeshed but filing here anyway.)

**Comment by annevk** [comment]
@tobie is this due to your recent change?

**Comment by tobie** [comment]
Yes. What's bogus about that?

**Comment by annevk** [comment]
The URL seems wrong. If a dated reference would work, it should also have the corresponding URL, no?

**Comment by tobie** [comment]
Oh, that. Yeah. Bikeshed should probably not use EDs for dated references.

**Comment by zcorpan** [comment]
Ah and I thought that the URL was the correct piece. :-) The reference here is `[UIEVENTS-20031107]`

**Comment by tobie** [comment]
Yeah, this is what the Web service [gives you](http://www.specref.org/?q=UIEVENTS-20031107) for this:

```json
{
    "versionOf": "uievents",
    "authors": [
        "Philippe Le Hégaret",
        "Tim Pixley"
    ],
    "href": "http://www.w3.org/TR/2003/NOTE-DOM-Level-3-Events-20031107",
    "title": "Document Object Model (DOM) Level 3 Events Specification",
    "status": "NOTE",
    "publisher": "W3C",
    "deliveredBy": [
        {
            "url": "http://www.w3.org/WebPlatform/WG/",
            "shortname": "webplatform"
        }
    ],
    "edDraft": "https://w3c.github.io/uievents/",
    "id": "uievents-20031107",
    "date": "7 November 2003"
}
```

Bikeshed should probably check for the presence of a `"versionOf"` field and if so, use `"href"` instead of `"edDraft"`.

**Comment by tabatkins** [comment]
...I've *really* got to go puzzle over your schema and figure out what your actual data model is.

**Comment by tobie** [comment]
@tabatkins there's an in and an out schema, which I guess is why you get confused.

**Comment by tabatkins** [comment]
All right, fixed. Any entry with a `versionOf` field uses its href for both "dated" *and* "current" biblio references, as it assumes you know what you're doing.
