### ISSUE TITLE
`overlarge` class added to table, causes bad formatting

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#631]
https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/WebBluetoothCG/web-bluetooth/gh-pages/index.bs#example-filter-by-services has a table with broken formatting. This appears to be caused by the `class="overlarge"` on the `<table>`. However, https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/index.bs#L595 doesn't have that class listed. Bikeshed probably shouldn't add it.

**Comment by tabatkins** [comment]
This is added by the fixup.js script required by the W3C. I've filed an issue at <https://github.com/w3c/tr-design/issues/86>
