### ISSUE TITLE
Duplicate CSSOM-VIEW references in DOM

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#636]
See https://github.com/whatwg/dom/pull/191 for details.

**Comment by tabatkins** [comment]
Just noting some details for myself:

* SpecRef has both CSSOM-VIEW and CSSOM-VIEW-1, with the former an alias for the latter.
* Shepherd sees the versioned shortname as CSSOM-VIEW-1, but I should be splitting that into its unversioned shortname and level.

Somewhere between these two I'm conflicting and accidentally not deduping.  Probably related to my improved handling of biblio aliasing recently.

**Comment by tabatkins** [comment]
So, there are two ways I could handle this.

The easy way is to just canonicalize all biblio refs that are aliases in the database to use the "final" form.  I can fix up the biblio ref itself to use the same key, so you don't get the mismatch between biblio ref and index entry.  Unfortunately, this can produce inconsistent display: for example, CSS specs are apparently *totally random* about whether "css3-foo" is the canonical form and "css-foo-3" the alias, or vice versa.

The harder way is to keep track of all aliases, so if you use one of them explicitly in a biblio ref, I can "bless" that as the canonical form and use that for the display of everything else.

Hmmmm, actually the "hard" one isn't too hard.  It will mean I'll have to throw errors if you refer to the same spec two different ways in different biblio refs, but that's probably a *good* thing.

**Comment by tabatkins** [comment]
And done. DOM now generates with `[CSSOM-VIEW]`, matching your explicit biblio ref.

**Comment by domenic** [comment]
Really glad this is fixed (and apparently [DOM] vs. [WHATWG-DOM] is fixed too!). Just as a note:

> So, there are two ways I could handle this.

Honestly I'd really prefer the easy way, so that all Bikeshed-created specs use the same reference names. I think there's a separate problem of updating the relevant databases so that the canonical names are sensible, consistent, and preferably always uppercase, but personally I'd rather live with some css3-foos and some css-bar-3s in my bibliography, than deal with switching between specs and sometimes seeing css3-foo and sometimes css-foo-3.

**Comment by tabatkins** [comment]
The "easy way" would mean that [DOM] vs [WHATWG-DOM] switches to the *other* spelling. ^_^

I don't think it's a big deal that specs can use different names for the same references? I mean, that's the whole point of having aliases.  The "easy" fix for this is to just drop all SpecRef aliases on the floor so you  *have* to use the correct "base" name.  

I don't have a problem, in the ideal future where all the "base" names are the "preferred" form, with switching this over to being opinionated and canonicalizing everything to use the base name.  But I think it would be a regression today, with the current database we have, to do so.  People usually know what's what and use the "best" names already.

**Comment by domenic** [comment]
Would it be specref that I would have to go update to get us to that ideal future?

**Comment by domenic** [comment]
Could we also make a list of the cases where the base name is not the preferred form? I know WHATWG-DOM, and I guess you've cited some CSS inconsistencies; could you narrow that to specific cases?
