### ISSUE TITLE
Quotes should not be part of the enum's identity

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#637]
That just looks wrong. An enum value is not `"example"`. It's "`example`".

**Comment by tabatkins** [comment]
An enum value is always and forever a string, which is why I'm including the quotes currently.  Why do you think it should exclude the quotes?

**Comment by annevk** [comment]
I think quotes should be there, but not as part of the value. The syntax used to denote strings can vary, so what you want to copy and reuse is `example`, not `"example"`.

**Comment by tabatkins** [comment]
I don't understand. In what way can the syntax to denote strings change?  Are you just talking about which choice of quotes you use?

**Comment by annevk** [comment]
Yeah, the problem is that " is syntax. I don't like including that in the term.

**Comment by tabatkins** [comment]
All I can say is that I strongly disagree. The other IDL terms are either terms of art, or correspond to idents in JS, both of which obviously get used "directly".  Enum values correspond to strings in JS; you'd never use them without quotes.

You can override the handling if you really want to - provide a `<dfn enum-value for="MyEnum" lt='"foo" | foo'>foo</dfn>` for all the enum values.  That'll give you the linking text you want, and make sure the IDL recognizes the dfn.

Or I guess I can have enum-values automatically provide both linking texts when they're parsed in IDL, so you can use either.

**Comment by annevk** [comment]
Maybe I should put this another way, can the markup look like `<span>"<code>string</code>"</span>`?

**Comment by tabatkins** [comment]
Yes, if you create that markup pattern yourself. ^_^

I'm just going to do what I said above - have enum-values define themselves both with and without quotes.

**Comment by tabatkins** [comment]
Done.
