### ISSUE TITLE
Bad encoding in https://api.csswg.org/bikeshed/

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#641]
https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permission-delegation-api/bikeshed/index.bs&output=both has a bunch of `â€` junk that I believe is caused by the `data:` urls for the iframes not specifying an encoding.

**Comment by tabatkins** [comment]
I've reported this to @plinss. Closing on this end, as it's not technically a Bikeshed bug.

**Comment by plinss** [comment]
Technically it's a bug in Chrome, but I added the encoding to the data urls to work around it.
