### ISSUE TITLE
<dfn>s inside headings

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#648]
I moved from

```html
<h4 id="rs-constructor">new ReadableStream(underlyingSource = {}, { size, highWaterMark = 1 } = {})</h4>
```

to

```html
<h4 id="rs-constructor">new <dfn constructor for="ReadableStream">ReadableStream(underlyingSource = {}, { size, highWaterMark = 1 } = {})</dfn></h4>
```

and now people have two ways to link to the ReadableStream constructor: the section marker on the left, which links to #rs-constructor, and the hash marker on the right, which links to #dom-readablestream-readablestream.

Could we have dfns inside headers get collapsed into somehow together into a single id and margin link (probably the section one)?

**Comment by tabatkins** [comment]
Just move the dfn attributes to the heading, and remove the `<dfn>` element entirely.  Headings are allowed to provide definitions.

In other words:

```
<h4 id="rs-constructor" constructor for=ReadableStream lt="ReadableStream()">
new ReadableStream(underlyingSource = {}, { size, highWaterMark = 1 } = {})</h4>
```

**Comment by domenic** [comment]
Ah, this is lovely, thank you!
