### ISSUE TITLE
Allow % in interface names

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#649]
ES defines several "intrinsic" interfaces, e.g. %Uint8Array%. Bikeshed won't let me mark those up inside `<pre class="anchors">` or while using `{{%Interface%}}` syntax. Would be nice.

**Comment by tabatkins** [comment]
Hmm, this works just fine for me:

```
<pre class='anchors'>
url: http://example.com#foo; type: interface; text: %Foo%
</pre>

{{%Foo%}}
```

Can you provide an example of the markup that's failing for you, and describe the error in more detail?

**Comment by domenic** [comment]
Oh, I bet it's because I'm inside an opaque element... dang... yeah, confirmed. I'll have to think better about how/whether I want to do autolinking inside those.

**Comment by tabatkins** [comment]
Opaque elements still get autolinked, they just don't process any shorthands.  Feel free to use `<a idl>...</a>` instead of `{{...}}`, as the two are exactly equivalent.
