### ISSUE TITLE
Methods must end with () error even when they do

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#650]
Neither of the following work:

```html
<h5 id="rs-cancel" method for="ReadableStream" lt="ReadableStream.prototype.cancel(reason)">cancel(reason)</h5>
```

it gave the error

```
FATAL ERROR: Functions/methods must end with () in their linking text, got 'ReadableStream.prototype.cancel(reason)'.
```

I thought maybe the exact string "()" is important so I tried

```html
<h5 id="rs-cancel" method for="ReadableStream" lt="ReadableStream.prototype.cancel()">cancel(reason)</h5>
```

(even though I prefer to have the arguments listed). But this didn't work:

```
FATAL ERROR: Functions/methods must end with () in their linking text, got 'ReadableStream.prototype.cancel()'.
```

**Comment by tabatkins** [comment]
Ah, sorry, that error message isn't actually exhaustive enough. It triggers whenever your method fails the regex `^[\w-]+\(.*\)$`.

In particular, it's angry about the `.`s in your `lt`.  I'm not sure why you're writing it that way; the correct `lt` is just `cancel(reason)`.

**Comment by domenic** [comment]
Well, I think it's a more descriptive name for the method, especially with regard to how I'd want it to appear in the appendix.

**Comment by tabatkins** [comment]
This sounds like you trying to describe things in "real JS" rather than IDL, yeah?  The IDL types aren't appropriate for that, and I haven't designed anything for "real JS" yet.  (And until implementors are happy with "real JS", I probably won't; better to make it difficult until its accepted as something reasonable.)

**Comment by domenic** [comment]
Oh, yeah, I'm trying to use this on streams, which is written as JS. I thought last time I brought these up the idea was to use the lookalike types, e.g. an internal slot is basically an attribute, a property is an attribute, a class is an interface, etc.

**Comment by tabatkins** [comment]
In that case, just use the definitions like they were IDL, and leave off the rest. ^_^  Or provide multiple linking texts, like `lt="cancel(reason) | ReadableStream.prototype.cancel(reason)"`.  They'll both show up in the index, but the first will be used to generate the ID (which is *definitely* what you want here).

**Comment by domenic** [comment]
Well, as per #648, I already have IDs for all of these (those of their containing headings).

**Comment by tabatkins** [comment]
Ah, kk. In that case the ID reasoning isn't important for you, but I still do classification and some other stuff off the first variant, so putting the "IDL version" first is still best.  And like I said, the "JS version" will then show in the index like you want, too.

**Comment by domenic** [comment]
Hmm, I guess I have a different vision for the appendix than you do; I'd prefer it to contain only a single link to the method definition, identified by its canonical long-form name. Not a big deal I guess, but that explains the mismatch. I noticed that it also generates duplicate appendix entries for overloads (e.g. `lt="pipeThrough(transform) | pipeThrough(transform, options)"`).

**Comment by tabatkins** [comment]
It's an index, not an appendix, and it's quite normal for an index to contain variations on a term that all refer to the same spot.

(The IDL Index is, indeed, an appendix, and it just contains all the IDL you've written, once, linking back to the canon definitions.)
