### ISSUE TITLE
Unknown tags get spaces introduced before and after them

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#653]
Input:

```html
The attributes of these properties must be { \[[Writable]]: <emu-val>true</emu-val>, \[[Enumerable]]: <emu-val>false</emu-val>,
\[[Configurable]]: <emu-val>true</emu-val> }.
```

Output:

```html

   <p>
    The attributes of these properties must be { [[Writable]]: 
    <emu-val>true</emu-val>
    , [[Enumerable]]: 
    <emu-val>false</emu-val>
    ,
[[Configurable]]: 
    <emu-val>true</emu-val>
     }.
   </p>
```

This adds spaces between "true" and the following comma.

**Comment by tabatkins** [comment]
Ah yeah, I have a list of HTML's inline elements, which get serialized inline properly, but everything else is assumed to be block and serializes as such.

Given that whether an element is inline or not also affects markdown parsing (when the tag is at the beginning of the line, it influences whether it'll trigger `<p>`-insertion based on inline vs block), I guess I need to take some metadata dictating which custom elements are inline vs block.

Do you have a preferred default?

**Comment by domenic** [comment]
I think Markdown has a whitelist of block elements. That's what we did in Ecmarkup. That also seems a better default since someone can always type an extra p tag if they need it.

**Comment by tabatkins** [comment]
Okay, fixed.  Custom elements now default to being parsed and serialized as inline, and there's a new `Block Elements` metadata (parallel to `Opaque Elements`) that lets you override that if you want.
