### ISSUE TITLE
Syntax highlighting gets turned off if you add links

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#654]
```html
<pre><code class="lang-javascript">
  class ReadableStreamDefaultReader {
    constructor(stream)

    get closed()

    cancel(reason)
    read()
    releaseLock()
  }
</code></pre>
```

gets syntax highlighted, but

```html
<pre><code class="lang-javascript">
  class <a idl>ReadableStreamDefaultReader</a> {
    constructor(stream)

    get closed()

    cancel(reason)
    read()
    releaseLock()
  }
</code></pre>
```

loses all highlighting.

**Comment by tabatkins** [comment]
Yup, because syntax highlighting takes text and outputs markup; it'll destroy any links or other markup you have.  I defensively don't highlight things with markup.

(And no, I don't know of any major Python highlighting libraries that work on DOM trees.)
