### ISSUE TITLE
When using the spec attribute it should still pick the first logical definition

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#660]
I have this primarily with HTML. HTML has a bunch of terms named origin, but all but one are marked `data-noexport=""`. So to disambiguate from origin in URL and CSS I think, I know, I use `spec=html`. Wrong. It now picks the first `<dfn>` in HTML, regardless of whether that has `data-noexport=""` specified. It should only do that if there's no explicit exported definition, imo.

**Comment by tabatkins** [comment]
Obviously this is the result of me overloading the meaning of `spec` on an autolink - it *also* indicates that you're okay with getting an unexported ref from that spec.

I'm inclined to close this in favor of just fixing #797; once I switch to that model, the "I want a private definition" flag is a separate thing.

The error message has at least been improved - at the time this was reported, all four of the HTML "origin" definitions were indistinguishable, and Bikeshed didn't output a good error for that, but it does now.  Now they've all got disambiguating `for` values, so they're fine.
