### ISSUE TITLE
Pubrules Issues

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#665]
TR drafts need a few tweaks:
  * Don't link to the csswg.ico
  * Use http not https links to www.w3.org

Pubrules is currently totally broken, so may find some more issues later.

**Comment by plehegar** [comment]
Here is the proposal to switch to https:
https://lists.w3.org/Archives/Public/spec-prod/2016AprJun/0024.html

**Comment by svgeesus** [comment]
Yes, I always have to delete this line on /TR documents:
<link href="../csslogo.ico" rel="shortcut icon" type="image/x-icon">

**Comment by svgeesus** [comment]
also
- change ../default.css to default.css
- move stylesheet link to /TR stylesheet to after all the other style rules

**Comment by svgeesus** [comment]
For FPWD, the "Latest" link has to be added manually

**Comment by tabatkins** [comment]
The Latest link is just generated by the `TR` metadata, which doesn't make sense to add until you actually get something up on TR (or are just about to).

Everything else is now handled automatically by the publishing script.

**Comment by svgeesus** [comment]
> Everything else is now handled automatically by the publishing script.
Re-opening because this is still an issue. Every time I manually publish a FPWD, CR or PR  I have to make these same edits.

If this is really fixed, please document what needs to be changed in the .bs besides changing Status: ED to Status: FPWD|CR|PR

**Comment by tabatkins** [comment]
Which edits, the ones you mention up above? As I said, those are handled by the autopublish script; if you're publishing manually, you do indeed need to do those yourself.  The list of things that you need to do yourself if basically "what pubrules complains about".

(I did put in a requirement just now that the `TR` metadata be added to any snapshot-status spec, so a FPWD will complain if you forget to add it.)
