### ISSUE TITLE
Allow one DFN to have multiple for= targets

### ISSUE THREAD

**Issue by travisleithead** [tabatkins/bikeshed#667]
Been happily editing HTML for a bit, and have run into a few capability mismatches. Due to spec factoring, it is relatively common to have a particular IDL or content attribute definition which is re-used is across multiple elements/interfaces. For example, in defining the HTML form elements, the "name", "autocomplete", etc., IDL and content attributes link to one section that describes how the attribute works.

Now, for content attributes, I make all the references to the definition, so I can set them up however I like. E.g., to link to the autocomplete definition `<dfn element-attr for="formcommon">autocomplete</dfn>` I can just use `<{formcommon/autocomplete}>` in each of the multiple elements that support this content attribute. 

However, I also have to deal with the auto-generated (er--regenerated) WebIDL blocks, where built-in refs are created that I don't control. In these cases, I am constrained in the definition in order to have the IDL blocks link to their definition. E.g., I must define like `<dfn attribute for="HTMLInterfaceHere">autocomplete</dfn>` or the `attribute DOMString autocomplete` will not be a link.

Given the above-mentioned constraint, if I have multiple WebIDL blocks that contain the same IDL definition, but I want them all to link to a common definition (which is what the WHATWG spec does), I can't. Instead, the workaround is to have multiple 'redirect' landing definitions that then lead the reader to the common definition.

My ask is that a dfn's `for` attribute be extended to support N targets instead of just 1. In this way I could create a single dfn that effectively self-replicates becoming the target for multiple interfaces. E.g., something like: `<dfn attribute for="HTMLInterface1|HTMLInterface2">autocomplete</dfn>`

**Comment by mkruisselbrink** [comment]
You can already comma-separate multiple for= target as far as I know...

**Comment by tabatkins** [comment]
Yup, comma-separation does it.  (Sorry that this is inconsistent with defining multiple link-texts. Legacy mistake, can't easily be fixed now.)

**Comment by travisleithead** [comment]
Woot!!! Awesome!
