### ISSUE TITLE
Unable to link to partial interfaces

### ISSUE THREAD

**Issue by arronei** [tabatkins/bikeshed#676]
```html
<pre class='metadata'>
Title: Test
Status: WD
TR: http://www.w3.org/TR/SpecName/
ED: http://www.w3.org/TR/SpecName
Previous Version: http://www.w3.org/TR/SpecName
Shortname: SpecName
Level: 1
Editor: John Doe, AnOrg., AnOrg@mail.com
Abstract: Abstract sentence
</pre>

<dfn attribute for=Foo>bar</dfn>
<dfn attribute for=Foo>baz</dfn>

{{Foo!!interface}}
{{Foo}}

<pre class=idl dfn-for=Foo>
partial interface Foo {
    attribute DOMString bar;
};
</pre>

<pre class=idl dfn-for=Foo>
interface Foo {
    attribute DOMString baz;
};
</pre>
```

maybe we can link like this `{{Foo!!partial-interface}}`

The IDL index doesn't seem to link correctly either in this case. I would expect the IDL Index, partial interface to link to the partial interface definition.

**Comment by tabatkins** [comment]
This is correct and intentional - partial interfaces don't `<dfn>` a new interface-type term, they just link up to the base definition.  You can link to the new things you're actually defining, tho.
