### ISSUE TITLE
Missing definition of term defined in header

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#678]
`bikeshed refs --text '"geolocation"'` returns data from https://w3c.github.io/permissions/, proving that spec is in Shepherd, but `bikeshed refs --text 'permission store'` returns nothing even though the spec includes:

``` html
<h2 class="heading settled dfn-paneled" data-dfn-type="dfn" data-export=""
 data-level="5" data-lt="Permission Store" id="permission-store"><span 
class="secno">5. </span><span class="content"> Permission Store </span><span 
class="dfn-panel" data-deco=""><b><a 
href="#permission-store">#permission-store</a></b><b>Referenced in:</b><span><a
href="#ref-for-permission-store-1">4. 
    Permission Registry </a></span></span></h2>
```

**Comment by tabatkins** [comment]
The described heading no longer seems to exist.  Did you work around the issue?

**Comment by jyasskin** [comment]
I avoided defining a term in a header the next time I updated that region of the spec.
