### ISSUE TITLE
Weirdness around `Level: 1`

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#683]
The CSSWG seems to publish new specifications as explicitly `Level: 1`, both in the document and in the shortname URL in `/TR` space (e.g. `http://www.w3.org/TR/2016/WD-whatever-1-20160101`). Other groups seem to leave off the level when there's no indication that level 2 is coming (e.g.  `http://www.w3.org/TR/2016/WD-whatever-20160101`).

Bikeshed will produce the latter URL if `Level: 1` is not present in the document's metadata, but throws a fatal error while doing so if the document's status is `WD`.

@wseltzer tells me that W3C folks prefer to leave off the level (see https://github.com/w3c/webappsec-secure-contexts/issues/25#issuecomment-214290700).

I'm not sure what the _correct_ behavior is, but it would be nice to have things worked out, either by adjusting Bikeshed, or by adjusting the W3C. :)

**Comment by mikewest** [comment]
Opened https://github.com/tabatkins/bikeshed/pull/696 as a suggested solution.

**Comment by tabatkins** [comment]
Went ahead and wrote this myself. ^_^

**Comment by mikewest** [comment]
Ah, sorry. I forgot about this.

Thanks for taking it and cleaning it up! :)

**Comment by tabatkins** [comment]
np, let me know if it causes issues. I didn't extensively test it.
