### ISSUE TITLE
em dashes shouldn't get suffixed with <wbr>

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#686]
Em dashes are defined to have a line break opportunity both before and after the em dash. Adding <wbr> is redundant and therefore silly.

**Comment by tabatkins** [comment]
Yeah, looks like you're right.  I'll remove that little hack.

**Comment by tabatkins** [comment]
Never mind, apparently Firefox doesn't linebreak around em dashes properly. Reopen this when they do.
