### ISSUE TITLE
dfn-panels no longer stay visible after you click a use.

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#690]
Some time in https://github.com/tabatkins/bikeshed/compare/ca4f7b75...e2ae065, dfn-panels stopped getting 'position:fixed' to the bottom-left corner when I click on a use. The panel stays visible in its original location, but that's now off-screen and not useful.

**Comment by tabatkins** [comment]
Probably a misfire in the code to recognize that you're clicking a link in the <dfn>. I'll have to make it smarter to still recognize links in the panel.

I'm planning to rewrite it a little to make all the panels be children of <body> anyway, so that'll clear up these issues easily.

**Comment by tabatkins** [comment]
Fixed!
