### ISSUE TITLE
`algorithm` attribute with no value should use its sole contained <dfn>

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#699]
If I write:
```html
<div algorithm>
  <p>The <dfn export>some definition</dfn> does the following:</p>
  <ol><li>Step 1</li><li>Step 2</li></ol>
</div>
```
that should "work", by pulling the algorithm name out of the definition. It should fail if there are two contained `<dfn>`s, since then it's not clear which algorithm is being defined in the block.

**Comment by tabatkins** [comment]
Interesting! I'm happy to make this work better (heading-algorithms can omit the value), and this seems pretty good.

**Comment by tabatkins** [comment]
Done.
