### ISSUE TITLE
Need to put a bikeshed version tag into the output document

### ISSUE THREAD

**Issue by szager-chromium** [tabatkins/bikeshed#715]
If I run the latest version of bikeshed on an unchanged .bs file, and it produces very different output, it would be nice to have a bikeshed version tag in the html so I can tell that bikeshed version drift is the reason.

**Comment by tabatkins** [comment]
I already output a version tag, I just don't update it. I guess this is actually asking for me actually follow some sort of semantic versioning?

**Comment by szager-chromium** [comment]
Where is the version tag in generated html?

**Comment by tabatkins** [comment]
Right where it's supposed to be - `<meta name=generator content="Bikeshed 1.0.0">`

**Comment by szager-chromium** [comment]
I see; then yes, my request is that the version be incremented, and that it always match a tag in the repository.

**Comment by tabatkins** [comment]
It sounds like you're asking for tagged releases that you can pin yourself to?

I'm not currently planning on doing that.
