### ISSUE TITLE
Internal stylesheets must be cascaded before the W3C style

### ISSUE THREAD

**Issue by deniak** [tabatkins/bikeshed#719]
From https://www.w3.org/2005/07/pubrules?uimode=filter&uri=#metadata, the internal stylesheets must precede the W3C stylesheet.
This is now enforced in specberus making all the bikeshed documents fail that check.

**Comment by tabatkins** [comment]
Yup, this is being handled by the under-construction `Prepare For TR` metadata, which does a number of arbitrary fixes to make things pass pubrules. Currently only defined for CSSWG, but once I decide this is ready I'll auto-apply it to all the relevant W3C WG boilerplates too.

**Comment by tabatkins** [comment]
(Currently this is expected to be handled manually, like the dozen other little fixes you need to do to prep for TR.)
