### ISSUE TITLE
Double ampersand (&&) is not linked to CSS Values spec

### ISSUE THREAD

**Issue by SebastianZ** [tabatkins/bikeshed#721]
The [double ampersand combinator (&&)](https://drafts.csswg.org/css-values-3/#comb-all) in values is not linked to the CSS Values and Units Module.

See the [`pad` descriptor of the `@counter-style`](https://drafts.csswg.org/css-counter-styles/#descdef-counter-style-pad) rule for example.

Sebastian

**Comment by tabatkins** [comment]
fixed, thanks! I was assuming && would always be escaped, but it doesn't actually need to be in practice.
