### ISSUE TITLE
Add shortcut autolink syntax for plain <dfn>s

### ISSUE THREAD

**Issue by inexorabletash** [tabatkins/bikeshed#722]
Using `<a>foo</a>` to link to `<dfn>foo</dfn>` is fairly succinct until `for="..."` is needed to disambiguate. In a spec with a top level definition (_a foo is a ..._), but also similarly named of abstract types (_a bar has a foo..._), it is necessary to write `<a for=/>foo</a>` everywhere to refer to the former, which gets verbose real quick.

For IDL and other more specific definition types with autolink shortcuts the syntax `/foo` can be used. Could we get an autolink shortcut syntax for plain old dfns?  I don't know if re-using `'single quotes'` is possible (i.e. adding dfns to the union) or if a new grawlix is needed.

(It's entirely likely I'm "doing it wrong" and this problem goes away if the definitions are structured differently. In which case, thanks in advance for the advice!)

**Comment by domenic** [comment]
I think the real problem here is not being able to set a default for=/ value. I remember trying to do that a while ago and @tabatkins telling me it should be possible and then running into edge cases where it was not possible...

**Comment by tabatkins** [comment]
There already was such a shorthand, it just wasn't documented - `[=foo=]` is a shorthand for the "dfn" type.

I updated all the docs to actually document this stuff.  I also:

1. Fixed shorthands that want to link to the non-for version of the definition. (Do `[=/foo=]`, as expected.)
2. Made every autolinking shorthand allow overriding the text, via the `|new text` suffix.
