### ISSUE TITLE
How to: both define a term and link elsewhere?

### ISSUE THREAD

**Issue by travisleithead** [tabatkins/bikeshed#723]
Hi Bikeshed experts,

In W3C/HTML, I want to support the "Dependencies" section by defining a term, let's say "get an encoding" such that all local `<a>get an encoding</a>` links in the spec will jump to the `<dfn>` in the dependencies section, but I also want that dependencies definition to be a link out to the Encoding spec where the term is defined.

This is nicely handled in WHATWG/HTML today, by popping a flyout with an additional link to the external definition.

The best I can do today is use a non-autolinking anchor inside a dfn. Given the above example, it would look like this:
`<dfn><a href="https://www.w3.org/TR/encoding/#concept-encoding-get">Getting an encoding</a></dfn>`

This has the desired effect, but also requires me to use a full anchor, which:
1. obliterates the useful flyout that, when clicked, shows the links to the term 😢 
2. requires me to specify a whole lot of redundant hrefs.

Is there a way to get the effect I want today? Or is this a feature in the backlog, e.g., https://github.com/tabatkins/bikeshed/issues/356?

**Comment by mkruisselbrink** [comment]
This almost sounds like it should be some kind of mode for the already generated "Terms defined by reference" section. Unless of course you only want this behavior for some external terms but not all...

**Comment by tabatkins** [comment]
Why do you want to link internally, rather than jump out to the actual definition?  What's useful to the reader about not actually going to the term's definition when they click the link?

The "dependencies" section that is common among WHATWG specs is mostly an obsolete holdover from the Anolis days, when cross-spec linking didn't exist.

**Comment by mkruisselbrink** [comment]
One thing currently missing with this jumping to the external definition is the dfn.js integration internal definitions have. There doesn't seem to really be a way to figure out where an externally defined term is used in the current spec.

**Comment by tabatkins** [comment]
Ah, that is true.  I'll have to think on that.

**Comment by tabatkins** [comment]
Moving the specific "how to find all local uses of an externally-defined term" issue to #1026. Closing this issue, as the rest of the topic is "don't do that".
