### ISSUE TITLE
Add automatic treating of CSS shorthand properties

### ISSUE THREAD

**Issue by SebastianZ** [tabatkins/bikeshed#724]
It should be possible to mark a CSS property as shorthand for other properties and fill in the different property definitions like 'see individual properties' or 'n/a' for the initial and computed values, percentages and animation type automatically.

Sebastian

**Comment by SebastianZ** [comment]
Oh, I just saw that this is [already implemented](https://github.com/tabatkins/bikeshed/blob/77f5e21872bbf694338268a3b1a2519a10b748d3/bikeshed/datablocks.py#L183-L184).

So, please forgive the noise!

Sebastian

**Comment by tabatkins** [comment]
np ^_^
