### ISSUE TITLE
Definitions with | in their text can't be defined

### ISSUE THREAD

**Issue by SebastianZ** [tabatkins/bikeshed#727]
There's not currently any way to define something with a `|` in its text, as `|` is used to separate definition texts instead.  Previously you could do so if you relied solely on the literal text, but now I eagerly load the literal text into the `lt` attribute and then clean up duplicated text afterwards; this means that nowhere is safe.

I need an escaping mechanism for this character, and then to apply it automatically when putting the literal text into the `lt` attribute.

---
**Original text of issue:**

When a `<dfn>` element contains a function, the parser should interpret the whole function name to distinguish it from previous definitions. Though instead it looks like it only checks parts of the definition.

An example can be seen here:
https://drafts.csswg.org/bikeshed/css-page-floats/

The output says this:
> FATAL ERROR: Multiple local 'value' <dfn>s for 'float' have the same linking text 'right'.
> FATAL ERROR: Multiple local 'value' <dfn>s for 'float' have the same linking text 'near ]?)'.

for the following two definitions:

    <dfn>snap-block(&lt;length> [, start | end | near ]?)</dfn>
    <dfn>snap-inline(&lt;length> [, left | right | near ]?)</dfn>

Sebastian

**Comment by tabatkins** [comment]
Ugh, this is an unexpected result of me eagerly copying the definition text into `lt` and it colliding with the syntax to introduce multiple definition texts.

It's also a result of this particular spec being marked up slightly wrong. I can fix the spec right now; I'll rewrite this issue to reflect the deeper problem accurately.
