### ISSUE TITLE
Figure counter-increment conflict

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#728]
When using /TR styles, Bikeshed should not include any counter-increment rules as they already exist in base.css.

This is currently causing a conflict because base.css increments on figcaption and .caption, whereas Bikeshed increments on figure, and the figure counter therefore goes up by two instead of by one. See https://github.com/w3c/csswg-drafts/issues/177

**Comment by tabatkins** [comment]
Yeah, I'll move the counter-increment to figcaption to match, so they'll just collide with each other rather than interacting.
