### ISSUE TITLE
"Privacy and Security Considerations" warning.

### ISSUE THREAD

**Issue by frivoal** [tabatkins/bikeshed#730]
It would be nice if Bikeshed would allow for more variation in the name of this section.

For instance, CSS-UI-3 and CSS-UI-4 have an `Appendix C. Considerations for Security and Privacy `section, which isn't being recognized. I'd be totally OK with switching that to `Appendix C. Privacy and Security Considerations`, but I'd like to keep `Appendix C` in there.

Could you either:
- match on the ID of the element (and document what it needs to be) instead of the title
- match if the element **contains** `Privacy and Security Considerations` instead of being exactly that phrase

**Comment by tabatkins** [comment]
Done. As long as the word "privacy", "security", and "considerations" occur in a header, you're good.
