### ISSUE TITLE
If check for no references in boilerplate.py seems incorrect

### ISSUE THREAD

**Issue by brycelelbach** [tabatkins/bikeshed#731]
I believe that [boilerplate.py:653](https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate.py#L653) is doing the wrong thing:

```
if len(doc.normativeRefs) == 0 and len(doc.informativeRefs) is None:
```

The second part of the check, `len(doc.informativeRefs) is None` seems to be wrong - `len()` should never be `None`, we want to check if it's zero (just like the first part).

**Comment by tabatkins** [comment]
Yeah, that's just plain dumb. Thanks for the catch!
