### ISSUE TITLE
Guidance on how to include angle brackets in code examples in bikeshed

### ISSUE THREAD

**Issue by brycelelbach** [tabatkins/bikeshed#733]
For C++, we'd like to be able to use angle brackets in inline and blockquoted code. E.g.

I'd like to be able to talk about `vector<>` and talk about:

```
vector<int> a(10);
a.push_back();
```

Ideally, we'd like to not have to use HTML escapes. What would be the best way for us to do this?

ATM in bikeshed we're doing `<code highlight="c++">vector&lt;&gt;</code>`.

**Comment by tabatkins** [comment]
Note: you never need to escape `>` in text (only in unquoted attribute values).

You can use the deprecated HTML element `<xmp>` for code blocks; it's styled like a `<pre>` but interprets everything until the closing `</xmp>` as literal text.  Bikeshed automatically rewrites it into a `<pre>` before output, and the serializer takes care of escaping things for you.

I don't have an inline variant, but I'd be up for adding one.  At minimum, at some point I'm going to add in support for Markdown's `` `literal` `` syntax, which'll allow it.  I can probably do, like, an `<ixmp>` fake element for now that gets rewritten into a `<span>` with its contents escaped.

(Also, note that if all your `<code>`/`<pre>` is C++ code, you can put the `highlight` attribute on some ancestor element, so you don't have to spam it into every code sample.)

**Comment by jfbastien** [comment]
Ha the `highlight` trick is nice.

@brycelelbach was trying to get an inline element, so `code quote` support would be very nice :D

**Comment by tabatkins** [comment]
Oh, interesting, I'd forgotten that I *do* have support for Markdown code spans.  So you can do that, I suppose.

Like:

```
Create a `vector<int>` and frob it.
```

This doesn't let you set the highlight language directly, so you'll *have* to put it on an ancestor.  (Or wrap that code in a `<span highlight=c++>`, but that shouldn't be necessary.)

You just have to turn on inline markdown support with a `Markup Shorthands: markdown yes` metadata.

**Comment by jfbastien** [comment]
The following doesn't seem to work at the moment:

```
<pre class='metadata'>
Title: Foo
Shortname: bar
Status: FINDING
Group: WG21
URL: http://example.com
Editor: JF Bastien, Google, jfb@google.com
Abstract: Foo
Date: 2016-07-12
Markup Shorthands: markdown yes
</pre>

<article hightlight="c++">

Title
=====

Here be example:

\```
  std::atomic&lt;int&gt; x;
  std::atomic&lt;int&gt; y;
\```

</article>
```



Highlight isn't working, and it transforms the triple-quote to `<p><code>` sections instead of `<pre>` blocks (so linebreaks get broken).

**Comment by tabatkins** [comment]
Correct, I don't (yet) support Markdown-style code blocks, so that's instead being recognized as an inline code span starting a paragraph.
