### ISSUE TITLE
Be smarter when applying propdefs to CSS shorthands

### ISSUE THREAD

**Issue by SebastianZ** [tabatkins/bikeshed#734]
If all longhands of a CSS shorthand property have the same value for a property definition, the shorthand should also get that value assigned instead of the general 'see individual properties'.

**Example:**
The 'flex' property covers 'flex-grow', 'flex-shrink' and 'flex-basis' and all three have 'Applies to: flex items', 'Inherited: no' and 'Media: visual', so those values should also be applied to the shorthand property.

So, in the end the property definition for 'flex' may look like this:

```
Name: flex
Value: none | [ <‘flex-grow’> <‘flex-shrink’>? || <‘flex-basis’> ]
Initial: see individual properties
Applies to: flex items
Inherited: no
Percentages: see individual properties
Media: visual
Computed value: see individual properties
Canonical order: per grammar
Animation type: see individual properties
```

Also the definitions for 'Percentages', 'Computed value' and 'Animation type' may be joined, which results in this:

```
Name: flex
Value: none | [ <‘flex-grow’> <‘flex-shrink’>? || <‘flex-basis’> ]
Initial: see individual properties
Applies to: flex items
Inherited: no
Percentages: ‘flex-basis’ part relative to the flex container’s inner main size, rest n/a
Media: visual
Computed value: ‘flex-basis’ part as specified, with lengths made absolute, rest as specified
Canonical order: per grammar
Animation type: ‘flex-basis’ part discrete for keywords, otherwise as length, percentage, or calc, rest numer
```

Percentages may also look like this:

```
Percentages: percentages allowed in ‘flex-basis’ part
```

Though joining different longhand values may result in long definitions in case there are several different longhand values.

Having said that, the values of 'Applies to', 'Inherited', 'Media' and 'Computed value' actually apply to the shorthand itself, so if they're not set they may be set to their default values like 'Applies to: all elements' or 'Media: visual', or throw an error like in case of 'Inherited'. See also https://github.com/w3c/csswg-drafts/issues/223.

Sebastian

**Comment by tabatkins** [comment]
The reason they're all "see individual properties" is because shorthands *don't have those qualites*.  Shorthands don't have an inheritance value, because they go away before inheritance happens.  They don't have Computed Values/etc either for the same reasons.  Shorthands just get torn apart into longhands immediately during parsing, usually with some defaulting (sometimes just to the initial values, sometimes based on more complex algos).

Shorthands have Names, Values, and Canonical Orders (for serialization), that's it.
