### ISSUE TITLE
WG21 things

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#739]
* [x] `Revision` (number) and `Audience` (@jfbastien will provide the list of valid vaues) as required metadata for the group.
* [x] Make `Revision` an alias for `Level`.

**Comment by jfbastien** [comment]
From: https://isocpp.org/std/the-committee
Audience is a comma separated list of:

* CWG
* LWG
* EWG
* LEWG
* SG[1-9][0-9]*

Where the last one is a regex because we're lazy and every so often we add a new subgroup.
