### ISSUE TITLE
Wg21 specref

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#741]
WG21 uses wg21.link as its URL shrtnr. It has this neat list: http://wg21.link/index.json
We need to massage the list into specref, and magic will happen.

/sub #713

**Comment by tobie** [comment]
Merged this. It seems to be holding on pretty well so far. (I was worried about the startup times as all the data is held in memory and building it up can timeout the max startup time allowed by Heroku.)

So it's live for now. For example: http://www.specref.org/?q=CWG393

**Comment by jfbastien** [comment]
@tobie thanks for doing this :-)

I poked around a bit and the site seems to do exactly what I expect. I also [updated a paper to use specref](https://github.com/jfbastien/papers/commit/ebf5df9e1dc09fe2354176132d29f06f9e65022f), and it works exactly as expected.

/cc @brycelelbach @jyasskin
