### ISSUE TITLE
Spec diff support

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#744]
We love `<ins>` and `<del>`, but sometimes you don't want to see `<del>` and you just want `<ins>`.

SPEC DIFF TO THE RESCUE!

With SPEC DIFF you can just show the spec as it would look!
e.g. that little checkbox at the top of http://wg21.link/n4430

(SPEC DIFF is a horrible misnomer)
(SPEC DIFF may lead to drowsiness)
(as your doctor if SPEC DIFF is right for you)

**Comment by tabatkins** [comment]
```
<!DOCTYPE html>
<body>
<input type=checkbox id=foo style="display:none">
<p>bar
<p>foo <label for=foo>click this</label>
<style>
#foo:checked ~ p, #foo:checked ~ * p { background: blue; }</style>
```

**Comment by jfbastien** [comment]
#754 is still missing a checkbox or some pretty magic to the clickedy-click thing (it's just text right now).

**Comment by jfbastien** [comment]
> #754 is still missing a checkbox or some pretty magic to the clickedy-click thing (it's just text right now).

I added the checkbox in https://github.com/tabatkins/bikeshed/pull/754/commits/91bbb61faa1a344786e4fe1cbbba7022406bf43b
