### ISSUE TITLE
Wg21 papers need ascii encoding

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#746]
Sadly, the wiki for C++ meetings (wiki.edg.com) has a latin-1 encoding, which it enforces using an HTTP header that overrides the `<meta content="text/html; charset=utf-8" http-equiv="Content-Type">` in Bikeshed output. e.g. http://wiki.edg.com/pub/Wg21oulu/SG1/P0394r4.html. So that we can attach papers to the wiki and have them appear correctly, the papers should be serialized as ascii.

**Comment by tabatkins** [comment]
That meta is added by the group's `header.include` file, so it can be removed.

**Comment by jfbastien** [comment]
Right, but I still want to use Unicode in the source. Because it's 2016.
And seriously wiki... seriously... It's 2016, serve stuff with the right encoding wiki!

**Comment by jyasskin** [comment]
The `.bs` file should certainly be in UTF-8, but Bikeshed should transcode that to ascii when producing the .html file.

**Comment by tabatkins** [comment]
Ahhhh, ok.  Yeah, I can do that.

**Comment by jyasskin** [comment]
Belay that, please. @jfbastien's latest entreaty seems to have gotten the wiki's encoding changed over. Let's see if that sticks before messing with Bikeshed.
