### ISSUE TITLE
Cannot set link default to this spec

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#748]
I think we discussed this in IRC but I couldn't find the bug here, and it continues to hurt referrer policy.

I have

```
<pre class="link-defaults">
spec: FETCH; type: dfn; text: referrer policy; for: /;
</pre>
```

however I keep getting

```
[1;33mLINK ERROR:[0m Multiple possible 'dfn' local refs for 'referrer policy'.
Arbitrarily chose the one with type 'dfn' and for 'Document'.
[1;33mLINK ERROR:[0m Multiple possible 'dfn' local refs for 'referrer policies'.
Arbitrarily chose the one with type 'dfn' and for 'Document'.
```

i.e. it is picking the wrong one.

**Comment by tabatkins** [comment]
Which spec was this happening in?

**Comment by domenic** [comment]
https://github.com/w3c/webappsec-referrer-policy/. Might be fixed with the latest changes, although per https://github.com/w3c/ServiceWorker/pull/995#issuecomment-256733299 maybe not...

**Comment by domenic** [comment]
Actually I think Fetch no longer defines referrer policy; we moved that into Referrer Policy itself. So this is probably not a useful bug report anymore. Feel free to close.

**Comment by tabatkins** [comment]
Yeah, the spec has some unrelated linking errors now.
