### ISSUE TITLE
WG21: no external resources

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#749]
C++ people like to read stuff offline.
Inline https://www.w3.org/scripts/TR/2016/fixup.js
Make people happy.

I'll forget to do it if I don't file a bug. I'd assign the bug to myself, but can't. Consider this assigned to me. I'll fix tomorrow.

**Comment by tabatkins** [comment]
If you'd started from the default files, this would have already been fixed. ^_^  Just go look at the default `footer.include`.
