### ISSUE TITLE
Referencing the second edition of WebIDL.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#750]
As @domenic noted in https://github.com/w3c/webappsec-secure-contexts/issues/33, `WebIDL` maps to `WebIDL-1`, which has a title of "Web IDL Level 1". I'd actually like to be referencing `https://heycam.github.io/webidl/`, which is "Web IDL (Second Edition)". Is this a SpecRef issue, or a Bikeshed issue? :)

**Comment by tabatkins** [comment]
That's a SpecRef issue. The relevant bits from Bikeshed's datafiles are:

```
-
a:webidl
WebIDL
webidl-1
-
d:webidl-1
WebIDL-1
8 March 2016
CR
WebIDL Level 1
https://www.w3.org/TR/WebIDL-1/
https://heycam.github.io/webidl/


Cameron McCormack
Boris Zbarsky
-
```

In other words, "webidl" is noted as an alias for webidl-1 in the SpecRef data.

**Comment by domenic** [comment]
Can you give some guidance on how people can fix this issue, even if it's not your fault?

**Comment by tabatkins** [comment]
Yeah, it's "file an issue on SpecRef so Tobie can get it fixed over there".
