### ISSUE TITLE
"status" boilerplate is broken.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#751]
@tabatkins: I believe that https://github.com/tabatkins/bikeshed/commit/f02935307493078ab95b09236b27d2f471aebb44 broke the include mechanism for status files, as it's now looking for things like `bikeshed/include/webappsec/status-w3c/ED.include` instead of `bikeshed/include/webappsec/status-ED.include`. Was this an intentional change? If so, can you update the include locations? If not, can you fix it up? :)

**Comment by mikewest** [comment]
(https://travis-ci.org/tabatkins/bikeshed/builds backs up my suspicion, FWIW)

**Comment by tabatkins** [comment]
WHOOPS, that's definitely a bug.  Sorry about that, need to switch that mechanism over to using `rawStatus`.

**Comment by tabatkins** [comment]
And fixed.
