### ISSUE TITLE
Linking to informative references.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#753]
https://w3c.github.io/webappsec-secure-contexts/#legacy-example links to pieces of the Geolocation API spec as an explanatory example. This section is marked (in a way that Bikeshed can't understand) as non-normative. It would be lovely if we had some way of marking either sections or specific references as non-normative, and moving a spec into the "Normative References" section of the document iff they're actually used in a normative way.

**Comment by tabatkins** [comment]
There is! If any ancestor has a class of "note", "example", or "non-normative" (closer than an ancestor with a class of "normative"), the section is non-normative.  This is then used by the autolinker to decide whether to insert it into the index as a normative or informative reference.

(This isn't documented well, sorry.)

**Comment by mikewest** [comment]
I don't think this works. At least, it's not working for me in my testing in this one document. I'm probably holding it wrong. :)

My current markup is:

```
<h4 id="whatever">Whatever!</h4>

<em>This section is non-normative.</em>

Blah, blah, {{SharedWorker()}}, blah.
```

Wrapping that last bit in a non-normative div doesn't seem to have any effect. Halp? https://github.com/w3c/webappsec-secure-contexts/blob/master/index.src.html <-- This document.

**Comment by mikewest** [comment]
Nevermind. I'm stupid. _That_ reference was being treated as informative, but there was something else being pulled in from that spec that wasn't. Ignore me!

**Comment by tabatkins** [comment]
Ah, yeah, if something shows up as both a normative and informative ref, I only put it in the normative refs. Gotta catch 'em all. ^_^
