### ISSUE TITLE
Tables extend outside example box in wide window

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#758]
With a very wide window, https://webbluetoothcg.github.io/web-bluetooth/#example-filter-by-name looks like:

![Table overflows example box to the right](https://cloud.githubusercontent.com/assets/83420/16970384/921c9aa6-4dd0-11e6-9df1-20494df0734c.png)

Removing the `class="overlarge"` from the output fixes it, but since that class isn't in [the source](https://github.com/WebBluetoothCG/web-bluetooth/blob/1563387a9b780f76acbe0044c650540b68062c25/index.bs#L646), it'll take a bikeshed fix to actually fix it.

**Comment by tabatkins** [comment]
Ok, let's tag in @fantasai - any clue how to fix this, or is this one of those "CSS sucks" problems? I think we talked about this before...

**Comment by tobie** [comment]
Seems related to w3c/tr-design#104.

**Comment by tabatkins** [comment]
fixed a while ago
