### ISSUE TITLE
Link to spec-specific issues list

### ISSUE THREAD

**Issue by fantasai** [tabatkins/bikeshed#763]
Throwing people at the entire CSSWG issue repository seems a little crude. How about pointing at the appropriate label, e.g. https://github.com/w3c/csswg-drafts/labels/css-values-3 ?

**Comment by tabatkins** [comment]
Done - I turned off the generic GitHub link for CSSWG, and added instead a link to the spec's label.  (This isn't generically added to Bikeshed specs, as we have no idea what GitHub structure is being used, but it's easy to duplicate for other groups as  necessary.)
