### ISSUE TITLE
Add common language names for translations

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#769]
https://github.com/tabatkins/bikeshed/blob/master/docs/metadata.md says "Translation indicates a translation of the document. At minimum it consists of a language code (BCP47 format) and a url.", but when I tried just 'ja' it didn't fill in "Japanese" and "日本語".

**Comment by tabatkins** [comment]
That's done by the languages.json file in bikeshed/spec-data/readonly. I've only got a few in there right now, because I only knew a handful of language names off the top of my head. Patches welcome. ^_^

**Comment by jyasskin** [comment]
Done. It'd be nice if Bikeshed would warn when it finds a language it doesn't know, and point at the file to add it to.

**Comment by tabatkins** [comment]
Good idea. I'll log a warning when Bikeshed can't fill in the holes.

**Comment by tabatkins** [comment]
And done. Thanks for the suggestion!

**Comment by jyasskin** [comment]
FYI, https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/jp-translation/index.bs&output=both hasn't caught the new language code. When I ran `bikeshed update` locally, I had to manually delete `bikeshed/spec-data/languages.json` to get it to be copied from `readonly/languages.json`.

**Comment by tabatkins** [comment]
Oh, duh, sorry, I have to bump the data version number.
