### ISSUE TITLE
Warn users about insecure links.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#772]
WDYT about adding something like the following to the default `stylesheet.include`:

```
  a[href^="http:"]:after {
    color: red;
    content: "🔓";
  }
```

I'm using it on https://w3c.github.io/webappsec-csp/, and I think it's a nice feature.

**Comment by tabatkins** [comment]
I try to keep the default stylesheet in alignment with the W3C stylesheet, only making changes where Bikeshed adds something new.  I discussed this with @fantasai and she's quite against adding it to the W3C stylesheet, so I don't particularly want to add it to Bikeshed's either. ^_^

**Comment by mikewest** [comment]
Bah. Don't you want to live in the gloriously padlocked future?!

I'll just throw it into the specs I write until someone tells me to stop. :)

**Comment by marcoscaceres** [comment]
Might be useful maybe for Editor's drafts... I'll see if we can add it to ReSpec as it's helpful for finding old busted links.

**Comment by tabatkins** [comment]
Hahaha, if you're *looking* for HTTP urls to fix, *that's* something I can easily add an opt-in warning for. Putting an unobtrusive padlock icon on your links won't really help with that, unless you do a careful visual check of your entire spec.

**Comment by tabatkins** [comment]
@mikewest Also you can, of course, just add that to the boilerplate for the groups you work in. Got no problem with that, y'all do whatever you want in your boilerplates.
