### ISSUE TITLE
Autolinking to Fetch

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#773]
Currently, I have big blocks of Fetch anchors in most of the specs I write. It would be lovely if the various bits and pieces would be picked up automagically.

@annevk is (understandably) reluctant to rewrite the spec in Bikeshed. Can it be imported as-is? If not, what's the minimal amount of work that needs to be done to bring it in?

/cc @tobie just in case this is a specref thing as well.

**Comment by domenic** [comment]
What someone can do is add lots of data- attributes, per https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md, and then it should probably just work.

**Comment by mikewest** [comment]
It looks like fetch already has `<dfn id="whatever">whatever</dfn>`. I suppose we'd need to add `data-export` everywhere, and types to the things that aren't `dfn`?

**Comment by tabatkins** [comment]
Yeah, everything needs a `data-dfn-type` attribute, and the ones that are `data-dfn-type=dfn` need a `data-export` too.  Several IDL things will need `data-dfn-for` to point to what they're for. And all the IDL methods with overrides or optional values need a `data-lt` listing each of the call variants.  (Like, `foo(int bar, optional baz)` needs `data-lt="foo(bar, baz) | foo(bar)"`.)

**Comment by tabatkins** [comment]
[Here's the full description of Bikeshed's dfn metadata](https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md).

**Comment by domenic** [comment]
`data-dfn-type` is not necessary for "dfn" type definitions.

**Comment by tabatkins** [comment]
I just added Fetch to Shepherd; sorry for forgetting to do that sooner.  And it looks like Fetch is metadata'd up now, so it should start showing up in the database soon.
