### ISSUE TITLE
Make oldids attribute also work on DFNs

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#775]
Currently the `oldids` attribute fails silently when you use it on `dfn` elements. It would be nice if that wasn't the case.

**Comment by tabatkins** [comment]
Patch accepted, or I'll take care of it next week.

**Comment by tobie** [comment]
Found a workaround for my particular use case in the meantime. Don't prioritize this for my sake.

**Comment by tabatkins** [comment]
Fixed.

**Comment by tobie** [comment]
Thanks!
