### ISSUE TITLE
Markdown lists can't be nested

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#776]
github-style markdown [gives](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists) the following list example:
```
1. First ordered list item
2. Another item
  * Unordered sub-list. 
1. Actual numbers don't matter, just that it's a number
  1. Ordered sub-list
4. And another item.

   You can have properly indented paragraphs within list items. Notice the blank line above, and the leading spaces (at least one, but we'll use three here to also align the raw Markdown).

   To have a line break without a paragraph, you will need to use two trailing spaces.  
   Note that this line is separate, but within the same paragraph.  
   (This is contrary to the typical GFM line break behaviour, where trailing spaces are not required.)

* Unordered list can use asterisks
- Or minuses
+ Or pluses
```
Which should render as:

----

1. First ordered list item
2. Another item
  * Unordered sub-list. 
1. Actual numbers don't matter, just that it's a number
  1. Ordered sub-list
4. And another item.

   You can have properly indented paragraphs within list items. Notice the blank line above, and the leading spaces (at least one, but we'll use three here to also align the raw Markdown).

   To have a line break without a paragraph, you will need to use two trailing spaces.  
   Note that this line is separate, but within the same paragraph.  
   (This is contrary to the typical GFM line break behaviour, where trailing spaces are not required.)

* Unordered list can use asterisks
- Or minuses
+ Or pluses

----

But bikeshed is le sad with:
```
FATAL ERROR: Line 43 isn't indented enough (needs 1 indent) to be valid Markdown:
"  * Unordered sub-list. "
 ✘  Did not generate, due to fatal errors
```

I've gotten it to accept lists with sub-lists (put empty lines in between), but they don't indent well.

**Comment by tabatkins** [comment]
Nope, they can absolutely be nested infinitely, but for simplicity I'm intentionally breaking from CommonMark and requiring you actually indent your list properly.  Either use a tab or 4 spaces (or set `Indent: 2` or whatever in your metadata).

The error you get is pretty straightforward about the problem.

**Comment by jfbastien** [comment]
Ha! Works now. The "needs 1 indent" thing is le confusing me: adding one space isn't sufficient, you need 2 to get to 4 spaces (it gives the same messages with 1, 2, and 3 spaces).
