### ISSUE TITLE
{{foo}} and <code>{{foo}}</code> should use the same font

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#782]
Instead,

```
{{Window}} <code>{{Window}}</code>
```

produces:

```html
<p><code class="idl"><a data-link-type="idl" href="https://html.spec.whatwg.org/multipage/browsers.html#window">Window</a></code>
<code><code class="idl"><a data-link-type="idl" href="https://html.spec.whatwg.org/multipage/browsers.html#window">Window</a></code></code></p>
```
which looks like:

![The first Window has a slightly larger font](https://cloud.githubusercontent.com/assets/83420/17573318/79f58394-5f0e-11e6-8d70-9018c1de271b.png)

due to an extra `font-size: .9em;` matching from https://github.com/tabatkins/bikeshed/blob/344b3f700fc98d8ae89e3282c4e5be9eac352059/bikeshed/include/stylesheet.include#L481

**Comment by tabatkins** [comment]
Fixed. I'm not even sure why we're applying `font-size: inherit` there. I switched it to `normal`, and will go PR the W3C stylesheet.
