### ISSUE TITLE
Literal backticks.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#788]
There doesn't seem to be a way to embed a literal `` ` `` in a Bikeshed document. WHATWG specs use backticks to demarcate byte-sequences from strings, so it would be nice to support this use case. We should probably support escapes, a la http://spec.commonmark.org/0.26/#example-287.

**Comment by tabatkins** [comment]
Okay, I rewrote backtick handling to allow for escapes.  Should work now.

**Comment by mikewest** [comment]
You == great. Thanks!
