### ISSUE TITLE
`data-dfn-for` values broken across lines aren't normalized.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#791]
The definition of https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-global has a `data-dfn-for` attribute that's broken across two lines. This means that `anchors.data` ends up with a two-line "for": 

```
-
global object
dfn
html
html
1
TR
https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-global
1
1
environment
   settings object
-
```

That doesn't match `<a for="environment settings object">global object</a>`. :(

Yes, HTML's line-breaking is weird. Still, it exists, and it would be nice if Bikeshed understood it.

**Comment by mikewest** [comment]
This looks fixed in `anchors.data`, but I don't see any corresponding change in Bikeshed. Is it actually fixed, or did HTML's markup change? :)

**Comment by tabatkins** [comment]
It was fixed in Bikeshed (small edit in update.py) and in Shepherd too - it's normalized on both ends just in case.
