### ISSUE TITLE
`data-dfn-type` doesn't seem to override heuristics.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#792]
https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-content-security-policy is marked up as `<dfn id=attr-meta-http-equiv-content-security-policy data-dfn-type=dfn data-export="">Content security policy state</dfn>`, but shows up in `anchors.data` as `element-attr` for `link`, which I don't understand.

Likewise, https://html.spec.whatwg.org/multipage/scripting.html#parser-inserted is marked up as `<dfn data-dfn-for=script id=parser-inserted data-dfn-type=dfn data-export="">"parser-inserted"</dfn>` and shows up with a type of `value`.

Am I holding it wrong?

/cc @annevk

**Comment by mikewest** [comment]
Ping! :)

**Comment by tabatkins** [comment]
Pinging @plinss

**Comment by tabatkins** [comment]
@plinss found the error - since type=dfn is also the default, it was accidentally kicking it into heuristic mode rather than Bikeshed mode. He's fixing it now.

**Comment by mikewest** [comment]
Wunderbar! Thanks to you both!

**Comment by plinss** [comment]
Fixed in Shepherd's spec parser

**Comment by mikewest** [comment]
And I see the right data in `anchors.data` now. Thanks!
