### ISSUE TITLE
<XMP> doesn't like comments :-)

### ISSUE THREAD

**Issue by FremyCompany** [tabatkins/bikeshed#793]
https://drafts.csswg.org/css-tables-3/#example-cca312e1
```
			<xmp class="lang-markup">
				<!-- built using dom api, as this would be fixed by the html parser -->
				<grid style="display: table">
					<row style="display: table-row">
						<th rowspan="2">1</th>
						<colgroup style="display: table-cell" span="2" colspan="2">2</colgroup>
					</row>
					<tr>
						<td>A</td>
						<td>B</td>
						<td>C</td>
					</tr>
				</grid>
			</xmp>
```

As you can see the comment has been dropped, somehow.
No big deal, but worth a fix still.

**Comment by tabatkins** [comment]
Or rather, Bikeshed has a preprocessing step, while the input is still text, that explicitly strips out all HTML comments from the source, because otherwise it can mess up the Markdown part.

There's, uh, not much you can do about that here, since XMP doesn't let you do escapes.  Move the comment out into the surrounding text, rather than embedded in the HTML?

**Comment by FremyCompany** [comment]
Ok, fair enough, will put the comment outside the xmp.

**Comment by FremyCompany** [comment]
Thanks for having a look

**Comment by FremyCompany** [comment]
Fixed it but thinking out loud, maybe the thing that strips the html comments could avoid doing so in <xmp> islands. Seems like that could work, since Markdown certainly doesn't run in <xmp> islands.

**Comment by FremyCompany** [comment]
Lol, looks like I found a way to break GitHub Comments :)

**Comment by tabatkins** [comment]
Nah, you just ran into the "GitHub markdown allows raw HTML, which is annoying when talking about HTML" problem.^_^

And unfortunately, I can't change the comment processing too much.  The processing I do before real HTML parsing is necessarily conservative; I don't want to write a duplicate HTML parser, so I have to be real careful about how I handle things.  Markdown processing avoids going into `<pre>`/etc by requiring that those tags be the first non-whitespace content on their lines; if you mess that up, Bikeshed might do crazy things.

But comments aren't generally restricted like that. People do all sorts of crazy things with comments, put them everywhere, put them inside of tags or multiple on the same line or make them cross lines.  And they use comments to comment out entire sections of specs, which means I want to remove the commented-out stuff before I start processing any of the blocks inside of it.

So it would be real hard to shift how it's currently operating. :/
