### ISSUE TITLE
Confusing errors with empty "for"

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#795]
Quiz:

Can you explain the difference between the two link errors below?

```
LINK ERROR: Multiple possible 'dfn' refs for 'origin'.
Arbitrarily chose the one in css-cascade-3.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:html; type:dfn; text:origin
spec:css-cascade-3; type:dfn; text:origin
LINK ERROR: Multiple possible 'dfn' refs for 'origin'.
Arbitrarily chose the one in url.
If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
spec:url; type:dfn; text:origin
spec:html; type:dfn; text:origin
spec:css-cascade-3; type:dfn; text:origin
```

The first comes from a `<a for=/>origin</a>`, while the second comes from a `<a>origin</a>`.

**Comment by tabatkins** [comment]
The URL definition for origin has a `for` value, so it doesn't get grabbed by a `for=/` autolink (explicitly requesting a dfn without a `for`). All three are valid for an autolink that doesn't care about `for`, tho.

And then you get different results chosen because, well, the choice is arbitrary. I'm literally just grabbing the first one I get when I iterate the dict, and that depends heavily on what's *in* the dict.

**Comment by jyasskin** [comment]
Yeah, the problem is that 
> LINK ERROR: Multiple possible 'dfn' refs for 'origin'.

doesn't say anything about not caring about `for`.

I suspect that the whole notion of "caring about `for`" winds up being confusing for humans, but if it sticks around, the errors should mention it.

**Comment by tabatkins** [comment]
Ah yes, this is true.

And yeah, matching vs defining isn't immediately intuitive, especially when empty values are allowed.  But I don't know how else to do it that doesn't require being overly verbose when there's no need?

**Comment by jyasskin** [comment]
I'd suggest something like:

```html
<pre class=default-for>
text: origin; for: /
text: url; for: request
</pre>
```

The syntax of `for: /` is confusing because you don't write `/` in the definition, so you could have the `default-for` section use `text: origin; for: ` or just `text: origin` to mean that the `for` is empty.

**Comment by domenic** [comment]
+1 on `/` being confusing. Ideally I would like to never use `/` in either the link defaults block or the `for=""` attribute.
