### ISSUE TITLE
hardcoded "please use GitHub issues" in "Status of this Document" sections?

### ISSUE THREAD

**Issue by equalsJeffH** [tabatkins/bikeshed#799]
The "please use GitHub issues" language in the "Status of this Document" section, which is generated by Bikeshed, points to this GitHub issues page <https://github.com/w3c/reporting/issues>, even if the "Group:" metadata item is set to another working group, e.g. "webauthn". Hat tip: @hillbrad

evidence: https://w3c.github.io/webauthn/

I tried adding the "issue tracking" metadata param within index.bs like so..
`Issue Tracking: Github https://github.com/w3c/webauthn/issues` ..but the resultant bikeshed output still has the problem as-described above. However, this did add an "issue tracking" item to the spec's front matter under the spec title, which is correctly linked.

**Comment by tabatkins** [comment]
That's because the boilerplate files @wseltzer committed originally for y'all's group has that written in it.  (In `bikeshed/include/webauthn/status-ED.include`.) Happy to change it.
