### ISSUE TITLE
Bikeshed output fails Specberus validation for WD

### ISSUE THREAD

**Issue by vijaybh** [tabatkins/bikeshed#802]
I hit this when trying to publish https://www.w3.org/TR/2016/WD-webauthn-20160902/ through Echidna.

Error (fatal):
- Bikeshed puts some local CSS after the W3C stylesheet. The pubrules say the W3C stylesheet must be last.

Warnings (not fatal but easily fixed):
- Local CSS includes -webkit-fit-content which is flagged as vendor-specific 
- Should put a "back to top" link at the end of the body

Aesthetic (not flagged but it bothered me):
- body element is not closed (i.e. no \</body> is generated)

**Comment by tabatkins** [comment]
> Bikeshed puts some local CSS after the W3C stylesheet. The pubrules say the W3C stylesheet must be last.

Fixed now. (This was something that had to be handled by an extension script in your `includes/webauthn` folder, but most of the changes are things that should be safe to run for all Echidna specs, so I moved them to just happen by default.)

> Local CSS includes -webkit-fit-content which is flagged as vendor-specific

I'll see if I can get this unflagged as a problem. Ignore for now.

> Should put a "back to top" link at the end of the body

Hmm, this must be a new requirement.  I'll investigate and see if I need to do anything or if it should be rolled back.

> body element is not closed (i.e. no </body> is generated)

There are lots of elements without end tags in a Bikeshed document, as it omits all the omittable end tags on purpose. ^_^

> Should put a "back to top" link at the end of the body

**Comment by vijaybh** [comment]
>> Bikeshed puts some local CSS after the W3C stylesheet. The pubrules say the W3C stylesheet must be last.

> Fixed now. (This was something that had to be handled by an extension script in your includes/webauthn folder, but most of the changes are things that should be safe to run for all Echidna specs, so I moved them to just happen by default.)

I just pulled down the latest bikeshed and this appears to still be broken for me. I ran Bikeshed on the spec and the W3C stylesheet was still before the local CSS.

Then I noticed that the code change puts this new processing in an if prepTR, so I tried adding "Prepare for Tr: true" to the metadata. That led to this error (I've changed the Windows style slashes to the Unix style so they show up better in the comment):

Traceback (most recent call last):
  File "\<path>/Python27/Scripts/bikeshed-script.py", line 9, in <module>
    load_entry_point('Bikeshed==0.0.0', 'console_scripts', 'bikeshed')()
  File "\<path_to_bikeshed>/bikeshed/\__init__.py", line 191, in main
    doc.preprocess()
  File "\<path_to_bikeshed>/bikeshed/\__init__.py", line 588, in preprocess
    for el in findAll("[rel ~= 'icon']", doc):
NameError: global name 'doc' is not defined

**Comment by tabatkins** [comment]
Ah darn, that's what I get for not actually testing the code. Fixed, sorry.

> I ran Bikeshed on the spec and the W3C stylesheet was still before the local CSS.

As you found, these fixups are gated by the `Prepare for TR` metadata.  If you're using `bikeshed echidna`, this gets flipped on for you automatically.

**Comment by vijaybh** [comment]
Thanks, works now.
