### ISSUE TITLE
Presence of DOMString in BS default links prevents building the WebIDL spec.

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#804]
More specifically the following line in `./spec-data/link-defaults.infotree`:

```
type: interface; text: DOMString; url: https://heycam.github.io/webidl/#idl-DOMString; spec: webidl
```

Fatals with:

```
bikeshed spec index.bs
FATAL ERROR: Multiple local 'interface' <dfn>s have the same linking text 'DOMString'.
 ✘  Did not generate, due to fatal errors
```

Current workaround: just remove that (last) line from  `./spec-data/link-defaults.infotree`.

**Comment by domenic** [comment]
@tabatkins we'd like to merge the Bikeshed conversion soon so if you could fix this ASAP that would be lovely <3.

**Comment by tabatkins** [comment]
Just pushed. Was waiting until last second, as anyone using DOMString in their specs that updates between me removing the line and WebIDL getting merged and updated in Shepherd would get a linking error.  (This especially includes anyone using the web api, as that updates its linking database regularly.)

Anyway, done. Merge away!

(This problem will disappear entirely after I do some fixing over how to treat anchor-block and default-file anchors; making them "local" solved some problems but created others.)
