### ISSUE TITLE
Update widlparser for namespace in ArgumentNameKeywords fix

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#805]
See https://github.com/plinss/widlparser/issues/17

For whatwg/dom I get the following, having updated bikeshed today:
```
FATAL ERROR: IDL SYNTAX ERROR LINE: 49 - skipped: "DOMString? lookupPrefix(DOMString? namespace)"
 ✘  Did not generate, due to fatal errors
```

cc @plinss

**Comment by tabatkins** [comment]
Updated for other reasons, so should be fixed now.
