### ISSUE TITLE
[=ref=] syntax should work on abstract-op type definitions too

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#809]
They're basically dfns that we want to preserve the case of.

**Comment by tabatkins** [comment]
I know I tried to do this once (unifying them under the supercategory "term"), but it turns out, for arcane and unnecessary reasons that are nevertheless hard to fix, that having both CS and CI categories in the same supercategory makes things screwy and terrible.

I should try it again, since I've forgotten all the details of what went wrong.

**Comment by jyasskin** [comment]
I'd be ok with a different shorthand too. `<a></a>` was actually fine for dfns; it's only 3 characters more than `[==]` anyway. It's `<a abstract-op></a>` that I want a shorthand for.

**Comment by tabatkins** [comment]
I can do that easy. I'd like to continue the syntax of square-bracket + something else; any suggestions for the something else?  `[|SomeFoo|]`, `[$SomeFoo$]`, etc?

**Comment by domenic** [comment]
Hmm, it'd be ideal if I didn't have to know the difference at the call site... I'd personally prefer to hold out until you can fix the architectural issues preventing [==] from working for both.

**Comment by tobie** [comment]
Actually, if we want to be passing args as in:

```
<a abstract-op>FooBar</a>(|arg|, |arg|, |arg|)...
```

Then having a different shorthand notation for abstract ops seems a better strategy.

It also would be nice to be able to include Ecmarkup "!" "?" prefixing without having to manually auto-link those.

All in all, I'd love for:

```
!FooBar(|x|) 
```

to just turn into:

```html
<a data-link-type="dfn" href="https://tc39.github.io/ecma262/#sec-algorithm-conventions">!</a>
<a data-link-type="abstract-op" href="#FooBar" id="ref-for-FooBar-1">FooBar</a>(<var>x</var>).
```

No idea whether that's possible or not given your parser, etc.

**Comment by TimothyGu** [comment]
I would be happy enough just to have a dedicated syntax for abstract ops because of https://github.com/tabatkins/bikeshed/issues/861.

**Comment by domenic** [comment]
This is causing issues for the WebAssembly spec now as well; /cc @littledan. I believe he is categorizing abstract ops as dfns, understandably because `<a abstract-op>X</a>` is a lot longer than `[=X=]`

**Comment by littledan** [comment]
I'd also be happy with some other fancy bracket combination!

**Comment by tabatkins** [comment]
All right, I went with `[$AbOp$]` syntax.
