### ISSUE TITLE
Some footers include note to use prefixed syntax for experimental implementations

### ISSUE THREAD

**Issue by SebastianZ** [tabatkins/bikeshed#813]
The [footer for Houdini drafts](https://github.com/tabatkins/bikeshed/blob/771ff239f0fa07c96b365128643c569f7b87aaff/bikeshed/include/houdini/footer.include) refers to CSS 2.1 and includes a recommendation to use prefixed syntax for experimental implementations.

That's obviously outdated, as implementors are encouraged to put experimental implementations behind a disabled-by-default preference.

Sebastian

**Comment by SebastianZ** [comment]
I just realized that obviously other footers like the one for the [FXTF](https://github.com/tabatkins/bikeshed/blob/8ce0b93c2cc4f0def681eadcb34a019e4c8de558/bikeshed/include/fxtf/footer.include) and [SVG](https://github.com/tabatkins/bikeshed/blob/771ff239f0fa07c96b365128643c569f7b87aaff/bikeshed/include/svg/footer.include) and [a CR Houdini footer](https://github.com/tabatkins/bikeshed/blob/771ff239f0fa07c96b365128643c569f7b87aaff/bikeshed/include/houdini/footer-CR.include) include that note, too.

Those should either be removed or be replaced by a section describing how experimental implementations should be done nowadays.

Sebastian

**Comment by tabatkins** [comment]
Done, thanks for noticing!
