### ISSUE TITLE
Shepherd: "call a user object's operation" cannot be found

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#815]
DOM is using this term and https://heycam.github.io/webidl/#call-a-user-objects-operation defines and exports it. However, for some reason this stopped working and it does not seem related to IDL being converted to bikeshed, at least as far as I can tell from the metadata on the element.

**Comment by tobie** [comment]
Spurious coincidence: before the conversion to Bikeshed, the text content of the DFN contained a line break (see [here](https://cdn.rawgit.com/heycam/webidl/dd77b1907e6af7ec27ff67edfb38f892f2fde3a8/index.html#dfn-single-operation-callback-interface)). It no longer does.

**Comment by tabatkins** [comment]
Ah, it's because Bikeshed is smart-quoting that apostrophe, so it's coming out as such in the DB.  @tobie, mind specifying an `lt` for that term?

**Comment by domenic** [comment]
Seems like this is a more general problem though? Maybe when Bikeshed smart-quotes something that's defining a term, it can add the lt automatically?

**Comment by tobie** [comment]
Or normalize quotes and apostrophes in the DB?

**Comment by tabatkins** [comment]
Ah, turns out I was already un-smarting the quotes *when you tried to autolink something*, I just wasn't doing the same when storing things in the DB. Just pushed a fix, running `bikeshed update --anchors` will fix you right up, @annevk.

**Comment by annevk** [comment]
❤️
