### ISSUE TITLE
Using the word metadata in a prop definition breaks the parser

### ISSUE THREAD

**Issue by jonathanKingston** [tabatkins/bikeshed#819]
I got the following Error:
```
LINE 17: Incorrectly formatted metadata line:
<p>test
```

The following code causes the issue:

```
<pre class="prod">crossorigin( <<integrity-metadata>> )</pre>
<p>test
```

Missing the `<p>` line also makes the whole `<pre>` block to be missing in the rendered output.

**Comment by tabatkins** [comment]
Fixed by your PR.
