### ISSUE TITLE
Look into steps that can be potentially skipped/optimized/cached

### ISSUE THREAD

**Issue by cynthia** [tabatkins/bikeshed#821]
While the main issue is the W3C HTML spec simply being extremely large, it would be worth looking into, as building the W3C HTML spec takes a ridiculous amount of time.

Any possibilities of getting this faster would be nice. (especially for CI)

**Comment by cynthia** [comment]
Profile report for later reference:
https://gist.github.com/cynthia/04c4d2122454fb26f06b7b9931b80b68

**Comment by tabatkins** [comment]
I'm not good at reading raw cProfile, but I have better profiling front-ends that I can run at work. (`bikeshed profile` invokes them; `bikeshed profile -h` tells you what additional programs need to be installed for it to work).

HTML is clearly banging on some N^2 behavior that nobody else is exercising nearly as hard; the slowest spec I know of besides this is DOM at about a 10s processing time, but processing HTML on my laptop today took 3m20s. That's *totally* ridiculous and clearly something fixable; I was assuming that y'all were hitting maybe a 20s or 30s build time, which is much slower than I'm happy about but still reasonably attributable to just "you have a big spec".  What you have instead is clearly a perf bug somewhere that I definitely need to fix, and in my experience this sort of thing is usually quite easy to find and fix.

**Comment by tabatkins** [comment]
All right, analyzing it a little bit, there are three big points:

1. ~29 seconds in the HTML parser
2. ~37 seconds in the HTML serializer
3. **~150 seconds in cleanupHTML()**

The first one I can't really touch, except by perhaps removing more inline uses of the HTML parser. I've killed most of these, but can see if I can find more; I doubt this'll remove more than a tiny amount.

The second one is probably capable of being fixed; I wrote the serializer to be easy to write and understand, not necessarily to be very efficient, and I bet there's some nice low-hanging fruit there.

The third one, tho, is *definitely* fixable.  That method is just running tons of selectors and doing tiny bits of work in the loops. It is not hard to instead rewrite this into a simple tree-walk that just checks each element for all the relevant conditions and does the work; at least, *most* of this can be simplified that way.

So a PR to simplify that method would be very appreciated, or I'll take care of it next week.

**Comment by tabatkins** [comment]
And it turns out cleanupHTML was only doing real simple selectors, so I was able to convert the entire thing into a single tree-walk that just checked properties of each element. The build on my work machine went from 2m8s to 1m16, a 40% reduction in running time.  It's still taking up a good chunk of runtime, so there's more room for improvement, but we're on our way.

**Comment by cynthia** [comment]
I'm assuming this is https://github.com/tabatkins/bikeshed/commit/9180ad2419eb198fef2f20c8aa575acf30d8670a ? Awesome work, thanks for looking into this. (I was meaning to, but jetlag and laziness kicked in.)

**Comment by tabatkins** [comment]
Been poking at more obvious small spots, and got the runtime down to 58s on my machine now. That's another 20% reduction! There's still a number of similar spots I can poke at for a second or two apiece.
