### ISSUE TITLE
Markdown inline transformation should be omitted in words/URLs

### ISSUE THREAD

**Issue by kba** [tabatkins/bikeshed#826]
The Markdown parser is a bit overzealous with transforming inline markup. It transforms markup within words and URLs, e.g.

```md
## my_fancy_property
```

is transformed to

```html
<h2>my<em>fancy</em>property</h2>
```

In the metadata section I have:

```html
<pre class='metadata'>
...
Previous Version: http://someplace/previous_version_here
...
</pre>
````

And it's rendered

```html
<dt>Previous Versions:</dt>
<dd>
  <a href="http://somplace/previous_version_here" rel="previous">http://someplace/previous<em>version</em>here</a>
</dd>
```

The URLs themselves work but the underscores are gone from the display which will lead to issues with auto-linking and different URLs being copied depending on whether people use "Copy Link address" or select the actual text.

Could the inline markdown parser be modified to only process delimiters at word boundaries and never within URL?

**Comment by tabatkins** [comment]
Yeah, this behavior violates the CommonMark spec - it intentionally prevents `_` from causing intra-word emphasis.  I'll see what I can do about it.

**Comment by kba** [comment]
I dabbled with `bikeshed/shorthands.py` a few days ago but couldn't get the placement of word boundaries in the regexes right to produce consistently correct output.

**Comment by tabatkins** [comment]
Yeah, I really need to just rewrite that entire thing. The approach I'm using doesn't work correctly - it fails to match things if there's an element between the delimiters.  I need to instead run thru all the text contents of a given element looking for opening delimiters, then dispatching to the correct matching function.

**Comment by tabatkins** [comment]
I think I'm going to turn off `_` emphasis entirely right now - I think most people use * emphasis anyway, and it's safer.

**Comment by tabatkins** [comment]
I've made a more specific issue for the "I need to rewrite the text replacer" thing: #832. Since this particular issue has been temporarily worked around, I'll go ahead and close it.
