### ISSUE TITLE
Test broken

### ISSUE THREAD

**Issue by kba** [tabatkins/bikeshed#829]
Commit https://github.com/tabatkins/bikeshed/commit/bdec26aaef62eaccaab681c49f76145df6700641 broke the tests

Compare:

https://travis-ci.org/kba/bikeshed/builds/164285676

vs

https://travis-ci.org/kba/bikeshed/builds/164286169

**Comment by tabatkins** [comment]
That's because I'm a dumb-dumb and had a typo in a place that didn't cause an immediate error. Fixed, thanks.
