### ISSUE TITLE
Link check

### ISSUE THREAD

**Issue by jfbastien** [tabatkins/bikeshed#833]
Sphinx has this nice "linkcheck" command which goes through all the URLs and checks that they're not dead (reporting HTTP status code as well).

It would be cool if bikeshed had the same thing.

**Comment by tabatkins** [comment]
Yup, would be cool. If you feel rambunctious, I'd invoke it via a `--link-check` argument on the `spec` command.

**Comment by tabatkins** [comment]
Oh, no, nevermind! I've got a `Complain About` metadata already, to invoke linting, which this certainly is. Maybe `Complain About: broken-links`, and put the code into the lint.py module?

The Requests library is available, too, for much easier link handling.

**Comment by tabatkins** [comment]
Done.
