### ISSUE TITLE
"Terms defined by reference" incomplete

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#836]
https://storage.spec.whatwg.org/ references both `<a for=/>origin</a>` and `<a for="environment settings object">origin</a>`. Only the former shows up in this section.

**Comment by tabatkins** [comment]
Ah, yup, I didn't consider a single spec defining multiple versions of the same term when I was writing this code. Fixing now.

**Comment by tabatkins** [comment]
And done. Confirmed that it outputs good on Storage.
