### ISSUE TITLE
Generated index gets a bit confused by the signature foo(...data)

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#838]
See e.g. https://console.spec.whatwg.org/#index-defined-here

**Comment by tabatkins** [comment]
I think this works correctly now; I had plinss change the widlparser stringification to use the JS syntax (prefix) when outputting just arg names, rather than the WebIDL syntax (suffix) that it uses when outputting typenames.

**Comment by domenic** [comment]
Nice. Yeah, it looks like the rebuild of Console on February 17 did indeed spit out a nice-looking index.
