### ISSUE TITLE
dfn contract docs have gone missing?

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#848]
Can't find the word "contract" in https://tabatkins.github.io/bikeshed/

**Comment by kba** [comment]
Last version before the documentation change:
https://github.com/tabatkins/bikeshed/blob/8b9c97c1c0decd9d521acef0093080e11bd8f02b/docs/dfn-contract.md

**Comment by kba** [comment]
The information in `dfn-contract.md` is in https://tabatkins.github.io/bikeshed/#definitions, however only from a spec writer's perspective, not for spec processors.

**Comment by domenic** [comment]
Yeah, as someone who creates specs with other preprocessors but wants them to be linkable from Bikeshed, that doesn't really suffice.

**Comment by tabatkins** [comment]
No idea how I dropped the dfn-contract stuff when consolidating the docs. Sorry about that! Fixed now.
