### ISSUE TITLE
Can I have multiple for=""?

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#849]
HTML defines the `message` event in one place, but it's "for" many different objects: <code>Window</code>, <code>EventSource</code>, <code>WebSocket</code>, <code>MessagePort</code>, <code>BroadcastChannel</code>, <code>DedicatedWorkerGlobalScope</code>, <code>Worker</code>. Is there a syntax for for="" that would allow me to express this? I was going to check the docs, but they seem to have gone missing (#848).

**Comment by kba** [comment]
You can separate multiple values with comma: 

https://github.com/tabatkins/bikeshed/blob/master/bikeshed/config.py#L624-L629:

```
Splits a string of 1+ "for" values into an array of individual value.
Respects function args, etc.
Currently, for values are separated by commas.
```

That's also what [the contract](https://github.com/tabatkins/bikeshed/blob/8b9c97c1c0decd9d521acef0093080e11bd8f02b/docs/dfn-contract.md).

**Comment by tabatkins** [comment]
Yup, the contract is now in the spec again, and the docs for dfn itself already specify that - `for` is a comma-separated list.

**Comment by kba** [comment]
> the docs for dfn itself already specify that - for is a comma-separated list.

Are you sure? I could not find that info either.

**Comment by tabatkins** [comment]
If you check again, you'll find that it's there, and nobody can prove that it wasn't there the whole time (don't look at the history).
