### ISSUE TITLE
Max ToC Level

### ISSUE THREAD

**Issue by g-ortuno** [tabatkins/bikeshed#854]
Is there something similar to ReSpec's [`maxTocLevel`](https://github.com/w3c/respec/wiki/maxTocLevel)? I realize I can use `class="no-toc" but I would have to add that class to a lot of sections.

**Comment by tabatkins** [comment]
Don't have one yet, but that's trivial to add and makes sense.  I'll add it.

**Comment by tabatkins** [comment]
Done, use `Max ToC Depth: 2` or whatever.
