### ISSUE TITLE
Shepherd https://streams.spec.whatwg.org/

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#858]
I would have thought this was already happening, but it does not seem like it.

This is blocking https://github.com/whatwg/fetch/issues/406.

**Comment by tabatkins** [comment]
Nah, it wasn't in.  Added.

**Comment by annevk** [comment]
It still doesn't work. I thought usually after midnight Europe there is a refresh (at least that usually seems to be the case). I guess I should wait another 24h.

**Comment by tabatkins** [comment]
Definitely works now, at least.

**Comment by annevk** [comment]
Indeed, sorry, forgot to close.
