### ISSUE TITLE
Add a way to ignore vars at the algorithmic level

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#859]
Something along the lines of:

```html
<div algorithm ignore-vars="foo, bar">
   ...
</div>
```

**Comment by annevk** [comment]
Or maybe just per-variable. I sometimes have one alone as an example or a different purpose. `<var ignore>this</var>` would do the trick.

My main use case is avoiding silencing errors with legitimate algorithm variables that happen to share the name.

**Comment by tobie** [comment]
I like @annevk's suggestion more than mine.

**Comment by tabatkins** [comment]
Done - use `<var ignore>` to make it shut up.

**Comment by haaami01** [comment]
> Valami a következők mentén:
> 
> ```
> < div  algoritmus  ignore-vars = " foo, bar " >
>    ...
> </ div >
> ```
