### ISSUE TITLE
Issue Tracking 'GitHub' too magical

### ISSUE THREAD

**Issue by scheib** [tabatkins/bikeshed#860]
Some specs list GitHub as an issue tracking source. E.g. [bikeshed documentation](https://tabatkins.github.io/bikeshed/), but they do not use the [Issue Tracking](https://tabatkins.github.io/bikeshed/#metadata-issue-tracking) metadata. At times when bikeshed is NOT generating GitHub as an issue tracking option it is confusing as to why not - when other specs do without using the Issue Tracking metadata.

Perhaps update documentation for [Issue Tracking](https://tabatkins.github.io/bikeshed/#metadata-issue-tracking) to describe when GitHub will be implicitly added? Or, add explicit use examples at least to BS doc?

**Comment by g-ortuno** [comment]
Somewhat related: The [generated spec](https://api.csswg.org/bikeshed/?url=https://github.com/g-ortuno/web-bluetooth/raw/move-use-cases-to-bikeshed/use-cases.bs) for [this file](https://github.com/g-ortuno/web-bluetooth/blob/move-use-cases-to-bikeshed/use-cases.bs) using the w3c bikeshed website does not include the Github issues link but when generating the file locally the link is included:

![fenmvjuxzka](https://cloud.githubusercontent.com/assets/3117611/19953794/4ce90de4-a1c6-11e6-9c88-9922aeee3f6c.png)

**Comment by kba** [comment]
The relevant field in the metadata is `Repository`. If set to a Github repository (implicit if value is `org/repo`), then `Github` will be listed in the `Issue Tracking` section, c.f. https://github.com/tabatkins/bikeshed/blob/master/bikeshed/MetadataManager.py#L129

@g-ortuno If you add `Repository: WebBluetoothCG/web-bluetooth` to your metadata, the Web service will generate the entry.

**Comment by g-ortuno** [comment]
@kba Thanks! It would be nice if this were documented.

**Comment by tabatkins** [comment]
Done now, sorry for the lack!
