### ISSUE TITLE
Add a few webappsec specs to Shephard.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#863]
Hey @tabatkins! Would you mind adding the following specs to Shepard?

* https://w3c.github.io/webappsec-upgrade-insecure-requests/
* https://w3c.github.io/webappsec-mixed-content/
* https://w3c.github.io/webappsec-subresource-integrity/

We're referencing them from Fetch, and it would help address whatwg/fetch#409 to get them in the database.

**Comment by mikewest** [comment]
Ping? :)

**Comment by tabatkins** [comment]
Done. They'll show up within the next 24 hours.
