### ISSUE TITLE
Variables sometimes don't generate warnings

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#865]
In https://fetch.spec.whatwg.org/#websocket-connections while host/secure generate warnings, port does not. Perhaps because a variable with the same name but different purpose appears in another section?

**Comment by tabatkins** [comment]
Yes, it's not in an algorithm block (either a container with `algorithm` attribute, or a section whose heading has `algorithm="algo name"`), so it's just considered as part of the document-global set of vars, and you apparently have used "port" as a var at least twice. (I see a usage in section 3.5.)

**Comment by annevk** [comment]
Shouldn't it be at least section-scoped?

**Comment by tabatkins** [comment]
Not necessarily; if you're not explicitly defining an algorithm, you might be using a variable globally across a spec.  I have explicit algorithms so you can indicate this properly.
