### ISSUE TITLE
Autolinking errors

### ISSUE THREAD

**Issue by jungkees** [tabatkins/bikeshed#870]
While referencing some of the IDL attributes defined in HTML from SW spec, I encountered linking errors. Could you look at them?

e.g. I made SW spec bs file [line 983](https://github.com/w3c/ServiceWorker/blob/master/docs/index.bs#L983) temporarily as:
```
<li>Let the <a href="https://html.spec.whatwg.org/#dom-messageevent-data">data</a> attribute of <var>e</var> be initialized to <var>clonedMessage</var>.</li>
```

Trying it with the following shorthand
```
<li>Let the {{MessageEvent/data}} attribute of <var>e</var> be initialized to <var>clonedMessage</var>.</li>
```
raises `LINK ERROR: No 'idl' refs found for 'data' with for='MessageEvent'.`

**Comment by tabatkins** [comment]
I've filed an issue https://github.com/whatwg/html/issues/2042 with the HTML spec to get that data exported properly.
