### ISSUE TITLE
Issues linking `origin` as a WD.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#875]
Building a document as a working draft gives the following error when resolving `origin`:

> ```
> LINK ERROR: Multiple possible 'dfn' refs for 'origin'.
> Arbitrarily chose the one in css-cascade-3.
> If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
> spec:html; type:dfn; text:origin
> spec:css-cascade-3; type:dfn; text:origin
> <a data-link-for="/" data-link-type="dfn" data-lt="origin">origin</a>
> ✔  Successfully generated, with 1 linking errors
> ```

I basically never want `css-cascade`. :) Adding `spec:html; type:dfn; text:origin` is a problem, as `origin` also is used in a number of other places as a property (`request/origin`, from Fetch for instance). Adding `spec:html; type:dfn; text:origin; for: /` doesn't seem to solve that, as it changes the link for `request/origin` from Fetch to HTML.

This is arguably HTML's fault, as it redefines the term, but since it's not marked as exported, that usually isn't a problem. The combination of redefinition and link defaults, however, seems to break things. :(

Halp?

/cc @tabatkins @annevk

**Comment by annevk** [comment]
Use `<a for=/>origin</a>`.

**Comment by mikewest** [comment]
@annevk: I do. However, `for="/"` is ambigious because CSS Cascade 3 defines https://www.w3.org/TR/css-cascade-3/#origin.

**Comment by annevk** [comment]
Oh, I have not gotten conflicts with that thus far. Seems that use of origin should use for="style rule" maybe.

**Comment by mikewest** [comment]
> Oh, I have not gotten conflicts with that thus far.

You'll only see the error if you build in "working draft" mode as part of a W3C WG. I think you're unlikely to be inconvenienced. ;)

> Seems that use of origin should use for="style rule" maybe.

Indeed. It's been renamed in the latest editor's draft to "cascade origin" (https://drafts.csswg.org/css-cascade/#origin), which seems fine. Ideally, @tabatkins and @fantasai would backport that change to the candidate recommendation at https://www.w3.org/TR/css-cascade-3/. :)

However we resolve this specific instance, however, the general behavior here seems strange. Adding a link default for `for=/` should not change the resolving behavior of `for=request`.

**Comment by tabatkins** [comment]
> Ideally, @tabatkins and @fantasai would backport that change to the candidate recommendation

Will do next time we pub.  I've got reminders set up to pub everything every 6 months at minimum, so it should get triggered soon.

> Adding a link default for for=/ should not change the resolving behavior of for=request.

You're right, that's a bug. One that's been here for quite a while, it seems! Fixed now.

You can now use `spec:html; type:dfn; text:origin; for: /` to get what you want.
