### ISSUE TITLE
Generate the Table to Define Each Member of the Enum Type

### ISSUE THREAD

**Issue by lisa0314** [tabatkins/bikeshed#880]
Hi, as a newcomer to this tool, I find that the class named 'argumentdfn' could be generated the table for the method of the interface with 'for' attribute in your test case. As a spec writer, if I want to generate a table to define the meaning of each member of a enum type, which class should I use?

**Comment by tabatkins** [comment]
Happy to provide more types of def blocks to help in defining things. Can you provide an example of the sort of markup you'd like to see in the final spec?

**Comment by lisa0314** [comment]
For example, I define a enum type as below:
enum AlertType {
    "new-face-detected",
    "face-out-of-fov",
    "face-back-to-fov"
};
Besides, I want to generate a table to show the meaning of each member for AlertType as below:
----|------
new-face-detected | A new face enters the FOV
face-out-of-fov | A new face is out of field of view
face-back-to-fov | A tracked face is back fully to field of view

**Comment by tabatkins** [comment]
It seems like this is pretty easy to just do on your own, and Bikeshed can't add very much?  You'd just write like:

```html
<table>
 <thead><tr><th>Member<th>Definition
 <tbody>
  <tr>
   <td>{{"new-face-detected"}}
   <td>A new face enters the FOV.
  <tr>
   <td>{{"face-out-of-fov"}}
   <td>A new face is out of field of view.
  <tr>
   <td>{{"face-back-to-fov"}}
   <td>A tracked face is back fully to field of view.
</table>
```

**Comment by lisa0314** [comment]
Thanks for your advice. I will define my table using .data class to make it look much better.
