### ISSUE TITLE
`algorithm` attribute with no value should use its sole contained element with dfn attribute

### ISSUE THREAD

**Issue by jakearchibald** [tabatkins/bikeshed#883]
Since https://github.com/tabatkins/bikeshed/issues/699, this works:

```html
<section algorithm>
  <h3><dfn>Do amazing stuff</dfn></h3>
```

But this doesn't:

```html
<section algorithm>
  <h3 dfn>Do amazing stuff</h3>
```

Feels like the above should work.

**Comment by tabatkins** [comment]
Yeah, it should work.  I'll fix to make it happen.

**Comment by tabatkins** [comment]
Done.

**Comment by jakearchibald** [comment]
Cheers!

**Comment by jakearchibald** [comment]
I think this may have broken https://github.com/w3c/ServiceWorker/blob/bikeshed-cleanup/docs/index.bs. What's the easiest way to debug this?
