### ISSUE TITLE
Regression: Multiple declarations of the '' algorithm

### ISSUE THREAD

**Issue by jakearchibald** [tabatkins/bikeshed#884]
4daafba22a8d9ff24ca2d46d0cbe540c15132681 seems to have broken algorithm name detection.

https://github.com/w3c/ServiceWorker/blob/4c0af6ebf6d2e14aa6425d4a44b1847142b52185/docs/index.bs fails with "FATAL ERROR: Multiple declarations of the '' algorithm.", but processes fine prior to 4daafba22a8d9ff24ca2d46d0cbe540c15132681.

**Comment by tabatkins** [comment]
Hmm, this is a confusing bug.  I'll need to sit and fiddle with it for a bit; in the mean time, I've reverted the change to avoid blocking anyone on spurious failures.
