### ISSUE TITLE
bikeshed generates odd HTML

### ISSUE THREAD

**Issue by garykac** [tabatkins/bikeshed#889]
I may be doing something wrong, but bikeshed generates HTML output files that don't close the &lt;html>, &lt;head> or &lt;body> tags.

For example: https://github.com/w3c/uievents/blob/gh-pages/index.html

I see this in other bikeshed-generated specs as well:
   https://github.com/w3c/ServiceWorker/blob/master/docs/index.html
so, maybe this is by-design?  But it feels wrong.

**Comment by tabatkins** [comment]
Yup, as-design. Bikeshed's HTML serializer omits all optional end tags. You'll notice that your p, like, and internal table elements don't have end tags either.

**Comment by tabatkins** [comment]
Oh wait, your p elements might have end tags, because the omission rules are more complex. But all the other optional end tags are omitted.

**Comment by garykac** [comment]
(I saw a few &lt;p>s with closing tags before I filed the bug which is why I was wondering what was going on).
