### ISSUE TITLE
Going deeper with for=""

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#895]
I'm not sure how to explain this properly. But say you define something called `<dfn>header</dfn>`. You then say header consists of a `<dfn for=header>name</dfn>` and a `<dfn for=header>value</dfn>`. Then you want to divide value further or define an operation for it. What `for` value (no pun) to use?

**Comment by tabatkins** [comment]
`header/value`. This is already used for 3+-level definitions in IDL and CSS.

**Comment by annevk** [comment]
Ah, I guess that makes sense. Hopefully I'll remember when I come across it again.
