### ISSUE TITLE
specifying "Boilerplate: abstract no" still generates the header for the abstract

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#901]
Specifying in the metadata block:
> Boilerplate: abstract no

still generates a *header* for the Abstract, it just doesn't put the body of the abstract in.

(I actually wanted to use this because I wanted an abstract with a markdown-generated nested list, but couldn't figure out how to get bikeshed not to strip the indentation that would allow the list markup to be accepted, so I tried this to generate the abstract manually.  I gave up and wrote the abstract in HTML instead of markdown instead.)

**Comment by tabatkins** [comment]
Hmm, I'm not sure why I didn't just put the Abstract header in the abstract.include.  Makes sense to reshuffle that, remove the Abstract header from the header.include.

**Comment by tabatkins** [comment]
Done.
