### ISSUE TITLE
Documented "Inline Github Issue Titles" metadata key isn't implemented.

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#910]
The "Inline Github Issue Titles" metadata key is [documented](https://tabatkins.github.io/bikeshed/#metadata-inline-github-issue-titles) but doesn't seem to work.

Greping for it in the source code also doesn't return anything.

**Comment by tabatkins** [comment]
Yeah, looks like an artifact of the first stab the PR took at this feature.  I'll fix.

**Comment by tobie** [comment]
Thanks.
