### ISSUE TITLE
Setting Default Highlight puts highlight class on result of {{IDL}} markup

### ISSUE THREAD

**Issue by dbaron** [tabatkins/bikeshed#930]
I noticed, while working on https://github.com/w3ctag/design-principles/pull/45 and preparing the two options there, that setting "Default Highlight" in bikeshed influences the result of {{DOMTimeStamp}} bikeshed markup.  It produces diffs like:

```
-   <p>When representing date-times on the platform, use the <code class="idl"><a data-link-type="idl" href="https://heycam.github.io/webidl/#common-DOMTimeStamp">DOMTimeStamp</a></code> type, with values being the
+   <p>When representing date-times on the platform, use the <code class="idl highlight"><a data-link-type="idl" href="https://heycam.github.io/webidl/#common-DOMTimeStamp">DOMTimeStamp</a></code> type, with values being the
```

This seems unexpected, particularly given that no highlighting seems to occur (and that there's no webidl highlighter... though that would be nice!).

**Comment by tabatkins** [comment]
Yeah, this is fixable; this clearly shouldn't get highlighted.

(And there is a webidl highlighter - how else do you think your IDL blocks get colored?)

**Comment by tabatkins** [comment]
Done.
