### ISSUE TITLE
Please add https://w3c.github.io/webcrypto/ to Shepherd

### ISSUE THREAD

**Issue by jyasskin** [tabatkins/bikeshed#931]

**Comment by tabatkins** [comment]
That appears to 404?

**Comment by jyasskin** [comment]
Oops, sorry, it's https://w3c.github.io/webcrypto/Overview.html.

**Comment by jyasskin** [comment]
The WG has also disbanded, so https://www.w3.org/TR/WebCryptoAPI/ is probably just as up to date. Actually, its metadata looks *more* up to date...

**Comment by tabatkins** [comment]
Done - I just linked up the TR url. As usual, give it a bit to update.  Note that, as a non-Bikeshed spec, the IDL will get picked up properly, but all the ordinary terms will be unexported.
