### ISSUE TITLE
Pull-in C++/WG21 biblio references directly from their source

### ISSUE THREAD

**Issue by tobie** [tabatkins/bikeshed#938]
Currently C++/WG21 references are pulled-in through Specref.

They're now available in a Specref-like format directly from https://wg21.link/specref.json.

Handling these in Specref frequently causes the auto-update process to run out of allocated memory and be terminated by Heroku. In turn, this blocks updates from W3C, WHATWG, WICG and IETF sources, sometimes for weeks.

There obviously are technical solutions to this issue, but given the only usecase for having them in Specref to begin with is so they can be used in Bikeshed, it makes sense to avoid having them in Specref altogether.

Copying @jfbastien, @jyasskin, and @m-ou-se so they can help adapt the format if necessary.

**Comment by tabatkins** [comment]
I'm happy to consume it directly if you can keep it in SpecRef's GitHub.  

Having them present in SpecRef is definitely the correct thing eventually, tho.

**Comment by tabatkins** [comment]
Or I guess wg21 is the one exposing it, so that's fine.

**Comment by jfbastien** [comment]
Haven't had time to pay attention due to family things, but from our IRC convo a few days ago that sounds like the right thing. @m-ou-se maintains wg21.link fwiw. On thing missing would be https 😊

**Comment by tobie** [comment]
@jfbastien you'd still get the Specref references, just Specref would host yours.

**Comment by tabatkins** [comment]
Okay, I'm getting it from wg21.link now. You can remove it from SpecRef, @tobie.
