### ISSUE TITLE
FATAL ERROR: 'Default Biblio Status' must be either 'current' or 'snapshot'. Got 'current'

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#941]
For whatwg/dom, /url, /fetch, /notifications.

Please do some regression testing before updating on the server...

**Comment by domenic** [comment]
(Reported at https://github.com/tabatkins/bikeshed/issues/940 for streams)

**Comment by tabatkins** [comment]
Fixed. :(
