### ISSUE TITLE
downloading anchor data failing on CI

### ISSUE THREAD

**Issue by patrickkettner** [tabatkins/bikeshed#944]
EHLO
Sorry if this is a rookie mistake, but the [travis job](https://travis-ci.org/patrickkettner/cookie-change-events/builds/208352243 for a bikeshed file is failing in the last couple of hours, with

```
FATAL ERROR: Either this version of the anchor-data API is no longer supported, or (more likely) there was a transient network error. Try again in a little while, and/or update Bikeshed. If the error persists, please report it on GitHub.
```

I have restarted the build a number of times to no avail, so now I am following the second half of the request

**Comment by tabatkins** [comment]
You appear to be using the right config, and the updates are working when I run them from my command line, and the same job worked fine 13 hours ago, so ???

**Comment by patrickkettner** [comment]
retrying the 7th time worked - ¯\_(ツ)_/¯ Emoji

**Comment by tabatkins** [comment]
Transient network errors it is, then!
