### ISSUE TITLE
Exclude pre.idl.extract from IDL index

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#946]
```
partial interface CSSStyleDeclaration {
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString _camel_cased_attribute;
};

partial interface CSSStyleDeclaration {
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString _webkit_cased_attribute;
};

partial interface CSSStyleDeclaration {
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString _dashed_attribute;
};
```
https://drafts.csswg.org/cssom/#idl-index

These should not be listed in the index, because they're templates, not final IDL. The `pre` has the class `extract` that is intended to allow exclusion when scraping IDL.

See https://github.com/w3c/csswg-drafts/issues/1089#issuecomment-285500693

**Comment by tabatkins** [comment]
Sounds fine. I didn't realize the `.extract` class being used for this; I'll document it and react to it accordingly.
