### ISSUE TITLE
Nightly Shepherd indexing stopped?

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#952]
Fetch and MIME Sniffing do not appear to be recently indexed. Blocks https://github.com/whatwg/xhr/pull/130.

**Comment by tabatkins** [comment]
Cc @plinss

**Comment by plinss** [comment]
Stuck process on server, kicked, running now... (will take a few minutes to update backlogged tasks)

**Comment by annevk** [comment]
Now bikeshed update seemingly hangs on "Downloading anchor data...".

**Comment by annevk** [comment]
Seemed to have eventually succeeded. Closing this. Thanks all!
