### ISSUE TITLE
Option to lint for RFC 2119 keywords in notes or other non-normative sections

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#958]
These keep creeping in. In HTML we have a rough lint check based on regexes: https://github.com/whatwg/html-build/blob/363186db4d1f31c2a3c44e82854760c2edf4c304/lint.sh#L17. Bikeshed could probably do better since it's scanning the document anyway.

Note that sometimes they need to be allowed if you're using the note to talk about a normative requirement. E.g.

```html
<p class="note">The "must do X" requirement above is because of hysterical raisins</p>
```

For this purpose @zcorpan introduced the syntax `<!-- non-normative -->must` in HTML.

**Comment by tabatkins** [comment]
Bikeshed does an early pass to strip comments (it makes markdown and datablocks happier), so that exact technique won't work, but we can def come up with something.

**Comment by tabatkins** [comment]
Done. Add `Complain About: accidental-2119 on` to your metadata to get this working.

**Comment by domenic** [comment]
Is there a way to make it fail the build?
