### ISSUE TITLE
Allow to define the rel=canonical URL

### ISSUE THREAD

**Issue by dontcallmedom** [tabatkins/bikeshed#959]
[ReSpec allows to set a canonical URL](https://github.com/w3c/respec/pull/938) for specs, and as [discussed in spec-prod](https://lists.w3.org/Archives/Public/spec-prod/2017JanMar/0008.html), I would like to bring the same feature to Bikeshed.

Since that'd would be my first code contribution to bikeshed, I would like to get some guidance on how to it right; my guess is that I need to update `MetadataManager.py` to detect the right configuration key, and then `boilerplate.py` to insert the `<link rel=canonical>` markup in the `<head>`.

Is that about right? any other thing I should pay special attention to?

**Comment by tabatkins** [comment]
You got it right, only additional thing to do is update the docs with the
new key. Might also want to add a new macro for the value; the function for
that is also in MetadataManager.

I recommend "Canonical URL" for the key.
