### ISSUE TITLE
Add fingerprinting watermark when requested

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#964]
<https://github.com/whatwg/infra/issues/20> suggests Bikeshed auto-handling fingerprinting watermarks.  <https://github.com/whatwg/whatwg.org/pull/64> is an SVG of the fingerprint icon.  Example usage is at <https://html.spec.whatwg.org/multipage/webappapis.html#a-plausible-language>.

Tentative plan is:

1. Look for elements with `class=tracking-vector`.
2. Append a link-image with the fingerprint, pointing to some Infra explanation of the concept.
3. If at least one shows up, trigger Bikeshed-specific styling to put it in the margin. Same as other styles, you can turn it off if you have your own.
4. If at least two show up, put the SVG as a `defs` instead, and make the instances just have a `use`.
5. Add a "Fingerprint Image" metadata, taking a url, so you can point it to a specific image, instead of the Bikeshed-generated SVG.

**Comment by zcorpan** [comment]
When using the image inline you need to add these attributes to the `<svg>`
```
width="46" height="64" role="img" aria-label="(This is a fingerprinting vector.)"
```

**Comment by zcorpan** [comment]
Ping.

**Comment by annevk** [comment]
@tabatkins ping?

**Comment by annevk** [comment]
So FWIW, I think we want to slightly change this based on feedback. It's useful to have both "fingerprinting vector" and "tracking vector". The latter being a superset for some cases that are not covered by fingerprinting alone. See https://github.com/whatwg/infra/pull/115#issuecomment-353135658.

**Comment by marcoscaceres** [comment]
Could this be a general "base.css" thing? https://github.com/w3c/tr-design/issues/162

**Comment by annevk** [comment]
That could work for W3C documents and should probably be tracked separately.

Also, I don't think we need the complexity for now from my comment above. Doing "tracking vector" alone should be sufficient for the foreseeable future and encompasses both.

**Comment by annevk** [comment]
@tabatkins ping and thank you!

**Comment by tabatkins** [comment]
All right, phew, I took two years to do something that was only thirty minutes of actual work. As of f5a6d58a you can now activate the tracking-vector icon automatically.

This isn't documented yet, because I haven't adjusted the default Bikeshed stylesheets to accommodate it yet, but:

* by default, anything with `class=tracking-vector` will get a tracking-vector icon added as its first child (ideal for positioning into the margin with a `position:absolute; left: XXXpx;`)
* you can change the class with `Fingerprint Class: foo`. Passing "none" will turn off the feature entirely.
* by default the image is a local SVG. You can change it to an image of your choice with `Fingerprint Image: https://example.com/foo`.
* by default the hovertext/alt is the same as what HTML currently uses. You can change it with `Fingerprint Title: here's a custom title`.

Even without any styling it's not unusable, just a little awkward as the big fingerprint sits at the start of the paragraph.

Before y'all start to use it you'll want to adapt your styles accordingly. You don't store your stylesheet in Bikeshed, so that's up to y'all.

----

Keeping this open so I can remember to finish integrating it into Bikeshed's stylesheet and document it.

**Comment by annevk** [comment]
Thank you! Some feedback:

* Could you rename various things from "fingerprint" to "tracking vector" so we have a single name for the concept?
* Could you add the link to https://infra.spec.whatwg.org/#privacy as suggested in OP? (This will require https://github.com/whatwg/infra/pull/115 to be merged.)
* Perhaps this link could have the `class=tracking-vector` similar to HTML and we have some kind of macro instruction attribute on the parent? That would make it simpler to keep HTML consistent with the rest.

**Comment by tabatkins** [comment]
I don't know what you mean by the last bullet point.

**Comment by annevk** [comment]
@tabatkins `<div insert-tracking-vector>` resulting in `<div><a class=tracking-vector ...`

**Comment by annevk** [comment]
Hey @tabatkins, is all clear now?

**Comment by tabatkins** [comment]
Ah yeah, that's clear enough. Happy to update.

**Comment by annevk** [comment]
Great, so pretty please update it?

**Comment by annevk** [comment]
@tabatkins heya, happy new year! Care to make the remaining tweaks?

**Comment by tabatkins** [comment]
All right, I've tweaked things a bit:

* Everything says "Tracking Vector" now; the metadatas are "Tracking Vector Class", etc.
* Use a `tracking vector` attribute on the container element to trigger it; this is removed during processing and won't show up in the output. `Tracking Vector Class` now controls which class is put on the *image*, instead.
* I'm still not linking to anything, because there's still nothing to link to. Merge that Infra patch and I'll add a link.

**Comment by tabatkins** [comment]
All fixed!
