### ISSUE TITLE
Upgrade links to HTTPS

### ISSUE THREAD

**Issue by edent** [tabatkins/bikeshed#966]
There are several links in `.spec-data` which don't use `https` where available.

Is it OK for me to go in an change [links like this](https://github.com/tabatkins/bikeshed/blob/master/bikeshed/spec-data/readonly/biblio/biblio-og.data#L10) to point to `https` sources where appropriate?

Or do I need to change them in a specific location and regenerate them? Or have I missed the point entirely? :-)

(Was originally https://github.com/w3c/html/issues/832 )

**Comment by tabatkins** [comment]
Sorry to give you a second redirect, but that file is generated from <https://github.com/tobie/specref>. They're quick about accepting patches, luckily. 😀

If you find fixable insecure links in other files, let me know.

**Comment by edent** [comment]
Haha! No worries. Thanks :-)

**Comment by edent** [comment]
Fixed upstream. https://github.com/tobie/specref/issues/340
