### ISSUE TITLE
Implement a WSGI frontend for Bikeshed-as-a-Service

### ISSUE THREAD

**Issue by reillyeon** [tabatkins/bikeshed#967]
This repository (or one depending on it) should contain the code to enable deploying a web service API like the one hosted at https://api.csswg.org/bikeshed/ to on any app hosting platform such as Heroku or Google App Engine.

**Comment by tabatkins** [comment]
I have no idea how to do this, so whenever you feel the urge to document it yourself, ping me and I'll re-open this. ^_^
