### ISSUE TITLE
Allow generating complex metadata from existing metadata

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#969]
In <https://github.com/whatwg/meta/issues/23>, Domenic wants to be able to include the bare minimum of metadata information in his specs, and have the rest of it (which is generally boilerplate, and inferrable from the shortname) auto-generate.

I think the best way to go about this is to have a Python hook that runs after all metadata is processed, before metadata validation, that lets you fill in additional metadata.  I don't think anything less powerful will work; in particular, string substitution probably isn't sufficient.

**Comment by domenic** [comment]
Hmm, so what would this end up looking like? Would we have to write Python? For our use case, string substitution would work, I am pretty sure...

**Comment by tabatkins** [comment]
Yeah, it looks like I should probably do a dumb string substitution first, because it's easy, and then perhaps do a Python thing after for more complicated use-cases.

**Comment by tabatkins** [comment]
Ok, just pushed this fix.  Went with a simple solution for now - there's a new `computed-metadata.include` boilerplate file you can use, which will get macro-substituted before being evaluated and added to the document's metadata.  Otherwise it's identical to `defaults.include`.

Note that, by necessity, this *overrides* any metadata set by any other source, so make sure that everything you put in that file is what you definitely want in every spec for your Group.
