### ISSUE TITLE
Report error when echidna fails

### ISSUE THREAD

**Issue by dontcallmedom** [tabatkins/bikeshed#970]
Right now, bikeshed doesn't report anything when publication with echidna fails, nor even indicates that it might.

A recent failure looked like below:
```
$ bikeshed echidna --u miguelao --p XXX --d https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0031.html
/usr/lib/python2.7/dist-packages/html5lib/ihatexml.py:262: DataLossWarning: Coercing non-XML name
  warnings.warn("Coercing non-XML name", DataLossWarning)
WARNING: This specification has neither a 'Security Considerations' nor a 'Privacy Considerations' section. Please consider adding both, see https://w3ctag.github.io/security-questionnaire/.
 ✔  Successfully generated, with warnings
https://labs.w3.org/echidna/api/status?id=ef5bbcb2-2911-4bae-98b1-7a9312fed898
```

The final URL shows failure, but that can easily be missed after the "Successfully generated" message.

Ideally, bikeshed would wait until the echidna process terminates to indicate success or failure. But if that's not an option, bikeshed should at least draw attention to the fact that the echdina publication may fail separately, and that the last URL should be followed to determine the status.

cc @vivienlacourba

**Comment by tabatkins** [comment]
Right, I don't currently surface any UI for the Echidna results.  I'm hoping that Echidna will do that at some point.

(Also, note that you have a markup error somewhere - that dataloss warning means you have something screwed up somewhere so that *something* is getting misparsed. It's usually an unclosed attribute.)
