### ISSUE TITLE
bikeshed update fails to download biblio data

### ISSUE THREAD

**Issue by jeisinger** [tabatkins/bikeshed#971]
With the following helpful error message:

```$ bikeshed update
Downloading anchor data...
Success!
Downloading biblio data...
FATAL ERROR: Couldn't download the biblio data.
<urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
 ✘  Did not generate, due to fatal errors
```

I'm using bikeshed at rev b734e371910e25ac23b774dca3dea5cfc7b7fc0b

**Comment by tabatkins** [comment]
Did this persist? I think this error has shown up before and been a transient connection error.

**Comment by jeisinger** [comment]
I tried several times since last week. @mikewest proposed to create a fresh bikeshed install, but that didn't help either :/

**Comment by tabatkins** [comment]
Ah, yup, I'm getting that too.  Surprised you're the first to report it.  Looking into it now.

**Comment by tabatkins** [comment]
Uggggggggh, it looks like the problem is that SpecRef is using SNI, and anything below Python 2.7.10 has a broken urllib that doesn't handle SNI properly.  The default Ubuntu install is still 2.7.6. >_<  

Gonna figure out if there's some other way to fix this.

**Comment by tabatkins** [comment]
As far as i can tell, there isn't.  Us Googlers stuck on Gubuntu Trusty and its 2.7.6 are kinda SOL. I've at least patched Bikeshed to recognize this and output a message telling you what to do. :(

**Comment by tabatkins** [comment]
And I worked around it! With @plinss' help, we have a proxy set up, so if your Python can't talk SNI to specref.org, we'll try that csswg.org instead.  Works for me now; should work for you too, @jeisinger.

**Comment by jeisinger** [comment]
yes, it works now! thanks!
