### ISSUE TITLE
Do not fatal error for Can I Use URL: foo and foo does not exist

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#973]
For https://tabatkins.github.io/bikeshed/#metadata-can-i-use-url I think it makes perfect sense to specify this to get notified if caniuse adds its first feature for your spec, but if it has no features from your spec bikeshed gives a fatal error. I think it shouldn't be an error/warning at all.

**Comment by tabatkins** [comment]
Ah, yup, I agree.

**Comment by tabatkins** [comment]
Well, hm.  I agree it shouldn't fatal.  But it's useful to be told that you have a typo; maybe I'll downgrade this to a warning?

**Comment by tabatkins** [comment]
k, done. The "url doesn't show up" error is now a warning, and there's a new `Ignore Can I Use URL Failure: <url>` metadata you can use to suppress even that.
