### ISSUE TITLE
Can't specify caniuse=foo in <pre class=propdef>

### ISSUE THREAD

**Issue by zcorpan** [tabatkins/bikeshed#974]
I wanted to add caniuse box for http://caniuse.com/#feat=css-scroll-behavior but it seems like it's not possible. A `<dfn caniuse=foo>` inside the `<pre class=propdef>` is ignored.

Maybe support specifying `caniuse=foo` on the `<pre class=propdef>`?

**Comment by tabatkins** [comment]
I don't remember why I required them to be on a `dfn` originally.  I've loosened the restriction. The only requirement now is that the element have an ID on it, so I can link to it.

**Comment by zcorpan** [comment]
Thanks. I guess I can specify it on the heading... but I kinda would like it to line up with/link to the `dfn` instead.

**Comment by tabatkins** [comment]
You can just put an ID on the propdef

**Comment by zcorpan** [comment]
I'd rather not have 3 IDs for 1 property (heading, propdef, dfn).

IMO the obvious thing to do is:
```
<pre class=propdef>
Name: <dfn caniuse=css-scroll-behavior>scroll-behavior</dfn>
...
```
