### ISSUE TITLE
InfoTree format would benefit from comments

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#979]
Maybe there is a way to do this but it isn't documented?

I'd like to comment link-defaults with things like "TODO: remove when URL properly exports this thing"

**Comment by tabatkins** [comment]
There isn't a way yet. Be fine with like, start a line with # to ignore it?

**Comment by domenic** [comment]
That'd work, although I'd appreciate being able to do comments on the same line, e.g.

```
<pre class="link-defaults">
spec: URL; type: dfn; text: base URL    # TODO: remove this when URL exports properly
</pre>
```

**Comment by tabatkins** [comment]
That requires a more complicated glyph, since # appears in values semi often.

**Comment by domenic** [comment]
Fair. Singleline is fine for now.

**Comment by tabatkins** [comment]
Done and documented.
