### ISSUE TITLE
Consoles without Unicode support

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#980]
My typical Bikeshed experience is as follows:

```
$ make
bikeshed spec
[1;96mWARNING:[0m Example needs ID:
<div class="example">
            This is an example of an informative example.
        </div>
[1;33mLINK ERROR:[0m No 'dfn' refs found for 'base url' that are marked for export.
<a data-link-type="dfn" data-lt="base URL">base URL</a>
[1;96mWARNING:[0m Your console does not understand Unicode.
  Messages may be slightly corrupted.
[7;32m &#10004; [0m Successfully generated, with 1 linking errors
```

I wonder though, if Bikeshed can tell my console doesn't support Unicode, maybe it could stop trying to output all these escape codes, instead of outputting them and then warning me that they might not work right?

**Comment by tabatkins** [comment]
You want the `--print` option <file:///usr/local/google/home/tabatkins/bikeshed/docs/index.html#cli-options>

**Comment by domenic** [comment]
But, my point was, if Bikeshed already knows it's not going to work, why is it doing this to me anyway?

**Comment by tabatkins** [comment]
(The escape codes aren't the unicode thing; they're coloring the text using standard console escape strings.  The unicode error is the ✔ and ✘ characters it outputs in the success/failure message.)

**Comment by domenic** [comment]
OK, so ignoring the escape codes, why is it warning me about Unicode not being supported and printing slightly corrupt output, instead of just acknowledging that I don't support Unicode and choosing to use non-Unicode checkmarks and Xs?

**Comment by tabatkins** [comment]
Because it outputs that when *anything* tries to print a unicode character. The success/failure message is the common cause of this, but any other error message that happens to contain unicode (because your spec does) will trigger it too, and I can't realistically do anything about that.

**Comment by tabatkins** [comment]
(The "slight corruption" you get is just the check/x being replaced with an HTML escape.)

**Comment by domenic** [comment]
I see. It'd be ideal if you could special-case the success/failure messages to not try to use Unicode when the console does not support it. Then we'd avoid the noisy warning message about something that I can't avoid in the first place.

**Comment by tabatkins** [comment]
There's nothing reasonable in ASCII for a checkmark, unfortunately.

**Comment by domenic** [comment]
Sure, but I don't care what you pick; I'm more likely to get the message with "FAIL" than I am with "Your console does not understand Unicode. Messages may be slightly corrupted." + "&#10004;"

**Comment by domenic** [comment]
Or, I guess, it'd be "SUCCESS"? See, I don't even know what Bikeshed's telling me when I see those two messages; is it failure or success?

**Comment by tabatkins** [comment]
Okay, reasonable point. I'll see what I can do.

**Comment by tabatkins** [comment]
Confirm that it works, plz?

**Comment by domenic** [comment]
Works great, thank you!!
