### ISSUE TITLE
Output contains lots of data-md="" attributes on <li>s

### ISSUE THREAD

**Issue by domenic** [tabatkins/bikeshed#981]
It seems like these could be stripped?

**Comment by tabatkins** [comment]
I'm currently using them to produce an approximation of the compact vs loose list-item handling, as I'm not handling those properly in the Markdown parser.

**Comment by domenic** [comment]
Oh, you mean there is a CSS rule targeting them, so they are actually important in the output? Eek, OK. Is there an issue tracking fixing that in the Markdown parser?

**Comment by tabatkins** [comment]
Yes and yes.

**Comment by domenic** [comment]
Could you point me to that tracker issue so I can subscribe to it/thumbs up it?

**Comment by tabatkins** [comment]
It's #213. You've already commented on it, and opened #219, which is essentially the same as this one. ^_^
