### ISSUE TITLE
Defining multiple partial dictionaries.

### ISSUE THREAD

**Issue by mikewest** [tabatkins/bikeshed#982]
https://w3c.github.io/webappsec-credential-management/ defines a `CredentialRequestOptions` dictionary as something of a base class, and then extends it twice via `partial dictionary` IDL blocks for reasons which are totally valid and reasonable I swear.

Currently this throws `FATAL ERROR: Multiple local 'dictionary' <dfn>s have the same linking text 'CredentialRequestOptions'`. It would be ideal if that didn't happen. :) Can I somehow control the ID that's produced for these items?

**Comment by tabatkins** [comment]
Ah, partial dictionaries weren't valid in the past, so I didn't include them in the "force them to be a link, not a dfn" code. Done now.

**Comment by mikewest** [comment]
I think we've now ended up with three definitions of `CredentialRequestOptions`:

> ```
> LINK ERROR: Multiple possible 'dictionary' refs for 'CredentialRequestOptions'.
> Arbitrarily chose the one in webappsec-credential-management-1.
> If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
> spec:webappsec-credential-management-1; type:dictionary; for:/; text:CredentialRequestOptions
> spec:webappsec-credential-management-1; type:dictionary; for:/; text:CredentialRequestOptions
> spec:webappsec-credential-management-1; type:dictionary; for:/; text:CredentialRequestOptions
> <a data-link-type="dictionary" data-lt="CredentialRequestOptions" class="nv">CredentialRequestOptions</a>
> ```

**Comment by mikewest** [comment]
Nevermind, `bikeshed update` saved the day. :)
