### ISSUE TITLE
Need way to omit/replace Feedback header generated if group boilerplate defines mailing list

### ISSUE THREAD

**Issue by inexorabletash** [tabatkins/bikeshed#983]
Per https://github.com/w3c/IndexedDB/issues/189

```html
<pre class=metadata>
...
Group: webplatform
...
</pre>
```
... results in a __Feedback__ link pointing to public-webapps@w3.org c/o the Mailing List definition in `boilerplate/webplatform/defaults.include`. We'd like to suppress it and direct feedback to the GitHub issue tracker. The __Issue Tracker__ link is automagically generated c/o developing out of a repo.

I tried:
* `Boilerplate: feedback-header no` &mdash; this suppresses the __Issue Tracking__ header, not the __Feedback__ header
* `!Feedback: foo bar` &mdash; this _appends_ to the __Feedback__ header, doesn't replace it
* `Mailing List: ` &mdash; error

**Comment by tabatkins** [comment]
Can't you just... remove the mailing list from the boilerplate? The entire point of it is to provide the information for that header.  Why include it if you're using GH instead?

**Comment by mkruisselbrink** [comment]
See also w3c/FileAPI#49, but yes, it seems that the correct fix is to update the boilerplate for the webplatform working group, so I assume that's what this bug is about?

**Comment by tabatkins** [comment]
Sure. So I guess I'll just remove that line from the boilerplate?  There might be stuff in the Status boilerplate or something that refers to the mailing-list text macro, that'll need to be changed as well.

**Comment by inexorabletash** [comment]
That'll affect every spec that uses the `webplatform` group, right?

But... I guess everyone prefers GitHub issues now. So SGTM

**Comment by tabatkins** [comment]
Done. Removed "Mailing List" from the defaults.include, and fixed all the status.include files to use the same verbiage as the CSSWG (referring to the mailing list archives solely as a historical archive).
