### ISSUE TITLE
CanIUse feature displays are wrong

### ISSUE THREAD

**Issue by LeaVerou** [tabatkins/bikeshed#985]
Take a look at: https://drafts.csswg.org/css-images/#image-set-notation

The caniuse panel claims no support, but if you actually visit the caniuse page, the story is a bit different:
![image](https://cloud.githubusercontent.com/assets/175836/25054578/f3bb73b6-212b-11e7-9607-93320727133f.png)

I suspect it's due to the `-webkit-` prefix, but shouldn't that be reflected in the table somehow? "Implemented behind a prefix" is closer to "implemented" than to "unimplemented"

**Comment by tabatkins** [comment]
Yes, it's due to it being prefixed - I simplify "needs a prefix" to "not supported".  Because, well, it's not - you can't use the feature as written.
