### ISSUE TITLE
Allow allow-2119 on an ancestor

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#996]
Would be nice for the Infra Standard.

**Comment by tabatkins** [comment]
The "only on parent" thing is intentional right now; it avoids a document doing something like putting it on the root to silence the warning, and then accidentally adding bad 2119 usage and it doesn't get caught.

**Comment by annevk** [comment]
It would be nice if you didn't close issues until you heard back from the reporter. E.g., what if I suggested we allowed it on ancestors that also contained the class "example"?

**Comment by tabatkins** [comment]
That doesn't address my objection, it just makes it slightly less bad.  You can still put it on the example container to handle the one 2119 violation you see now, and then a later edit can introduce another violation that's now hidden.

(Theoretically this can happen even today - you could put it on a paragraph and then make the edit. But it's as tight as I can make it without requiring, say, the parent to contain *only* the 2119 keyword in question (that is, require `<span class=allow-2119>may</span>`), which seems like too much of an annoyance.)
