### ISSUE TITLE
Remove for=except-field and exception-code?

### ISSUE THREAD

**Issue by xfq** [tabatkins/bikeshed#997]
They are used in [globalnames.py](https://github.com/tabatkins/bikeshed/blob/aa692b5bb18791d7660cd494994fd0ac2ec23132/bikeshed/globalnames.py#L137) and the [docs](https://github.com/tabatkins/bikeshed/blob/aa692b5bb18791d7660cd494994fd0ac2ec23132/docs/index.bs#L1645).

IIUC they should be removed, per:

* ce3415237cd6224464d15e22b47d7fd2d909c993
* ec25f354da3689cfcb39967bf4cf8a510e292fb8
* ae3b4eaa941e5ea380931f30ba9a0086026a44aa

**Comment by tabatkins** [comment]
Yeah. `globalnames` needs to be removed; it's a legacy effort that I've thought better of. I'll happily take a PR. ^_^

**Comment by xfq** [comment]
It's still in globalnames.py. Is it intentional?

**Comment by tabatkins** [comment]
That file's not used currently, so it doesn't matter.

**Comment by xfq** [comment]
I see. Thanks.
