### ISSUE TITLE
Markdown parsing problem

### ISSUE THREAD

**Issue by xfq** [tabatkins/bikeshed#999]
Code span inside link text isn't recognized by Bikeshed. For example:

* https://github.com/tabatkins/bikeshed/blob/2694cf87482eb631bb8582afc69be1fae22f2bff/docs/index.bs#L1735 (source)
* https://github.com/tabatkins/bikeshed/blob/2694cf87482eb631bb8582afc69be1fae22f2bff/docs/index.html#L3125 (HTML)

Expected result: http://spec.commonmark.org/dingus/?text=%5B%60lt%60%20attribute%5D(%23changing-lt)

Relevant CommonMark spec section: http://spec.commonmark.org/0.27/#link-text

**Comment by tabatkins** [comment]
This is yet another specific example of #832, so I'm closing this as a dupe. I really need to fix #832. ;_;
